### ISSUE TITLE
xROI

### ISSUE THREAD

**Issue by bnasr** [ropensci/software-review#223]
### Summary

-   What does this package do? (explain in 50 words or less):
Delineate Region of Interests (ROI's) and Extract Time-Series Data from Digital Repeat 

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: xROI
Title: Delineate Region of Interests (ROI's) and Extract Time-Series Data from Digital Repeat Photography Images
Version: 0.1.2
Date: 2018-03-26
Author: Bijan Seyednasrollah, Thomas Milliman, Andrew D. Richardson
Maintainer: Bijan Seyednasrollah <bijan.s.nasr@gmail.com>
Description: Digital repeat photography and near-surface remote sensing have been used by environmental scientists to study the environmental change for nearly a decade. However, a user-friendly, reliable, and robust platform to extract color-based statistics and time-series from a large stack of images is still lacking. Here, we present an interactive open-source toolkit, called 'xROI', that facilitate the process time-series extraction and improve the quality of the final data. 'xROI' provides a responsive environment for scientists to interactively a) delineate regions of interest (ROI), b) handle field of view (FOV) shifts, and c) extract and export time series data characterizing image color (i.e. red, green and blue channel digital numbers for the defined ROI). Using 'xROI', user can detect FOV shifts without minimal difficulty. The software gives user the opportunity to readjust the mask files or redraw new ones every time an FOV shift occurs. 'xROI' helps to significantly improve data accuracy and continuity. 
Depends: R (>= 3.0.0)
Imports:
    raster,
    rgdal,
    sp,
    jpeg,
    tiff,
    shiny,
    shinyjs,
    shinyBS,
    shinyAce,
    shinyTime,
    shinyFiles,
    shinydashboard,
    shinythemes,
    colourpicker,
    rjson,
    stringr,
    data.table,
    lubridate,
    plotly,
    moments,
    RCurl,
    methods,
    utils,
    graphics,
    stats
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
BugReports: https://github.com/bnasr/xROI/issues
RoxygenNote: 6.0.1.9000

```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/bnasr/xROI

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]
data extraction, because the package extract color based statistics from stack of digital repeat images.

-   Who is the target audience and what are scientific applications of this package?  
Environmental scientist who use digital repeat photography to study the environmental changes such as vegetation phenology, salt marsh restoration, monitoring tidal wetlands, assessing gross primary productivity, investigating growth in croplands and anyone who is interested to extract time series data from digital images.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?
No.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [ ] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [x] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [x] The package is novel and will be of interest to the broad readership of the journal. 
    - [x] The manuscript describing the package is no longer than 3000 words.
    - [x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:
0 error, 0 warning, 0 notes submitted on CRAN

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:
name of the package is not all in lower case: xROI

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by sckott** [comment]
thanks for your submission @bnasr ! 

## programmatic work

A high level issue is the interactive Shiny interface. We don't have a policy in our documents yet as we haven't had a submission before that's purely a Shiny app, but we are in the process of adding it now. Basically, Shiny interfaces are great, but we'd like there to be a way for users to do the same thing in whole or at least in part, programatically. One way to do this is have a code tab in your Shiny app which gives users the code to do what they did in the Shiny app, and eventually they may learn how to use your pkg through code as well as via Shiny. One example of combining interactive with code is tabulizer, see https://github.com/ropensci/tabulizer#code-examples 

Do you think you'd be willing to try to incorporate functions/etc. for using your pkg programmatically? Or are you committed to only the Shiny interface?

## tests

As per our [packaging guide](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-testing) we do require every submission to have a test suite.  Please add a test suite - check out this guide https://rstudio.github.io/shinytest/articles/shinytest.html for how to add tests for shiny apps.

**Comment by sckott** [comment]
any thoughts @bnasr ?

**Comment by bnasr** [comment]
Thanks @sckott for your review and comments and sorry for the delay. I've been working on this.
The package actually does have some low-level programmatic work options in addition to the high-level shiny interface. Part of this has been documented in the package, however not in the vignette page. I will try to add this to the vignette and prepare a test case. Thanks.

**Comment by sckott** [comment]
Sounds good. Thanks very much @bnasr

**Comment by sckott** [comment]
@bnasr be aware that our policies https://ropensci.github.io/dev_guide/policies.html#review-process state that this issue will be closed after one year from applying the holding label (jul 2019) and you'll need to resubmit

**Comment by sckott** [comment]
as per our policies (link in above comment) - this submission is now closed

**Comment by Rajesh78079** [comment]
i want to use this xROI package but when i try it doesn't respond how i can use it correctly without any error please help me

**Comment by mpadge** [comment]
@Rajesh78079 The repository source is https://github.com/bbcrown/xROI, so you'd have to ask over there. But note that it hasn't been touched for years, so you should expect that the package will no longer work.
