### ISSUE TITLE
wateRinfo package

### ISSUE THREAD

**Issue by stijnvanhoey** [ropensci/software-review#255]
### Summary

-   What does this package do? (explain in 50 words or less):

wateRinfo facilitates the access to a variety of environmental water-related data about Flanders (Belgium) available on [waterinfo.be](https://www.waterinfo.be/), a website managed by the Flemish Environmental Agency.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: wateRinfo
Title: Download Time Series Data from Waterinfo.be
Version: 0.2.0
Description: The wateRinfo package provides an R interface to the data available
    at waterinfo.be, the data portal provided by the Flemish Environmental
    Agency. The package provides R functions to check the available stations for 
    a given variable, check the available variable for a given station and 
    download time series using the database identifiers as well as station 
    names.
Authors@R: c(
    person("Stijn", "Van Hoey", role = c("aut", "cre"), email = "stijn.vanhoey@inbo.be", comment = c(ORCID = "0000-0001-6413-3185")),
    person("Willem", "Maetens", role = "ctb", email = "w.maetens@vmm.be"),
    person("Peter", "Desmet", role = "ctb", email = "peter.desmet@inbo.be", comment = c(ORCID = "0000-0002-8442-8025"))
    )
License: MIT + file LICENSE
URL: https://github.com/inbo/wateRinfo, https://inbo.github.io/wateRinfo
BugReports: https://github.com/inbo/wateRinfo/issues
Depends:
    R (>= 2.10)
Imports:
    dplyr,
    httr,
    jsonlite,
    openssl,
    lubridate (>= 1.6.0),
    rlang,
    utils
Suggests:
    covr,
    ggplot2,
    knitr,
    rmarkdown,
    testthat
LazyData: true
Encoding: UTF-8
VignetteBuilder: knitr
RoxygenNote: 6.1.0.9000
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/inbo/wateRinfo

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

**data retrieval**: because the package provides R access to environmental data (water level and tidal information, discharge data, water quality variables, meteorological variables...) provided by the Flemish Environmental Agency. Without the package, people need to download data manually using the web interface or using the available API calls. The web interface, although evolving, does not support downloads for a list of stations and variables leading to lots of clicks to download data. The [API documentation ](https://www.waterinfo.be/download/9f5ee0c9-dafa-46de-958b-7cac46eb8c23?dl=0)is limited and only available in Dutch. The package overcomes these limitations, supporting downloads of multiple variables and stations more efficiently.

-   Who is the target audience and what are scientific applications of this package?  

Anyone interested in using the water-related data from waterinfo.be, for example hydrologists and ecologists. Scientific applications are ranging from environmental prediction and risk assessment modelling studies (e.g hydrological flood models) to ecological studies requiring environmental data. 

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

To our knowledge, there is no other R package to retrieve data from waterinfo.be. Although some loose scripts have been circulating among researchers from different institutes, this package aims to support a collaborative/community effort. 

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

    * NEWS file - there is one now, but only started with version 0.1.1 and using the ropensci structure since 0.2.0
    * Package name: Unfortunately, the name contains capital letters (wateRinfo), but this is how the package is already in use for almost a year
    * The main download function names are setup as `get_**` which does not use the `object_verb()` recommendation. As these are the main functions, we would keep the naming as such.
    * We did not use the `@family` tag as this provides full control on the order in between different sections. Considering the limited set of functionalities, the management of the `pkgdown` yml file is still feasible. 
    * We do run the documentation website locally before deployment.
    * The current set of untested functionalities consists of interactions (mainly exceptions) with the waterinfo.be API which are hard to replicate. 

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by sckott** [comment]
@stijnvanhoey et al. Do other regions of Belgium have water data available?  If so, can the pkg be generalized to use those other data?

**Comment by stijnvanhoey** [comment]
Good point. I'll try to provide an overview of the information I'm aware of. Notice that we have for water-related issues different governmental levels: national level and regional levels, i.e. Flanders, Walloon and Brussels). Rivers are monitored on regional (and subregional) level:
- The main data source for meteorological data (rainfall, evapotranspiration,...) on the national level is the [Royal Meteorological Institute of Belgium](http://www.meteo.be/meteo/view/en/65239-Home.html), but they do not provide open data for the moment.
- For the Walloon region, there is no data on the [open data platform](https://opendata.digitalwallonia.be/dataset?q=&tags=Environnement&sort=score+desc%2C+metadata_modified+desc), but there data on discharge on their [aqualim](http://aqualim.environnement.wallonie.be/login.do?time=1538594260100) website. The latter presents data from the [last 30 days online](http://aqualim.environnement.wallonie.be/Station.do?method=selectStation&time=1538594305999&station=L5201) and a form to [download data as an excel-sheet](http://aqualim.environnement.wallonie.be/Station.do?method=displayDownloadData&sParam=HAUT&typeGraph=GRAPH_HORAIRE&oper=H30&time=1538594384138) when providing contact details etc. For water quality, there are two websites: [aquapol](http://aquapol.environnement.wallonie.be/StationDataHisto.do?method=tableData) and [aquaphyc](http://aquaphyc.environnement.wallonie.be/GeneralPages.do?method=displayAccueil&menu1=accueil) providing water quality data for a number of stations. I do not have a direct idea how these could be incorporated (no REST or something alike services)? 
- For Brussels, the is no water data available on the [open data platform](https://opendata.brussel.be/page/home/). Their main river is *Zenne*, see the [map](https://leefmilieu.brussels/themas/water/water-brussel/het-blauwe-netwerk/kaart-van-de-waterlopen). I do know of a project [belini](http://life-belini.be/portfolio-item/monitoring/) with a monitoring component, but the data seems not available as open data or a webservice.
- The Flemish environmental agency (VMM) also provides data about [water quality](http://geoloket.vmm.be/Geoviews/), but they told us their water quality system is currently in redevelopment (with other endpoints), so rather something to take into scope when the new system will be in place. 
- There is a database/webportal on soil and groundwater in Flanders, called [DOV](https://www.dov.vlaanderen.be/), which is, among other subsoil data (e.g. geological data), the aggregator for groundwater time series. There is a current initiative to increase the number of data contributors to DOV and a Python package for data access to DOV is currently in development as well, https://github.com/dov-vlaanderen/pydov. As the groundwater level data is thematically (and technically) linked to the other data sources of DOV (geological interpretations, boreholes,...) we consider it out of scope for the wateRinfo package.

Notice that we opt for GBIF to publish species occurrences related to water, e.g. [fish](https://www.gbif.org/dataset/823dc56e-f987-495c-98bf-43318719e30f), so this data is covered by the rgbif package. 

As such, to my knowledge, there is no direct other source of data to incorporate. I'm adding @WillemMaetens (VMM), @pietercolpaert (open knowledge), @Sachagobeyn, @bartpannemans, @pjhaest to the discussion,  maybe they know about other initiatives?

**Comment by Sachagobeyn** [comment]
Dear all,

With respect to water quality data hosted by the VMM (Flanders): as I am currently aware, they are not available open source. They can be requested via the VMM website, however from my own experience, requests are often declined. An alternative for this type of information is the European Union Open Data Portal, in which ecological water quality, and a number of physico-chemical water quality variables are reported. For the latter, it should noted that data are only available for a few years. In addition, the datasets are not 'callable' as they are in waterinfo (zips hosted on the website). 

http://cdr.eionet.europa.eu/be
https://www.eea.europa.eu/data-and-maps

**Comment by sckott** [comment]
Thanks very much @stijnvanhoey and @Sachagobeyn for the thorough overview. 

It sounds like there are no other data sources at the moment, so we can move forward with this submission. 

assigning an editor now

**Comment by karthik** [comment]
👋 @stijnvanhoey. I’ll be editing your submission. Stay tuned for more instructions from me shortly.

**Comment by karthik** [comment]
### Editor checks:

- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [ ] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

👋 @stijnvanhoey. Apologies for the delay in assigning a reviewer (just returning from travels). Laura has kindly agreed to review. Given that we have a week off in November, I have given her a month to review this submission. I have also posted some results from the goodpractice check (from the `goodpractice` package). Please address these issues as they will also come up in the review.

```
---
── GP wateRinfo ────────────────────────────────────────────────────────────────

It is good practice to

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    R/token.R:44:1
    tests/testthat/test-token_usage.R:75:1
    tests/testthat/test-waterinfo_call.R:35:1

  ✖ fix this R CMD check ERROR: Running examples in
    ‘wateRinfo-Ex.R’ failed The error most likely occurred in: > ###
    Name: get_timeseries_tsid > ### Title: Download timeseries data
    from waterinfo.be > ### Aliases: get_timeseries_tsid > > ### **
    Examples > > get_timeseries_tsid("35055042", from = "2017-01-01",
    to = "2017-01-02") Timestamp Value Quality Code 1 2016-12-31
    23:00:00 0.00 130 2 2016-12-31 23:15:00 0.00 130 3 2016-12-31
    23:30:00 0.00 130 4 2016-12-31 23:45:00 0.00 130 5 2017-01-01
    00:00:00 0.00 130 6 2017-01-01 00:15:00 0.00 130 7
    ...
    Error: Waterinfo API request failed [500] Waterinfo error:
    InvalidParameterValue Waterinfo return message: Datasource
    parameter not found in config. Execution halted
  ✖ checking tests ... ERROR Running the tests in
    ‘tests/testthat.R’ failed. Last 13 lines of output: >
    library(testthat) > library(wateRinfo) > > test_check("wateRinfo")
    ── 1. Failure: non existing tsid to API (@test-waterinfo_call.R#21)
    ─────────── `call_waterinfo(query)` threw an error with unexpected
    message. Expected match: "Waterinfo API request
    failed.*InvalidParameterValue" Actual message: "API did not return
    json - " ══ testthat results
    ═══════════════════════════════════════════════════════════ OK: 104
    SKIPPED: 4 FAILED: 1 1. Failure: non existing tsid to API
    (@test-waterinfo_call.R#21) Error: testthat unit tests failed
    Execution halted
  ✖ fix this R CMD check WARNING: LaTeX errors when creating
    PDF version. This typically indicates Rd problems.
  ✖ fix this R CMD check ERROR: Re-running with no
    redirection of stdout/stderr. Hmm ... looks like a package You may
    want to clean up by 'rm -Rf /tmp/RtmpHVX5D6/Rd2pdf9fb1c6e9df4'
─────────────────────────────────────────────────────────────────────────
```


---


Reviewers: @ldecicco-usgs
Due date: Nov 29, 2018

**Comment by stijnvanhoey** [comment]
Thanks for the information. 

With respect to the issues with the example and unit tests: Apparently, the unique time series identifiers have changed on the [waterinfo.be](https://www.waterinfo.be/) side for a subset of stations. I was expecting them to be stable, but they are not. I'm doing the best I can to fix these issues asap.

**Comment by stijnvanhoey** [comment]
New version `fix-source-info` branch (will be merged soon), has following output for the `gp` command:

```
── GP wateRinfo ─────────────────────────────────────────────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in general. 87% of code lines are
    covered by test cases.

    R/call_waterinfo.R:58:NA
    R/call_waterinfo.R:59:NA
    R/call_waterinfo.R:60:NA
    R/call_waterinfo.R:61:NA
    R/call_waterinfo.R:62:NA
    ... and 49 more lines

  ✖ fix this R CMD check WARNING: LaTeX errors when creating PDF version. This typically
    indicates Rd problems.
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
```

One of the elements missing in the unit testing is the XML-parsing of a specific type of error. We encountered the issue earlier, but it is hard to reproduce systematically. Hence, we do not know exactly how to properly handle this. Advice is welcome.

**Comment by stijnvanhoey** [comment]
With respect to the Tex errors, I'm not completely aware on how to tackle this. I tried to execute  `devtools check` with the manual creation option:
```
devtools::check(document = FALSE, cleanup = TRUE, manual = TRUE)
```
I get the warning:

```
❯ checking PDF version of manual ... WARNING
  LaTeX errors when creating PDF version.
  This typically indicates Rd problems.
```

However, when I do check the logs and output in the `wateRinfo.Rcheck` folder, the `wateRinfo-manual.pdf` is there and the `Rdlatex.log` is (I just subset some potentially relevant sections):

```
Hmm ... looks like a package
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./Rd2.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 5 language(s) loaded.

...
No file Rd2.aux.
...
No file Rd2.toc.
...
Overfull \hbox (15.18042pt too wide) in paragraph at lines 370--370
...

Output written on Rd2.pdf (12 pages, 90183 bytes).
Transcript written on Rd2.log.
Saving output to ‘wateRinfo-manual.pdf’ ...
Done
You may want to clean up by 'rm -rf /tmp/RtmpeypCkA/Rd2pdf508051cc1987'
```
And the output looks like: [wateRinfo-manual.pdf](https://github.com/ropensci/onboarding/files/2557573/wateRinfo-manual.pdf) Another file, `wateRinfo-Ex.pdf` is also created, but *document contains no pages*. 

Any input on how to tackle this issue is certainly welcome.

**Comment by peterdesmet** [comment]
@ldecicco-USGS thank you so much for your review, this is really useful input.

**Comment by ldecicco-USGS** [comment]
Sounds great to me!

**Comment by stijnvanhoey** [comment]
Thanks!

**Comment by karthik** [comment]
Congrats @stijnvanhoey, your submission has been approved! 🎉 Thank you for submitting and @ldecicco-USGS for thorough and timely review. I'm very pleased with this package and find it very easy to use and well put together. To-dos:

- [ ] Transfer the repo to the rOpenSci organization under "Settings" in your repo.  I have invited you to a team that should allow you to do so.  You'll be made admin once you do.

- [ ] Add the rOpenSci footer to the bottom of your README

```
[![ropensci_footer](https://ropensci.org/public_images/ropensci_footer.png)](https://ropensci.org)

```
- [ ] Fix any links in badges for CI and coverage to point to the ropensci URL. (We'll turn on the services on our end as needed)

Welcome aboard! We'd also love a blog post about your package, either a short-form intro to it (https://ropensci.org/technotes/) or long-form post with more narrative about its development. ((https://ropensci.org/blog/). If you are, @stefaniebutland will be in touch about content and timing.

**Comment by stijnvanhoey** [comment]
@karthik can you please send the invite again, I can't find any invite to the organisation. Thanks

**Comment by karthik** [comment]
@stijnvanhoey I resent the invite. Once you accept, I will give you admin on it (can't do it till you accept).

**Comment by stijnvanhoey** [comment]
@karthik thanks, I'm member now.

**Comment by stijnvanhoey** [comment]
@karthik I transferred the repo, but apparently I should have added the `wateRinfo` team during transfer. Sorry to ask you again, could you provide the waterinfo team admin access to the repo? Thanks

**Comment by stefaniebutland** [comment]
@stijnvanhoey Your draft post will be great for the rOpenSci blog! Such a good weaving of practical and very engaging story with package use case. That video is incredible. We can publish on Jan 15, 2019.

Please submit your draft as a pull request by Jan 8 according to the instructions here: https://github.com/ropensci/roweb2#contributing-a-blog-post. That will give me an opportunity to review prior to publication.

Looking forward to this one!

**Comment by karthik** [comment]
@stijnvanhoey Your team should have full admin access on the repo now.

**Comment by stijnvanhoey** [comment]
@stefaniebutland Great! We'll make sure to have a version submitted by Jan 8. 
@karthik thanks for all the help, a PR is ready, just a single check on the coveralls link, https://github.com/ropensci/wateRinfo/pull/47

Any other admin we need to do or can I/you close this issue?

**Comment by karthik** [comment]
@stijnvanhoey  All good. Closing now. :tada:

**Comment by stijnvanhoey** [comment]
@stefaniebutland, we are running into deadline trouble with the blog post. The current version is available [here](https://github.com/stijnvanhoey/wateRinfo_post), but we still need to have some internal rewriting and review.  Would it still be ok to submit the PR on Monday? Our excuses for the rather late notice.

**Comment by stefaniebutland** [comment]
Not a problem @stijnvanhoey. We're very happy to host your post when it is ready.

If you submit a pull request on Monday I'll do my best to do a final review asap after it's in. My responses might be delayed, however, because I'm involved in a workshop next week. The post is in very good shape so I don't expect it will need many changes after my review. 

If you're not able to submit on Monday, then submit when ready and we can assign a different publication date.

rOpenSci will tweet about the post and you are welcome to suggest any tweet-content, preferred images or people who should be tagged and I will work to incorporate them.

Thank you for getting in touch!
