### ISSUE TITLE
Pre-submission inquiry: rromeo

### ISSUE THREAD

**Issue by Rekyt** [ropensci/software-review#273]
Submitting Author: Name (@Rekyt)  
Repository:   https://github.com/Rekyt/rromeo

---

-   Paste the full DESCRIPTION file inside a code block below:

```

Package: rromeo
Type: Package
Title: An R Client for SHERPA/RoMEO API
Version: 0.1.0
Authors@R: c(
  person("Matthias", "Grenié", email = REDACTED,
         role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4659-7522")),
  person("Hugo", "Gruson", email = REDACTED,
         role = "aut", comment = c(ORCID = "0000-0002-4094-1476"))
  )
Description: Provides an R Client for SHERPA/RoMEO API.
License: GPL (>= 2)
Encoding: UTF-8
LazyData: true
Imports: 
    httr,
    xml2
RoxygenNote: 6.1.1
Roxygen: list(markdown = TRUE)
Suggests:
    dplyr,
    ggplot2,
    knitr,
    rmarkdown,
    spelling,
    testthat,
    tidyr,
Language: en-US
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package provides an R wrapper to the [SHERPA/RoMEO API](www.sherpa.ac.uk/romeo/index.php). SHERPA/RoMEO is a database that aggregates open access policies and summarises self-archiving permissions and conditions given to authors by scientific journals.

-   Who is the target audience and what are scientific applications of this package?  

People working in the field of bibliometry or researchers curious about the open access policies of the journals in their communities. We aim to provide an example of analysis of open access policies in Ecology and Evolution in the vignette showing the kind of scientific application of the package.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

We are not aware of any other R package providing similar access to this database.

-  Any other questions or issues we should be aware of?:

This package is still in the making (it needs more user-friendly documentation & vignette) but I'm submitting an inquiry to know to what extent it could interest the rOpenSci community.

**Comment by sckott** [comment]
Thanks very much for your submission @Rekyt - We're discussing now

**Comment by sckott** [comment]
@Rekyt the appropriate category is likely **data retrieval**

**database access** is defined as 

> Bindings and wrappers for generic database APIs (Example: [rrlite](https://github.com/ropensci/rrlite))

`database` meaning a piece of software that is a database - e.g., if your package was an R client for SQLite database, then **database access** would be appropriate.

**Comment by sckott** [comment]
Hi @Rekyt - It is a good fit and we welcome a full submission 👍

**Comment by Rekyt** [comment]
Thank you for the rapid examination @sckott!
