### ISSUE TITLE
Interest in submitting an original R package: hhi

### ISSUE THREAD

**Issue by pdwaggoner** [ropensci/software-review#275]
Submitting Author: Name (@pdwaggoner)  
Repository: https://github.com/pdwaggoner/hhi   

---

-   Paste the full DESCRIPTION file inside a code block below:

```{r}
Package: hhi
Type: Package
Title: Calculate and Visualize the Herfindahl-Hirschman Index
Version: 1.2.0
Author: Philip D. Waggoner <pdwaggoner@wm.edu>
Maintainer: Philip D. Waggoner <pdwaggoner@wm.edu>
Description: Based on the aggregated shares retained by individual firms or actors within a market or space, the Herfindahl-Hirschman Index (HHI) measures the level of concentration in a space. This package allows for intuitive and straightforward computation of HHI scores, requiring placement of objects of interest directly into the function. The package also includes a plot function for quick visual display of an HHI time series using any measure of time (year, quarter, month, etc.). For usage, please cite the Journal of Open Source Software paper associated with the package: Waggoner, Philip D. (2018) <doi:10.21105/joss.00828>.
License: MIT + file LICENSE
Imports: ggplot2
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [X] reproducibility (and `other` from sec. 5.2.2 of the policies link above)
	- [ ] geospatial data
	- [ ] text analysis

	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

My package, `hhi`, fits under reproducibility as well as the generally "other" category as it streamlines the use of the Herfindahl-Hirscman Index in many domains of applied statistical research. I recently authored a paper on the applicability of it at JOSS: http://joss.theoj.org/papers/10.21105/joss.00828. It helps with both reproducible research and also clean, efficient research (hence the secondary "other" category, based on the description in sec. 5.2.2 in the policies: "Packages should be general in the sense that they should solve a problem as broadly as possible while maintaining a coherent user interface and code base.")

-   Who is the target audience and what are scientific applications of this package?  

The target audience is a any applied researcher interested in competition or concentration in a variety of forms. From concentration and density of galaxies to firms in a competitive common space, the package facilitates efficient calculation and visualization of one of the most widely used measures of concentration.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

None to my knowledge that are solely dedicated to the HHI.

-  Any other questions or issues we should be aware of?:

The package is currently on CRAN (1.2.0) and has an associated paper mentioned above at JOSS. Please don't hesitate to reach out if you need anything else from me in the regard of ir you have questions. Happy to do whatever I can, as I think this is a good, simple tool for a variety of researchers in a variety of domains. Thanks for considering!

**Comment by sckott** [comment]
thanks very much for your pre-sub inquiry @pdwaggoner  we're discussing now and will have a decision soon

**Comment by sckott** [comment]
hi again. We have dicsussed this and have decided that it is out of scope because in our view it's mainly a methods package. That is, it's an implementation of a method, see https://ropensci.github.io/dev_guide/policies.html#other-scope-considerations 

Thanks again for your inquiry!

**Comment by pdwaggoner** [comment]
I get it - thanks for letting me know and for considering!

All best,
Phil
