### ISSUE TITLE
Pre-Submission Inquiry: tacmagic

### ISSUE THREAD

**Issue by eebrown** [ropensci/software-review#277]
Submitting Author: Eric Brown (@eebrown)  
Repository:   https://github.com/eebrown/PET/tree/devel

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: tacmagic
Type: Package
Title: tacmagic: PET Analysis in R
Version: 0.1.8.9000
Authors@R: c(person("Eric", "Brown", 
                    role = c("aut", "cre"),
                    email = "eb@ericebrown.com",
                    comment = c(ORCID = "0000-0002-1575-2606")))
Description: To faciliate analysis of positron emission tomography (PET) time
    activity curve (TAC) data, and to encourage open science and replicability,
    this package supports data loading and analysis of multiple TAC file 
    formats. Functions are available to analyze loaded tac data for individual 
    participants or in batches. Major functionality includes weighted TAC 
    merging by region of interest (ROI), calculating models including SUVR and
    DVR, basic plotting functions and calculation of cutoff values. Please see
    the walkthrough vignette for a detailed overview of tacmagic functions.
Depends: R (>= 3.4)
License: GPL-3
URL: https://github.com/eebrown/PET
BugReports: https://github.com/eebrown/PET/issues
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Imports: 
    graphics, 
    grDevices, 
    pracma, 
    utils,
    R.matlab
Suggests:
    testthat,
    knitr,
    rmarkdown,
    covr
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [x] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

A major feature of this package is to support the loading of positron emission tomography (PET) time-activity curves (TACs) from several different major formats, to allow a common subsequent analysis pipeline within R. This should satisfy "data extraction". There are functions to support merging of regional time-activity curves, an often important analysis step, which should qualify as "data munging". Additional analysis is available in the package, which I am unsure whether is included in the scope, but which I hope is allowed. By virtue of being open source and offering support for multiple formats and pipelines, this package promotes open science reproducibility.

-   Who is the target audience and what are scientific applications of this package?  

Scientists working with PET data who would like to analyze TAC data in R can take advantage of the loading (including batch loading) functions and basic plotting. Those who need basic non-invasive models can take advantage of the implemented models. We will invite contributors to extend the package in its support for file formats and models.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There do not appear to be packages that offer the loading and merging functions. There are packages that have some PET models implemented but not full overlap.

-  Any other questions or issues we should be aware of?:

This package is very close to being ready for submission. Thank you for clarifying whether it meets the scope requirements.

**Comment by sckott** [comment]
Thanks for your submission @eebrown Editors will discuss and get back to you soon

**Comment by eebrown** [comment]
Wonderful, thanks!

**Comment by sckott** [comment]
@eebrown we've decided it's in scope. we welcome a full submission

**Comment by eebrown** [comment]
That's great news. We will make the final preparations for submission. Thanks, @sckott.
