### ISSUE TITLE
Pre-submission inquiry. ghr: Explore & access GitHub directories

### ISSUE THREAD

**Issue by maurolepore** [ropensci/software-review#283]
Submitting Author: Mauro Lepore (@maurolepore)  
Repository:   https://github.com/maurolepore/ghr

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ghr
Title: Explore and Access GitHub Directories
Version: 0.0.0.9001
Authors@R: 
    person(given = "Mauro",
           family = "Lepore",
           role = c("aut", "cre"),
           email = "maurolepore@gmail.com",
           comment = c(ORCID = "0000-0002-1986-7988"))
Description: Explore and access GitHub directories using an
    intuitive syntax of the form "owner/repository/subdirectory@branch".
License: GPL-3
URL: https://github.com/maurolepore/ghr
BugReports: https://github.com/maurolepore/ghr/issues
Depends:
    R (>= 3.2)
Imports: 
    gh (>= 1.0.1),
    glue (>= 1.3.0),
    memoise (>= 1.1.0),
    purrr (>= 0.3.0)
Suggests: 
    covr (>= 3.2.1),
    magrittr (>= 1.5),
    rmarkdown (>= 1.11),
    spelling (>= 2.0),
    testthat (>= 2.0.1)
Encoding: UTF-8
Language: en-US
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

__Data retrieval:__ {ghr} directly retrieves components of a GitHub-API response, and indirectly retrieves data, for example, with a code of this form:

```R
path <- "owner/repo/folder@branch"
ghr::ghr_ls_download_url(path, regexp = "[.]csv$") %>% 
  readr::red_csv()`.
```

__Database access:__ {ghr} provides access to a "GitHub database", i.e. a collection of data files hosted on one or more GitHub organizations and repositories.

-   Who is the target audience and what are scientific applications of this package?  

{ghr} targets GitHub users in general and researchers in particular. Researchers can easily extend {ghr} to create a custom interface to access the datasets they host on GitHub.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

What you can do with {ghr} you can also do with {[gh](https://github.com/r-lib/gh)} plus a good understanding of the [GitHub API](https://developer.github.com/v3/). {ghr} shines because it makes it easy to create a request (using a syntax inspired by `remotes::install_github()`) and to search directories (using an interface inspired by `fs::dir_ls()`).

-  Any other questions or issues we should be aware of?:

No.

**Comment by sckott** [comment]
Thanks for your submission @maurolepore ❗️ ❗️ 

We have discussed and we have decided this submission is out of scope. Referencing our scope page https://ropensci.github.io/dev_guide/policies.html#package-categories under __data retrieval__ retrievavl packages should be focused on data sources/topics rather than services

**Comment by maurolepore** [comment]
Thanks @sckott for your consideration. I'm sorry to have misinterpreted the scope; I hope I didn't waste too much of you time. Next time I'll be sure to see more examples and in more detail before I decide if my submission would be a good fit.
:)

**Comment by sckott** [comment]
No need to say sorry! Not a waste of our time at all.  And don't take this decision as reflective of the quality/etc. of your pkg, it's just about scope
