### ISSUE TITLE
Presubmission inquiry: opentripplanner

### ISSUE THREAD

**Issue by mem48** [ropensci/software-review#291]
Submitting Author: Malcolm Morgan (@mem48)  
Repository:   https://github.com/ITSLeeds/opentripplanner

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: opentripplanner
Title: Open Trip Planner for R
Version: 0.0.1.0000
Authors@R: c(
    person("Marcus", "Young", email = "M.A.Young@soton.ac.uk", role = c("aut", "cre")),
    person("Malcolm", "Morgan", email = "m.morgan1@leeds.ac.uk", role = c("aut"), comment = c(ORCID = "0000-0002-9488-9183")),
    person("Robin", "Lovelace", role = c("ctb"))
    )
Description: An interface for Open Trip Planner <http://www.opentripplanner.org/>.
    OpenTripPlanner (OTP) is an open source platform for multi-modal and multi-agency
    journey planning written in Java. OTP provides a REST API which Open Trip Planner
    for R uses to connect to OTP.
License: GPL-3
Encoding: UTF-8
LazyData: true
Imports:
    checkmate,
    httr,
    sf,
    googlePolylines,
    dplyr,
    geosphere,
    jsonlite,
    pbapply
RoxygenNote: 6.1.1
Suggests: 
    testthat,
    knitr,
    rmarkdown
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
Open Trip Planner is a multimodal route planning tool written in Java, the package allows R users to access the functionality of Open Trip Planner running locally or on a server. So, the package performs the role of data retrieval of geospatial data.

-   Who is the target audience and what are scientific applications of this package?  
Transport planners and people engaging in transport-related research.  Route planning is the basis of many different transport related research questions such as traffic management, accessibility measurement, and infrastructure planning. The package is being actively developed to support research at the University of Leeds Institute for Transport Studies.
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There are many packages that enable route planning in R (e.g. osrmr &  dodgr) However there are no packages on CRAN that connect R to the Open Trip Planner. We are aware of one package on GitHub (https://github.com/datasciencecampus/access-to-services/tree/develop/propeR ) which relates to connecting R and OTP although its purpose is more specialised.
A key benefit of OTP over other route planning tools is its integration of public transport and other modes of travel (e.g. bike hire) that are not supported by other tools such as osrm.

-  Any other questions or issues we should be aware of?:
Open Trip Planner requires Java 8 to be installed, the vignettes outline the basics of installing and setting up Java and the OTP.

**Comment by melvidoni** [comment]
Thanks for your submission @mem48. Editors will discuss and get back to you soon.

**Comment by melvidoni** [comment]
Hello again @mem48. After a discussion, we've decided it's in scope. we welcome a full submission.
Good luck, I am closing the issue now.

**Comment by mem48** [comment]
@melvidoni Great I'll get started on a full submission
