### ISSUE TITLE
Presubmission inquiry: holodeck

### ISSUE THREAD

**Issue by Aariq** [ropensci/software-review#293]
Submitting Author: Eric Scott (@Aariq)  
Repository:   https://github.com/Aariq/holodeck

---

```
Package: holodeck
Title: A Tidy Interface for Simulating Multivariate Data
Version: 0.1.0
Authors@R: 
    person(given = "Eric",
           family = "Scott",
           role = c("aut", "cre"),
           email = "scottericr@gmail.com")
Description: Provides pipe-friendly (%>%) functions to create simulated multivariate data sets
    with groups of variables with different degrees of variance, covariance, and effect size. 
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
biocViews:
Imports: 
    dplyr,
    tibble,
    MASS,
    purrr,
    rlang,
    assertthat
RoxygenNote: 6.1.1
URL: https://github.com/Aariq/holodeck
BugReports: https://github.com/Aariq/holodeck/issues
Suggests: 
    testthat,
    covr,
    knitr,
    rmarkdown,
    iheatmapr,
    mice,
    ropls,
    ggplot2
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package provides dplyr friendly wrappers for MASS::mvrnorm() to simplify generation of multivariate data frames with different covariance structures.  I've used it primarily for generating data under different scenarios in order to test different statistical methods.  I'm unsure if its enough of a simplification over the usual route of making a variance-covariance matrices, passing them to mvrnorm(), then converting the resulting matrices into dataframes, and joining them together.

-   Who is the target audience and what are scientific applications of this package?  

Anyone learning about the properties of multivariate data analysis techniques, or using simulated data to formally test properties of analysis techniques.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

As I mentioned before, this could be done with MASS, but my package simplifies things and makes the code more readable.

-  Any other questions or issues we should be aware of?:

I'm just not sure if it's a good fit or if it's doing enough as a wrapper to be in scope.  Thanks.

**Comment by melvidoni** [comment]
Hello @Aariq, thank you for your submission. The editors have discussed your inquiry. This seems to be a very useful package, however, it is out-of-scope for onboarding since it may be too statistical, and only converting data.

We hope you will find an appropriate venue for your package, and wish you the best.

**Comment by Aariq** [comment]
Thank you for the quick response and the feedback!
