### ISSUE TITLE
Presubmission inquiry: chemspiderapi

### ISSUE THREAD

**Issue by RaoulWolf** [ropensci/software-review#294]
Submitting Author: Raoul Wolf (@RaoulWolf)  
Repository: https://github.com/NIVANorge/chemspiderapi  

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: chemspiderapi
Type: Package
Title: R wrapper for ChemSpider's new API services
Version: 0.0.1.0000
Authors@R: person("Raoul", "Wolf", email = "raoul.wolf@niva.no", role = c("aut", "cre"))
Description: ChemSpider has announced a fundamental change to the syntax of their API services in late 2018.
    This package provides convenience wrappers for the new API functionalities of ChemSpider, as well as complementary functions, e.g., to save pictures or MOL files.
License: MIT + file LICENSE
Imports: 
    curl, 
    jsonlite,
    png
Suggests: 
    keyring,
    memoise,
    ratelimitr,
    testthat
URL: https://github.com/NIVANorge/chemspiderapi
Encoding: UTF-8
LazyData: true
ByteCompile: true
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [X] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The `chemspiderapi` package is an easy-to-use R interface to use all new ChemSpider API functionalities, as introduced in ChemSpiders complete redesign of its API structure late 2018.  

-   Who is the target audience and what are scientific applications of this package?  

Researchers and citizen scientists who work on anything chemistry-related and need to routinely query against any of ChemSpider's API services.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The rOpenSci-maintained package `webchem` aims at offering (currently outdated / not working) functionality for accessing ChemSpider's API services. However, the redesign of ChemSpider's API structures in late 2018 broke all available functionalities. 

Because of the complete redesign, I think a separate ChemSpider API package is necessary. The new workflow of POSTing a query -> GETing a status -> GETing a result is different from all `webchem` query approaches and requires a "best practice" approach to use it sustainably (i.e., not ruining your quota).

`chemspiderapi` currently supports *every* functionality of ChemSpider's new API services as well as additional "convenience" functionalities.

-  Any other questions or issues we should be aware of?:

Testing has under API quota constraints has been difficult for me and I would welcome suggestions on improving this aspect of the package.

ChemSpider is aware of the `chemspiderapi` package and has shown passive support via Twitter.

**Comment by melvidoni** [comment]
Hello @RaoulWolf, thank you for your submission. Editors are now discussing this.

**Comment by melvidoni** [comment]
Hello again @RaoulWolf . After a discussion, we've decided it's in scope. we welcome a full submission.
Good luck, I am closing the issue now.
