### ISSUE TITLE
Presubmission inquiry: stringapi

### ISSUE THREAD

**Issue by MahShaaban** [ropensci/software-review#296]
Submitting Author: Name (@MahShaaban)  
Repository:  https://github.com/MahShaaban/stringapi

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: stringapi
Type: Package
Title: An R client for STRING API
Version: 0.1.0
License: GPL-3
Authors@R: person("Mahmoud", "Ahmed",
  email = "mahmoud.s.fahmy@students.kasralainy.edu.eg",
  role = c("aut", "cre"))
URL: https://github.com/MahShaaban/stringapi
BugReports: https://github.com/MahShaaban/stringapi/issues
Description: Provide a set of functions to interact with the STRING API in R.
  The functions are organized a round the API database and request types. The
  query parameters are checked and the output is returned in a tibble.
Encoding: UTF-8
LazyData: true
Imports: httr,
  readr
Suggests: 
    testthat,
    covr
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package wraps the STRING v11 API to provide access to the database from R.

-   Who is the target audience and what are scientific applications of this package?  

Researchers in bioinformatics, computational science and biology.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I am aware of at least one Bioconductor package by the maintainers of STRING. The package is called [STRINGdb](https://bioconductor.org/packages/release/bioc/html/STRINGdb.html).  `STRINGdb` does more than just accessing the database and it can be a bit tricky to install. Last I checked the package uses v10, the database itself is in v11 now.

-  Any other questions or issues we should be aware of?:

If there is an interest, I will work on improving the code and the docs.

**Comment by noamross** [comment]
Thank your for your inquiry, @MahShaaban!  I am not yet sure if this package can meet or maintain best-in-category designation.  STRINGdb installs via the standard Bioconductor methods (an alternative system to CRAN but a robust one), and it is not an issue that it has _more_ functionality. I understand the V11 of the API has more functionality and data, but as STRINGdb has been maintained through multiple versions of the API, I would expect it to update. Do you know if it will or have you contacted the STRINGdb maintainers about it?

**Comment by MahShaaban** [comment]
Thanks @noamross. Please, let me clarify. Of course it is not an issue to have more functionality. What I meant is, the package does more, so it has more dependencies including Bioconductor and this increases the install requirements. 
I have not contacted the maintainers about updating the package.

**Comment by noamross** [comment]
I would ask that you contact the maintainers. From my perspective the primary justification accepting this would be it's support of v11 and the additional data, but if STRINGdb is likely to be updated to support v11, we would not likely accept this submission.

**Comment by MahShaaban** [comment]
Alright. Thanks @noamross for your time.
