### ISSUE TITLE
Applicability of 'rnassqs' as a Ropensci package.

### ISSUE THREAD

**Issue by potterzot** [ropensci/software-review#297]
Submitting Author: Nicholas Potter (@potterzot)  
Repository: https://github.com/potterzot/rnassqs

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rnassqs
Type: Package
Title: Access the NASS 'Quick Stats' API
Version: 0.4.0.9000
Date: 2019-04-29
Authors@R: c(
  person('Nicholas', 'Potter', email='potter.nicholas@gmail.com', role = c('aut', 'cre')),
  person('Joseph', 'Stachelek', email='', role = c('ctb')),
  person('Julia', 'Piaskowski', email='', role = c('ctb'))) 
Maintainer: Nicholas Potter <potter.nicholas@gmail.com>
Description: Interface to access data via the United States Department of 
  Agricultre's National Agricultural Statistical Service (NASS) 'Quick Stats' 
  web API <https://quickstats.nass.usda.gov/api>. Convenience functions 
  facilitate building queries based on available parameters and valid parameter 
  values.
URL: https://github.com/potterzot/rnassqs
BugReports: http://www.github.com/potterzot/rnassqs/issues
License: MIT + file LICENSE
LazyData: TRUE
Language: en-US
Imports:
  httr,
  jsonlite,
Suggests:
  testthat,
  here,
  knitr,
  rmarkdown
RoxygenNote: 6.1.1
Encoding: UTF-8
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [X] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package is a set of functions to access the USDA National Agricultural Statistical Service (NASS) 'Quick Stats' API. It is used for making http GET requests and returning data.

-   Who is the target audience and what are scientific applications of this package?  

Target audience is those who want to automate or reproducibly fetch data from 'Quick Stats', including agronomists, economists, and others working with agricultural data. Scientific applications include analysis of agricultural data by administrative region (e.g. county, state, watershed), economic analysis of policies that affect agriculture, and sociological/demographic analysis of agricultural producers over time.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I have not been able to find another package that provides this access. To my knowledge there is no other R package that interfaces with 'Quick Stats'.

-  Any other questions or issues we should be aware of?:

**Comment by noamross** [comment]
Thanks for your inquiry, @potterzot.  Yes, this package falls in-scope for us.  We welcome a full submission.

**Comment by potterzot** [comment]
Wonderful, thank you!
