### ISSUE TITLE
Presubmission inquiry: chlorpromazineR

### ISSUE THREAD

**Issue by eebrown** [ropensci/software-review#306]
Submitting Author: Eric Brown (@eebrown)  
Repository: https://github.com/eebrown/chlorpromazineR

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: chlorpromazineR
Title: Convert Antipsychotic Doses to Chlorpromazine Equivalents
Version: 0.0.0.9000
Authors@R: 
    c(person(given = "Eric",
             family = "Brown",
             role = c("aut", "cre"),
             email = "eb@ericebrown.com"),
      person(given = "Parita",
             family = "Shah",
             role = "aut"),
      person(given = "Julia",
             family = "Kim",
             role = "aut"))
Description: As different antipsychotic medications have different potencies, the doses of different medications cannot be directly compared. Various strategies are used to convert doses into a common reference so that comparison is meaningful. Chlorpromazine (CPZ) has historically been used as a reference medication into which other antipsychotic doses can be converted, as "chlorpromazine-equivalent doses". Using conversion keys generated from widely-cited scientific papers (Gardner et. al 2010 <https://doi.org/10.1176/appi.ajp.2009.09060802>, Leucht et al. 2016 <https://doi.org/10.1093/schbul/sbv167>), antipsychotic doses are converted to CPZ (or any specified antipsychotic) equivalents. The use of the package is described in the included vignette. Not for clinical use.
URL: https://github.com/eebrown/chlorpromazineR
BugReports: https://github.com/eebrown/chlorpromazineR/issues
Depends: R (>= 3.5)
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Suggests: 
    knitr,
    rmarkdown,
    testthat,
    covr
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package should fall within "data munging" by virtue of its main feature - to convert antipsychotic doses into a common reference equivalent. It fosters reproducibility as the current practice is typically to reference the source paper without showing the conversion method (which if done manually, though simple, is prone to error). This improves accuracy and transparency.

-   Who is the target audience and what are scientific applications of this package?  

Researchers in psychiatry/neuroscience involving antipsychotic medications often need to calculate equivalent doses, which is why the papers describing such methods are widely cited. Yet, there is no R package that facilitates this. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

None to my knowledge.

-  Any other questions or issues we should be aware of?:

**Comment by noamross** [comment]
Hello @eebrown, thanks for your inquiry! The editors have discussed this and agree this would be in-scope under the data access / data munging categories. We'd welcome a full submission.
