### ISSUE TITLE
Presubmission inquiry: exo

### ISSUE THREAD

**Issue by tyluRp** [ropensci/software-review#308]
Submitting Author: Tyler Littlefield (@tylurp)  
Repository: https://github.com/tyluRp/exo

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: exo
Title: Provides access to NASA's Exoplanet Archive, see <https://exoplanetarchive.ipac.caltech.edu/index.html>
Version: 0.0.0.9000
Authors@R: 
    person(given = "Tyler",
           family = "Littlefield",
           role = c("aut", "cre"),
           email = "tylurp1@gmail.com")
Description: The goal of exo is to provide access to NASA's Exoplanet Archive 
  database in by table name or by writing the URL query manually. For more
  information please read the documentation 
  <https://exoplanetarchive.ipac.caltech.edu/index.html>.
Depends: R (>= 2.10)
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Suggests: 
    tibble,
    testthat (>= 2.1.0),
    covr
Imports: 
    utils
URL: https://github.com/tyluRp/exo
BugReports: https://github.com/tyluRp/exo/issues
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package falls under the **data retrieval** category because it pulls data from [NASA's Exoplanet Archive Database](https://exoplanetarchive.ipac.caltech.edu/index.html).

-   Who is the target audience and what are scientific applications of this package?  

     * Target Audience: astronomers, space enthusiasts, NASA datanauts
     * Applications: Planet hunting

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

None that I am aware of, there is a [thread](https://github.com/ropensci/unconf17/issues/67) that discusses NASA APIs but I'm not sure if the Exoplanet Archive was ever targeted or implemented in an R package. Additionally there is [nasadata](https://github.com/Eflores89/nasadata) which provides access to NASA's EONET API. Same API page but doesn't include the Exoplanet archive as far as I can tell.

-  Any other questions or issues we should be aware of?:

I have one issue with the name of the package. Considering changing it to `exoplanets` to be more clear.

**Comment by noamross** [comment]
Thank you for the inquiry @tyluRp! This is straightforwardly in-scope for us as a data retrieval package, and we'd welcome a full submission. From a quick glance I see you don't yet have a vignette - you will need one to pass initial editor checks.  I agree that the name change makes it more clear what the package's purpose is.
