### ISSUE TITLE
Submission: gpdd

### ISSUE THREAD

**Issue by AlexLi0104** [ropensci/software-review#310]
Submitting Author: Zihao Li (@AlexLi0104)  
Repository:   https://github.com/boettiger-lab/gpdd
Version submitted:   1.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gpdd
Title: Download datasets from the Global Population Dynamics Database
Version: 0.0.0.9001
Authors@R: as.person(c(
    "Carl Boettiger <cboettig@berkeley.edu> [aut, cre]",
    "Zihao Li <zihao0104@berkeley.edu> [aut]",
    "Brian Blair <r@ninth.cat> [aut]"
  ))
Description: This package downloads and saves datasets from the Global Population Dynamics Database (GPDD),
    a large collection of animal and plant population data. All data and information, including
    metadata and user guide, could be accessed through the KNB website (https://doi.org/10.5063/F1BZ63Z8).
URL: https://github.com/boettiger-lab/gpdd
BugReports: https://github.com/boettiger-lab/gpdd/issues
License: file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.0
Imports:
    readr,
    rappdirs,
    crayon,
    utils
VignetteBuilder:
    utils,
    knitr
Suggests:
    testthat,
    knitr,
    rmarkdown,
    covr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
This package downloads and loads data from the Global Population Dynamic Database. 

-   Who is the target audience and what are scientific applications of this package?  
The target audience would be researchers who want to use the GPDD data. This package can be helpful in investigating scientific (e.g. ecological) questions that use GPDD data.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
We are not aware of other packages that accomplish the same thing.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by noamross** [comment]
Thank your for your submission, @AlexLi0104!  

After some discussion amongst the editors, we decided that this package is not in scope for rOpenSci.  The relevant portion of [our policies](https://ropensci.github.io/dev_guide/policies.html#aims-and-scope) is this:

> Packages should be general in the sense that they should solve a problem as broadly as possible while maintaining a coherent user interface and code base. For instance, if several data sources use an identical API, we prefer a package that provides access to all the data sources, rather than just one.

No doubt your package would be useful to heavy users of GPPD! The challenge with packages like yours is that we could easily have an unmanageable number of packages which download specific data sets from KNB. We think it would be better for us to maintain general packages that allow users to access any data set from a repository, unless the packages address address specific challenges that arise from particular data sets.
