### ISSUE TITLE
Presubmission enquiry: gitgantt

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/software-review#311]
Submitting Author: Name (@robinlovelace)  
Repository:   https://github.com/Robinlovelace/gitgantt

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gitgantt
Title: Create Gantt Charts with GitHub Issues and R
Version: 0.0.0.9000
Authors@R: 
   person("Robin", "Lovelace", email = "rob00x@gmail.com", role = c("aut", "cre"),
      comment = c(ORCID = "0000-0001-5679-6536"))
Description: Downloads GitHub issues that have GanttStart and GanttDue tags and converts them into Gantt charts.
License: GPL-3
Encoding: UTF-8
LazyData: true
Imports: 
    gh,
    stringr,
    purrr,
    tibble,
    timevis
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Creating project plans is often a frustrating and non-reproducible process. This package can help ensure reproducibility, transparency and integration with community/team by linking a key part of a project plan with GitHub issues.

-   Who is the target audience and what are scientific applications of this package?  

Anyone needing project time-lines, e.g. for funding applications, communicating planned work, communicating the status of scientific projects and packages.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

See https://github.com/Robinlovelace/gitgantt#thanks

-  Any other questions or issues we should be aware of?:

I have needed this package many times in the past an wasted hours creating gantt charts using many adhoc workflows, sometimes involving Microsoft Excel. I think it's an issue that really slows many projects down and leads to duplication of effort between GitHub tracking and 'client facing' plans. Finally I've developed something that works! I don't have a huge amount of time for maintenance, but suspect it could be very useful to many people, so thinking that if it's in a community-supported place like rOpenSci that could help me, and potential users, ensure it's robust and well maintained. Have already asked @mpadge and @layik to take a look, but think having eyes of a much larger community could greatly benefit this nascent project. Any thoughts on best way forward very welcome.

**Comment by noamross** [comment]
Thanks for the inquiry, @Robinlovelace! This looks useful (I may use it myself!), but it is out-of-scope for us.

You may want to comment on this proposal we have to clarify Aims and Scope by breaking up the "reproducibility" category into its specific parts: https://github.com/ropensci/software-review-meta/issues/81 .

**Comment by Robinlovelace** [comment]
Thanks @noamross, closing for now in that case. The idea is to get the word out there and invite feedback. Do you have any further advice on how to go about that? ATFutures, which also hosts the [`calendar`](https://github.com/ATFutures/calendar) package, is my default plan for a home for this. To anyone else who reads this: new issues/PRs are very welcome https://github.com/Robinlovelace/gitgantt/issues

**Comment by noamross** [comment]
I've long suggested that people use our [forum](https://discuss.ropensci.org/) to solicit feedback on packages/projects that weren't explicitly in our peer-review process.  In the past this has limited success, but I think that we finally have gotten enough people on the forum through other projects that there's a critical mass.  And maybe I can get @stefaniebutland and @sckott to add a "This week on the forum" to our newsletter and do something similar on Twitter/Slack 😉

**Comment by maelle** [comment]
You can also post the link to the package to R Weekly, and if you write a blog post somewhere explaining what the package does and where help is needed, that link too can go to R Weekly.

**Comment by stefaniebutland** [comment]
I've opened an issue for myself to be intentional about @noamross's suggestion

**Comment by Robinlovelace** [comment]
One follow-up on this: I posted this after seeing gitignore accepted as it aids reproducibility: https://github.com/ropensci/software-review/issues/303

The statements as to why it fits that category were "Because it helps facilitate use of version control." Thinking about it, I would say the aim of this package is similar: it aids the use of a version control and collaboration platform in a way that should encourage transparent (in that the plans will be visible publicly rather than just in private reports or funding applications) and reproducible (because the visuals can be reproduced, unlike most time planning software) work.

Clarification welcome, hope this helps rOpenSci process if nothing else.

**Comment by Robinlovelace** [comment]
Looking at https://github.com/ropensci/software-review-meta/issues/81  I just spotted:

> Scientific workflow automation and testing

Could it fit that category? I guess it depends whether project management and timeline generation is defined as part of a scientific workflow. `gitgantt` certainly automates it.

**Comment by noamross** [comment]
Thanks for your follow-up @Robinlovelace. Certainly there are grey areas in this and we're always adjusting and refining as we find new edge cases or priorities.  You didn't leave anything out of your justification - we consider qualification against all categories, using authors' justification as a place to start.  It's my opinon that **gitgantt** still falls out of scope, in that it primarily uses other features of GitHub than version control itself, and falls into scientific workflow only if we would include any report-generating package in our scope.

That said, I am hoping to take this for a spin soon - I think it would be neat to incorporate a project gantt chart right into it's website.

**Comment by Robinlovelace** [comment]
Hi @noamross thank you for the follow-up too. Makes sense. Gantt chart / timeline report generation is not something that is specific to *scientific* work. I put it together for one specific project. Will be stoked if it's of use for others. Any feedback very welcome. @mpadge has raised the possibility of going further, creating a project management tool that can read and write to GH issues but for now I think the priority is polishing what is already there, perhaps with a focus on nice default visuals.

**Comment by maelle** [comment]
If you two take it further have a look at https://github.com/emilyriederer/projmgr that has similar aims I think.

**Comment by Robinlovelace** [comment]
That looks awesome! One option could be to integrate the timeline code into that project.
