### ISSUE TITLE
economiccomplexity

### ISSUE THREAD

**Issue by pachamaltese** [ropensci/software-review#312]
Submitting Author: Mauricio "Pachá" Vargas (@pachamaltese)  
Repository: https://github.com/pachamaltese/economiccomplexity

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: economiccomplexity
Type: Package
Title: Methods used in the Economic Complexity literature
Version: 0.1.0
Authors@R: c(
    person(given = "Mauricio",
      family = "Vargas",
      role = c("aut", "cre", "cph"),
      email = "mvargas@dcc.uchile.cl",
      comment = c(ORCID = "0000-0003-1017-7574")
    ),
    person(given = "Carlo",
      family = "Bottai",
      role = c("ctb"),
      email = "carlo.bottai@unito.it",
      comment = "improved the eigenvalues calculation"
    ),
    person(family = "Open Trade Statistics",
      role = "dtc"),
    person(family = "Center for International Development at Harvard University",
      role = "dtc")
  )
Description: A wrapper of different indices and networks commonly used in Economic Complexity
  to explore bipartite relations such as countries and their exported products. These methods
  are also useful for different kind of relations such as countries and their spoken languages.
License: GPL-3
Encoding: UTF-8
LazyData: true
Imports: methods, magrittr, tibble, dplyr, tidyr, Matrix, igraph, rlang
Depends: R (>= 2.10)
BugReports: http://github.com/pachamaltese/economiccomplexity/issues
RoxygenNote: 6.1.1
Suggests: 
    testthat (>= 2.1.0)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
        - [x] scientific software wrappers
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

I read The Atlas of Economic Complexity and I wanted to provide an R package that does exactly what they propose and present as equations and text paragraphs. This package introduces some novel formulas to explore bipartite relations such as countries-products, which is somehow related to tradestatistics package.

-   Who is the target audience and what are scientific applications of this package? 

The general audience is people from Economics and Sociology.
In particular, people interested in Economic Complexity (quite new area of research) and people from Economic Geography which use almost the same methods.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The methods I coded here are not covered in R to the best of my knowledge except for unmaintained/abandoned drafts of R packages on github.

-  Any other questions or issues we should be aware of?:

No.

**Comment by noamross** [comment]
Thanks for this inquiry, @pachamaltese!  I'm afraid this package does not fall in rOpenSci's scope, because it is a direct implementation of statistical methods or estimators.  We generally think of scientific software wrappers and bindings or interfaces to external libraries, such as https://github.com/ropensci/babette.
