### ISSUE TITLE
gravity

### ISSUE THREAD

**Issue by pachamaltese** [ropensci/software-review#313]
Submitting Author: Mauricio "Pachá" Vargas (@pachamaltese)  
Repository: https://github.com/pachamaltese/gravity

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gravity
Type: Package
Title: Estimation Methods for Gravity Models
Version: 0.9.8
Authors@R: c(
  person("Anna-Lena", "Woelwer",
    role = c("aut", "cph"),
    email = "woelwer@uni-trier.de"),
  person("Jan Pablo", "Burgard",
    role = c("aut", "cph"),
    email = "burgardj@uni-trier.de"),
  person("Joshua", "Kunst", 
    role = c("aut", "cph"),
    email = "jbkunst@gmail.com"),
  person("Mauricio", "Vargas", 
    role = c("aut","cre","cph"), 
    email = "mvargas@dcc.uchile.cl", 
    comment = c(ORCID = "0000-0003-1017-7574")),
  person("Romain", "Francois", 
    role = "ctb", 
    email = "romain@purrple.cat",
    comment = "adapted parts of the code to use dplyr 0.8.0"),
  person("Lionel", "Henry", 
    role = c("ctb"), 
    email = "lionel@rstudio.com",
    comment = "simplified parts of the code"),
  person("Hrisyana", "Doytchinova", 
    role = c("rev"), 
    email = "hrisyana.doytchinova@un.org",
    comment = "sent us different suggestions and bug reports")
  )
Description: A wrapper of different standard estimation methods for gravity models. 
  This package provides estimation methods for log-log models and multiplicative models.
URL: http://pachamaltese.github.io/gravity
Imports: 
    lmtest,
    sandwich,
    glm2,
    MASS,
    stats,
    censReg,
    survival,
    multiwayvcov,
    tibble,
    magrittr,
    dplyr,
    tidyr,
    purrr,
    rlang,
    Rdpack,
    utils
RdMacros: Rdpack
Depends: R(>= 3.4.0)
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Suggests: knitr,
  rmarkdown,
  testthat,
  broom
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
        - [x] scientific software wrappers
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package aims at providing already existing and well covered methods in Stata. Unfortunately, Stata requires a paid license which is the 1st barrier toward full independent replication.

-   Who is the target audience and what are scientific applications of this package? 

Economists and people from Urban Planning. They use gravity models a lot but at very different areas of application.
Gravity is wrapper of different standard estimation methods for gravity models which are highly non-trivial. This package provides estimation methods for log-log models and multiplicative models.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Not at the moment. I found gravity v1.0 and I wrote the original authors to maintain the project and try to make it more performant.

-  Any other questions or issues we should be aware of?:

No.

**Comment by noamross** [comment]
Thanks for this inquiry, @pachamaltese! As with *economiccomplexity*, I'm afraid this package does not fall in rOpenSci's scope, because it is a direct implementation of statistical methods or estimators.
