### ISSUE TITLE
Presubmission: UCSCXenaTools

### ISSUE THREAD

**Issue by ShixiangWang** [ropensci/software-review#314]
Submitting Author: Shixiang Wang (@ShixiangWang)  
Repository:   https://github.com/ShixiangWang/UCSCXenaTools

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: UCSCXenaTools
Title: Download and Explore Datasets from UCSC Xena Data Hubs
Version: 1.2.2
Authors@R: c(person("Shixiang", "Wang", email = "w_shixiang@163.com", role = c("aut", "cre"), 
            comment = c(ORCID = "0000-0001-9855-7357")),
            person("Martin", "Morgan", role="aut"))
Maintainer: Shixiang Wang <w_shixiang@163.com>
URL: https://github.com/ShixiangWang/UCSCXenaTools
BugReports: https://github.com/ShixiangWang/UCSCXenaTools/issues
Description: Download and explore datasets from UCSC Xena data hubs, which are
    a collection of UCSC-hosted public databases such as TCGA, ICGC, TARGET, GTEx, CCLE, and others.
    Databases are normalized so they can be combined, linked, filtered, explored and downloaded.
Depends: R (>= 3.0)
Imports: 
    httr,
    readr,
    methods,
    utils,
    dplyr,
    magrittr,
    jsonlite,
    shinydashboard,
    shiny,
    DT
License: GPL-3
Encoding: UTF-8
LazyData: true
Suggests: 
    knitr,
    rmarkdown,
    prettydoc,
    testthat,
    covr
VignetteBuilder: knitr
RoxygenNote: 6.1.1
Roxygen: list(markdown = TRUE)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package falls under the **data retrieval category** because it pulls data from [UCSC Xena Hubs](https://xenabrowser.net/datapages/).

-   Who is the target audience and what are scientific applications of this package?  
    -  Target Audience:  cancer and clinical researchers, bioinformaticians
    - Applications: genomic and clinical analyses

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

None that I am aware of. There is a Python package called [xenaPython](https://github.com/ucscXena/xenaPython) which is the official API for Xena Hubs. However, **UCSCXenaTools** is more powerful and provides more features including download whole dataset and query a small amount of data. 

-  Any other questions or issues we should be aware of?:

I am wondering if this package can fall into more categories except for data retrieval.

**Comment by noamross** [comment]
Thanks for your inquiry, @ShixiangWang! This is straightforwardly in-scope for us as a data retrieval package, feel free to submit for full review.  

I do note that your test coverage is a bit low at 44%. The handling editor will flag this at submission, so it would be best to get this up to 80% or so before submitting.

**Comment by ShixiangWang** [comment]
@noamross Thanks, I will add more tests before submitting.
