### ISSUE TITLE
distributions

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/software-review#316]
Submitting Author: Alex Hayes (@alexpghayes)
Repository:   https://github.com/alexpghayes/distributions/

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: distributions
Title: Probability Distributions as S3 Objects
Version: 0.0.0.9001
Authors@R: c(
    person(given = "Alex",
           family = "Hayes",
           role = c("aut", "cre"),
           email = "alexpghayes@gmail.com",
           comment = c(ORCID = "0000-0002-4985-5160")),
    person(given = "Daniel",
           family = "Jordan",
           role = "ctb",
           email = "dandermotj@gmail.com"),
    person(given = "Bruna",
           family = "Wundervald",
           role = "ctb",
           email = "brunadaviesw@gmail.com"))
Description: Tools to create and manipulate probability
    distributions using S3.  Generics random(), pdf(), cdf() and
    quantile() provide replacements for base R's r/d/p/q style functions.
    Functions and arguments have been named carefully to minimize
    confusion for students in intro stats courses. The documentation for
    each distribution contains detailed mathematical notes.
License: MIT + file LICENSE
URL: https://github.com/alexpghayes/distributions
BugReports: https://github.com/alexpghayes/distributions/issues
Imports: 
    ellipsis,
    glue
Suggests: 
    testthat,
    ggplot2,
    knitr,
    rmarkdown,
    patchwork (>= 0.0.1),
    covr
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.1.1
VignetteBuilder: knitr
Remotes: 
    thomasp85/patchwork
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
        - [x] scientific software wrapper
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

`distributions` is a blatant wrapper around base R utilities for manipulating random variables. However, it provides S3 objects corresponding to each random variable, which enables users to write and use generic functions that work on random variables. Another major goal is to provide extensive student friendly documentation.

-   Who is the target audience and what are scientific applications of this package?  

Anyone who uses random variables and can't remember if they should be using `rnorm()`, `pnorm()` or `qnorm()`.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

`distr` provides random variables objects as S4 classes. `distributions` uses a different class system, one that I believe many people find more intuitive.

-  Any other questions or issues we should be aware of?:

Not really. Just curious if this within scope.

**Comment by noamross** [comment]
Thanks for the inquiry, Alex! I don't think this is in scope. We envision the wrappers category as bindings to non-R scientific software, so providing tools that help users create fully reproducible workflows from R that use that software.

**Comment by alexpghayes** [comment]
Gotcha, thanks!
