### ISSUE TITLE
GenTag: A package to improve animal color tagging protocol  

### ISSUE THREAD

**Issue by biagolini** [ropensci/software-review#317]
Submitting Author: Carlos Biagolini-Jr (@biagolini)
Repository: https://github.com/biagolini/GenTag
Version submitted: 1.0

I would like to submit the R package entitled 'GenTag' for consideration in rOpenSci. This is a package which proposes an improved protocol for animal color tagging. Since the early 1980s, several studies have suggested a negative influence of color tags on animal social behavior. However, methodological approaches to deal with this issue are lacking.  'GenTag' was designed to produce random sequences of color tag combinations. The package was designed to run on R base, without cross-package dependence. The computational routine is simple, implying low CPU usage. Despite the simplicity of the routine itself, the application of this method is exceptionally broad, as it can be applied in any project that uses visual identification of animals based on color marking, across a wide range of taxa, including birds, mammals, and fishes.

**Comment by noamross** [comment]
Thank you for the inquiry, @biagolini.  This package is a bit of an edge case topically. We don't have a package category specifically that it fits in to, but we think that packages like this - that are designed to facilitate field and laboratory processes and set up experimental designs, are in-scope, so we may say so explicitly in the next revision of our [Aims and Scope](https://devguide.ropensci.org/policies.html#aims-and-scope).

However, I do note that this package is not yet ready for review.  We require a number of things before sending a package to review, including a full README and vignette, a test suite with continuous integration and test coverage reporting, and Roxygen-based documentation.  Please consult our [packaging guide](https://devguide.ropensci.org/building.html), which describes our packaging standards, in getting your package prepared for a full submission, and feel free to use our [forum](https://discuss.ropensci.org/) if you have questions.

**Comment by biagolini** [comment]
Thank you for your attention, @noamross. I included: README, vignette, Travis and AppVeyor CI continuous integration; also I update the documentation to Roxygen-based files. 

Best,
- Carlos Biagolini

**Comment by biagolini** [comment]
> Thank you for the inquiry, @biagolini. This package is a bit of an edge case topically. We don't have a package category specifically that it fits in to, but we think that packages like this - that are designed to facilitate field and laboratory processes and set up experimental designs, are in-scope, so we may say so explicitly in the next revision of our [Aims and Scope](https://devguide.ropensci.org/policies.html#aims-and-scope).
> 
> However, I do note that this package is not yet ready for review. We require a number of things before sending a package to review, including a full README and vignette, a test suite with continuous integration and test coverage reporting, and Roxygen-based documentation. Please consult our [packaging guide](https://devguide.ropensci.org/building.html), which describes our packaging standards, in getting your package prepared for a full submission, and feel free to use our [forum](https://discuss.ropensci.org/) if you have questions.

**Comment by biagolini** [comment]
> Thank you for the inquiry, @biagolini. This package is a bit of an edge case topically. We don't have a package category specifically that it fits in to, but we think that packages like this - that are designed to facilitate field and laboratory processes and set up experimental designs, are in-scope, so we may say so explicitly in the next revision of our [Aims and Scope](https://devguide.ropensci.org/policies.html#aims-and-scope).
> 
> However, I do note that this package is not yet ready for review. We require a number of things before sending a package to review, including a full README and vignette, a test suite with continuous integration and test coverage reporting, and Roxygen-based documentation. Please consult our [packaging guide](https://devguide.ropensci.org/building.html), which describes our packaging standards, in getting your package prepared for a full submission, and feel free to use our [forum](https://discuss.ropensci.org/) if you have questions.

Thank you for your attention, @noamross. I included: README, vignette, Travis and AppVeyor CI continuous integration; also I update the documentation to Roxygen-based files.

Best,
Carlos Biagolini

**Comment by noamross** [comment]
Thank you @biagolini, fast work!  I note that while you have set up continuous integration and test coverage, you still do not have any tests for your package. As stated in our guide, we aim for at least 75% test coverage in the test suite, any less needs specific justification.  

When you package is ready, please open a new issue using the full submission template.

**Comment by noamross** [comment]
Hi @biagolini, I'm closing this issue.  Please so open a new one when you're ready to submit.  A quick note - when you test for coverage, it should be evaluated using`"tests"`, rather than `"all"` as is currently set in your `.travis.yml`.
