### ISSUE TITLE
Presubmission inquiry - projmgr: GitHub-integrated project management in R 

### ISSUE THREAD

**Issue by emilyriederer** [ropensci/software-review#321]
Submitting Author: Emily Riederer (@emilyriederer)  
Repository: https://github.com/emilyriederer/projmgr/

---

-   Paste the full DESCRIPTION file inside a code block below:

```

Package: projmgr
Title: Task tracking and project management with GitHub via R
Version: 0.0.0.9902
Authors@R:
    person(given = "Emily",
           family = "Riederer",
           role = c("cre", "aut"),
           email = "emilyriederer@gmail.com")
Description: Provides programmatic access to GitHub API with a
    focus on project management.  For example, key functionality includes
    setting up issues and milestones and reporting the progress of those
    events. It should be useful for those using GitHub in personal,
    professional, or academic settings with an emphasis on streamlining
    the workflow of data analysis projects.
License: MIT + file LICENSE
URL: https://github.com/emilyriederer/projmgr
BugReports: https://github.com/emilyriederer/projmgr/issues
Depends: 
    R (>= 3.1.2)
Imports:
    gh,
    magrittr
Suggests:
    clipr,
    curl,
    dplyr,
    ggplot2,
    knitr,
    purrr,
    reprex,
    rmarkdown,
    testthat,
    tidyr,
    yaml,
    htmltools
VignetteBuilder: 
    knitr
Encoding: UTF-8
Language: en-US
LazyData: true
RoxygenNote: 6.1.1

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

**Data retrieval:** Provides an interface to both retrieving and submitting data via the GitHub API. The heavy lifting is done by `gh`, but the interface is opinionated to specifically focus on project management tasks.

**Reproducibility:** Using GitHub or other version control / collaboration systems is a core piece of open science and reproducible research. This package does not explicitly promote the use of version control; however, it hopefully further increases the incentives to use GitHub by streamlining project management on the same platform. 

The package also enhances reproducibility since many "latent" analysis tasks (going down side projects, debugging data and code, discussing output and considering alternatives, etc.) happen in real-time lab / office settings. Logging these as issues, discussing them online, and then capturing that in text output for posterity [as described here](https://emilyriederer.github.io/projmgr/articles/documenting-discussion.html) can enhance transparency into the full research process. 

-   Who is the target audience and what are scientific applications of this package?  

The target audience for this package is anyone who uses GitHub and whose work requires project planning and communication. The idea is to streamline rote tasks which distract from actual science and analysis by limiting context switches between project management and analysis tools. Users can file issues and generate reports all within R.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are many packages that provide an interface to the GitHub API. These include RStudio's `gh`, `ghapiv3`, rOpenSci's own `ghrecipes`, and `ghclass`. However, I do not see any of these packages as directly overlapping with `projmgr`.  The relation to these packages are noted on the [package website](https://emilyriederer.github.io/projmgr/articles/design-notes.html) but are also summarized below.

`gh` and `ghapiv3` are general-purpose packages that allow greater flexibility than `projmgr`. However, they may required greater knowledge of the underlying API to use and are not optimized around performing specific tasks / workflows. Similarly, `ghrecipes` provides very helpful functionality to navigate GitHub's v4 API but is also in the general purpose category.

`ghclass`, on the other hand, is similar to `projmgr` in that it is highly customized around a specific GitHub-based workflow. However, the specific workflow it seeks to wrap is quite different. It is more focused on automation around populating the contents of GitHub repos, whereas this package works on issues, milestones, etc.

-  Any other questions or issues we should be aware of?:

I do not have any other questions at this time. Just curious whether this might be in scope. Thanks!

**Comment by annakrystalli** [comment]
Hello @emilyriederer and many thanks for your presubmission enquiry! 

While personally I'm really excited about the package (and will definitely be using it), it actually is out of scope for rOpenSci for similar reasons that we determined the recent presubmission for `gitgantt` #311 (discussions in that thread are quite informative) as out of scope.  It is a bit too general (not focused enough on scientific workflows in particular) and primarily builds on other features of GitHub than version control itself.

**Comment by emilyriederer** [comment]
Thanks for the reply and consideration,@annakrystalli - makes sense! Thanks also for the reference to `gitgantt`. I'd missed that one, so I'm very happy to know about it!
