### ISSUE TITLE
Presubmission: mapscanner

### ISSUE THREAD

**Issue by mpadge** [ropensci/software-review#322]
Submitting Author: mark padgham (@mpadge)
Repository: [`mapscanner`](https://github.com/mpadge/mapscanner)

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: mapscanner
Title: Print Maps, Draw on Them, Scan Them Back In
Version: 0.0.1
Authors@R: c(
    person("Mark", "Padgham", email="mark.padgham@email.com", role=c("aut", "cre")),
    person("Michael D.", "Sumner", role = "aut", email = "mdsumner@gmail.com"))
Description: Print maps, draw on them, scan them back in, and convert to spatial
    objects.
License: GPL-3
Encoding: UTF-8
LazyData: true
NeedsCompilation: yes
Imports:
    cli,
    curl,
    dplyr,
    fs,
    glue,
    jpeg,
    magrittr,
    magick,
    memoise,
    pdftools,
    png,
    purrr,
    raster,
    Rcpp,
    reproj,
    RNiftyReg,
    sf,
    sfdct,
    slippymath,
    tibble
Suggests: 
    ggplot2,
    knitr,
    lwgeom,
    mapview,
    osmdata,
    rmarkdown,
    testthat,
    spelling
LinkingTo: Rcpp
SystemRequirements:
    C++11
VignetteBuilder: knitr
URL: https://github.com/mpadge/mapscanner
BugReports: https://github.com/mpadge/mapscanner/issues
RoxygenNote: 6.1.1
Language: en-GB
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [x] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

`mapscanner` fits nicely into both data extraction and geospatial data. It is definitely geospatial because it concerns maps, and ultimately generates spatial output in standard (`sf`) format. It is nevertheless primarily a "data extraction" tool that extracts useful (spatially) structured data from unstructured input in either `pdf` or image formats.

-   Who is the target audience and what are scientific applications of this package?  

The target audience comprises social researchers interested in spatial phenomena such as subjective perceptions of regions or areas, or perceptions of location. More specifically, these kinds of analyses are currently restricted to (highly) commercial service provision, and the package aims to aid and empower social researchers in financially disadvantageous circumstances by providing analytic abilities that would otherwise be prohibitively expensive.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

None that we are aware of.

-  Any other questions or issues we should be aware of?:

None at present :smile: (Ping co-author @mdsumner)

**Comment by noamross** [comment]
An interesting case! I think it's in-scope.  I like these packages that connect computational processes to data collection processes.

**Comment by mpadge** [comment]
Thanks @noamross; may I interpret that as approval to open a new issue as full submission?

**Comment by noamross** [comment]
Yup!
