### ISSUE TITLE
torpor

### ISSUE THREAD

**Issue by vullioud** [ropensci/software-review#324]
Submitting Author: Name (@github_handle)  
Repository:   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: torpor
Type: Package
Title: Assigning metabolic rate measurements to torpor and euthermia in heterothermic endotherms  
Version: 0.2.1
Authors@R: 
    c(person(given = "Colin",
             family = "Vullioud",
             role = c("aut", "cre"),
             email = "colino.vullioud@gmail.com"),
      person(given = "Nicolas",
             family = "Fasel",
             role = "aut"))
Description: This package enables an objective and standardized distinction 
    between torpid and euthermic metabolic rates (MR) measured in steady-state 
    conditions. Furthermore, it provides parameters’ estimations of the relation 
    between ambient temperatures (Ta) and MR in both physiological states. This 
    package is aimed to support any physiologist working in thermal energetics. 
    More information can be found on the companion article Fasel et al. (in prep).
License: GPL (>=2)
Depends: R (>= 2.10)
Encoding: UTF-8
LazyData: true
SystemRequirements: jags
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.1.1
Imports: jagsUI, 
        ggplot2,
        truncnorm, 
        purrr, 
        dplyr, 
        magrittr,
        overlapping, 
        knitr,
        rmarkdown
VignetteBuilder: knitr
Suggests: 
    testthat (>= 2.1.0),
    covr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
Most functions in `torpor` aims at facilitating the interpretation and use of a relatively complex mixture model and thus could fit in the "data munging" category.
Our doubts concern the core function of the package (the implementation of the model) and the general goal of the package which could fit nicely in the "scientific software wrappers" category listed in the Ropensci user guide but for some reason is not present here. We are also concerned by the relative specificity of the model and thus would like to know if the package could fit into the scope of Ropensci. 

-   Who is the target audience and what are scientific applications of this package?  
physiologists
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
No
-  Any other questions or issues we should be aware of?:
nothing for now.

**Comment by noamross** [comment]
Thank you for your inquiry, @vullioud! Based on my understanding of the package, it is out-of-scope.  This is not because of its specificity - rOpenSci explicitly tries to serve the "long-tail" of scientific use cases.  Rather, this is a package that implements a statistical method. Even though you use JAGS to do so, we don't consider this a "scientific software wrapper," as the purpose of that category is writing bindings to non-R software (we could probably include the definition).

We are actually just [starting a project](https://ropensci.org/blog/2019/07/15/expanding-software-review/) to develop a new set of standards and expand our scope, but it will be a while before we are ready to review packages like this.

**Comment by vullioud** [comment]
Thanks for your quick clarification. Looking forward to see the implementation of these new projects, looks  great.
