### ISSUE TITLE
Presubmission: ruODK, Client for the ODK Central API

### ISSUE THREAD

**Issue by florianm** [ropensci/software-review#328]
Submitting Author: @florianm
Repository:   https://github.com/dbca-wa/ruODK/

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: ruODK
Title: Client for the ODK Central API
Version: 0.3.1
Authors@R: 
    person(given = c("Florian", "W."),
           family = "Mayer",
           role = c("aut", "cre"),
           email = "Florian.Mayer@dbca.wa.gov.au",
           comment = c(ORCID = "0000-0003-4269-4242"))
Author: Florian W. Mayer [aut, cre]
Maintainer: Florian W. Mayer <Florian.Mayer@dbca.wa.gov.au>
Description: Utilities to access and tidy up data from ODK Central's API.
    ODK Central is OpenDataKit's clearinghouse for digitally captured data 
    <https://docs.opendatakit.org/central-intro/>. 
    ODK Central's API is documented at <https://odkcentral.docs.apiary.io/>.
URL: https://github.com/dbca-wa/ruODK
BugReports: https://github.com/dbca-wa/ruODK/issues
License: GPL-3
Depends: 
    R (>= 3.4)
Imports: 
    dplyr (>= 0.8.1),
    fs (>= 1.3.1),
    glue (>= 1.3.1),
    httr (>= 1.3.1),
    magrittr (>= 1.5),
    purrr (>= 0.3.2),
    readr (>= 1.3.1),
    rlang (>= 0.1.2),
    stringr (>= 1.3.1),
    tibble (>= 2.1),
    tidyr (>= 0.8.3.9000),
    xml2 (>= 1.2.0)
Suggests: 
    covr (>= 3.0.1),
    DT (>= 0.4),
    knitr (>= 1.22),
    ggplot2 (>= 3.1.0),
    leaflet (>= 2.0.2),
    lubridate (>= 1.7.4),
    listviewer (>= 1.4.0),
    rmarkdown (>= 1.12),
    testthat (>= 2.1.0)
Remotes: github::tidyverse/tidyr
VignetteBuilder: knitr
Encoding: UTF-8
Language: en_AU
LazyData: true
RoxygenNote: 6.1.1
X-schema.org-keywords: database, open-data, opendatakit, odk, api, data, dataset
X-schema.org-applicationCategory: Data Access
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Data retrieval: `ruODK` retrieves data from ODK Central, a data clearinghouse containing data which have been digitally captured by the data collection app ODK Collect using Xforms.

As mentioned by @annakrystalli, the below categories are touched by ruODK, but don't apply:

Data extraction or munging: `ruODK` transforms and sanitises the data from ODK Central from the original format (which parses to nested lists in R) into tibbles.

Reproducibility: `ruODK` allows to script and repeat the data extraction step - the main use case it is being written for.

Geospatial data: while ODK allows to capture location data (points, lines, polygons), and `ruODK` extracts these values, `ruODK` is not primarily a spatial package.

-   Who is the target audience and what are scientific applications of this package?  

(Scope and use cases are also mentioned in the [README](https://dbca-wa.github.io/ruODK/index.html).)

Any organisation collecting data with the [OpenDataKit](https://opendatakit.org/) suite will need to extract the data from the data clearinghouses, ODK Aggregate (outgoing) or ODK Central (new). Some may want to analyse the data straight out of ODK Central, some may need to transfer the data into another data warehouse for further post-processing, QA, and integration with other data sources. 

For both use cases, `ruODK` bridges and simplifies the gap between the data sitting in ODK Central, and the data being a tibble in R, ready for further processing.

In a nutshell, `ruODK` aims to be to ODK Central what `ckanr` is to CKAN.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are currently no other R packages wrapping the ODK Central API, neither the OData nor the RESTful API endpoints. [Relevant discussion](https://forum.opendatakit.org/t/odk-central-odata-to-r/15623/2) in the ODK forum.
Some R packages exist demonstrating basic OData access, but none worked with the OData version employed by ODK Central.
Most examples found online simply deconstruct the problem of accessing OData into parsing XML.
https://www.cdata.com/kb/tech/odata-jdbc-r.rst provides a Java-based OData client, but is not specific to ODK Central.

`ruODK` probably fulfills ROpenSci's criteria for best in class:

* `ruODK` is so far the only dedicated ODK Central API wrapper in R.
* Scope: all "data access" API endpoints, both RESTful and OData.
* Driver for development and ongoing maintenance is production use at DBCA for all Western Australian turtle monitoring projects (so far ~20k records collected through ODK since 2016) and other monitoring and research projects.
* ODK Central is in active development; DBCA is in close contact with the ODK developer community.

-  Any other questions or issues we should be aware of?:

(TODO before ROpenSci submission: see [changelog](https://dbca-wa.github.io/ruODK/news/index.html#todo))

`ruODK` is a few functions away (seven at time of writing) from covering all "getting my data out" API endpoints, lacks some examples in the function docs, and currently uses a live ODK Central instance for testing instead of vcr/webmockr, but the existing content might be just enough to get your feedback on `ruODK`'s suitability for a later submission to ROpenSci. Any feedback is welcome!

Crosslink to [my post in ROpenSci Forum](https://discuss.ropensci.org/t/ruodk-an-api-wrapper-for-opendatakits-new-clearinghouse-odk-central/1788)

Edit: updating issue while spit-shining `ruODK`

**Comment by annakrystalli** [comment]
Hi @florianm 👋and thanks for your presubmission enquiry,

I'd not heard of this framework before but it looks really cool! I listened to the podcast @sckott posted in response to your forum post last night, will definitely be checking it out.

In terms of the topic, you've ticked data retrieval, extraction and reproducibility but we feel the correct category is data retrieval only. I appreciate that it still needs some work but in principle, we feel we can invite a full submission when ready.

**Comment by annakrystalli** [comment]
I'll be closing this issue now. Please open a full submission issue when you are ready. 👍

**Comment by florianm** [comment]
Cheers @annakrystalli! 
ODK is indeed the bees knees.

The categories are updated now, and I've included a paper to JOSS (is `/inst/joss` a good place for the paper.md?)

**Comment by annakrystalli** [comment]
Great! 

I think just the root of the repo is fine as it doesn't really need to be included in the package when installed (it will stand as it's one publication in JOSS).  It will be easier for reviewers to find too. In this case it would also need to be included in `.Rbuildignore`

Having said that, we don't have specific guidelines on the location of `paper.md` so it certainly wouldn't be a problem to store it in `inst/joss`. Just make sure reviewers know where it is. :)

**Comment by florianm** [comment]
Cool - didn't want to clutter root with non-standard files, but the paper can go in either place. If I add the remaining functions (with docs, examples, tests, and examples in README and in vignette), is there any other glaring error or omission I could fix or add prior to submission?
