### ISSUE TITLE
windfarmGA

### ISSUE THREAD

**Issue by trafficonese** [ropensci/software-review#331]
Submitting Author: Name (@YsoSirius)  
Repository:   [windfarmGA](https://github.com/YsoSirius/windfarmGA)

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: windfarmGA
Title: Genetic Algorithm for Wind Farm Layout Optimization
Version: 2.2.2
Date: 2019-07-17
Author: Sebastian Gatscha
Maintainer: Sebastian Gatscha <sebastian_gatscha@gmx.at>
Description: The genetic algorithm is designed to optimize wind farms of any shape. It requires a predefined amount of turbines, a unified rotor radius and an average wind speed value for each incoming wind direction. A terrain effect model can be included that downloads an 'SRTM' elevation model and loads a Corine Land Cover raster to approximate surface roughness.
Depends:
    R (>= 3.2.3)
Imports: rgdal (>= 1.3.6),
    Rcpp (>= 1.0.0),
    raster (>= 2.8.19),
    sf (>= 0.7.2),
    sp (>= 1.2-2),
    plyr (>= 1.8.4),
    rworldmap (>= 1.3.6),
    gstat (>= 1.0-26),
    ggplot2 (>= 2.2.0),
    RColorBrewer (>= 1.1.2),
    calibrate (>= 1.7.2),
    grDevices,
    graphics,
    leaflet (>= 1.1.0),
    magrittr (>= 1.5),
    foreach (>= 1.4.3),
    parallel (>= 3.4.1),
    doParallel (>= 1.0.11),
    methods (>= 3.2.5),
    spatstat (>= 1.42-2),
    stats,
    utils
LinkingTo: Rcpp
LazyData: TRUE
License: MIT + file LICENSE
URL: https://ysosirius.github.io/windfarmGA/index.html
BugReports: https://github.com/YsoSirius/windfarmGA/issues
RoxygenNote: 6.1.1
Suggests: testthat, pkgdown, dplyr (>= 0.8.0.1), rgeos (>= 0.3-8)
Encoding: UTF-8
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [x] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The package requires spatial data to perform a windfarm optimization and it is able to automatically download elevation data and a Corine land Cover Raster to include in the calculation. I wrote the package during my master thesis, as I read many papers on how to optimize windfarms with genetic algorithms but couldn't find any open source software tools that did that, so I wrapped it in a package for others to easily reproduce the results, improve the algorithm and compare other algorithms.

-   Who is the target audience and what are scientific applications of this package?  
Researches in the field of renewable energy / optimization but also companies/engineers that finally built the windfarms. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Not that I am aware of. There is the package `GA` for general purpose genetic algorithms, but this package has a single purpose, optimizing wind farm layouts.

-  Any other questions or issues we should be aware of?:
I published it on [CRAN](https://cran.r-project.org/web/packages/windfarmGA/index.html) already, as I was unaware of `ropensci` at that time.

**Comment by annakrystalli** [comment]
Hello @trafficonese, and thanks for your submission.

This looks like a really cool package! Unfortunately, because it is more of a statistical analysis package, rOpenSci are not currently able to provide review.  However it is [an area we are actively working on](https://ropensci.org/blog/2019/07/15/expanding-software-review/), so perhaps try again in future.
