### ISSUE TITLE
Submission: c14bazAAR

### ISSUE THREAD

**Issue by nevrome** [ropensci/software-review#333]
Submitting Author: Clemens Schmid (@nevrome)  
Repository: https://github.com/ISAAKiel/c14bazAAR
Version submitted: 1.0.3.9000
Editor: @melvidoni 
Reviewer 1: @benmarwick  
Reviewer 2: @ercrema
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: c14bazAAR
Title: Download and Prepare C14 Dates from Different Source Databases
Description: Query different C14 date databases and apply basic data cleaning, merging and calibration steps.
Version: 1.0.3.9000
Authors@R: 
    c(person(given = "Clemens",
             family = "Schmid",
             role = c("aut", "cre", "cph"),
             email = "clemens@nevrome.de",
             comment = c(ORCID = "0000-0003-3448-5715")),
      person(given = "Dirk",
             family = "Seidensticker",
             role = "aut",
             email = "dirk.seidensticker@gmail.com",
             comment = c(ORCID = "0000-0002-8155-7702")),
      person(given = "Daniel",
             family = "Knitter",
             role = "aut",
             email = "knitter@geographie.uni-kiel.de",
             comment = c(ORCID = "0000-0003-3014-4497")),
      person(given = "Martin",
             family = "Hinz",
             role = "aut",
             email = "martin.hinz@iaw.unibe.ch",
             comment = c(ORCID = "0000-0002-9904-6548")),
      person(given = "David",
             family = "Matzig",
             role = "aut",
             email = "matzigdavid@gmail.com",
             comment = c(ORCID = "0000-0001-7349-5401")),
      person(given = "Wolfgang",
             family = "Hamer",
             role = "aut",
             email = "hamer@geographie.uni-kiel.de",
             comment = c(ORCID = "0000-0002-5943-5020")),
      person(given = "Kay",
             family = "Schmütz",
             role = "aut",
             email = "kschmuetz@ufg.uni-kiel.de"),
      person(given = "Nils",
             family = "Mueller-Scheessel",
             role = "ctb",
             email = "nils.mueller-scheessel@ufg.uni-kiel.de",
             comment = c(ORCID = "0000-0001-7992-8722")))
URL: https://github.com/ISAAKiel/c14bazAAR
BugReports: https://github.com/ISAAKiel/c14bazAAR/issues
Depends: R (>= 3.4.0)
Language: en_GB
License: GPL-2 | file LICENSE
Encoding: UTF-8
LazyData: true
Imports:
    crayon (>= 1.3.4),
    data.table (>= 1.11.4),
    dplyr (>= 0.7.2),
    httr (>= 1.4.0),
    magrittr (>= 1.5),
    pbapply (>= 1.3-3),
    rlang (>= 0.1.1),
    stats (>= 3.4.0),
    tibble (>= 1.3.3),
    tidyr (>= 0.6.3)
Suggests:
    Bchron,
    countrycode,
    dataverse,
    ggplot2,
    ggridges,
    knitr,
    lwgeom,
    mapview,
    openxlsx,
    plyr,
    rgeos,
    rmarkdown,
    rnaturalearth,
    rworldmap,
    rworldxtra,
    sf,
    stringdist,
    testthat
RoxygenNote: 6.1.1
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ]  data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

c14bazAAR was created to access radiocarbon dates from openly accessible archives. All functions are related to data download and data preparation.

-   Who is the target audience and what are scientific applications of this package?  

Mostly archaeologists as most radiocarbon databases currently accessible via c14bazAAR contain radiocarbon dates from archaeological contexts. The package could also be of interest for geographers and other kinds of ecologists -- especially if non-archaeological data sources are added to the portfolio.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No. Not that I'm aware of. 

## Technical checks

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  

It already is on CRAN in version [1.0.3](https://CRAN.R-project.org/package=c14bazAAR).

- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [x] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
  - [x] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
  - [x] The package is deposited in a long-term repository with the DOI: 10.17605/OSF.IO/3DS6A
  - (*Do not submit your package separately to JOSS*)  
  
</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by melvidoni** [comment]
Hello @nevrome and thank you for your submission. I have noticed that you haven't ticked the rOpenSci's CoC box. Is that for a particular reason? It is fundamental for us to have that, otherwise we cannot continue the process.

**Comment by nevrome** [comment]
@melvidoni No idea how I managed to forget that. Done now.

**Comment by melvidoni** [comment]
### Editor checks:

- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

Thank you for submitting, I'll be your handling editor. I run `goodpractices` but apparently you are clear to go, so I will start finding reviewers for the package. I'll let you know once they are in, and we have a review deadline.


---

Reviewers: TBD
Due date: TBD

**Comment by melvidoni** [comment]
I am in the search for a second reviewer. I will update here and give a review deadline as soon as someone accepts my invitation. Apologies for the delay, @nevrome

**Comment by melvidoni** [comment]
Reviewers have been assigned, @nevrome. Thanks to @benmarwick and @ercrema. The review deadline is Monday 16th of September.

**Comment by benmarwick** [comment]
## Package Review

- [x] As the reviewer I confirm that there are no [conflicts of interest](#coi) for me to review this work 

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [x] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

>##### For packages co-submitting to JOSS
>
>- [x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements)
>
>The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:
>
>- [x] **A short summary** describing the high-level functionality of the software
>- [x] **Authors:**  A list of authors with their affiliations
>- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [x] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [x] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 2

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

This is an exemplary package that was a delight to review. It is a perfect fit for rOpenSci and deserves a wide audidence. 

I ran some of the code in the README.md and everything worked as expected. I appreciated the comments that some code would take long to run! The vignette is beautifully written and elegantly and efficiently demonstrates some typical uses of the package. The function help files are thorough and encyclopedic, and rich with examples. All of the metadata files are excellent and have been prepared to the highest standards. I inspected a sample of functions and everything I saw looked excellent.

One suggestion for improvement: in `get_country_thesaurus` and similar `get_` functions I see we are downloading data, eg. from `"https://raw.githubusercontent.com/ISAAKiel/c14bazAAR/master/data-raw/material_thesaurus.csv"`. Looking in `data-raw/` I see that these files are not large (none more than 100 KB). So I suggest that the authors make these exported data objects in the package so users don't have to download again. 

I used [pkgreviewr](https://ropenscilabs.github.io/pkgreviewr/index.html]) to help prepare this review, the full contents of my review are in the fold below

<details><summary>pkgreviewr output</summary>
<p>

---
output:
    html_notebook:
        toc: true
        toc_float: true
editor_options:
  chunk_output_type: console
---



```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

library(magrittr)
library(devtools)
```

# `c14bazAAR` - package review

## **Reviewer:** [\@benmarwick](https://github.com/benmarwick)

### Review Submitted:
**`r cat(sprintf("**Last updated:** %s", Sys.Date()))`**

***

<br>

This report contains documents associated with the review of **rOpenSci** submitted package:

### **`c14bazAAR`: ropensci/software-review**  issue [\#NA](https://github.com/ropensci/onboarding/issues/).

<br>

## Package info

**Description:**

Query different C14 date databases and apply basic data cleaning, merging and calibration steps.

**Author:** `r 
    c(person(given = "Clemens",
             family = "Schmid",
             role = c("aut", "cre", "cph"),
             email = "clemens@nevrome.de",
             comment = c(ORCID = "0000-0003-3448-5715")),
      person(given = "Dirk",
             family = "Seidensticker",
             role = "aut",
             email = "dirk.seidensticker@gmail.com",
             comment = c(ORCID = "0000-0002-8155-7702")),
      person(given = "Daniel",
             family = "Knitter",
             role = "aut",
             email = "knitter@geographie.uni-kiel.de",
             comment = c(ORCID = "0000-0003-3014-4497")),
      person(given = "Martin",
             family = "Hinz",
             role = "aut",
             email = "martin.hinz@iaw.unibe.ch",
             comment = c(ORCID = "0000-0002-9904-6548")),
      person(given = "David",
             family = "Matzig",
             role = "aut",
             email = "matzigdavid@gmail.com",
             comment = c(ORCID = "0000-0001-7349-5401")),
      person(given = "Wolfgang",
             family = "Hamer",
             role = "aut",
             email = "hamer@geographie.uni-kiel.de",
             comment = c(ORCID = "0000-0002-5943-5020")),
      person(given = "Kay",
             family = "Schmütz",
             role = "aut",
             email = "kschmuetz@ufg.uni-kiel.de"),
      person(given = "Nils",
             family = "Mueller-Scheessel",
             role = "ctb",
             email = "nils.mueller-scheessel@ufg.uni-kiel.de",
             comment = c(ORCID = "0000-0001-7992-8722")))`

**repo url:** <https://github.com/ISAAKiel/c14bazAAR>

**website url:** <>

## Review info


#### See [reviewer guidelines](https://ropensci.github.io/dev_guide/reviewerguide.html) for further information on the rOpenSci review process.

**key review checks:**

- Does the code comply with **general principles in the [Mozilla reviewing guide](https://mozillascience.github.io/codeReview/review.html)**?
- Does the package **comply with the [ROpenSci packaging guide](https://ropensci.github.io/dev_guide/building.html)**?
- Are there **improvements** that could be made to the **code style?**
- Is there **code duplication** in the package that should be reduced?
- Are there **user interface improvements** that could be made?
- Are there **performance improvements** that could be made?
- Is the [**documentation**](https://ropensci.github.io/dev_guide/building.html#documentation) (installation instructions/vignettes/examples/demos) **clear and sufficient**?

Please be respectful and kind to the authors in your reviews. The rOpenSci [code of conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) is mandatory for everyone involved in our review process.

***

### session info


```{r sessionInfo}
sessionInfo()
```


```{r pkg_dir, echo = F}
pkg_dir <- "/Users/bmarwick/Desktop/c14bazAAR-review/c14bazAAR"
```

## Test installation

### test local `c14bazAAR` install:

```{r test-local}
install(pkg_dir, dependencies = T, build_vignettes = T)
```

```{r github-rm}
remove.packages("c14bazAAR")
```
#### **comments:**


No issues with local install of `c14bazAAR`.

***

### test install of `c14bazAAR` from GitHub with:

```{r test-github}
devtools::install_github("ISAAKiel/c14bazAAR", dependencies = T, build_vignettes = T)
```

#### **comments:**


No issues with GitHub install of `c14bazAAR` 

***

## Check package integrity

### run checks on `c14bazAAR` source:

```{r check-checks}
devtools::check(pkg_dir)
```
#### **comments:**


No issues with checks of `c14bazAAR`: 

```
── R CMD check results ─────────────────── c14bazAAR 1.0.3.9000 ────
Duration: 32.6s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

***

### run tests on `c14bazAAR` source:

```{r check-tests}
devtools::test(pkg_dir)
```
#### **comments:**


No issues with tests of `c14bazAAR`: 

```
══ Results ════════════════════
Duration: 48.8 s

OK:       68
Failed:   0
Warnings: 0
Skipped:  0
```

***


### check `c14bazAAR` for goodpractice:

```{r test-goodpractice}
goodpractice::gp(pkg_dir)
```
#### **comments:**


Many warnings of 'write unit tests for all functions, and all package code in general. 42% of code lines are covered by test cases.' Looks like these warning are appearing on unexported helper functions that do checking and formatting. I don't believe it is a high priority to have test coverage on these. 

***

## Check package metadata files

### inspect

- #### [README](https://github.com/ISAAKiel/c14bazAAR)
- #### [DESCRIPTION](https://github.com/ISAAKiel/c14bazAAR/blob/master/DESCRIPTION)
- #### [NAMESPACE](https://github.com/ISAAKiel/c14bazAAR/blob/master/NAMESPACE)

### spell check

```{r spell-check}
devtools::spell_check(pkg_dir)
```

#### **comments:**


All of these metadata files are excellent and have been prepared to the highest standards.

***

## Check documentation

online documentation: **<>**

* Is the [documentation](https://ropensci.github.io/dev_guide/building.html#documentation) (installation instructions/vignettes/examples/demos) clear and sufficient?

### test `c14bazAAR` function help files:

```{r test-help}
help(package = "c14bazAAR")
```

#### **comments:**


The function help files are thorough and encyclopeadic, and rich with examples. 

***

### test `c14bazAAR` vignettes:

```{r test-vignettes}
vignette(package = "c14bazAAR")
```

#### **comments:**


The vignette is beautifully written and elegantly and efficiently demonstrates some typical uses of the package. 

***

## Test functionality:

- Are there **user interface improvements** that could be made?
- Are there **performance improvements** that could be made?

```{r free-style}
library("c14bazAAR")
```

```{r parse-functions}
exports <-ls("package:c14bazAAR")
exports
```

#### **comments:**


I ran some of the code in the README.md and everything worked as expected. I appreciated the comments that some code would take long to run!

***

## Inspect code:

- Does the package **comply with the [ROpenSci packaging guide](https://ropensci.github.io/dev_guide/building.html)**?
    * good [function & variable naming?](https://ropensci.github.io/dev_guide/building.html#function-and-argument-naming)
    * good [dependency management](https://ropensci.github.io/dev_guide/building.html#package-dependencies)?
- Are there **improvements** that could be made to the [**code style?**](https://ropensci.github.io/dev_guide/building.html#code-style)
- Is there **code duplication** in the package that should be reduced?

```{r inspect-code, eval=FALSE}
pkgreviewr::pkgreview_print_source("c14bazAAR")
```

<br>
<br>

#### **comments:**


I inspected a sample of functions and everything I saw looked excellent.

One suggestion for improvement: in `get_country_thesaurus` and similar `get_` functions I see we are downloading data, eg. from `"https://raw.githubusercontent.com/ISAAKiel/c14bazAAR/master/data-raw/material_thesaurus.csv"`. Looking in `data-raw/` I see that these files are not large (none more than 100 KB). So I suggest that the authors make these exported data objects in the package so users don't have to download again. 

## Review test suite:

See guidance on [testing](https://ropensci.github.io/dev_guide/building.html#testing) for further details.

### test coverage

```{r pkg_coverage}
covr::package_coverage(pkg_dir)

```

### inspect [tests](https://github.com/ISAAKiel/c14bazAAR/blob/master/tests/testthat)

```
c14bazAAR Coverage: 42.53%
R/get_14sea.R: 0.00%
R/get_adrac.R: 0.00%
R/get_austarch.R: 0.00%
R/get_calpal.R: 0.00%
R/get_context.R: 0.00%
R/get_eastafrica.R: 0.00%
R/get_eubar.R: 0.00%
R/get_euroevol.R: 0.00%
R/get_palmisano.R: 0.00%
R/get_radon.R: 0.00%
R/get_radonb.R: 0.00%
R/helpers_db_urls.R: 0.00%
R/zzz.R: 0.00%
R/get_all_dates.R: 40.00%
R/c14_date_list_basic.R: 42.11%
R/helpers_general.R: 62.50%
R/c14_date_list_spatial_determine_country_by_coordinate.R: 71.83%
R/c14_date_list_fuse.R: 81.82%
R/c14_date_list_spatial_finalize_country_name.R: 87.50%
R/c14_date_list_classify_material.R: 89.47%
R/c14_date_list_spatial_standardize_country_name.R: 92.50%
R/c14_date_list_convert.R: 92.86%
R/c14_date_list_duplicates_remove.R: 93.02%
R/c14_date_list_spatial_coordinate_precision.R: 93.10%
R/c14_date_list_duplicates_mark.R: 94.87%
R/c14_date_list_calibrate.R: 95.92%
R/c14_date_list_enforce_types.R: 96.43%
R/c14_date_list_order_variables.R: 97.22%
R/helpers_thesauri.R: 100.00%
```


#### **comments:**


I'm satisfied with the testing coverage. 

***


</p>
</details>

**Comment by ercrema** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no [conflicts of interest](#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [x] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

>##### For packages co-submitting to JOSS
>
>- [x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements)
>
>The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:
>
>- [x] **A short summary** describing the high-level functionality of the software
>- [x] **Authors:**  A list of authors with their affiliations
>- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [x] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing:

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

This is an excellent package that will undoubtedly help many users handling radiocarbon datasets. I tested several commands and had no problems at all. I strongly recommend its publication on rOpenSci. Some minor points below:

* _Statement of Need_ should have perhaps a separate section from Summary in `paper.md`.
*  Oslisly:2013 does not have a DOI
* There is currently a possible error in `BchronCalibrate()` yielding a small discrepancy with the calibration output of other packages such as  `rcarbon`  and `OxCal` (via oxcAAR). I appreciate the authors cannot do much, but thought this was worth mentioning here. There is currently a Pull Request that might fix the problem.
* The functions `coordinate_precision()`, `enforce_types()`, `fuse()` do not have examples. I don't think this is crucial though. 
* I wonder whether it makes more sense to have a single `get_c14data` function rather than separate ones for each c14 archive. Or perhaps make these functions internal and have a wrapper calling these functions, perhaps returning a list of available databases when the user does not specify one?

**Comment by melvidoni** [comment]
Reviews are in @nevrome, so we will await for your reply/changes/actions.

**Comment by nevrome** [comment]
Thank you for your time and valuable feedback, @benmarwick and @ercrema! And of course thank you for the organisation so far, @melvidoni. I spoke with @dirkseidensticker and we decided to answer your requests in the following way:

@benmarwick
1. This unusual raw data download setup was established on purpose to be able to react fast in case of changes in the location (url) or content (new country names, new materials) of the source databases. A CRAN release can take a relatively long time. With this setup we are a lot more flexible and can make things work again immediately.

@ercrema 
1. https://github.com/ISAAKiel/c14bazAAR/commit/b21770f435279cc13c08b9204fd4698dde33619b establishes a separation of a *Background* and a *Code Summary* section. This structure is also used by other JOSS papers. I hope that's what you had in mind?
2. DOI added with https://github.com/ISAAKiel/c14bazAAR/commit/ab42faa1c495a19f5f9372ae2cccf19deada76b5.
3. I guess the relevant PR is this one here: https://github.com/andrewcparnell/Bchron/pull/12, ja? Interesting! I'll keep an eye on it.
4. https://github.com/ISAAKiel/c14bazAAR/commit/b4889e5df9bfb702c969ce12ea7f852767423671 adds some example code for these functions.
5. Both Dirk and I like the idea of simplifying the interface in this way. I wrote a first draft [here](https://github.com/ISAAKiel/c14bazAAR/pull/76) and we will explore it further. 

Beyond these changes I also added you to the DESCRIPTION file: https://github.com/ISAAKiel/c14bazAAR/commit/2d2ffc4f0a4af8c8dc8344f1c31b2c014dddb50b. Is your information correct?

**Comment by ercrema** [comment]
1. Yes precisely.
2. Great!
3. Yes indeed - Of course rcarbon and Oxcal might have got this wrong, but I think the calibration curve is reporting errors in sigma and not sigma^2
4. Great - and they all work fine.
5. Looks great!

**Comment by melvidoni** [comment]
Approved! Thanks @nevrome  for submitting and @ercrema and @benmarwick for your reviews! 

To-dos:
- [ ] Transfer the repo to rOpenSci's "ropensci" GitHub organization under "Settings" in your repo.  I have invited you to a team that should allow you to do so.  You'll be made admin once you do.
- [ ] Add the rOpenSci footer to the bottom of your README
"```
[![ropensci_footer](https://ropensci.org/public_images/ropensci_footer.png)](https://ropensci.org)```"
- [ ] Fix any links in badges for CI and coverage to point to the ropensci URL. We no longer transfer Appveyor projects to ropensci Appveyor account so after transfer of your repo to rOpenSci's "ropensci" GitHub organization the badge should be `[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/ropensci/pkgname?branch=master&svg=true)](https://ci.appveyor.com/project/individualaccount/pkgname)`.
- [ ] We're starting to roll out software metadata files to all ropensci packages via the Codemeta initiative, see https://github.com/ropensci/codemetar/#codemetar for how to include it in your package, after installing the package - should be easy as running codemetar::write_codemeta() in the root of your package.
- [ ] Activate Zenodo watching the repo
- [ ] Tag and create a release so as to create a Zenodo version and DOI
- [ ] Submit to JOSS using the Zenodo DOI.  They will tag it for expedited review.


Should you want to acknowledge your reviewers in your package DESCRIPTION, you can do so by making them `"rev"`-type contributors in the `Authors@R` field (with their consent).  More info on this [here](https://ropensci.github.io/dev_guide/building.html#authorship).

Welcome aboard! We'd love to host a blog post about your package - either a [short introduction to it with one example](https://ropensci.org/tech-notes/) or [a longer post with some narrative about its development or something you learned, and an example of its use](https://ropensci.org/blog/). If you are interested, review [the instructions](https://github.com/ropensci/roweb2#contributing-a-blog-post), and tag @stefaniebutland in your reply. She will get in touch about timing and can answer any questions.

We've started putting together a gitbook with our best practice and tips, [this chapter](https://ropensci.github.io/dev_guide/collaboration.html) starts the 3d section that's about guidance for after onboarding. Please tell us what could be improved, the corresponding repo is [here](https://github.com/ropensci/dev_guide).

**Comment by nevrome** [comment]
Thanks for these instructions, @melvidoni.

I was not fully aware that the package is intended to be hosted at the "ropenci" github organization at the end of the review. I would rather not do that. c14bazAAR is currently placed at the [ISAAKiel](https://github.com/ISAAKiel) github organization and I would prefer not to move it. ISAAK is a brand with recognition value in the field of computational archaeology.

What are the consequences of this decision and would you advise me to reconsider?

**Comment by benmarwick** [comment]
If I could suggest one possible option for the best of both worlds: use multiple remotes. Would you consider to mirror the pkg on rOpenSci, and keep the official repo on ISAAK? Clemens can then simultaneously push to both remotes to easily keep them in sync.

**Comment by melvidoni** [comment]
Hello @nevrome . We are discussing this with the editors. Please bear with me while we try to reach a consensus on what to do.

**Comment by stefaniebutland** [comment]
Hi @nevrome. I'm rOpenSci's Community Manager. Once the archiving issue is resolved, would you be interested in writing a blog post about some aspect of c14bazAAR? To the best of my knowledge, this is the first Archaeology-focused package to go through rOpenSci software peer review so a post would garner some attention. @benmarwick said he'd be happy to contribute if you feel that's appropriate.

This tag gets you (diverse) examples of blog posts by authors of peer-reviewed packages: https://ropensci.org/tags/software-peer-review/.

Here are some technical and editorial guidelines: https://github.com/ropensci/roweb2#contributing-a-blog-post. Publication date is flexible. I like to get a draft via pull request a week before the planned publication date so I can review.

Happy to answer any questions.

**Comment by nevrome** [comment]
@stefaniebutland Ja - absolutely! That's a great idea and I would love to do that. 

I'm sure you have some ideas, which aspects of c14bazAAR might be the most interesting for this purpose @benmarwick. I have some as well. Let's discuss this, when the archiving is sorted out.

**Comment by melvidoni** [comment]
Hello @nevrome, apologies for the extended delay. The package needs to be under our GitHub repo, but there's no reason it can't also be under another GitHub repo, too, and there are several reasonable solutions for this (multiple remotes, update by CI, etc.). Could you set up something like that?

**Comment by nevrome** [comment]
@melvidoni The delay was mutual: I just started a new job and was not able to think much about this project. I will do some research about the possible solutions and come back to you asap.

**Comment by nevrome** [comment]
@melvidoni I discussed this now with the ISAAK people and decided to transfer the package to the ropensci organisation. I will establish a mirror system via CI to keep a copy of the repo at the ISAAKiel organisation. 

Unfortunately I was not able to start the transfer: `You don’t have the permission to create public repositories on ropensci`. What's the problem here?

**Comment by melvidoni** [comment]
Hello @nevrome. You need to first transfer the repo (you need to be part of the rOpenSci org, and _transfer_ not _create_ the repo), and then I'll assign you admin rights on it. That is how we always do it. Is transfer what you tried?

**Comment by nevrome** [comment]
Ah - just got the invitation. Thank you

**Comment by stefaniebutland** [comment]
@nevrome Great to hear things are sorting out. I'm keen to host a blog post when you have time to work on this. Both you and @benmarwick are in rOpenSci Slack so we could move the blog post discussion to a DM there.

**Comment by nevrome** [comment]
@melvidoni: I fulfilled all the ToDos in https://github.com/ropensci/software-review/issues/333#issuecomment-531599658 now. Except for the blog post.

**Comment by arfon** [comment]
> - [ ] Submit to JOSS using the Zenodo DOI. They will tag it for expedited review.

:wave: @melvidoni - this isn't quite correct sorry, we actually need authors to submit to JOSS using the repository address (https://github.com/ropensci/c14bazAAR). Is there an rOpenSci template I can propose a modification to?

**Comment by melvidoni** [comment]
> > * [ ]  Submit to JOSS using the Zenodo DOI. They will tag it for expedited review.
> 
> 👋 @melvidoni - this isn't quite correct sorry, we actually need authors to submit to JOSS using the repository address (https://github.com/ropensci/c14bazAAR). Is there a rOpenSci template I can propose a modification to?

Yes, there is. Let me mention this to the other editors first, please.
