### ISSUE TITLE
Submission: gtsummary

### ISSUE THREAD

**Issue by ddsjoberg** [ropensci/software-review#334]
Submitting Author: Daniel Sjoberg (@ddsjoberg)  
Repository: gtsummary
Version submitted:   1.1.1.9004
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gtsummary
Title: Presentation-Ready Data Summary and Analytic Result
    Tables
Version: 1.1.1.9004
Authors@R: 
    c(person(given = "Daniel D.",
             family = "Sjoberg",
             role = c("aut", "cre"),
             email = "danield.sjoberg@gmail.com",
             comment = c(ORCID = "0000-0003-0862-2018")),
      person(given = "Margie",
             family = "Hannum",
             role = "aut",
             comment = c(ORCID = "0000-0002-2953-0449")),
      person(given = "Karissa",
             family = "Whiting",
             role = "aut",
             comment = c(ORCID = "0000-0002-4683-1868")),
      person(given = "Emily C.",
             family = "Zabor",
             role = "aut",
             comment = c(ORCID = "0000-0002-1402-4498")),
      person(given = "Michael",
             family = "Curry",
             role = "ctb",
             comment = c(ORCID = "0000-0002-0261-4044")),
      person(given = "Esther",
             family = "Drill",
             role = "ctb",
             comment = c(ORCID = "0000-0002-3315-4538")),
      person(given = "Jessica",
             family = "Flynn",
             role = "ctb",
             comment = c(ORCID = "0000-0001-8310-6684")))
Description: Creates presentation-ready tables summarizing data
    sets, regression models, and more. The code to create the tables is
    concise and highly customizable. Data frames can be summarized with
    any function, e.g. mean(), median(), even user-written functions.
    Regression models are summarized and include the reference rows for
    categorical variables. Common regression models, such as logistic
    regression and Cox proportional hazards regression, are automatically
    identified and the tables are pre-filled with appropriate column
    headers. The package is enhanced when the {gt} package is installed.
    Use this code to install: 'remotes::install_github("rstudio/gt")'.
License: MIT + file LICENSE
URL: http://www.danieldsjoberg.com/gtsummary/
BugReports: https://github.com/ddsjoberg/gtsummary/issues
Depends: 
    R (>= 3.4)
Imports: 
    broom (>= 0.5.1),
    broom.mixed (>= 0.2.3),
    crayon (>= 1.3.4),
    dplyr (>= 0.7.8),
    glue (>= 1.3.0),
    knitr (>= 1.21),
    magrittr (>= 1.5),
    purrr (>= 0.3.0),
    rlang (>= 0.3.1),
    stringr (>= 1.3.1),
    survival,
    tibble (>= 2.0.1),
    tidyr (>= 0.8.2),
    tidyselect (>= 0.2.5)
Suggests: 
    car (>= 3.0.2),
    covr (>= 3.2.1),
    curl (>= 3.3),
    geepack (>= 1.2.1),
    ggplot2 (>= 3.1.0),
    Hmisc (>= 4.2.0),
    lme4 (>= 1.1.18.1),
    remotes (>= 2.1.0),
    rmarkdown (>= 1.11),
    spelling (>= 2.0),
    testthat (>= 2.1.0),
    usethis (>= 1.5.0)
Enhances:
    gt (>= 0.1.0)
VignetteBuilder: 
    knitr
Encoding: UTF-8
Language: en-US
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

A common task medical researchers perform is summarizing data sets (i.e. cohorts of patients in studies) and reporting on results from regression models.  The {gtsummary} package is unique from other table packages in that the data and model summary tables are 100% reproducible and formatted to be publication-ready directly from R markdown. 

-   Who is the target audience and what are scientific applications of this package?  

The package is geared towards statisticians and researchers in the medical field.  Two of the package authors (DS and EZ) have served as statistical editors for high-impact journals and have authored papers on statistical reporting guidelines adopted by the top four Urology journals.  The output tables from {gtsummary} have been tailored to be publication-ready following well-established guidelines.  While created with medical researchers in mind, the functionality of the package extends to nearly every data analytics field.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are existing packages that summarize data and regression models.  The package {tableone} is likely the most widely used to summarize data sets, and {stargazer} for summarizing regression models.  Neither of these packages, however, directly produce tables via R markdown that are ready for submission to a journal.  For example, {tableone} prints output to the console and the authors recommend the results are pasted into an Excel file to create the table.  {stargazer} works with R markdown, but lacks necessary formatting for publication (for example, the reference row for a categorical variable in a regression model is never printed).  Our package contains far more customization abilities than any existing summarizing packages we are aware of, by leveraging functionality from the {glue} package, so users can design and customize the exact format and statistics desired in their tables within a few short lines of code.  We also include sensible defaults, such as running appropriate comparison tests based on the data and automatically including footnotes denoting tests used.

The {gtsummary} package takes advantage of the {gt} package being developed by Rstudio, which prints gorgeous tables.  {gtsummary} has a feature we've never seen in any package that improves reproducibility: the package includes a function that reports statistics from the summary tables directly in R markdown text.  Moreover, much thought went into the API and the documentation, which has made the package easy to learn for new users.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
NA

## Technical checks

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
A very early version of this package is on CRAN.  We will send the udpate to CRAN after rOpenSci review.

- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

GitHub: https://github.com/ddsjoberg/gtsummary
Package Website: http://www.danieldsjoberg.com/gtsummary/

**Comment by melvidoni** [comment]
Hello @ddsjoberg , and thanks for your submission. Unfortunately, after a discussion with the editors, we agreed that your package is out-of-scope for rOpenSci: although it does help with reproducibility (and is a great package), it is a too general organisation tool that's beyond our current aims and scope. Thanks again for submitting software peer review. We hope you find another venue for it.

**Comment by ddsjoberg** [comment]
Thank you for the quick response!
