### ISSUE TITLE
baRcodeR presubmission

### ISSUE THREAD

**Issue by yihanwu** [ropensci/software-review#336]
---

Submitting Author: Yihan Wu (@yihanwu)  and Robert Colautti (@ColauttiLab)
Repository: yihanwu/baRcodeR

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: baRcodeR
Title:  Label Creation for Tracking and Collecting Data from Biological Samples
Version: 0.1.3
Authors@R: 
    c(person(given = "Yihan", 
             family = "Wu", 
             role="aut", 
             email = "yihan.wu@queensu.ca", 
             comment = c(ORCID = "0000-0002-1202-4208")), 
      person(given = "Robert", 
             family = "Colautti", 
             email = "robert.colautti@queensu.ca", 
             role = c("aut", "cre"), 
             comment = c(ORCID = "0000-0003-4213-0711")))
Maintainer: Yihan Wu <yihan.wu@queensu.ca>
Description: Tools to generate unique identifier codes and printable barcoded 
    labels for the management of biological samples. The creation of unique ID 
    codes and printable PDF files can be initiated by standard commands, user 
    prompts, or through a GUI addin for R Studio. Biologically informative codes
    can be included for hierarchically structured sampling designs.
Depends:
    R (>= 3.4.0),
    qrcode
License: file LICENSE
Language: en-CA
Encoding: UTF-8
LazyData: true
Imports:
    DT (>= 0.3),
    grDevices,
    grid,
    miniUI (>= 0.1.1),
    shiny (>= 0.13),
    rstudioapi
Suggests: 
    testthat (>= 2.1.0),
    knitr,
    rmarkdown,
    covr,
    shinytest
RoxygenNote: 6.1.1
VignetteBuilder: knitr
URL: https://github.com/yihanwu/baRcodeR
BugReports: https://github.com/yihanwu/baRcodeR/issues

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

- [ ] data retrieval
- [ ] data extraction
- [ ] database access
- [ ] data munging
- [ ] data deposition
- [x] reproducibility
- [ ] geospatial data
- [ ] text analysis

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Reproducibility: baRcodeR facilitates the creation of unique text identifier (ID) codes and scannable barcodes (linear and 2D) that can be printed onto customized sticker labels with consumer-grade printers to facilitate management, tracking, and data collection involving biological samples. Unique identifier codes and scannable barcode labels are produced via reproducible code which reduce transcription errors that arise with hand-written labels and manual entry of label codes. In contrast to commercial software, no proprietary hardware is required, labels can be generated automatically with biologically informative coding, and labels can be created from the command line.

-   Who is the target audience and what are scientific applications of this package?  

baRcodeR is designed to minimize bookkeeping errors and to assist researchers who need to track, curate, or measure biological samples. It is particularly well-suited for large collaborative projects with complex sampling design and numerous samples shared among researchers. For example, a large biological research project may have subjects organized as population/treatment-by-family/line-by-time – that is, each subject sampled multiple times and representing a specific family group or genetic line from one or more nested experimental populations or treatments. The custom layout options in baRcodeR allow researchers to rapidly generate meaningful identifier codes that capture the hierarchical sampling structure, and then print customizable labels containing the ID codes as human-readable text with corresponding digital linear or 2D barcodes. The command-line interface also facilitates rapid re-creation of a set of generated identifiers with different sized labels or minor changes to identifier codes – for example, to label multiple tissue collection containers and then later to label test tubes for purified extracts, each with the same basic code with a new code corresponding to sample type.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category] (https://ropensci.github.io/dev_guide/policies.html#overlap)?
    - [zintr](https://github.com/carlganz/zintr) creates individual barcode image files but does not include functions for (i) automating the creation of biologically-relevant, unique ID codes or (ii) customizable layouts for printing multiple barcodes.
    - [qrcode](https://cran.r-project.org/web/packages/qrcode/index.html) generates qrcodes and is a dependency for baRcodeR to generate 2D barcodes. However, qrcodes also does not include functions for (i) automating the creation of biologically-relevant, unique ID codes or (ii) customizable layouts for printing multiple barcodes.

-  Any other questions or issues we should be aware of?:
This package has already been released onto CRAN (original release + 2 accepted updates).

**Comment by melvidoni** [comment]
Thank you for your submission @yihanwu and @ColauttiLab. We will discuss your enquiry with the editors, and will get back to you soon with an answer. Thanks for submitting!

**Comment by melvidoni** [comment]
Hello @yihanwu and @ColauttiLab!  This package is a bit of an edge case topically, because we don't have a package category specifically that it fits in to, but we think that packages like this are in-scope, so we may say so explicitly in the next revision of our Aims and Scope, which we are currently working on.

That being said, we look forward to receiving a formal submission from you.

**Comment by yihanwu** [comment]
Hi @melvidoni,

Thanks for the review! I'll get the formal submission done shortly!
