### ISSUE TITLE
presubmission : ceRNAnetsim-Competing Endogeneous RNA Network Simulator

### ISSUE THREAD

**Issue by selcenari** [ropensci/software-review#340]
Submitting Author: Selcen Ari (@selcenari)  
Repository:   selcenari/ceRNAnetsim

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: ceRNAnetsim
Title: Regulation Simulator of Interaction between miRNA and
    Competing RNAs (ceRNA)
Version: 0.1.0
Authors@R: 
    c(person(given = "Selcen",
             family = "Ari",
             role = c("aut", "cre"),
             email = "selcenarii@gmail.com",
             comment = c(ORCID = "0000-0002-0028-2453")),
      person(given = "Alper",
             family = "Yilmaz",
             role = "aut",
             email = "alperyilmaz@gmail.com",
             comment = c(ORCID = "0000-0002-8827-4887")))
Author: Selcen Ari [aut, cre], Alper Yilmaz [aut]
Maintainer: Selcen Ari <selcenarii@gmail.com>
Description: This package simulates regulations of ceRNA
    (Competing Endogenous) expression levels after a expression level
    change in one or more miRNA/mRNAs. The methodolgy adopted by the
    package has potential to incorparate any ceRNA (circRNA, lincRNA,
    etc.) into miRNA:target interaction network.  The package basically
    distributes miRNA expression over available ceRNAs where each ceRNA
    attracks miRNAs proportional to its amount. But, the package can
    utilize multiple parameters that modify miRNA effect on its target
    (seed type, binding energy, binding location, etc.).  The functions
    handle the given dataset as graph object and the processes progress
    via edge and node variables.
License: GPL-3.0
URL: https://selcenari.github.io/ceRNAnetsim/
BugReports: https://github.com/selcenari/ceRNAnetsim/issues
Depends:
    dplyr,
    tidygraph
Imports: 
    furrr,
    rlang,
    tibble,
    ggplot2,
    ggraph,
    igraph,
    purrr,
    tidyr
Suggests:
    knitr,
    png,
    rmarkdown,
    testthat,
    covr
VignetteBuilder: 
    knitr
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

A tabular dataset is converted into network, and then network based analysis/simulation is performed.

-   Who is the target audience and what are scientific applications of this package?  

Molecular Biologists, studying gene expression, microRNA expression.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No

-  Any other questions or issues we should be aware of?:

**Comment by alperyilmaz** [comment]
Hi @melvidoni , we were wondering if our presubmission is overlooked. Is there anything we should do while waiting?

**Comment by melvidoni** [comment]
Hello @alperyilmaz sorry about that! I apparently missed up on replying to you. My sincere apologies.

With have discussed this with the editors and think this is a challenging/borderline submission. We are going to have a third party help us with this (we need a bioinformatic person). Please, bear with me for a couple days while we get the feedback.

**Comment by melvidoni** [comment]
Hello again @alperyilmaz! After discussing with invited third party, we consider this as out of scope, mostly because it is not 100% data munging, and because its being mainly about something out-of-scope. Apologies again for keeping you waiting, occasionally, those things happen.
