### ISSUE TITLE
presubmission: opendatatoronto

### ISSUE THREAD

**Issue by sharlagelfand** [ropensci/software-review#343]
Submitting Author: Sharla Gelfand (@sharlagelfand)  
Repository:  https://github.com/sharlagelfand/opendatatoronto/

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: opendatatoronto
Title: Access the City of Toronto Open Data Portal API
Version: 0.0.0.9007
Authors@R: 
    c(person(given = "Sharla",
           family = "Gelfand",
           role = c("aut", "cre"),
           email = "sharla.gelfand@gmail.com"),
      person(given = "City of Toronto",
             role = c("cph", "fnd")))
Description: Search and retrieve data from the City of Toronto Open Data Portal
    (<https://open.toronto.ca>) directly from R.
License: MIT + file LICENSE
URL: https://sharlagelfand.github.io/opendatatoronto/, https://github.com/sharlagelfand/opendatatoronto/
BugReports: https://github.com/sharlagelfand/opendatatoronto/issues
Depends: 
    R (>= 2.10)
Imports: 
    ckanr (>= 0.3.3.9140),
    tibble,
    httr,
    jsonlite,
    magrittr
Suggests: 
    covr,
    testthat,
    sf,
    readxl,
    xml2,
    knitr,
    rmarkdown,
    geojsonsf,
    cancensus,
    dplyr,
    ggplot2,
    purrr
Remotes: 
    ropensci/ckanr
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

`opendatatoronto` enables access of data from the [Toronto Open Data portal](https://open.toronto.ca/) directly from R. 

This is definitely (open) data retrieval but not necessarily from an "online source with scientific applications". Since the portal is based off CKAN, and ropensci has a `ckanr` package (I'll address the overlap below), I'm inclined to inquiry about submission anyways!

-   Who is the target audience and what are scientific applications of this package?  

The target audience is people who want to use data from the Toronto Open Data portal and don't necessarily want to go through the process of finding the data, downloading it, figuring out what function to use to read it in depending on the format, etc. Enabling easier access to open data helps folks ask and answer questions about civic issues.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Definitely - this package is built off of ropensci's own [`ckanr`](https://github.com/ropensci/ckanr), with `ckanr` doing a lot of the heavy lifting. I see a few differences:

1. The scope of `opendatatoronto` is deliberately a lot narrower. `ckanr` enables you "to create, modify, and manage datasets, as well as search and download pre-existing data, and then to proceed using in R for data analysis (stats/plotting/etc.)." It is intended for the CKAN dev *and* a user of a CKAN instance. `opendatatoronto` is specifically designed for someone looking to use open data, and the functionality is limited to searching and downloading pre-existing data.
2. This package was built in collaboration with the Open Data Toronto team based on how they use CKAN. Specifically, the function `get_resource()` obscures the existence of two different storage systems in CKAN, the file store and the data store, so that a user doesn't have to know which function to use (e.g. `ckanr::ckan_fetch()` and `ckanr::ds_search()`, respectively).
3. There are more specific error messages and return types (i.e., always a tibble or list of tibbles).

I'm definitely not trying to replace `ckanr` here - while developing opendatatoronto, I contributed needed functionality into `ckanr` instead of squirrelling it away in my own package and will continue to do so. This is also why the package imports such a specific dev version of ckanr.

-  Any other questions or issues we should be aware of?:

**Comment by melvidoni** [comment]
Thanks for your submission! Editors will discuss this, and  I'll come back with an answer soon.

**Comment by melvidoni** [comment]
Hello @sharlagelfand, and thanks again for the submission. We have discussed this with the editors, but ultimately agreed it is _out of scope_, as it is more of a government data camp, rather than providing tools for scientific data. Nonetheless, I wish you the best and I'm sure you'll find a venue for your package.
