### ISSUE TITLE
presubmission: SDesti

### ISSUE THREAD

**Issue by SD1060** [ropensci/software-review#345]
Submitting Author: Diogo Sayanda (@SD1060)  
Repository:   https://github.com/SD1060/SDesti

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: SDesti
Type: Package
Title: An R package for the analysis of macroinvertebrate and periphyton environmental studies’ data
Version: 0.1.0
Date:2019-03-27
Author: Diogo Sayanda
Maintainer: Diogo Sayanda <dsayanda@yahoo.com>
Description: An adequate and complete statistical analysis for Stone dwelling organisms and Periphyton biomonitoring data. It receives data on macroinvertebrates (counts or biological index), or Periphyton (counts, chlorophyll concentration, ash free dry mass (AFDM), or biological index), environmental variables and site habitat composition data collected over a period of time and has four user accessible functions that return: 1) the descriptive analysis of each sample and a surficial evaluation of the quality of the data recurring to the power function; 2) estimates of number of individuals/chlorophyll concentration/AFDM/index per area of benthic habitat at one given site; 3) the typical descriptive analysis that precedes the adjustment of a regression model, including detection of multi-collinearity and determining the transformation that maximizes the linear relation between the response and the covariates in analysis; 4) the adjustment of a regression model (linear, Poisson, quasipoisson, or negative binomial) according to the characteristics of the data, selection of the best model recurring to automated backward and forward routines, estimation of measures of goodness-of-fit, identification of the outliers, influent observations, and delivery of the graphics necessary to analyze the residuals. The program delivers information that allows the user to make a general evaluation of the quality of each sample, evaluate the quality of the analysis and interpret the data. The program includes a complete manual.
License: BSD3 + file LICENSE
Copyright: Diogo Sayanda and Alberta Enviroment and Parks
Encoding: UTF-8
LazyData: true
Imports: grDevices, broom, car, caret, faraway, graphics, MASS, stats
RoxygenNote: 6.1.1
Suggests: knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The program is intended to be used in multiple environmental monitoring programs increasing their transparency, consistency and facilitating the integration of distinct studies on surface aquatic systems management.

-   Who is the target audience and what are scientific applications of this package?  

Biologists that monitor the heath of rivers' aquatic ecosystems.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There is no other package that simplify so much the data analysis as SDesti does.
To perform the exact same analysis the user could recur to numerous functions within other packages which means that the process would be much more complex and time consuming than it is when using SDesti. The selection of the "best" quasipoisson model and testing multiple interaction terms would also have to be done manually. SDesti includes algorithms that perform these automatically while respecting the hierarchical principle.

Chlorophyll data tables are usually complex and chlorophyll concentration, or AFDM have to be calculated. SDesti performs all the needed calculations regarding to this data and reduces the complexity of the analysis and human error.

SDesti was developed for non statisticians and persons that are not proficient with R, delivering the information that they need to interpret the data and reducing time for data analysis and human error.

-  Any other questions or issues we should be aware of?:
I don't think so...

**Comment by melvidoni** [comment]
Hello @SD1060, could you provide a link to the original repo?

**Comment by SD1060** [comment]
I haven't uploaded the package to any repository yet... Is that what you are asking? I'm sorry I'm new to this...

**Comment by SD1060** [comment]
Sorry, I'm not familiar with gitHub, I've just created it https://github.com/SD1060/SDesti.git

**Comment by melvidoni** [comment]
Thank you @SD1060, and don't worry! We are discussing it and I will come back with an answer soon.

**Comment by melvidoni** [comment]
Hello @SD1060. Thanks for the repo link, but it still has no code inside of it. Based on the information you provided, it seems a like a methods / "methods workflow" package, which would be out of scope. We do hope the best for you, and that you can find an appropriate venue for it. Good luck!

**Comment by SD1060** [comment]
I have a question:
SDesti is a statistical analysis package, its objective is to facilitate the data analysis of two of the most widely used bio-indicators for the health of aquatic systems and grant consistency in the results and facilitate repetition the integration of data and results from different studies in decision making and management.
Would the above count as "reproducibility: Tools that facilitate reproducible research."?
Thank you,
Diogo

**Comment by melvidoni** [comment]
Hello @SD1060, as EiC I can take your argument to the rest of the editors, but we need the repo of your package to be completed with the code, if we want to reconsider this. Can you please do that, and let me know?

**Comment by melvidoni** [comment]
Hello @SD1060. Our _reproducibility_ category actually refers to a few distinct subtopics and that we realise that it can sound like a catch-all, which is why we just updated the guide to separate these out for more clarity ([check here](https://devguide.ropensci.org/policies.html#aims-and-scope)). 

There is also an upcoming blog post about that: https://github.com/ropensci/roweb2/pull/521/files

**Comment by SD1060** [comment]
My problem is that I want to publish my program in Methods in Ecology and Evolution, they strongly recommend to use rOpenSci to validate our code before submitting a paper... I got rejected by the editor most probably because I didn't get my code reviewed, is there any other platform where I can get my program reviewed?

**Comment by melvidoni** [comment]
Hello @SD1060. 

We are not sure where MEE "strongly recommends to use rOpenSci," as the partnership only works for packages that fit into both scopes. However, they are increasingly using our standards in the review.  Our guess is that the editor suggested that you use our standards to bring his package up to snuff to be reviewed.

We suggest submitting to JOSS, but similar journals will want the code hosted on GitHub or a similar platform, and at minimum pass checks for CRAN and have testing.  Our guide or the R packages book can provide guidance for how to do this.

If you encounter issues whilst trying to apply best practice from these sources then there are a few places where to ask specific questions, which you can find at: https://docs.r-hub.io/#places-to-ask-questions
