### ISSUE TITLE
presubmission: healthdatacsv

### ISSUE THREAD

**Issue by iecastro** [ropensci/software-review#350]
Submitting Author: Ivan Castro (@iecastro)  
Repository:   https://github.com/iecastro/healthdatacsv

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: healthdatacsv
Title: Access and download data from the healthdata.gov catalog
Version: 0.0.0.9000
Authors@R: 
    person(given = "Ivan",
           family = "Castro",
           role = c("aut", "cre"),
           email = "ivedcastr@gmail.com",
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: This package will make an API call to the data.json endpoint of HealthData.gov 
             and download data if available in csv format.  Some helper functions available
             help users first query by listed Agency and/or keywords.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
URL: https://github.com/iecastro/healthdatacsv
BugReports: https://github.com/iecastro/healthdatacsv/issues
Imports: 
    dplyr,
    httr,
    jsonlite,
    purrr,
    stringr,
    tidyr
RoxygenNote: 6.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
`healthdatacsv` falls under *data retrieval* because it accesses and downloads data from an online source.  This package focuses on health-related data made available from the [HealthData.gov API](https://healthdata.gov/node/25341).

-   Who is the target audience and what are scientific applications of this package?  
Target audience would be researchers, instructors, students, and analysts in health-related fields (i.e. Epidemiology, Health Economics, Health Services Research).  The data accessed are collected by agencies of the US Dept. of Health and Human Services, and are often nationally representative. 
 Scientific applications include, among others, the investigation of: disease patterns, trends in health behaviors, or deficits in health systems.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There is [rHealthDataGov](https://github.com/rOpenHealth/rHealthDataGov); however, this package has not been updated and does not function properly with the current [HealthData.gov API](https://healthdata.gov/node/25341).

-  Any other questions or issues we should be aware of?:
If `healthdatacsv` was to fall within scope, it is not ready to be submitted for review.  It is pending a test suite; and maybe additional functionality - which makes me wonder, is there a threshold of what would be considered a *package*, as opposed to just a set of functions?

**Comment by maelle** [comment]
Thanks for your pre-submission inquiry @iecastro! 😀 Yes your package is in scope and we'd welcome a full submission when it's ready.

Our threshold of what constitutes a _good_ package is our [dev guide](https://devguide.ropensci.org). If you have any trouble between now and submission do not hesitate to ask for resources/help on discuss.ropensci.org 🙂

**Comment by iecastro** [comment]
Thank you for the feedback, @maelle! I will keep working on this.
