### ISSUE TITLE
BIRDS: A set of tools for Biodiversity Informatics in R

### ISSUE THREAD

**Issue by aleruete** [ropensci/software-review#352]
Pre-submittion
Submitting Author: Alejandro Ruete (@github_handle)  
Repository:   https://github.com/Greensway/BIRDS

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: BIRDS
Type: Package
Title: A set of tools for Biodiversity Information Review and Decision Support 
Version: 0.0.3
URL: https://github.com/greensway/BIRDS
Authors@R: c(
    person("Debora", "Arlt", email = "debora.arlt@slu.se", role = "aut",
            comment = c(ORCID = "0000-0003-0874-4250")),
    person("Alejandro", "Ruete", email = "alejandro@greensway.se", role = c("aut","cre"),
            comment = c(ORCID = "0000-0001-7681-2812")),
    person("Anton", "Hammarström", email = "anton@greensway.se", role = "aut"))
Description: A set of tools to review and make decisions upon the use of
   biodiversity data. This R package helps making the evaluation and preparation 
   of biodiversity data easy, systematic and reproducible. It also helps the users
   to overlay the point observations into a custom grid that is useful for further
   analysis. The review summarise statistics that helps evaluate whether a set 
   of species observations is fit-for-use and take decisions upon its use of on
   further analyses. It does so by quantifying the sampling effort (amount of 
   effort expended during an event) and data completeness (data gaps) to help 
   judge whether the data is representative, valid and fit for any intended 
   purpose. The `BIRDS` package is most useful when working with heterogeneous 
   data sets with variation in the sampling process, i.e. where data have been 
   collected and reported in various ways and therefore varying in sampling effort 
   and data completeness (i.e. how well the reported observations describe the 
   “true” state). Primary biodiversity data (PBD) combining data from different 
   data sets, like e.g. GBIF mediated data, commonly vary in the ways data has 
   been generated - containing opportunistically collected presence-only data 
   toghether with and data from systematic monitoring programs. The set of tools
   provided is aimed at understanding the process that generated the data (i.e. 
   observing, recording and reporting species into databases).
License: GPL-3
Encoding: UTF-8
LazyData: true
Depends: R (>= 3.4.0)
SystemRequirements: GDAL (>= 2.0.1)
Imports:
    data.table, 
    dggridR, 
    dplyr,
    esquisse,
    geosphere (>= 1.5),
    leaflet (>= 2.0),
    lubridate (>= 1.7.4),
    magrittr,
    mapedit (>= 0.5),
    methods,
    rgeos (>= 0.4),
    rgdal (>= 1.4),
    rlang,
    sf (>= 0.7),
    shiny (>= 1.0),
    sp (>= 1.3),
    stringr (>= 1.4), 
    vegan,
    xts
Suggests: 
    biogeo,
    CoordinateCleaner, 
    covr, 
    knitr, 
    KnowBR, 
    leaflet.extras,
    leafpm,
    maps, 
    rgbif, 
    rmarkdown, 
    taxize, 
    testthat,
    utils
RoxygenNote: 7.0.0
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
        - [x] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
This package works with primary biodiversity data (PBD). We offer functions to make the process data curation process [after data download and possible cleaning and before analysis] systematic and reproducible. This process includes organization of the point data in a grid cell, evaluation of gaps and sampling effort, report of statistics that help taking decisions whether the data is fit-for-use, and export functions for use in further analysis (i.e. completeness analyses, community comparisons, SDM of various kinds, time trends, etc). 

-   Who is the target audience and what are scientific applications of this package?  
The target audience is anyone downloading data from biodiversity data portals that aims to better understand the data. We envision that the scientific papers and technical reports using this package will include sentences like: "We organised the species observations into a 10km-wide hexagonal grid where 90% of the grid cells had at least 10 observations and the all visits had a sampling radius lower than 1 km. Visits where defined by unique combinations of observation day and recorder name (BIRDS 2019; see R scripts in supporting materials)".  

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
As far as we are aware, no. There are complementary packages like rgif, taxasize, coordinateCleaner. These packages take on after that. See [technical vignette](https://greensway.github.io/BIRDS/articles/technical_details.html)

-  Any other questions or issues we should be aware of?:
The package is under development and we are considering and perfecting new tools all the time.

**Comment by maelle** [comment]
Thanks @aleruete for your submission that we however deemed out of scope.

After discussion we decided that it does not fit under the selected categories as we view them. Your package seems to be a data exploration (EDA) tool, that we don't support because we cannot judge what is the best way to assess such data.

Thanks again for your submission, congrats on the awesome diagram in the docs :star2:, and good luck with `BIRDS` development and promotion! :rocket:

**Comment by aleruete** [comment]
Hi Maelle, 
Thank you for taking your time to review it. 
is there any chance to try to explain that it is NOT ONLY a EDA but it also systematize data processing and makes all assumptions taken on each step transparent (even when authors don't realize they are taking assumptions)? 

Best Regards,

Alejandro

**Comment by maelle** [comment]
Hi Alejandro, thanks and you're welcome, as I said the docs were a pleasure to look at.

The data processing is quite specific to your field (e.g. drake and assertr are general tools), and too methodological for us to review. But I suppose other venues than rOpenSci might be relevant!
