### ISSUE TITLE
Presubmission inquiry: packexplorer

### ISSUE THREAD

**Issue by arielolafsalgado** [ropensci/software-review#355]
Submitting Author: Ariel Salgado (@arielolafsalgado)  
Repository:  https://github.com/arielolafsalgado/packexplorer

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: packexplorer
Title: Help in searching for new packages
Version: 0.0.0.9000
Authors@R: as.person(c(
    "Ariel Salgado <asalgado@df.uba.ar> [aut, cre]", 
    "Andrés Farall <afarall@gmail.com> [aut]",
    "Inés Caridi <ines@df.uba.ar> [aut]"
  ))
Description: Tools to explore CRAN and visualize relationships between packages. With a leaflet-based visualization, create your own network of packages and get information about new packages, related to the packages you use regularly. Also, find packages based on specific terms, taking into account the underlying dependency network.
Depends: R (>= 3.5), igraph
Imports: leaflet, stringr, Matrix, htmltools, methods
Suggests: mailR, knitr,rmarkdown,testthat
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package aims to shorten the distance between the multiplicity of packages available in CRAN and the user. Provides a friendlier view of software package options, from a network perspective.

-   Who is the target audience and what are scientific applications of this package?  

We hope that the basic user of R will be helped with this tool, providing a better experience in finding useful software for their specific work area.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

This package relates to `cranlogs`, which provides information on the different package downloads, and` cranly`, which allows you to browse the CRAN network. It is different in that this package aims to recommend new packages, based on those already installed, with the addition of useful support tools to explore specific packages or topics.

-  Any other questions or issues we should be aware of?:

**Comment by maelle** [comment]
Thanks for your pre-submission inquiry @arielolafsalgado ! However, your package is out-of-scope: it is a too general tool (rather than a tool helping scientific workflows and scientific research) that's beyond our current aims and scopes. 

It is a good idea for a package, best of luck with its future development and promotion!
