### ISSUE TITLE
presubmission : R package conjurer

### ISSUE THREAD

**Issue by SidharthMacherla** [ropensci/software-review#364]
Submitting Author: Name (@SidharthMacherla)  
Repository:   https://github.com/SidharthMacherla/conjurer

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: conjurer
Type: Package
Title: A Parametric Method for Generating Synthetic Data
Version: 1.0.0
Date: 2020-01-07
Authors@R: person("Sidharth", "Macherla", email = "msidharthrasik@gmail.com",
                  role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4825-2026"))
Description: Builds synthetic data applicable across multiple domains. This package also provides flexibility to control data distribution to make it relevant to many industry examples.
License: MIT + file LICENSE
URL: https://github.com/SidharthMacherla/conjurer
BugReports: https://github.com/SidharthMacherla/conjurer/issues
Encoding: UTF-8
LazyData: FALSE
RoxygenNote: 7.0.2.9000
Suggests: 
    knitr,
    rmarkdown
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [x] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
This package builds synthetic data. I am not entirely sure if the category selected is appropriate as there is no category explicitly speaking about synthetic data generation.

-   Who is the target audience and what are scientific applications of this package?  
In academia, this package helps students and researchers while in industry, it helps data scientists.
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
I am aware of 2 packages in R that generate synthetic data namely, **charlatan** and **synthpop**. These packages focus on synthetic versions of microdata containing confidential information. For example, these packages generates synthetic personal identifiers such as addresses, person names, phone numbers etc. However, this package **conjurer** provides for a more generic use that helps users to test and validate their research or industry projects that rely on data distributions.

-  Any other questions or issues we should be aware of?:
This package is on CRAN already and wanted to know if it qualifies for rOpenSci submission.

**Comment by maelle** [comment]
Thanks for your submission @SidharthMacherla! However, packages with statistical algorithms/methods (like the creation of data with a given distribution) are out-of-scope. We hope you find another venue for your package.
