### ISSUE TITLE
presubmission: Does EPGMr package fit?

### ISSUE THREAD

**Issue by SwampThingPaul** [ropensci/software-review#365]
Submitting Author: Paul Julian (@SwampThingPaul)  
Repository:   https://github.com/SwampThingPaul/EPGMr

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: EPGMr
Type: Package
Title: Implements the Everglades Phosphorus Gradient Model in R
Version: 0.1.0
Authors@R: person("Paul","Julian",email="pauljulianphd@gmail.com",role=c("aut","cre"))
Maintainer: Paul Julian <pauljulianphd@gmail.com>
URL: https://github.com/swampthingpaul/EPGMr
Description: The model used for Stormwater Treatment Area (STA) design is expanded to include mass balances on marsh water-columns and surface soils. EPGM (Everglades Phosphorus Gradient Model) predicts variations in water-column P concentration, peat accretion rate, and soil P concentration along a horizontal gradient imposed by an external phosphorus load and sheet-flow conditions. Potential biological responses are expressed in terms of marsh surface area exceeding threshold criteria for water-column and soil phosphorus concentrations. More information of the model can be found at http://www.wwwalker.net/epgm/
License: CC0
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1.9000
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Honestly, I am not sure if this package fits the @ropensci package policy or if it does which category this package falls. Generally, this package is implementation of an ecological model originally developed as a spreadsheet model with several macros (originally in Lotus123, then converted to Excel; [webpage](http://www.wwwalker.net/epgm/)). Originally this model was developed for application in specific to the [Everglades ecosystem](https://en.wikipedia.org/wiki/Everglades) but has the potential to be applied to other wetland ecosystems more broadly.

-   Who is the target audience and what are scientific applications of this package?  

Ecosystem scientists, data scientist and modelers

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

To the author's knowledge, there are no `R` packages that accomplish what [EPGMr](https://github.com/SwampThingPaul/EPGMr), specifically. 

-  Any other questions or issues we should be aware of?:

I have been in communication with the model's original developer [Dr. Walker](http://www.wwwalker.net), I have shared the GitHub repo and he is aware of the progress.

**Comment by maelle** [comment]
Thanks for your presubmission @SwampThingPaul! As it is a methodological package (a re-write of a tool providing an ecological model), it is out-of-scope. Rewriting the Excel tool in R is a great effort nonetheless! We hope you find another venue for it (maybe [JOSS(https://joss.theoj.org/)?).
