### ISSUE TITLE
eneRgetics

### ISSUE THREAD

**Issue by CamiloCarneiro** [ropensci/software-review#374]
Submitting Author: Name (@CamiloCarneiro)  
Repository:   https://github.com/CamiloCarneiro/eneRgetics

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: eneRgetics
Title: Estimates the Maintenance Metabolism of shorebirds
Version: 0.0.0.9000
Description: eneRgetics provides a fast and straightforward way to calculate the
    Maintenance Metabolism of shorebirds. It has functions to retrieve the necessary
    environmental data to calculate it, to retrieve tidal data and to create
    categories for the tide state in relation to low tide. Additionally, it provides
    a function to calculate the Basal Metabolic Rate of shorebirds.
Depends:
    R (>= 3.4.0)
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Imports:
    checkmate (>= 1.8.5),
    dplyr (>= 0.5.0),
    camsRad (>= 0.3.0),
    darksky (>= 1.3.0),
    lubridate (>= 1.1.7),
    RCurl (>= 1.95-4.8),
    jsonlite(>= 1.5)
Suggests:
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: rmarkdown
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [X] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The main advantage of this package is to easily retrieve, from online sources, the data required to calculate the maintenance metabolism of shorebirds, such as weather and tidal data.

-   Who is the target audience and what are scientific applications of this package?  
Researchers interested in determining the maintenance metabolism of shorebirds. For example, to compare the maintenance metabolism across a wide wintering range (which most shorebirds have) allows the investigation of costs/benefits and their trade-off with certain life-history traits (e.g. migration distance). This package creates a fast route to gather the necessary data for such analysis. These kind of analysis are relevant when we think about the global changes in the climate, that might lead to a change in the energetic requirements of animals.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
We are not aware of any other package that aims to accomplish the same thing.

-  Any other questions or issues we should be aware of?:
This is the first package we are preparing.

**Comment by annakrystalli** [comment]
Hi @CamiloCarneiro ! Thanks for your submission. Could you please a link to the package's GitHub repository?

**Comment by CamiloCarneiro** [comment]
Hi. Sure. Here it is: https://github.com/CamiloCarneiro/eneRgetics

**Comment by noamross** [comment]
⚠️⚠️⚠️⚠️⚠️

***In the interest of reducing load on reviewers and editors as we manage the
COVID-19 crisis, rOpenSci is temporarily pausing new submissions for software peer review
for 30 days (and possibly longer). Please check back here again after 17 April
for updates.***

***In this period new submissions will not be handled, nor new reviewers assigned. 
Reviews and responses to reviews will be handled on a 'best effort' basis, but
no follow-up reminders will be sent.***

***Other rOpenSci community activities continue. We express our continued great
appreciation for the work of our authors and reviewers. Stay healthy and take
care of one other.***

***The rOpenSci Editorial Board***

⚠️⚠️⚠️⚠️⚠️

**Comment by annakrystalli** [comment]
Dear @CamiloCarneiro,

Thanks again for your submission. We have been discussing whether the package is in scope and have concluded that unfortunately it is not for the following reasons:

- The package has been submitted under data retrieval
- The main innovation as we see it is retrieval of the tide data. However, the world tides API is a paid service and calls to it are costed. Users seem to get 100 free credits (calls) but then need to be paid for https://www.worldtides.info/developer. 
- The weather is spatially limited and just combines data sourced through packages `darksky` and `camsRad`) and then combine the data. While useful, this does not add significant value.
- The main function of the package is the maintenance metabolism calculation `mmaint`, which as useful as it might be to domain specialists, renders it ultimately out of scope under data retrieval.

Having said that we still think your package may well be of use to domain specialist so we encourage you to continue making it available to your community should you wish to. 

#### Some general advice for improving the package:

- It is not clear from the README that the tide data is sourced from a paid service. We advise you make details of potential costs much clearer in the README.
- We also recommend you mention the various APIs users need to get tokens for in the README (perhaps following installation instructions) and provide more details on how to get each API token and how to handle them in a separate vignette. API tokens need to be handled securely and you may need to educate users on how to do so. See for example instructions on how to [handle `GITHUB_PAT`](https://happygitwithr.com/github-pat.html) API tokens.
- Your `build` and `coverage` badges in the README are showing **unknown**. You might want to trigger a build to ensure the data required for the badges is available.

Many thanks again for your patience as we assessed the package.

**Comment by CamiloCarneiro** [comment]
Dear @annakrystalli,

Thank you for your time to assess the package and for the advice to improve it. Much appreciated.

Best regards.
