### ISSUE TITLE
Submission: set6

### ISSUE THREAD

**Issue by RaphaelS1** [ropensci/software-review#383]
Submitting Author: Raphael Sonabend (@RaphaelS1)  
Repository:   https://github.com/xoopR/set6
Version submitted:  0.1.4
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: set6
Title: R6 Mathematical Sets Interface
Version: 0.1.4
Authors@R: 
      c(person(given = "Raphael",
             family = "Sonabend",
             role = c("aut","cre"),
             email = "raphael.sonabend.15@ucl.ac.uk",
             comment = c(ORCID = "0000-0001-9225-4654")),
      person(given = "Franz",
             family = "Kiraly",
             role = "aut",
             email = "f.kiraly@ucl.ac.uk"))
Description: An object-oriented package for mathematical sets, upgrading the current gold-standard {sets}. Many forms of mathematical sets are implemented, including (countably finite) sets, tuples, intervals (countably infinite or uncountable), and fuzzy variants. Wrappers extend functionality by allowing symbolic representations of complex operations on sets, including unions, (cartesian) products, exponentiation, and differences (asymmetric and symmetric).
LinkingTo: Rcpp
Imports: checkmate, Rcpp, R6, utils
Suggests: knitr, testthat, devtools, rmarkdown
License: MIT + file LICENSE
LazyData: true
URL: https://xoopR.github.io/set6/, https://github.com/xoopR/set6
BugReports: https://github.com/xoopR/set6/issues
VignetteBuilder: 
    knitr
Encoding: UTF-8
RoxygenNote: 7.1.0
Roxygen: list(markdown = TRUE, r6 = TRUE)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automataion
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

`set6` implements mathematical sets, tuples, and conditional sets thus allowing the manipulation and organisation of data of any types in R.

-   Who is the target audience and what are scientific applications of this package?  

`set6` is built using the `R6` paradigm and thus serves as an alternative to the S3/S4 `sets` package; any object-oriented package using R6 can make use of set6 as a single base class to unify R types. Specific applications that it currently is being used for include representation of distribution and parameter domains, and validation checks.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are a few packages in R that handle sets, however with the exception of `sets`, all are primarily focused on one specific purpose, e.g. fuzzy sets, clustering, 'tidy' representation. The `sets` package is the most general but this is built using an older object-oriented paradigm. To my knowledge, no other package can handle symbolic representation in the same way as set6 because of the use of R6 classes.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [x] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [x] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [x] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by annakrystalli** [comment]
Hello @RaphaelS1 and many thanks for your submissions. 

In the end after discussion we decided that because there is not a research specific aspact to it, the package is sadly too general for the rOpenSci scope.

Thanks again for taking the time to submit.

**Comment by RaphaelS1** [comment]
Okay, thanks very much for your time!
