### ISSUE TITLE
RingdateR app

### ISSUE THREAD

**Issue by ringdater** [ropensci/software-review#388]
Submitting Author: David Reynolds (@ringdater) 
Repository:   ringdater_pkg
Version submitted:   0.1.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ringdater
Type: Package
Title: A Statstical and Graphical Tool for Crossdating
Version: 0.1.0
Author: c(person("David", "Reynolds", role = c("aut", "cre"),
    person("David", "Edge", role = "aut"),
    person("Bryan", "Black", role = "aut"))
Maintainer: David Reynolds <davidreynolds@email.arizona.edu>
Description: An interactive application (Shiny app) for visual and statistical crossdating
    of annually resolved measurement time series (e.g. tree rings or mollusc, fish and coral growth rings).
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
Depends: R (>= 4.0.0)
Suggests: 
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
Imports: 
    data.table,
    DataCombine,
    DescTools,
    doParallel,
    dplR,
    dplyr,
    DT,
    ggplot2,
    grid,
    gridExtra,
    htmlwidgets,
    magrittr,
    readxl,
    shinycssloaders,
    shinydashboard,
    shinyjs,
    shinyalert,
    stats,
    stringr,
    tidyselect,
    xml2,
    zoo,
    zoocat,
    shiny,
    shinyWidgets

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automataion
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

RingdateR is a shiny application to facilitate the rapid and robust construction of annually resolved crossdated chronologies built from annually resolved growth rings (e.g. tree rings). Crossdating, a key technique in dendrochronology, is the pain staking and time-consuming task of visually and statically comparing tree ring width patterns to samples of unknown antiquity against live sampled trees. The process facilitates the construction of chronologies that extend further back in time than a single individual tree would allow. Crossdating dead samples is particularly time consuming as their antiquity is unknown and so requires a large number of analyses to be conducted. RingdateR aims to facilitate this process.

-   Who is the target audience and what are scientific applications of this package?  
Researchers in the fields of dendrochronology and sclerochronology who use crossdating techniques.

Researchers in the fields of dendrochronology and sclerochronology who use crossdating techniques.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The dplR package is the primary package currently used by dendrochronologists. dplR is a large package which facilitates a wide array of dendrochronology based analyses, of which crossdating is a component. RingdateR differs from the crossdating tools in dplR in several ways. Firstly, Ringdater facilitates crossdating through an interactive shiny application and so users are not required to have a working knowledge of R. RingdateR is available as an R package, from github, as a webpage via the shinyapps.io server or as a standalone windows application. Links to access the app are available from the main RingdateR web page ( https://ringdater.github.io/ringdater/). The shiny app will facilitate the engagement with a wider number of users as well as enhance reproducibility. In addition, RingdateR has been designed to operate with measurement files that are created by several measurement applications (e.g. CooRecorder and Image Pro) as well as compiled datasets in various formats (excel, csv etc.). This allows an easy movement from data generation to data analysis and validation. Once the data are loaded, RingdateR uses lead-lag analyses to identify the possible crossdates between samples, automatically aligns the selected samples in time, and produces time series plots of the aligned data as well as running lead-lag correlation heat maps. The heat maps provide a powerful tool to examine the coherence of the variability between samples through time and to assess if potential problems exist in the measurement timeseries. They therefore provide an important step in data validation. Finally, the user can set and apply statistical filters to quantitatively evaluate the crossdates and then choose to align selected samples in time to construct a chronology or conduct further analyses using data outputs from RingdateR. 

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

We have prepared a manuscript which we plan to submit to the journal Dendrochronologia following this review process. This journal requires the application is reviewed by ROpenSci prior to submitting the manuscript. We can make it available to the ROpenSci reviewers if that would be helpful.

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by geanders** [comment]
Hi @ringdater! Could you please include a link to the package's GitHub repository?

**Comment by ringdater** [comment]
HI @geanders, Sorry I didn't include this!  https://github.com/ringdater/ringdater_pkg

**Comment by geanders** [comment]
@ringdater : Thank you so much for your submission. We have discussed it and decided that it is out-of-scope for ROpenSci for two reasons. First, is seems the data processing is fairly specific to your field, making it more of a methodological package in terms of the underlying R functions. Second, we consider out-of-scope packages that focus on providing a Shiny app that package users would use for data analysis if there is not also a mechanism to make the interactive workflow reproducible, such as code generation. 

We wish you good luck with your package, as it looks for interesting for its target audience, and encourage you to look into publishing or promoting it through other venues in your field. If you do want to explore adding code generation as part of your package at some point, one of our editors suggested that the following resource might be useful: https://github.com/rstudio/shinymeta.

Again, I apologize that we do not have better news for you, but I wish you the best of luck in continuing your work on this and other R packages!
