### ISSUE TITLE
CoSMoS - does our package fit?

### ISSUE THREAD

**Issue by KevinShook** [ropensci/software-review#390]
Submitting Author: Kevin Shook@https://github.com/KevinShook
Repository:   https://github.com/TycheLab/CoSMoS

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: CoSMoS
Type: Package
Title: Complete Stochastic Modelling Solution
Version: 2.0.0
Authors@R: c(person("Filip", "Strnad",
                     role = "aut"),
             person("Simon Michael", "Papalexiou", 
                      role = c("aut")),
             person("Francesco", "Serinaldi", 
                      role = "aut"),
             person("Yannis", "Markonis", 
                      role = "aut"),
             person("Kevin", "Shook", 
                      role = c("ctb", "cre"),
                      email = "kevin.shook@usask.ca")
              )
Description: A single framework, unifying, extending, and improving a general-purpose modelling strategy, based on the assumption that any process can emerge by transforming a specific 'parent' Gaussian process Papalexiou (2018) <doi:10.1016/j.advwatres.2018.02.013>.
License: GPL-3
Depends: R (>= 3.5.0), ggplot2, data.table
Imports: 
    utils,
    methods, 
    stats,
    grDevices,
    nloptr,
    MBA,
    Matrix,
    mAr, 
    matrixcalc,
    mvtnorm, 
    plotly,
    cowplot,
    directlabels,
    animation,
    pracma
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
Roxygen: list(markdown = TRUE)
Suggests: 
    testthat,
    knitr,
    rmarkdown
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	-  geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The package would appear to fit under the geospatial data category as it generates synthetic geospatial data.
I see that the **charlatan** package on rOpenSci also generates fake data, although of completely different kinds - perhaps this is also a model for CoSMoS.

-   Who is the target audience and what are scientific applications of this package?  
The main users of CoSMoS are scientists or practitioners who want to generate synthetic environmental data. Synthetic data are useful for designing water-resource infrastructure, or for forcing physical models, as historical time series are often too short to be useful. Synthetic data also allow the creation of many realisations of data sets having the same properties, which allows the determination of the sensitivity of a model to its input forcings.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There are no other packages on CRAN or rOpenSci which do the same things as CoSMoS.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
NA. No human data is involved.
-  Any other questions or issues we should be aware of?:
The package is currently on CRAN: https://cran.r-project.org/package=CoSMoS

**Comment by geanders** [comment]
@KevinShook : Thank you so much for your query! We are discussing among the editorial board if this package falls in-scope and will get back to you.

**Comment by melvidoni** [comment]
Hello @KevinShook. Apologies for the delay, it was extremely long. We have decided that this package is in-scope giving the geospatial component, so we welcome a full submission. Please, feel free to submit whenever is possible for you.

**Comment by KevinShook** [comment]
Thanks very much!
I'll get in touch with the rest of the team and will submit ASAP.
Thanks again,
K

**Comment by maelle** [comment]
(closing as a decision had been reached)

**Comment by KevinShook** [comment]
We are working on a new version of the package, and hope to have it finished very shortly. I will submit it when it is completed
Sorry to have been so long
