### ISSUE TITLE
Presubmission inquiry: Is toolbox.E3D in scope?

### ISSUE THREAD

**Issue by jonaslenz** [ropensci/software-review#392]
Submitting Author: Jonas Lenz (@jonaslenz)  
Repository:  https://github.com/jonaslenz/toolbox.e3d

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: toolbox.e3d
Type: Package
Title: Toolbox for the soil erosion modeling tool EROSION-3D
Version: 0.0.0.90
Author: Jonas Lenz
Maintainer: Jonas Lenz <jonaspunktlenz@gmail.com>
Description: A R wrapper package for the soil erosion modelling tool EROSION-3D (available from Geognostics at http://www.geognostics.de/e3d_demo.html).
  Supports reproducable work with EROSION-3D via command line.
  Automates common workflows (iteration of calibration parameters).
URL: https://github.com/jonaslenz/toolbox.e3d
BugReports: https://github.com/jonaslenz/toolbox.e3d/issues
License: GPL-3
Depends: R (>= 3.3.4)
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
Imports: raster, ini
Suggests: 
    testthat (>= 2.1.0),
    knitr,
    rmarkdown
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

**scientific software wrappers**
The package allows users to reproducable run EROSION-3D from R, which is used up to now mainly through a GUI.

**workflow automation**
A key feature of the package is the automated determination of calibration parameters, which is currently done in a tedious manual  iteration process.

-   Who is the target audience and what are scientific applications of this package?  

Users of EROSION-3D.
Enchance reproducability, parameter determination for large datasets.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable.

-  Any other questions or issues we should be aware of?:

I want to ask if this package may be in scope. There are some potential issues and not all can be solved by me:  
1. EROSION-3D is not open-source. Software and licence is available from Geognostics at http://www.geognostics.de/e3d_demo.html. (Licence for review purpose will be available free of charge.)
 2. A documentation of the command line interface of EROSION-3D is not realy existent. Model settings used in the package were explored in a trial and error process and with support of developers of EROSION-3D.
 3. Tests and CI/CD are not implemented now.

**Comment by geanders** [comment]
@jonaslenz : Thanks very much for your submission as well as your clear explanation of some of the potential issues! 

A key question will likely be that the software being wrapped is not open-source, as you have pointed out.  I will discuss with the rest of the editorial team, and we may have some more questions and clarifications to ask of you.

In the mean time, you may also want to check the section on "scientific software wrappers" in the [rOpenSci Packages book](https://devguide.ropensci.org/policies.html#aims-and-scope), as this has a note about this open-source/not open-source question and points to a couple of examples of exceptions.

**Comment by jonaslenz** [comment]
@geanders : thank you very much for your response and the hint to the software wrapping section.

regarding this section, I wan't to give a hopefully helpful description of the wrapped software EROSION-3D:
 - it is a standalone modelling tool for soil erosion processes (including infiltration, flow routing, erosion processes)
 - other comparable tools do exist - kardyras et. al listed ~25 directly comparaple tools (https://doi.org/10.1080/17538947.2012.671380); some of these tools are/got recently open source (e.g. OpenLISEM)
 - each of these tools put their focus on specific aspects in erosion processes, so in my eyes there is added value in EROSION-3D as an additional option to describe the complex topic.
 - In the package are functions, which add significant added values over simple system() calls (for now mainly fitting of calibration parameters)

**Comment by maelle** [comment]
:wave: @jonaslenz sorry for the delay and thanks for your answer. Because of the existence of open-source alternatives to EROSION-3D, ultimately we decided that your package is out-of-scope. Thanks again for your submission and good luck with further development!
