### ISSUE TITLE
Submission: bleiglas

### ISSUE THREAD

**Issue by nevrome** [ropensci/software-review#393]
Submitting Author: Clemens Schmid (@nevrome)  
Repository:  https://github.com/nevrome/bleiglas
Version submitted: 0.0.1
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: bleiglas
Title: 3D Tessellation with Voro++
Description: 3D tessellation with voro++ and subsequent horizontal cutting of the resulting polygons for 2D plotting.
Version: 0.0.1
Date: 2020-07-22
Authors@R: 
    c(
      person(given = "Clemens",
        family = "Schmid",
        role = c("aut", "cre", "cph"),
        email = "clemens@nevrome.de",
        comment = c(ORCID = "0000-0003-3448-5715")),
      person(given = "Stephan",
        family = "Schiffels",
        role = "ctb",
        comment = c(ORCID = "0000-0002-1017-9150"))
    )
License: MIT + file LICENSE
Depends:
    R (>= 3.5.0)
Imports: 
    checkmate,
    data.table,
    Rcpp
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
SystemRequirements:
    voro++
LinkingTo: Rcpp
Suggests: 
    knitr,
    pbapply,
    rmarkdown,
    sf,
    testthat
VignetteBuilder: knitr
URL: https://github.com/nevrome/bleiglas
BugReports: https://github.com/nevrome/bleiglas/issues
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The package provides a general wrapper for the [voro++](http://math.lbl.gov/voro++/) command line tool and adds additional value by providing functions for 2D cutting of the 3D tessellation result. I consider the package to be especially valuable for spatiotemporal data visualization.

-   Who is the target audience and what are scientific applications of this package?  

Tessellation has many scientific applications in various fields, including material science, astronomy or geography. I developed the package for interpolation and visualization of archaeological and archaeogenetic spatiotemporal data.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I'm not aware of an other R package that either serves as an interface to voro++ or provides an own implementation of 3D tessellation.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

I don't see any issues here.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [x] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [x] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by geanders** [comment]
@nevrome : Thank you so much for this very interesting submission! The editorial team is discussing to make sure it falls within scope. We will be back in touch if we have follow-up questions as we discuss this.

**Comment by maelle** [comment]
:wave: @nevrome, sorry for the delay. We've discussed and ultimately decided it's out-of-scope:

* The category for scientific software wrappers isn't for packages with C++ inside the package;
* Your packages is not _specifically_ for geospatial applications (its more general scope is a strength for sure, but makes it out of scope).

Thanks again for your submission, we hope you find another venue for your package!

**Comment by nevrome** [comment]
What a pity! But thank you for considering it!
