### ISSUE TITLE
Presubmission inquiry: khroma (Colour Schemes for Scientific Data Visualization)

### ISSUE THREAD

**Issue by nfrerebeau** [ropensci/software-review#394]
Submitting Author: Nicolas Frerebeau (@nfrerebeau)  
Repository:  https://github.com/nfrerebeau/khroma

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: khroma
Title: Colour Schemes for Scientific Data Visualization
Version: 1.4.0
Authors@R: 
    c(person(given = "Nicolas",
             family = "Frerebeau",
             role = c("aut", "cre"),
             email = "nicolas.frerebeau@u-bordeaux-montaigne.fr",
             comment = c(ORCID = "https://orcid.org/0000-0001-5759-4944")),
      person(given = "Brice",
             family = "Lebrun",
             role = "ctb",
             email = "brice.lebrun@u-bordeaux-montaigne.fr",
             comment = c(ORCID = "https://orcid.org/0000-0001-7503-8685")),
      person(given = "Vincent",
             family = "Arel-Bundock",
             role = "ctb",
             email = "vincent.arel-bundock@umontreal.ca",
             comment = c(ORCID = "https://orcid.org/0000-0003-2042-7063")))
Maintainer: Nicolas Frerebeau
    <nicolas.frerebeau@u-bordeaux-montaigne.fr>
Description: An implementation of Paul Tol's colour schemes for
    use with 'graphics' or 'ggplot2'. These schemes are ready for each
    type of data (qualitative, diverging or sequential), with colours that
    are distinct for all people, including colour-blind readers. This
    package provides tools to simulate colour-blindness and to test how
    well the colours of any palette are identifiable. Several scientific
    thematic schemes (geologic timescale, land cover, FAO soils, etc.) are
    also implemented.
License: GPL-3
URL: https://khroma.archaeo.science,
    https://github.com/nfrerebeau/khroma,
    https://cran.r-project.org/package=khroma
BugReports: https://github.com/nfrerebeau/khroma/issues
Depends: 
    R (>= 3.3)
Imports:
    ggplot2,
    grDevices,
    grid,
    scales
Suggests:
    covr,
    crayon,
    fansi,
    knitr,
    rmarkdown,
    testthat,
    vdiffr
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
Collate: 
    'anomalize.R'
    'colour.R'
    'ggplot2.R'
    'khroma-package.R'
    'plot.R'
    'scale_colour_okabeito.R'
    'scale_colour_science.R'
    'scale_colour_tol.R'
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

My package does not really fit into the existing categories. Maybe it could go to "reproducibility tools", but an "accessibility tools" category would be more appropriate.

-   Who is the target audience and what are scientific applications of this package?  

`khroma` is intended for any scientist concerned about accessibility when communicating her results. This package allows the user to test her colour schemes before producing figures to ensure that they are understandable by all. Several colourblind safe schemes are implemented for direct use. `khroma` also provides dagnostic tools to check how well the colours of any custom scheme are identifiable, to simulate colour-blindness and to compute distance metric (colour difference within a colour scheme).

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
    - The [`ggthemes`](https://github.com/jrnold/ggthemes) package offers colour scales for `ggplot2`, but is limited to Paul Tol's discrete data schemes.
    - The  [`colorblindr`](https://github.com/clauswilke/colorblindr) package is dedicated to simulate colour-blindness in production-ready figures, while `khroma` allows to produce colourblind-safe figures. `khroma` should be used at the beginning of the figure production process, using the built-in color schemes or checking tools, while `colorblindr` should be used at the end.
    - The [`dichromat`](https://cran.r-project.org/package=dichromat) package provides color schemes suitable for people with anomalous red-green vision and a simulation tool to approximate the effect of dichromacy. The color schemes provided by the `khroma` and `dichromat` packages are complementary. `khroma` offers a similar simulation tool, but also offers additional diagnostic tools (visual verification and measurement of colour difference).

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-  Any other questions or issues we should be aware of?:

This package has already been released onto CRAN.

**Comment by geanders** [comment]
@nfrerebeau : Thank you so much for your submission, and we are discussing if this will be considered in-scope. In the meantime, could you please provide a bit more description of how this package differs from `colorblindr`, and also how it differs from the `dichromat` package?

**Comment by nfrerebeau** [comment]
@geanders : Sorry for this late response, I just edited my first comment to clarify the differences with the `colorblindr` and `dichromat` packages.

**Comment by maelle** [comment]
:wave: @nfrerebeau, thanks again for your submission and clarifications. However, we no longer have a visualization category for software review see https://devguide.ropensci.org/policies.html#aims-and-scope so this package would be out of scope. Thanks again for your asking, and we hope you find another venue for this important work for accessibility!
