### ISSUE TITLE
Submission : insee 

### ISSUE THREAD

**Issue by hadrilec** [ropensci/software-review#396]
Submitting Author: Hadrien Leclerc (@hadrilec)  
Repository:   https://github.com/hadrilec/insee
Version submitted:   0.9.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: insee
Type: Package
Title: Tools to Easily Download Data from INSEE BDM Database
Version: 0.9.0
Authors@R: person("Hadrien", "Leclerc", email = "leclerc.hadrien@gmail.com", role = c("aut", "cre"))
Author: Hadrien Leclerc [aut, cre]
Maintainer: Hadrien Leclerc <leclerc.hadrien@gmail.com>
Description: Using embedded sdmx queries, get the data of more than 140 000 insee series from bdm database. Have a look at the detailed sdmx web service page with the following link : <https://www.insee.fr/en/information/2868055>.
URL: https://hadrilec.github.io/insee/
Encoding: UTF-8
LazyData: true
License: GPL-2
VignetteBuilder: knitr
BugReports: https://github.com/hadrilec/insee/issues
Imports: 
  httr,
  xml2,
  tibble,
  dplyr,
  stringr,
  lubridate,
  tidyselect,
  rlang,
  crayon,
  openssl
Suggests:
    tidyverse,
    prettydoc,
    htmltools,
    kableExtra,
    knitr,
    rmarkdown,
    magrittr,
    testthat,
    covr,
    png
RoxygenNote: 7.1.1

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
The insee package gathers tools to easily download data and metadata from INSEE's main database.
More than 140 000 INSEE series are available for download from the package. It is then a gateway for reproducible reasearch on French data.

-   Who is the target audience and what are scientific applications of this package?  
Anyone interested in studying French data could be interested in this package. The use cases are numerous, ranging from simple data analysis and visualisation to econometrics.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Yes, rsdmx and eurostat are also helpful, but they do no provide metadata as much as insee package does. Overall, insee package is more user-friendly to handle INSEE's series as query functions are easy to use.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
I believe the package complies with ethical guidelines in the Internet Research: Ethical Guidelines 3.0 document.
It makes it easier for researchers to access and make use of INSEE's data that is already in the public domain.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by hadrilec** [comment]
I would like to pause this submission, as further work is needed on my side to settle some issues.
I may follow up on this submission later on.
Best regards,
Hadrien

**Comment by maelle** [comment]
:wave: @hadrilec, any update?

**Comment by hadrilec** [comment]
Hi @maelle, 
as the package is still maturing and might have to be modified in the coming months it is better to close this submission.
I may resubmit later on the package when the working process gets closer to the end but at this stage it is too soon.
Thanks a lot to ropensci team for taking care ! :)
Kind regards,

**Comment by maelle** [comment]
No problem, à bientôt !
