### ISSUE TITLE
Presubmission inquiry:  ROriginStamp - obtaining trusted timestamps from OriginStamp

### ISSUE THREAD

**Issue by rkrug** [ropensci/software-review#397]
Submitting Author: Rainer M Krug (@rkrug)  
Repository:   https://github.com/rkrug/ROriginStamp

---

```
Package: ROriginStamp
Type: Package
Title: Interface to OriginStamp API to Obtain Trusted Time Stamps
Version: 0.6.1
Authors@R: c(
    person( "Rainer M.", "Krug", , "Rainer@krugs.de", c("aut", "cre", "cph"))
    )
Description: Functions to get and download trusted timestamps and seed files from OriginStamp.
License: GPL-3 + file LICENSE
Imports:
        httr,
        jsonlite,
        xml2
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
Suggests: 
        testthat,
        covr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [X] data deposition
	- [X] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- The package is a wrapper around the [API](https://docs.originstamp.com/api/) of [OriginStamp](https://originstamp.com)
The packages makes it easy to obtain and verify trusted timestamps for a sha256 hash of any object.

-   anybody, who needs trusted timestamps to prove that a certain object was created at a certain time. Can be used for automation of analysis workflows.

-   Are there other R packages that accomplish the same thing? I am not aware of any.

**Comment by geanders** [comment]
@rkrug : Thanks very much for your inquiry! We are discussing if this would be in-scope and will get back in touch.

**Comment by rkrug** [comment]
Thanks a lot.

**Comment by maelle** [comment]
:wave: @rkrug sorry for the delay. We've discussed and assessed it would fit under "workflow automation".

Before submission, we'd encourage you to add more docs of the use of the package from the reproducibility point-of-view (in the README and elsewhere), and higher-level functions automatically that automatically hash and timestamp an R object would be useful (if they don't already exist and we missed them).

**Comment by rkrug** [comment]
Thanks a lot. 

I have now time to look at it... Will try to submit it within the next month.
