### ISSUE TITLE
Presubmission inquiry: PRDA

### ISSUE THREAD

**Issue by ClaudioZandonella** [ropensci/software-review#400]
Submitting Author: Claudio Zandonella Callegher (@ClaudioZandonella)  
Repository: https://github.com/ClaudioZandonella/PRDA

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: PRDA
Title: Conduct a Prospective or Retrospective Design Analysis
Version: 1.0.0.9000
Authors@R: c(
    person("Claudio", "Zandonella Callegher", role = c("aut", "cre"),
           email = "claudiozandonella@gmail.com",
           comment = c(ORCID = "0000-0001-7721-6318")),
    person("Massimiliano", "Pastore", role = c("aut"),
           email = "massimiliano.pastore@unipd.it",
           comment = c(ORCID = "0000-0002-7922-6365")),
    person("Angela", "Andreella", role = c("aut"),
           email = "a.andreella8@gmail.com",
           comment = c(ORCID = "0000-0002-1141-3041")),
    person("Anna", "Vesely", role = c("aut"),
           email = "anna.vesely92@gmail.com",
           comment = c(ORCID = "0000-0001-6696-2390")),
    person("Enrico", "Toffalini", role = c("aut"),
           email = "enrico.toffalini@yahoo.it",
           comment = c(ORCID = "0000-0002-1404-5133")),
    person("Giulia", "Bertoldo", role = c("aut"),
           email = "giuliabertoldo94@gmail.com",
           comment = c(ORCID = "0000-0002-6960-3980")),
    person("Gianmarco", "Altoè", role = c("aut"),
           email = "gianmarco.altoe@unipd.it",
           comment = c(ORCID = "0000-0003-1154-9528")))
Description: An implementation of the "Design Analysis" proposed by 
    Gelman and Carlin (2014). It combines the evaluation of Power-Analysis 
    with other inferential-risks as Type-M error (e.g. Magnitude) and Type-S
    error (e.g. Sign). See also Altoè et al. (2020) and Bertoldo et al. (2020).
Depends: 
    R (>= 3.5.0)
Suggests:
    covr,
    devtools,
    ggplot2,
    knitr,
    rmarkdown,
    roxygen2,
    testthat,
    tidyverse
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
VignetteBuilder: knitr
LinkingTo: 
    Rcpp, RcppArmadillo
Imports:
    MASS,
    Rcpp
URL: https://claudiozandonella.github.io/PRDA/, https://github.com/ClaudioZandonella/PRDA
BugReports: https://github.com/ClaudioZandonella/PRDA/issues
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of: 
The pakage allows conducting a Design Analysis to evaluate power levels together with estimates uncertainty (i.e., Type M error and Type S error) under hypothetical replications of a study. This is useful in the planning stage of a study to define the required sample size, or to evaluate the inferential risks associated with a study that has been already conducted.

-   Who is the target audience and what are scientific applications of this package?  
Researchers that want to preregister their studies and need to conduct a power analysis, or researcher that want to evaluate inferential risks related to their studies when interpreting the results. In particular, researchers in Psychology or Social Sciences.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Another recent R package, `retrodesign` (https://github.com/csetraynor/retrodesign), allows conducting retrospective design analysis considering the estimate of the unstandardized effect size (i.e., regression coefficient or mean difference) and standard error of the estimate. `PRDA` package, instead, considers standardized effect size (i.e., Pearson correlation coefficient or Cohen’s d) and study sample size. These are more commonly used in research fields such as Psychology or Social Science, and therefore are implemented in PRDA to facilitate researchers’ reasoning about design analysis.  PRDA, additionally, offers the possibility to conduct a prospective design analysis and to account for the uncertainty about the hypothetical value of effect size. In fact, the hypothetical effect size can be defined as a single value according to previous results in the literature or experts indications, or by specifying a distribution of plausible values.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
No data privacy is involved.

-  Any other questions or issues we should be aware of?:
I could not find a proper category for the package. I would suggest something as "preregistration tools" or more general "statistical tools". Following recent concern about replicability crisis in many scientific fields (e.g., psychology and social sciences), this package aims to increase researchers' awareness about inferential risks and the importance of the design phase of the studies. The package documentation is available at https://claudiozandonella.github.io/PRDA/

**Comment by ClaudioZandonella** [comment]
Is there something wrong in my presubmission inquiry?

**Comment by maelle** [comment]
Sorry, we're discussing and will update this thread shortly. Thanks for your presubmission!

**Comment by maelle** [comment]
:wave: @ClaudioZandonella thanks again for your submission! We've however decided it is out-of-scope as it is too statistical... which means it might be in-scope for ["rOpenSci Statistical Software Peer-Review"](https://ropensci.org/stat-software-review/) to be launched in the first half of 2021, so you might try and submit your package to it then. :slightly_smiling_face:

**Comment by ClaudioZandonella** [comment]
Hi @maelle, thank you for taking the time to review my presubmission. I understand your decision. I want to thank you and the entire rOpenSci community as your documentation and guidelines were really useful and helped me a lot in developing a better package. I really appreciate your work!

**Comment by maelle** [comment]
Thanks you for saying this :heart_eyes:  and sorry for the delay answering!
