### ISSUE TITLE
dmtools

### ISSUE THREAD

**Issue by chachabooms** [ropensci/software-review#402]
Submitting Author: Konstantin Ryabov (@chachabooms)  
Repository:https://github.com/chachabooms/dmtools   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: dmtools
Title: Tools for Validation the Dataset
Version: 0.2.5
Authors@R: 
    person(given = "Konstantin",
           family = "Ryabov",
           role = c("aut", "cre"),
           email = "chachabooms@gmail.com")
Description: For checking the dataset from EDC(Electronic Data Capture) in clinical trials.
             'dmtools' can check laboratory, dates and rename the dataset.
             Laboratory - does the investigator correctly estimate the laboratory analyzes?
             Dates - do all dates correspond to the protocol's timeline?
             If the clinical trial has different lab reference ranges, 'dmtools' also can help.
Depends: R (>= 3.6)
Imports:
  magrittr (>= 1.5),
  dplyr (>= 1.0.0),
  readxl (>= 1.3.1),
  purrr (>= 0.3.3),
  lubridate (>= 1.7.4),
  httr (>= 1.4.1),
  tidyr (>= 1.1.0),
  tibble (>= 3.0.1)
License: MIT + file LICENSE
URL: https://github.com/chachabooms/dmtools
BugReports: https://github.com/chachabooms/dmtools/issues
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
Suggests: 
    testthat,
    knitr,
    rmarkdown
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The dmtools can help the data manager to check the dataset, for example, 30 subjects involve in a clinical trial. Сlinical blood tests for every subject should be three times, so the data manager has 30 * 3 = 90 clinical blood tests in a clinical trial. But that's not all. Every clinical blood test has usually 15 parameters. As a result, the data manager should check 90 * 15 = 1350 parameters. And this is not the limit of the target to check.

-   Who is the target audience and what are scientific applications of this package? 
The clinical data manager is the target audience. The main application is to check the dataset.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? 
No, I don't know the same package.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
The dmtools don't use the surname or name of a subject, only id subject.

-  Any other questions or issues we should be aware of?:

**Comment by melvidoni** [comment]
Hello @chachabooms . We were discussing your submission with the editors, but we were wondering if you could address how your package is different from [assetr](https://github.com/ropensci/assertr) and [validate](https://github.com/data-cleaning/validate). We are under the impression this package is similar, but less flexible.

**Comment by chachabooms** [comment]
My package only checks data received from EDC. The main difference from a regular dataset is that a dataset from EDC has recurring events for each visit (Screening, Visit 1, Visit 2). Each recurring event has a fixed structure, for example, the result of laboratory analysis (**lab**) and its assessment: normal/abnormal(**lab_ind**). And this structure will be repeated for each visit. That is, the minimum dataset is general columns: id subject (**id**), gender subject (**sex**), age subject (**age**), and where two columns are repeated 3 times (**lab**_screening, **lab_ind**_screening, **lab**_visit1, **lab_ind**_visit1, **lab**_visit2, **lab_ind**_visit2, **lab**_visit3, **lab_ind**_visit3). I have to check the interaction of these columns (**id**, **age**, **sex**, **lab**, **lab_ind**) for each visit: (**id**, **age**, **sex**, **lab**_screening / visit1 / visit2 / visit3, **lab_ind**_screening / visit1 / visit2 / visit3).
For example,
https://en.wikipedia.org/wiki/Reference_ranges_for_blood_tests
Aspartate transaminase - ast, laboratory test(lab above), also can be alt, glu(glucose) and etc.
laboratory reference range - _it's only example and only for ast!_
AGELOW | AGEHIGH | SEX | LBTEST | LBORRES | LBNDIND | LBORNRLO | LBORNRHI
-- | -- | -- | -- | -- | -- | -- | --
18|45|male|Aspartate transaminase|ast|ast_ind|0|40|
18|45|female|Aspartate transaminase|ast|ast_ind|0|45
46|70|female\|male|Aspartate transaminase|ast|ast_ind|0|50

|id|age|sex|ast_screening|ast_ind_screening|ast_v1|ast_ind_v1|ast_v2|ast_ind_v2|ast_v3|ast_ind_v3|
|--|----|----|--------------|--------------------|-------|-----------|-------|-----------|-------|-----------|
|01|20|male|30|normal|45|**normal** _should be abnormal, because, for male, age 18-45 normal range of ast is 0-40 in reference_ |50|abnormal|30|normal|
|02|30|female|45|**abnormal** _should be normal, because, for female, age 18-45 normal range of ast is 0-45 in reference_|45|normal|50|abnormal|60|**normal** _should be abnormal, because, for female, age 18-45 normal range of ast is 0-45 in reference_|
|03|65|female|50|normal|45|normal|49|**abnormal**  _should be normal, because, for female or male, age 46-70 normal range of ast is 0-50 in reference_|60|abnormal|

**Comment by melvidoni** [comment]
Hello @chachabooms.

On my previous questions, the Editors had requested a comparison, but you didn't provide it. Please look [here](https://docs.ropensci.org/rtweet/#package-functionality) and [here](https://github.com/ropensci/software-review/issues/199#issuecomment-375358362) for nice comparisons.

However, from what we can see, the package works with generic excel tables, without any very specific format requiring special handling. This also isn't a workflow automation package, in the sense that we define linking together systems such as CI or Make-like processes. Though there is a custom validation for the data you work with, it doesn't seem to provide a better/very different approach to what it is available.

As a result, we have deemed this package out-of-scope. I wish you good luck on finding a more suitable venue!

**Comment by chachabooms** [comment]
@melvidoni Ok, thank you.
