### ISSUE TITLE
yotover: An Advanced Guide to Trade Policy Analysis

### ISSUE THREAD

**Issue by pachamaltese** [ropensci/software-review#403]
Submitting Author: Mauricio Vargas Sepúlveda (@pachamaltese)  
Repository: https://github.com/pachamaltese/yotover   
Version submitted: 0.1
Editor: TBD  
Reviewer 1: Noam Ross? (this is heavily inspired after citesdb)  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: yotover
Title: An Advanced Guide to Trade Policy Analysis
Version: 0.1
Authors@R: c( 
        person(given = "Mauricio",
               family = "Vargas",
               role = c("aut", "cre"),
               email = "mvargas@dcc.uchile.cl",
               comment = c(ORCID = "0000-0003-1017-7574")),
        person(given = "Alexey",
               family = "Kravchenko",
               role = c("ths"),
               email = "kravchenkoa@un.org"),
        person(family = "The United Nations",
               role = c("dtc", "cph", "fnd")
        )
    )
Description: On-disk embedded database with SQL versions of the original 
    datasets from the book An Advanced Guide to Trade Policy Analysis by Yotov, 
    et. al (2016)and functions to report regressions with clustered robust
    standard errors.
URL: https://pacha.dev/yotover/
BugReports: https://github.com/pachamaltese/yotover/issues/
License: CC BY 4.0
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1.9000
Imports:
    magrittr,
    tibble,
    ggplot2,
    dbplyr,
    dplyr,
    tidyr,
    purrr,
    cli,
    crayon,
    multiwayvcov,
    lmtest,
    broom,
    Matrix,
    msm,
    DBI,
    duckdb,
    R.utils,
    rappdirs,
    httr,
    scales,
    munsell,
    pander,
    gtable,
    colorspace,
    rstudioapi
Suggests:
    devtools,
    usethis,
    testthat,
    covr
Depends: 
    R (>= 3.5)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

This work aims at making the reproduction of the original results more accessible throughout the distribution of both open source software and open formats data. It creates an on-disk SQL database instead of the original stata files and provides function that ease fitting generalized linear models with fixed effects and clustered robust standard errors.

-   Who is the target audience and what are scientific applications of this package?  

The audience is economists and people who work with international trade. The scientific application is that we organized all the data and functions to reproduce each result from An Advanced Guide to Trade Policy Analysis (2016)

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Not that I know.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses. *the vignette is a full ebook found at https://pacha.dev/yotover*
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [x] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
   - [x] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
   - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by melvidoni** [comment]
Hello @pachamaltese, thank you for the submission. After a discussion with the Editors, we believe this submission to be out of scope for rOpenSci. We suggest you look into the [Journal of Open Source Education](https://jose.theoj.org/about), as it can be a great resource for that. Therefore, I am closing the issue.
