### ISSUE TITLE
Presubmission inquiry: forestecology - Methods and Data for Forest Ecology Model Assessment and Selection

### ISSUE THREAD

**Issue by rudeboybert** [ropensci/software-review#404]
Submitting Author: Albert Y. Kim (@rudeboybert)  
Repository:   https://github.com/rudeboybert/forestecology

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: forestecology
Type: Package
Title: Methods and Data for Forest Ecology Model Assessment and Selection
Version: 0.1.0.9002
Authors@R: c(
    person("Albert Y.", "Kim", email = "albert.ys.kim@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-7824-306X")),
    person("David", "Allen", email = "dallen@middlebury.edu", role = "aut", comment = c(ORCID = "0000-0002-0712-9603"))
    )
Maintainer: Albert Y. Kim <albert.ys.kim@gmail.com>
Description: Code for assessing and selecting models for predicting the growth 
    of trees. In particular spatial cross-validation for estimation of 
    out-of-sample prediction error, permutation methods for testing the 
    signficance of competitor species, and Bayesian linear regression.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
URL: https://github.com/rudeboybert/forestecology
BugReports: https://github.com/rudeboybert/forestecology/issues
Depends:
    R (>= 3.2.4)
Suggests: 
    testthat
Imports: 
    magrittr,
    ggplot2,
    stringr,
    dplyr,
    tidyr,
    proxy,
    purrr,
    ggridges,
    mvnfast,
    sf,
    sfheaders,
    tibble
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

We envision this package being used in a generalized framework for assessing and selecting geospatial models of interspecies competition between trees. This includes define notions of spatial autocorrelation, "buffer" regions, spatial cross-validation. Hence the ✔️ for **geospatial data**. Furthermore, we implement this using the `sf` package framework to ensure maximal compatibility with `tidyverse` tools. Hence  the ✔️ for **data munging**.

However, in your [Other scope considerations](https://devguide.ropensci.org/policies.html#other-scope-considerations) section you state: "Here are some types of packages we are unlikely to accept: Packages that wrap or implement statistical or machine learning methods." Our package is currently implemented to work with a specific Bayesian linear regression statistical model from [Allen and Kim 2020](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0229930). So we weren't sure if this precludes us from submission. (We do however envision our package eventually being flexible enough to work with any type of model/method, but that is not currently the case.)

-   Who is the target audience and what are scientific applications of this package?  

Forest ecologists and anyone interested in models for spatial competition between groups.  

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I *believe* that certain elements of how our package accesses forestry data are duplicated by the [`fgeo`](https://forestgeo.github.io/fgeo/) package. However that package focuses on using such data for abundance, demography, and species-habitats associations analysis. Our package centers on using such data for analysis of geospatial competition models. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

**Comment by melvidoni** [comment]
Hello @rudeboybert. Thanks for submitting. We will discuss this with the Editors, and I'll get back to you.

**Comment by melvidoni** [comment]
Hello @rudeboybert. We have been discussing, and **forestecology** seems like a methods package with some example data sets included and some workflow support.  The geospatial side of the scope is really more that we include geospatial data handling as a special case. Therefore, we think that the type of data munging provided here is too generic for us.

I'm positive that you'll find an appropriate venue for this package. Thank you for taking the time to pre-submit.

**Comment by rudeboybert** [comment]
Thank you for both considering my pre-submission nonetheless, and for the prompt responses.
