### ISSUE TITLE
tanggle

### ISSUE THREAD

**Issue by KlausVigo** [ropensci/software-review#408]
Submitting Author: Klaus Schliep (@KlausVigo)  
Repository:   https://github.com/KlausVigo/tanggle
Version submitted:  0.99.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: tanggle
Type: Package
Title: Visualization of Phylogenetic Networks
Version: 0.99.0
Authors@R: c(person("Klaus", "Schliep", email="klaus.schliep@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2941-0161")),
             person("Marta", "Vidal-Garcia", role="aut"), 
             person("Claudia", "Solis-Lemus", role="aut"), 
             person("Leann", "Biancani", role="aut"), 
             person("Eren", "Ada", role="aut"), 
             person("L. Francisco", "Henao Diaz", role="aut"), 
             person("Guangchuang", "Yu", role = c("ctb")))
Description: 'ggplot2' like system to plot phylogentic networks from 'ape' and 'phangorn'.
Depends:
    R (>= 3.6),
    ggplot2 (>= 2.2.0),
    ggtree
Imports: 
    magrittr,
    ape (>= 5.0), 
    phangorn (>= 2.5),
    utils
Suggests:
    tinytest,
    BiocStyle,
    ggimage,
    knitr,
    rmarkdown
VignetteBuilder: knitr    
biocViews: Software, Visualization
License: AGPL (>= 3)
URL: https://github.com/KlausVigo/tanggle
BugReports: https://github.com/KlausVigo/tanggle/issues
RoxygenNote: 7.0.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [X] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
Our R package allows to plot both implicit and explicit networks and it builds on the flexibility of ggplot2 and ggtree to manipulate colors and other plot characteristics. tanggle works towards reproducible, script-based publication figures, as opposed to figures created with design software such as Adobe Illustrator. 

-   Who is the target audience and what are scientific applications of this package?  
Researchers doing phylogenetic analyses.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
R packages ape and phangorn can plot phylogenetic networks, however using the base R plots and not the ggplot2, ggtree syntax. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [X] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

We are still discussing internally whether Bioconductor or CRAN is more appropriate and hope the review will help with the decision.   
- [x] Do you intend for this package to go on CRAN?  
- [x] Do you intend for this package to go on Bioconductor?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [x] The package is novel and will be of interest to the broad readership of the journal. 
- [x] The manuscript describing the package is no longer than 3000 words.
- [x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by melvidoni** [comment]
Hello @KlausVigo, thank you for your submission. However, packages centred on visualisation are out of scope for rOpenSci. After a discussion with the editors, we found that the automation portion is not strong enough for us to consider this package. Thank you for submitting, and I'm confident you'll find a suitable venue for publication.
