### ISSUE TITLE
censo2017: Base de Datos de Facil Acceso del Censo 2017 de Chile (2017 Chilean Census Easy Access Database)

### ISSUE THREAD

**Issue by pachamaltese** [ropensci/software-review#410]
Submitting Author: M Vargas (@pachamaltese)  
Repository:   https://github.com/pachamaltese/censo2017

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Provee un acceso conveniente a mas de 17 millones de registros de la base de datos del Censo 2017. Los datos fueron importados desde el DVD oficial del INE usando el Convertidor REDATAM creado por Pablo De Grande y ademas se proporcionan los mapas que acompanian a estos datos. Esta paquete esta documentado intencionalmente en castellano asciificado para que funcione sin problema en diferentes plataformas. (Provides convenient access to more than 17 million records from the Chilean Census 2017 database. The datasets were imported from the official DVD provided by the Chilean National Bureau of Statistics by using the REDATAM converter created by Pablo De Grande and in addition it includes the maps accompanying these datasets.)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [x] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package is an adaptation of citesdb. It provides the original census data and cartographies (Chile) in SQLite format, alongside functions to import the data, process the maps, etc. What is important about this package is  that it has local impact and solves the problem that the original format (REDATAM) puts Mac and Linux users under the need of using a virtual machine or another laptop since it can only be read with a specific Windows-only program, and the REDATAM converter is also Windows-only. The original data comes in DVD format, so I had to obtain one to read it.

-   Who is the target audience and what are scientific applications of this package?  

Economists, sociologists and professionals who need demographic data. The audience is focused in Chile.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Not at the moment.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes.

-  Any other questions or issues we should be aware of?:

* It is heavily inspired in citesdb.
* I hope other users from Latin America can adapt this for their countries.
* It contains anonymous people's data, which can only be identified at zone level (zone = sub-district area), as the original data protects the statistical secret

**Comment by melvidoni** [comment]
Hello @pachamaltese! Thanks for submitting. The package is definitely on-topic, but I have a question for you. 

rOpenSci has been considering supporting Spanish peer-reviews. Considering the nature of this package, and that the code and `roxygen` (also your Readme file!) appear to be in Spanish... would you prefer to conduct the review in English or Spanish? If the latter (Spanish) you would help us pilot the review.

Please, let me know your decision so that we know how to proceed.

**Comment by pachamaltese** [comment]
Hi

I am not really sure. I think English eases the review. Google translate
does its magic.

I can translate the documentation to english.

Best,

**Comment by melvidoni** [comment]
Hello @pachamaltese! Apologies for the delay. As discussed in Slack, the Issue Template for a Spanish Submission is ready, so we will be piloting or Spanish reviews with your package. I will be closing this issue now, so please open it again, fully in Spanish.

**Comment by FvD** [comment]
*Nota: revisión esta en proceso - aun no lo he finalizado*
*Nota 2: este machote de revisión `review-es.md` esta disponible como pull requeste en el `dev-guide`*

## Revisión de un paquete

*Por favor trata de marcar tantas casillas como te es posible y elabora tus argumentos en comentarios abajo de cada uno. Tu revisión no se necesita listar a estos temas, tal como se describe en la guia para revisores (Reviewer Guide)*

**Por favor describe cualquier relación de trabajo que tienes/has tenido con los autores del paquete)**

- [ ] Como revisor confirmo que no tengo [conflictos de interés](https://devguide.ropensci.org/policies.html#coi) para poder hacer la revisión de este trabajo (si no estas seguro si tienes un conflicto por favor entra en contacto con tu editor _antes_ de arrancar con la revisión.

#### Documentación

El paquete incluye todos los siguiente tipos de documentación:

- [ ] **Una declaración de necesidades** que claramente describe las necesidades que el software esta diseñado a resolver y el public meta que busca atender en el archivo README
- [ ] **Instrucciones de instalación** tanto para la versión en desarrollo incluyendo cualquier dependencia no-estándar en el archivo README
- [ ] **Vignette(s)** demostrando la funcionalidad principal que ademas corren localmente
- [ ] **Documentación de las funciones** en la ayuda de R para todas la funciones exportadas
- [ ] **Ejemplos** para todas las funciones exportadas que corren localmente
- [ ] **Directrices comunitarias** incluyendo una guia de contribución en el archivo README o el archivo CONTRIBUTING y un archivo DESCRIPTION que incluye `URL`, `BugReports` and `Maintainer` (todas en inglés por concenvión y para que puedan ser autogeneradas con `Authors@R`).

>##### For packages co-submitting to JOSS
>
>- [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.theoj.org/about#submission_requirements)
>
>The package contains a `paper.md` matching [JOSS's requirements](https://joss.theoj.org/about#paper_structure) with:
>
>- [ ] **A short summary** describing the high-level functionality of the software
>- [ ] **Authors:**  A list of authors with their affiliations
>- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Funcionalidad

- [ ] **Instalación:** La instalación se completa con éxito tal como fue documentado.
- [ ] **Funcionalidad:** Todo afirmación de funcionalidad del software se confirma como existente.
- [ ] **Desempeño:** Toda afirmación de desempeño del software se confirma como alcanzada.
- [ ] **Pruebas automáticas:** Hay pruebas unitarias que cubren las funciones esenciales dentro del paquete con un rango razonable de entradas y condiciones. Todas las pruebas corren en la maquina local.
- [ ] **Directrices de empaque**: El paquete cumple con las directrices de empaque de rOpenSci.

Estimación de horas dedicadas a la revisión:

- [ ] Si la o las persona(s) autora(s) lo considera(n) apropiado, yo estoy de acuerdo con que me reconozcan como revisor del paquete (el rol "rev') en la el archivo DESCRIPTION del paquete.

---

### Comentarios de la revisión
