### ISSUE TITLE
submission of the {batata} package

### ISSUE THREAD

**Issue by feddelegrand7** [ropensci/software-review#423]
Submitting Author: Mohamed El Fodil Ihaddaden (@feddelegrand7)  
Repository: https://github.com/feddelegrand7/batata   
Version submitted:  0.2.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: batata
Type: Package
Title: Managing Packages Removal and Installation
Version: 0.2.0
Author: Mohamed El Fodil Ihaddaden
Maintainer: Mohamed El Fodil Ihaddaden <ihaddaden.fodeil@gmail.com>
Description: 
    Allows the user to manage easily R packages removal and installation. It offers many functions to display installed packages according to
    specific dates and removes them if needed. The user is always prompted when running the removal functions in order to confirm
    the required action. It also provides functions that will install 'Github' starred R packages whether available on 'CRAN' or not. 
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Imports: 
    fs,
    utils,
    glue,
    lubridate,
    jsonlite,
    remotes,
    purrr
RoxygenNote: 7.1.1
URL: https://github.com/feddelegrand7/batata
BugReports: https://github.com/feddelegrand7/batata/issues
Suggests: 
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
```
## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

1. data retrieval
{batata} has a many functions that help retrieve Github starred repositories. For example: 

`install_starred_cran("feddelegrand7", n = 10)` will retrieve the R Github repositories that I've starred and install them if available on CRAN. 

2. workflow automation 
{batata} provides functions that help automating the packages' removal process. For example, let's say I have been in a conference today and I had to install a bunch of packages to follow along, at the end of the day, I can decide to remove the packages (if I don't need to them and if I want to keep my packages' folder clean) using the `rm_today_packages( )` function. There are other helper functions that allow the the user to specify a date for packages removal. 

- 3 field and lab reproducibility tools
The package can be used as a reproducibility tool. For example, imagine that I've a paper that rely on many packages to run, I create a new Github repo that will starr the above mentioned packages so that I can run later (whenever I need those package) `install_starred_cran('new_github_repo')`, I can also use `install_starred_github( )` if the packages are not available on CRAN. These functions can also be used for teaching purposes. Instead of providing user a list of packages to install, one can just starr the necessary packages and use one of the functions provided by {batata} 

-   Who is the target audience and what are scientific applications of this package?  

The packages aims to reach a broad audience of R users as it is useful for general purposes (packages management) and it's relatively easy to use. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There is the {renv} package which is a bit different a more powerful in the sense that {renv} tries to ensure a thoroudh reproducibility. {batata} on the other hand tries to help R users remove superfluous packages and install interesting ones.  

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you intend for this package to go on Bioconductor?  

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by melvidoni** [comment]
Hello @feddelegrand7. Thanks for the submission, however, the Associate Editors feel like this package is out of scope: the data retrieval and workflow automation is not quite strong, as this does not help with CI/build systems. It comes across as a utility tool rather than what we look for in rOpenSci.

We wish you the best in finding an appropriate venue for your package!

**Comment by feddelegrand7** [comment]
Hi @melvidoni I understand, I will try to improve it. Thanks anyway.
