### ISSUE TITLE
Request for presubmission of the package concstats

### ISSUE THREAD

**Issue by schneiderpy** [ropensci/software-review#424]
Submitting Author: Andreas Schneider (@schneiderpy)  
Repository: github/schneiderpy/concstats

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: concstats
Title: Market Structure and Concentration Measures
Version: 0.1.0
Authors@R: 
    person(given = "Andreas",
           family = "Schneider",
           role = c("aut", "cre"),
           email = "schneiderconsultingpy@gmail.com",
           comment = c(ORCID = "https://orcid.org/0000-0001-5630-1097"))
Description: Based on individual market shares of all participants in a market or space, the function calculates a set of
    different structural and concentration measures frequently - and not so frequently - used in research and in practice.
    The resulting vector in table format should help practitioners make more informed decisions.
License: MIT + file LICENSE
Imports: knitr
Suggests: 
    tidyverse,
    rmarkdown
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Depends: 
    R (>= 2.10)
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x? ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
It automates the workflow of calculating market structure, concentration, and competition measures, which - of course - can be calculated one by one. The package calculates 12 measures in one step.

-   Who is the target audience and what are scientific applications of this package?  
The target audience might be researchers and pratitioners in the field (Market competetion regulation, Consumer defense). The related research article (which inspired me to write my first package (and a lot of other things which come along with that) is under review (in german language), hower, there is a draft in english available.
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Yes, but just one or two measures, e.g. Herfindahl-Hirschman Index
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-  Any other questions or issues we should be aware of?:
Not so far.

**Comment by melvidoni** [comment]
Hello @schneiderpy and thank you for the presubmission. We will discuss this with the editors, and get back to you as soon as possible.

**Comment by melvidoni** [comment]
Hello @schneiderpy. We have discussed with the editors, and the package is too statistical for the regular review process. _However_, we are piloting a stats peer-review, and you are encouraged to submit there. Please, [checks this link](https://ropensci.org/stat-software-review/) to get familiar with all the information about rOpenSci's Stats Peer Review.

**Comment by mpadge** [comment]
@schneiderpy If you are interested in submitting to our stats peer-review pilot programme, please feel free to contact myself and/or @noamross via email.
