### ISSUE TITLE
Presubmission: allodb: An R package for biomass estimation at extratropical forest plots

### ISSUE THREAD

**Issue by gonzalezeb** [ropensci/software-review#427]
Submitting Author: Erika Gonzalez-Akre (@gonzalezeb) 
Other Authors: Camille Piponiot (@cpiponiot), Mauro Lepore (@maurolepore), Kristina Teixeira (@teixeirak) 
Repository: https://github.com/forestgeo/allodb  

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: allodb
Title: An R Package For Tree Biomass Estimation At Extratropical Forest Plots
Version: 1.0.0.9000
Authors@R: 
    c(person(given = "Erika",
             family = "Gonzalez-Akre",
             role = c("aut", "cre"),
             email = "GonzalezEB@si.edu"),
      person(given = "Camille",
             family = "Piponiot",
             role = "aut",
             email = "camille.piponiot@gmail.com"),
      person(given = "Mauro",
             family = "Lepore",
             role = "aut",
             email = "maurolepore@gmail.com"),
      person(given = "Kristina",
             family = "Anderson-Teixeira",
             role = "aut",
             email = "TeixeiraK@si.edu"))
Description: Tool to standardize and simplify the tree biomass
    estimation process across globally distributed extratropical forests.
License: GPL-3
URL: https://github.com/forestgeo/allodb
BugReports: https://github.com/forestgeo/allodb/issues
Depends: 
    R (>= 3.5.0)
Imports: 
    data.table (>= 1.12.8),
    dplyr (>= 0.8.0.1),
    kgc (>= 1.0.0.2),
    readr (>= 1.3.1),
    ggplot2 (>= 3.3.2),
    raster,
    utils
Suggests: 
    covr (>= 3.2.1),
    knitr (>= 1.21),
    purrr,
    spelling,
    testthat (>= 2.0.1),
    rmarkdown
VignetteBuilder: 
    knitr
Encoding: UTF-8
Language: en-US
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
_allodb_ integrates compiled data and built-in functions to calculate tree above-ground biomass (AGB). AGB is a critical value used by forest ecologists to estimate the amount of carbon sequester and resealed by forests. _allodb_ aims to standardize and simplify steps used to calculate AGB once the user provides tree size data.  
By exploring rOpenSci package categories definitions (Chapter 5) I believe _allodb_ falls in the "field and laboratory reproducibility tools" category as our package intents to improve and standardize the calculation of a widely used forest metric, however this category is not listed above but described [here](https://devguide.ropensci.org/policies.html#package-categories). 
I should mention that MEE recommended us to rOpenSci after re-inviting our manuscript describing _allodb_ functionalities for submission.

-   Who is the target audience and what are scientific applications of this package?  
Our package is designed to be used by forest ecologists with basic or advanced knowledge of R. This scientific application is intended to be used by individuals interested in calculating forest metrics such as AGB in extratropical forest (subtropical, temperate, and boreal forests).  

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The BIOMASS package is designed to estimate biomass in tropical forest. The main difference between _allodb_ and BIOMASS is the set of equations used to estimate AGB. There is an existing calibrated equation used globally for tropical environments but not for areas outside the tropics. Our goal is to provide a set of curated equations and the ability to add new and additional equations in order to have a more reliable value of AGB outside the tropics. We do not duplicate any functionality of the BIOMASS package and only agree on the ecological scope.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
N/A

-  Any other questions or issues we should be aware of?:
None

**Comment by melvidoni** [comment]
Hello. Thank you for your submission. We have discussed your submission with the Associate Editors, and consider the package to be in-scope. Please, proceed to make a full submission.

Please notice that, due to having an Editor in your author list, we will also need to find a Guest Editor to handle your package. This may extend the review process.

**Comment by gonzalezeb** [comment]
Thanks @melvidoni, we will make some final checks and will submit shortly.
