### ISSUE TITLE
broken links to https://ropensci.org/onboarding/

### ISSUE THREAD

**Issue by cmaimone** [ropensci/software-review#440]
There are links to https://ropensci.org/onboarding/, which is currently returning a 404 error, on the following pages (possibly others)

- https://github.com/ropensci/software-review#readme  (this repo)
- https://github.com/ropensci/roweb3/blob/83d6ffa4734b30d6112990c5e5316123f74b0503/themes/ropensci/layouts/partials/whole-page-fragments/review.html (main website repo)

**Comment by maelle** [comment]
Oops, thank you for catching this, now fixed!
