### ISSUE TITLE
rdbhapi package: An R package to simplify API access to data on higher education in Norway

### ISSUE THREAD

**Issue by makinin** [ropensci/software-review#442]
Submitting Author: Marija Ninic (@makinin)  
Other Package Authors: Sigve Hofland Berge (@sigve-berge-hofland)
Repository:  https://github.com/makinin/rdbhapi

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rdbhapi
Title: Interface to 'DBH-API' 
Version: 2.1.0
Authors@R: c(person(given = "Marija",family = "Ninic",role = c("cre", "aut"),email = "marija.ninic@nsd.no", comment=c(ORCID ="0000-0001-8484-5817")),person(given=c("Sigve", "Hofland"), family="Berge", role = "aut"))
Description: Downloads 'DBH-API'<https://dbh.nsd.uib.no/tjenester.action> data as dataframes. These data are in machine-readable format and provides information about education, finances, research and publications. 
License: MIT + file LICENSE
Encoding: UTF-8
RoxygenNote: 7.1.1
Imports: 
    httr,
    readr,
    rjson,
    jsonlite,
    rlang,
    stats
Suggests:
    spelling, 
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
Language: en-US
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ x ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  
This package falls under the category of data retrieval because it simplify API access from to data on higher education in Norway, as provided by NSD - Norwegian Centre for Research Data. This package read data from API into R dataframe.

-   Who is the target audience and what are scientific applications of this package?  
   The target audience are students and researchers who needs data about education in their work.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
 No there is not. 
  
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-  Any other questions or issues we should be aware of?:
- No

**Comment by maelle** [comment]
:wave: @makinin thanks for your submission, but you forgot to fill out parts of the template / to answer some of the questions. :slightly_smiling_face:

**Comment by maelle** [comment]
:wave: @makinin could you please update the submission to answer all applicable questions in the template?

**Comment by makinin** [comment]
How to add Technical checks, Publication options, MEE Options, Code of conduct, can not find them in template

**Comment by maelle** [comment]
@makinin I mean that in the body of the template there are questions like "Explain how and why the package falls under these categories (briefly, 1-2 sentences)." and no answer yet. :slightly_smiling_face: 

Also, were you intending to fill a pre-submission inquiry rather than a submission? The template is https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/B-submit-a-presubmission-inquiry.md (and also has some of the questions you haven't answered yet).

**Comment by makinin** [comment]
It is fixed now , thank you for help :)

**Comment by noamross** [comment]
@makinin Thanks for making those changes and submitting a pre-submission inquirty. This does fit into our package Aims and Scope. When you want to start the review process, please fill out the full submission template here: https://github.com/ropensci/software-review/issues/new?assignees=&labels=&template=A-submit-software-for-review.md
