### ISSUE TITLE
Pre-submission trackdown: Collaborative writing and editing of R Markdown (or Sweave) Documents in Google Drive

### ISSUE THREAD

**Issue by ClaudioZandonella** [ropensci/software-review#449]
Submitting Author: Claudio (@ClaudioZandonella)  
Other Package Authors:  Emily (@ekothe) Filippo  (@filippogambarota) Janosch (@januz) Mathew (@Lingtax)
Repository:  https://github.com/ekothe/trackdown/
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: trackdown
Title: Collaborative Writing and Editing of R Markdown (or Sweave) Documents in Google Drive
Version: 0.1.0
Authors@R:
    c(person(given = "Emily",
             family = "Kothe",
             role = c("aut", "cre"),
             email = "claudiozandonella@gmail.com",
             comment = c(ORCID = "0000-0003-1210-0554")),
      person(given = "Claudio",
             family = "Zandonella Callegher",
             role = c("aut"),
             email = "claudiozandonella@gmail.com",
             comment = c(ORCID = "0000-0001-7721-6318")),
      person(given = "Filippo",
             family = "Gambarota",
             role = c("aut"),
             email = "claudiozandonella@gmail.com",
             comment = c(ORCID = "0000-0002-6666-1747")),
      person(given = "Janosch",
             family = "Linkersdörfer",
             role = "aut",
             email = "jlinkersdoerfer@ucsd.edu",
             comment = c(ORCID = "0000-0002-1577-1233")),
      person(given = "Mathew",
             family = "Ling",
             role = "aut",
             email = "m.ling@deakin.edu.au",
             comment = c(ORCID = "0000-0002-0940-2538")))
Description: Collaborative writing and editing of R Markdown (or Sweave) documents. The local .Rmd (or .Rnw) is uploaded as a plain-text file to Google Drive. By taking advantage of the easily readable Markdown (or LaTeX) syntax and the well-known online interface offered by Google Docs, collaborators can easily contribute to the writing and editing process. After integrating all authors’ contributions, the final document can be downloaded and rendered locally.
Depends: R (>= 3.5)
License: GPL-3
Encoding: UTF-8
Imports:
    cli,
    googledrive,
    rmarkdown
Suggests: 
    covr,
    devtools,
    gargle,
    knitr,
    pagedown,
    sodium,
    testthat (>= 3.0.0),
    vcr
Config/testthat/edition: 3
RoxygenNote: 7.1.1
VignetteBuilder: knitr
URL: https://github.com/ekothe/trackdown/, https://ekothe.github.io/trackdown/
BugReports: https://github.com/ekothe/trackdown/issues
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [X] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package enables an R Markdown-Google Docs workflow for collaborative writing and editing of R Markdown (or Sweave) documents. But I am not sure about the proper category.

-   Who is the target audience and what are scientific applications of this package?  

Researchers and students using R Markdown (or Sweave) to create documents in a literate programming framework.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Other R packages aiming to improve the user experience during the collaborative editing of R Markdown (or Sweave) documents are available. [`redoc`](https://github.com/noamross/redoc) offers a two-way R Markdown-Microsoft Word workflow; [`reviewer`](https://github.com/ropensci-archive/reviewer) allows to evaluate differences between two rmarkdown files and add notes using the Hypothes.is service; [`trackmd`](https://github.com/ropensci-archive/trackmd) is an RStudio add-in for tracking changes in Markdown format; [`latexdiffr`](https://CRAN.R-project.org/package=latexdiffr) creates a diff of two R Markdown, .Rnw or LaTeX files. However, these packages implement a less efficient writing/editing workflow and all of them, but `latexdiffr`, are no longer under active development. 

The `trackdown` workflow has the advantage of being based on Google Docs which offers users a familiar, intuitive, and free web-based interface that allows multiple users to simultaneously write/edit the same document. Moreover, `trackdown` allows anyone to contribute to the writing/editing of the document. No programming experience is required, users can just focus on writing/editing the narrative text in Google Docs.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-  Any other questions or issues we should be aware of?:

I have opened a pre-submission issue to evaluate if rOpenSci is interested in the aim of the package. Two similar packages (`reviewer` and `trackmd`) were supported by rOpensci but they are now archived.

I hope `trackdown` will have better luck. The `trackdown` workflow is very simple and efficient as it is based on the familiar Google Docs web-based interface. The package will facilitate collaborative writing and editing an activity common to all researchers.

In the package documentation (<https://ekothe.github.io/trackdown/>) all the package features are presented.

**Comment by noamross** [comment]
Thank you for submitting this inquiry, @ClaudioZandonella.  I'm afraid this package is out of scope.  In our [policies](https://devguide.ropensci.org/policies.html#package-categories) we note that R Markdown extensions and similar literate programming support are not included.

The main reason we do not include this topic, as well as other tools such as highly general data-manipulation workflows, is that we find that general workflows are highly subjective and it is difficult to make useful "best-in-class" designations that we try to for packages that are specific to scientific data types and sources.

Nonetheless, this is a very promising workflow and one I'll follow closely (as author of `redoc` this is a topic of great interest to me).  We encourage you to submit to [JOSS](https://joss.theoj.org/) or elsewhere.

`trackmd` and `reviewer` were experimental packages developed by teams at our uncoference / hackathons, which often include topics far beyond our peer-review scope.
