### ISSUE TITLE
Pre-submission request: World Magnetic Model calculator

### ISSUE THREAD

**Issue by wfrierson** [ropensci/software-review#461]
Submitting Author: Will Frierson (@wfrierson)  
Repository:  https://github.com/wfrierson/wmm
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: wmm
Type: Package
Title: World Magnetic Model
Version: 1.1.1
Authors@R: person("Will", "Frierson", email = "will.frierson@gmail.com",
  role = c("aut", "cre"))
Maintainer: Will Frierson <will.frierson@gmail.com>
Description: Calculate magnetic field at a given location and time according to 
  the World Magnetic Model (WMM). Both the main field and secular variation 
  components are returned. This functionality is useful for physicists and 
  geophysicists who need orthogonal components from WMM. Currently, this package 
  supports annualized time inputs between 2000 and 2025. If desired, users can
  specify which WMM version to use, e.g., the original WMM2015 release or the 
  recent out-of-cycle WMM2015 release. Methods used to implement WMM, including 
  the Gauss coefficients for each release, are described in the following 
  publications: Chulliat et al (2020) <doi:10.25923/ytk1-yx35>,
  Chulliat et al (2019) <doi:10.25921/xhr3-0t19>, 
  Chulliat et al (2015) <doi:10.7289/V5TB14V7>, 
  Maus et al (2010) <https://www.ngdc.noaa.gov/geomag/WMM/data/WMMReports/WMM2010_Report.pdf>, 
  McLean et al (2004) <https://www.ngdc.noaa.gov/geomag/WMM/data/WMMReports/TRWMM_2005.pdf>,
  and Macmillian et al (2000) <https://www.ngdc.noaa.gov/geomag/WMM/data/WMMReports/wmm2000.pdf>.
License: MIT + file LICENSE
Encoding: UTF-8
Depends: 
  R (>= 2.10)
RoxygenNote: 6.1.1
Suggests:
  testthat (>= 2.0.1),
  data.table (>= 1.12.2)
URL: https://github.com/wfrierson/wmm
BugReports: https://github.com/wfrierson/wmm/issues
Language: en-US
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [X] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The `wmm` R package is a tool for scientists who need magnetic field vector value predictions at certain locations and times (consistent with the official test values from NOAA) . The package has 1 exported function, `GetMagneticFieldWMM`, which provides magnetic field components described on the repo's [README](https://github.com/wfrierson/wmm/blob/main/README.md). This seems consistent with "scientific software wrappers."

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
n/a

-   Who is the target audience and what are scientific applications of this package?  
Any role that requires magnetic field vector value predictions in the scope of the coefficients provided by NOAA, e.g., geophysicists and navigators.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
I have not found any R packages that offer the same output given a location and time. The most similar package is [oce](https://cran.r-project.org/web/packages/oce/index.html), which offers the function `magneticField` that returns a "list containing declination, inclination, and intensity." In comparison, the `wmm` package returns the orthogonal vector components of the main magnetic field, secular variation field, and other magnetic field elements (see the repo's [README](https://github.com/wfrierson/wmm/blob/main/README.md) for details).

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
N/A, since the only data derived from measurements are Gauss coefficients provided by NOAA.

-  Any other questions or issues we should be aware of?:
__Notes__: 
1) I am not affiliated with NOAA and this was a personal project. The package uses Gauss coefficients provided by NOAA. I have shown them the package and they recently added it to their [3rd party software page](https://www.ngdc.noaa.gov/geomag/WMM/thirdpartycontributions.shtml) for R.
2) The unit tests for the package compare calculated with official magnetic field values for certain locations and times. The package uses travis-ci to perform automatic unit testing with each commit.

**Comment by noamross** [comment]
Thank you for the pre-submission, @wfrierson! We consider this in-scope and welcome a full submission. We consider it a data retrieval and munging package as much as anything as it eases access to this data and performs common data processing steps specific to the data on top of that.

**Comment by mpadge** [comment]
@wfrierson A re-submission will now automatically respond with standard package checks. Documentation for these is forthcoming, so until then could you please install our [`pgkcheck` package](https://github.com/ropensci-review-tools/pkgcheck) and run the following prior to full submission:
``` r
x <- pkgcheck("<path>/<to>/wmm")
summary(x)
```
That will clarify any remaining issues which you can address prior to submission. Thanks!

**Comment by wfrierson** [comment]
Thanks, @mpadge. I'm trying to install `pkgcheck`. However, it just won't install.

I'm using Windows (R 3.6.1). When first trying to install `pkgcheck`, I compile from source using Rtools v3.5.0.4. It errors out saying `pkgstats` and `ssr` need to be installed (with extremely long compilation output). I try compiling from source `pkgstats` and get the output below. I'm stumped. Do I really need to run `pkgcheck` before submitting, especially if I can't install `pkgcheck`?

* installing *source* package 'pkgstats' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
mkdir -p ../inst
"C:/PROGRA~1/R/R-36~1.1/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R"
cp -rf ../windows/universal-ctags-5.9.20210530.0/bin ../inst/
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Users/willf/Documents/R/win-library/3.6/cpp11/include"        -O2 -Wall  -mtune=generic -c code-symbols.cpp -o code-symbols.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Users/willf/Documents/R/win-library/3.6/cpp11/include"        -O2 -Wall  -mtune=generic -c cpp11.cpp -o cpp11.o
cpp11.cpp:9:1: error: reference to 'writable' is ambiguous
 writable::integers cpp_loc(const strings flist, const strings cmt_open, const strings cmt_close, const strings cmt);
 ^
In file included from cpp11.cpp:5:0:
C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11/declarations.hpp:9:39: note: candidates are: namespace writable = cpp11::cpp11::writable;
 namespace writable = ::cpp11::writable;
                                       ^
In file included from C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11/list.hpp:10:0,
                 from C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11/data_frame.hpp:12,
                 from C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11.hpp:7,
                 from C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11/declarations.hpp:8,
                 from cpp11.cpp:5:
C:/Users/willf/Documents/R/win-library/3.6/cpp11/include/cpp11/r_vector.hpp:44:20: note:                 namespace cpp11::writable { }
 namespace writable {
                    ^
cpp11.cpp:9:1: error: 'writable' does not name a type
 writable::integers cpp_loc(const strings flist, const strings cmt_open, const strings cmt_close, const strings cmt);
 ^
cpp11.cpp: In function 'SEXPREC* _pkgstats_cpp_loc(SEXP, SEXP, SEXP, SEXP)':
cpp11.cpp:12:250: error: 'cpp_loc' was not declared in this scope
     return cpp11::as_sexp(cpp_loc(cpp11::as_cpp<cpp11::decay_t<const strings>>(flist), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt_open), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt_close), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt)));
                                                                                                                                                                                                                                                          ^
make: *** [C:/PROGRA~1/R/R-36~1.1/etc/i386/Makeconf:215: cpp11.o] Error 1
ERROR: compilation failed for package 'pkgstats'
* removing 'C:/Users/willf/Documents/R/win-library/3.6/pkgstats'
Warning in install.packages :
  installation of package ‘pkgstats’ had non-zero exit status

**Comment by mpadge** [comment]
@wfrierson You don't strictly need to run `pkgcheck`, but it is certainly very helpful to ensure your package has met all pre-submission criteria. If you can't get it to work locally, you could try using [the `pkgcheck-action` GitHub action](https://github.com/ropensci-review-tools/pkgcheck-action) to run the checks on GitHub. Alternatively, you just have to ensure you read the [Dev Guide](https://devguide.ropensci.org) very carefully and address every single requirement described there.
