### ISSUE TITLE
Presubmission inquiry: {cffr} Generate Citation File Format ('cff') Metadata for R Packages

### ISSUE THREAD

**Issue by dieghernan** [ropensci/software-review#462]
Submitting Author: Diego Hernangómez  (@dieghernan)  
Repository:   https://github.com/dieghernan/cffr 
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```

Package: cffr
Title: Generate Citation File Format ('cff') Metadata for R Packages
Version: 0.0.0.9000
Authors@R: 
    person(given = "Diego",
           family = "Hernangómez",
           role = c("aut", "cre"),
           email = "diego.hernangomezherrero@gmail.com",
           comment = c(ORCID = "0000-0001-8457-4658"))
Description: The Citation File Format version 1.2.0 (Druskat, S. et al.
    (2021) <doi:10.5281/zenodo.5171937>) is a human and machine readable
    file format which provides citation metadata for software.  This
    package provides core utilities to generate and validate this
    metadata.
License: GPL (>= 3)
URL: https://dieghernan.github.io/cffr/,
    https://github.com/dieghernan/cffr
BugReports: https://github.com/dieghernan/cffr/issues
Depends: 
    R (>= 3.6.0)
Imports: 
    crayon (>= 1.4.1),
    desc (>= 1.3.0),
    jsonlite (>= 1.7.2),
    jsonvalidate (>= 1.1.0),
    yaml (>= 2.2.1)
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
X-schema.org-keywords: attribution, citation, credit, citation-files, cff,
    metadata

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [x] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package extract metadata from DESCRIPTION and CITATION and generates a [CITATION.cff file](https://citation-file-format.github.io/).

CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets)

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not aplicable.

-   Who is the target audience and what are scientific applications of this package?  

Any R package developer. A CITATION.cff file provides clarity when citating R packages. [GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files), [Zenodo](https://twitter.com/ZENODO_ORG/status/1420357001490706442) and [Zotero](https://twitter.com/zotero/status/1420515377390530560) supports this format.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

[{citation}](https://cran.r-project.org/package=citation) package seems to provide similar support. {cffr} adds an extensive extraction of CITATION metadata. It seems that supports CFF v1.1.0 whereas {cffr} supports v1.2.0 (latest release).

I haven’t explore it in deep, but {cffr} provides a set of functions for managing the full lifecycle of the creation of the file: generation, customisation, generation and validation against the official schema with {jsonvalidate}.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable 

-  Any other questions or issues we should be aware of?:

The package is functional right now, with minor tweaks to capture corner cases. It has been tested againts >800 packages on my local installation, see <https://github.com/dieghernan/cffr/tree/main/tests/testthat/test_local_installation>.

**Comment by noamross** [comment]
Hi @dieghernan. Yes, this package falls neatly into our scope for citation support and we'd be glad for a full submission.  I think it would be useful to use the review process to work out recommended workflows for using CITATION, CITATION.cff and codemeta.json, as we will probably update our own guidance and requirements for citation based on that! Glad to see you've already started the conversation in `codemeta`.

**Comment by dieghernan** [comment]
Thanks @noamross, I will submit it in the next few days
