### ISSUE TITLE
Presubmission inquiry: BCEA

### ISSUE THREAD

**Issue by n8thangreen** [ropensci/software-review#466]
Submitting Author Name: Nathan Green
Submitting Author Github Handle: @n8thangreen
Other Package Authors Github handles: (comma separated, delete if none) @giabaio
Repository:  https://github.com/cran/BCEA
Submission type: Pre-submission

---

```
Package: BCEA
Type: Package
Title: Bayesian Cost Effectiveness Analysis
Version: 2.3-1.1
Date: 2019-08-05
Author: Gianluca Baio, Andrea Berardi, Anna Heath
Maintainer: Gianluca Baio <gianluca@stats.ucl.ac.uk>
Suggests: R2jags, R2OpenBUGS, ggplot2, grid, INLA, splancs, mgcv, ldr,
        shiny, shinythemes, knitr, rmarkdown, plotly
Imports: MASS, dplyr, rlang
Additional_repositories: https://inla.r-inla-download.org/R/stable/
Description: Produces an economic evaluation of a Bayesian model in the form of MCMC simulations. Given suitable variables of cost and effectiveness / utility for two or more interventions, This package computes the most cost-effective alternative and produces graphical summaries and probabilistic sensitivity analysis.
License: GPL (>= 2)
URL: http://www.statistica.it/gianluca/BCEA,
        http://www.statistica.it/gianluca
Depends: R (>= 2.10)
NeedsCompilation: no
RoxygenNote: 6.1.1
Encoding: UTF-8
Packaged: 2019-08-26 07:41:20 UTC; hornik
Repository: CRAN
Date/Publication: 2019-08-26 07:55:24 UTC
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [x] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The package takes the results of an MCMC (or MC) analysis done externally and creates cost-effectiveness summary statistics and EDA plots.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
Not yet.

-   Who is the target audience and what are scientific applications of this package?  
Anyone who is performing health economic modelling, including academics in epidemiology, statistics and medicine, and consultancies, pharmaceuticals, governments and regulatory bodies such as NICE.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Some packages are designed to do the modelling and present their own results e.g. heemod or hesim. The only other package on CRAN known to the authors is dampack. BCEA has more functionality and is designed to be simpler to use, requiring a single call to the `bcea()` function to generate all of the statistics.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
NA

-  Any other questions or issues we should be aware of?:
We are close to a new release of BCEA to CRAN having largely refactored the code base and a code review would be ideal timing.

**Comment by noamross** [comment]
Thanks for this inquiry, @n8thangreen! I believe this package is in-scope and we would be pleased to accept a full submission.  Since it processes MCMC results and returns summaries and visualizations, EDA is an appropriate category, but standards from Bayesian and Monte Carlo Routines likely apply, as well.  Please submit checking off both categories and use `srr` to annotate code with standards from both.  Some MCMC-related standards will likely apply directly, some will be a matter of documenting and providing access to underlying routines or objects from the package wrapped (e.g., convergence tests), and other may not apply at all and you can use`@srrstatsNA` to mark these.
