### ISSUE TITLE
MazamaSpatialUtils: Harmonized spatial datasets and spatial search functions

### ISSUE THREAD

**Issue by jonathancallahan** [ropensci/software-review#472]
Submitting Author: Jonathan Callahan (@jonathancallahan)  
Repository:  https://github.com/MazamaScience/MazamaSpatialUtils
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: MazamaSpatialUtils
Version: 0.7.6
Title: Spatial Data Download and Utility Functions
Authors@R: c(
    person("Jonathan", "Callahan", email="jonathan.s.callahan@gmail.com", role=c("aut","cre")), 
    person("Rachel", "Carroll", email="rachelcarroll4@gmail.com", role=c("aut")),
    person("Eli", "Grosman", email="eligrosman1@gmail.com", role=c("aut")),
    person("Roger", "Andre", email="randre@gmail.com", role=c("aut")),
    person("Tom", "Bergamaschi", email="tbergama@gmail.com", role=c("aut")),
    person("Tina", "Chen", email="chen.tinaa@gmail.com", role=c("aut")),
    person("Ruby", "Fore", email="ruby.a.fore@gmail.com", role=c("aut")),
    person("Will", "Leahy", email="procterw@gmail.com", role=c("aut")),
    person("Helen", "Miller", email="helen@ohana.org", role=c("aut")),
    person("Henry", "Nguyen", email="oh.henry.nguyen@gmail.com", role=c("aut")),
    person("Robin", "Winstanley", email="robin@winstan.net", role=c("aut")),
    person("Alice", "Yang", email="wenhuy@uw.edu", role=c("aut"))
    )
Author: Jonathan Callahan [aut, cre],
    Rachel Carroll [aut],
    Eli Grosman [aut],
    Roger Andre [aut],
    Tom Bergamaschi [aut],
    Tina Chen [aut],
    Ruby Fore [aut],
    Will Leahy [aut],
    Helen Miller [aut],
    Henry Nguyen [aut],
    Robin Winstanley [aut],
    Alice Yang [aut]
Maintainer: Jonathan Callahan <jonathan.s.callahan@gmail.com>
Description: A suite of conversion functions to create internally standardized
    spatial polygons data frames. Utility functions use these data sets to
    return values such as country, state, time zone, watershed, etc. associated
    with a set of longitude/latitude pairs. (They also make cool maps.)
License: GPL-2
URL: https://github.com/MazamaScience/MazamaSpatialUtils
BugReports: https://github.com/MazamaScience/MazamaSpatialUtils/issues
Repository: CRAN
Depends:
    R (>= 3.5.0),
    sp
Imports:
    cleangeo,
    countrycode,
    dplyr,
    magrittr,
    MazamaCoreUtils (>= 0.4.5),
    rgdal,
    rgeos,
    rlang,
    rmapshaper,
    stringr
Suggests:
    knitr,
    maps,
    markdown,
    readr,
    rmarkdown,
    testthat
Encoding: UTF-8
VignetteBuilder: knitr
LazyData: true
RoxygenNote: 7.1.1
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The **MazamaSpatialUtils** package includes functions to download, harmonize and simplify a variety of spatial datasets useful for analysis with environmental monitoring data. A database of pre-generated .rda versions of spatial datasets can be easily installed and then used for quick spatial lookups of things like state, county, timezone, _etc._

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?  

The target audience includes analysts working with environmental data who just want access to some spatial metadata for their target locations without having to embrace a full suite of GIS tools.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I am not aware of any other packages that allow end users to work with spatial data this easily.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Does not apply.

-  Any other questions or issues we should be aware of?:

The `DESCRIPTION` file has a long list people with `role=c("aut")`. Yet I only included myself as the "author" in this form. I did so because the other people listed in the `DESCRIPTION` file no longer have any relationship to this package.
They were all undergrads or recent grads working as interns or short term employees at MazamaScience -- an open source consulting firm I ran for 10 years but closed down this summer. I always included anyone who worked on a package as an "author" but am not sure what rOpenSci wants. Many of them no longer have GitHub accounts.

**Comment by ldecicco-USGS** [comment]
Thanks again for submitting @jonathancallahan . The editors have had a chance to take a look at this package, and while it is cool and certainly useful within the lego set of air quality monitoring tools, we think this "brick" is too narrow scope for rOpenSci.

You might want to consider Noam's comment about refactoring from `sp` to `sf`. The maintainer of the `sp` package directly recommends using `sf`.

**Comment by jonathancallahan** [comment]
Thanks again for taking the time to review. I agree that refactoring to use **sf** is in order and I hope to get to that over the winter.

Best wishes for health and success in 2022!
