### ISSUE TITLE
ccviR: NatureServe Climate Change Vulnerability Index

### ISSUE THREAD

**Issue by see24** [ropensci/software-review#488]
Submitting Author 
**Reviewers:** 
**Editor:** 
Language Code 
Submitting Author: Sarah Endicott (@see24)  
Repository:  
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ccviR
Title: NatureServe CCVI in R
Version: 0.0.0.9003
Authors@R: person(given = "Sarah",
  family = "Endicott",
  role = c("aut", "cre"),
  email = "sarah.endicott@canada.ca",
  comment = c(ORCID = "0000-0001-9644-5343"))
Description: The [NatureServe Climate change vulnerability index (CCVI)](https://www.natureserve.org/conservation-tools/climate-change-vulnerability-index) 
is currently distributed as an excel spreadsheet and is used to calculate a relative climate 
change vulnerability index for any North American species. Some of the factors in the spreadsheet require
geospatial computations and the user is expected to do these externally in GIS software. 
The ccviR package performs the spatial analysis and index calculation in R making it 
reproducible and also provides a Shiny app interface for calculating the index. 
License: TBD
Encoding: UTF-8
LazyData: true
Imports: 
    dplyr,
    raster,
    sf,
    purrr,
    tidyr,
    shiny,
    stringr,
    units,
    exactextractr,
    shinyFiles,
    shinyjs,
    tmap,
    ggplot2,
    shinycssloaders,
    R.utils,
    fs,
    plotly,
    shinyFeedback,
    rgdal,
    methods,
    stats,
    utils
Suggests: 
    gdalUtils,
    testthat (>= 2.1.0),
    knitr,
    rmarkdown,
    shinytest
RoxygenNote: 7.1.1
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
If you consider an excel spreadsheet programmed with an algorithm to be software then this package makes the NatureServe CCVI software accessible from R. I am not sure if this counts or if the "software" being wrapped here is broad enough for ROpenSci
- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?  
The NatureServe CCVI has been used in many situations eg ([Young, 2015](https://www.natureserve.org/sites/default/files/young_et_al._2014_wsb_on_line_early_version.pdf)) this package would make it possible to do it in R and the Shiny app makes it more user friendly to biologists or conservation planners without the technical skills to do the GIS analysis. The package also makes it more reproducible since there are no calculations being transferred from GIS to the spreadsheet by hand.
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Not that I know of. 
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
NA
-  Any other questions or issues we should be aware of?:
The package is still in development so the repo is currently private because of my employers approach to OSS but it will be open source once completed. The developer of the NatureServe CCVI has approved of the package informally but we haven't gone further than that yet. It is not quite ready for submission but I was curious if it would fit the criteria.

**Comment by ldecicco-USGS** [comment]
I think there is some potential for this to be considered "scientific software wrappers". Until the repo can be made public however, I don't think we can make any further considerations.

**Comment by see24** [comment]
@ldecicco-USGS  The repo is public now so I would be interested to know if you have further thoughts or suggestions. 

Here is the missing info:
author1: Sarah Endicott
repourl: https://github.com/LandSciTech/ccviR
language: EN

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package
