### ISSUE TITLE
Using GitHub Actions continuous integration to automate quality assurance and control of data on ecological dynamics

### ISSUE THREAD

**Issue by rudeboybert** [ropensci/software-review#491]
Submitting Author 
**Reviewers:** 
**Editor:** 
Language Code 
Submitting Author: Albert Y. Kim (@rudeboybert)  
Other Package Authors: Valentine Herrmann (@ValentineHerr), Kristina Anderson-Texeira (@teixeirak)
Repository:  https://github.com/SCBI-ForestGEO/SCBImortality
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

Note this `DESCRIPTION` file doesn't relate to an R package per se, rather one that is needed to run [GitHub Actions for the R language](https://github.com/r-lib/actions)

```
Package: SCBImortality
Title: Smithsonian Conservation Biology Institute (SCBI) ForestGEO Tree Mortality Data
Description: This is the private data portal for the SCBI ForestGEO plot tree mortality raw data. 
A script generates the cleaned data, which is then pushed to the public repo.
License: MIT + file LICENSE
Version: 0.1.0
Authors@R: c(
    person(given = c("Albert", "Y."), family = "Kim", role = c("cre", "aut"), email = "albert.ys.kim@gmail.com", comment = c(ORCID = "0000-0001-7824-306X")),
    person(given = c("Valentine"), family = "Herrmann", role = c("aut"), email = "HerrmannV@si.edu", comment = c(ORCID = "0000-0002-4519-481X")),
    person(given = "Kristina", family = "Anderson-Teixeira", role = "aut")
)
Depends: R (>= 4.0.0)
Imports: 
    testthat,
    here,
    readxl,
    rgdal,
    dplyr,
    readr,
    stringr,
    janitor,
    lubridate,
    patchwork,
    tidyr,
    ggplot2
URL: https://github.com/SCBI-ForestGEO/SCBImortality
BugReports: https://github.com/SCBI-ForestGEO/SCBImortality/issues
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

(Note I added and checked off _data validation and testing_ to the above list b/c it was present in your list of [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories)). My software is a framework to automate quality assurance (QA/QC) and control of data on ecological dynamics using GitHub Actions Continuous Integration, specifically this example driver GitHub Actions [.yml file](https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/.github/workflows/data-tests.yaml) and all derivative R scripts. 

The workflow of this software is visualized in the figure below (from a private WIP manuscript repo). It uses GitHub Actions for _workflow automation_ and Steps 2-4 ensure _data validation and testing_. **I'm wondering if such R software is appropriate for rOpenSci review. While not an R package, IMO the use-case of this continuous integration software and framework aligns with rOpenSci's [mission statement](https://ropensci.org/about/).** 

![data_pipeline](https://user-images.githubusercontent.com/4574203/143870194-ababaca2-b0e6-4756-984f-a6d2d65e7922.png)

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not applicable

-   Who is the target audience and what are scientific applications of this package?  

Field ecologists who are looking to both disseminate data via GitHub, but also automate (QA/QC). This QA/QC not only limits detectable errors from entering databases, it also (1) ensures reproducibility of the data collection pipeline and (2) acts a device for field personnel training feedback.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No, but the paper builds on the ideas of another similar framework [Developing an automated iterative near-term forecasting system for an ecological study](https://doi.org/10.1111/2041-210X.13104). However we drill down on data QA/QC testing as well as the field personnel training effects in our manuscript. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes

-  Any other questions or issues we should be aware of?:

**Comment by ldecicco-USGS** [comment]
I'm a huge fan of automated checks and using GitHub Actions. We do require submissions to be R packages however. 

On one hand, it might be a good idea for you to bundle all of your scripts into a package. You can still call the same "scripts", but it would be a function call. This would give you the chance to split up the scripts into smaller functions and document each step. It would also help people who might not be able to use GitHub Actions (my organization for example is require to use GitLab. While the GitLab "actions" are similar, they aren't identical). 

One package that has a similar feel is `tic`:
https://github.com/ropensci/tic
You might want to check out that package. You could even think about using `tic` as an Import to help users set up this workflow.

On the other hand, I suspect this workflow (even if turned into a package), will be too specific for an rOpenSci submission. One idea might be to write up a nice blog post on how you've set this up, what you've learned in the process, and how/why others might want to incorporate that knowledge in their QA processes. If you like that idea, you could chat with @stefaniebutland to find out what is the process for submitting an rOpenSci blogpost.

**Comment by rudeboybert** [comment]
Many thanks for your prompt response @ldecicco-USGS, and thanks for the pointer to `tic`. Please feel free to close this issue.

@stefaniebutland I am curious about the process for submitting an rOpenSci blogpost; could we communicate over email? albert.ys.kim@gmail.com
