### ISSUE TITLE
hudr: An interface for the Department of Housing and Urban Development APIs

### ISSUE THREAD

**Issue by etam4260** [ropensci/software-review#500]
Submitting Author Name: Emmet Tam
Submitting Author Github Handle: @etam4260
Repository:  https://github.com/etam4260/hudr
Version submitted: 0.0.0.9000
Submission type: Pre-submission
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en
---

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: hudr
Title: An R interface for accessing HUD (US Department of Housing and Urban Development) APIs
Version: 0.0.0.9000
Authors@R: 
    person("Emmet", "Tam", , "emmet_tam@yahoo.com", role = c("aut", "cre"))
Description: 
	An R interface for accessing HUD (US Department of Housing and Urban Development) API.
	The HUD has four main datasets, USPS Crosswalk, Fair Markets Rent,
	Income Limits, and the Comprehensive Housing Affordability Strategy.
	Interfaces with the HUD DRGR reporting system part which is part of HUD Exchange.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2.9000
URL: https://github.com/etam4260/hudr
BugReports: https://github.com/etam4260/hudr/issues
Suggests: 
    covr,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Imports:
    httr,
    stringr
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [X] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
It makes API requests from HUD. If you go https://www.huduser.gov/portal/pdrdatas_landing.html and click datasets it will show various datasets that this package is going to retrieve. However, currently I only have USPS Zip Code Crosswalk Files, Income Limits, Fair Markets Rent, and Comprehensive Housing Affordability Strategy. Hoping to extend these to the other datasets, but these are the only ones that HUD has an API tool for.
- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
N/A
-   Who is the target audience and what are scientific applications of this package?  
The target audience would mainly be student/faculty research scientists and professors who would like an easy way to access this data in R.
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There might exist some overlap with the datasets retrieved, depending on if other R API libraries for US departments/agencies also have this data. However, there isn't currently one specifically for gaining access to data from the Department of Housing and Urban Development.
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Currently looking more into https://devguide.ropensci.org/package-development-security-best-practices.html as my tool does need an API key to access data. It can be saved into the package environment and there is the ability to print the current key if the user would like so. However, I imagine there is a safer place to store it.
-  Any other questions or issues we should be aware of?:
No tests have been written yet but is linked with codecov. Currently failing R CMD Check workflow.

**Comment by mpadge** [comment]
@etam4260 Can you please edit the submission template and replace all of the required HTML variables. The header should be 12-13 lines long; your current one has removed most of these, and has only 3 lines. Please do the following:

1. Open a new issue just to obtain and copy the template - do not submit a new issue
2. Paste the entire header material back into the header of your opening issue here
3. Ensure all of the "<--symbol-->...<!---end-symbol>" bits are kept and values filled where appropriate.

Thanks!

**Comment by jooolia** [comment]
Dear @etam4260, thank you for your pre-submission. We consider this in-scope and welcome a full submission. We consider it a data retrieval package as it eases access to these data. Thanks and let us know if you have any further questions. 
Cheers, Julia

**Comment by etam4260** [comment]
Hi @joolia
Thanks for the confirmation. Going to work a little bit more on it before a full submission.  Looking forward to seeing what the peer review process is like.
Emmet
