### ISSUE TITLE
rpaleoclim

### ISSUE THREAD

**Issue by joeroe** [ropensci/software-review#503]
Submitting Author Name: Joe Roe
Submitting Author Github Handle: @joeroe
Repository:  https://github.com/joeroe/rpaleoclim
Version submitted: 0.9.0.9000
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rpaleoclim
Title: R Interface for the PaleoClim Paleoclimate Database
Version: 0.9.0.9000
Authors@R:
    person(given = "Joe",
           family = "Roe",
           role = c("aut", "cre"),
           email = "[joe@joeroe.io](mailto:joe@joeroe.io)")
Description: 
    PaleoClim <http://paleoclim.org> is a database of free, high resolution 
  paleoclimate surfaces covering the whole globe. It includes the standard
  bioclimatic variables commonly used in ecological modelling, downscaled from
  the HadCM3 general circulation model for key time periods, at up to 2.5 minute
  spatial resolution.
    This package provides a simple interface for downloading PaleoClim data in R,
  with support for spatial queries and caching.
License: MIT + file LICENSE
URL: https://github.com/joeroe/rpaleoclim
BugReports: https://github.com/joeroe/rpaleoclim/issues
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
Imports: 
    utils,
    rlang,
    fs,
    rgdal,
    raster,
    curl
Suggests: 
    covr,
    mockery,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

rpaleoclim retrieves data from [PaleoClim](http://www.paleoclim.org/), a set of high-resolution global paleoclimate surfaces.

-   Who is the target audience and what are scientific applications of this package?

As the PaleoClim authors put it, "easily accessible paleoclimate data are essential for environmental, evolutionary, and ecological studies". I would add to that studies of human ecology in the past, e.g. environmental archaeology. The package is simple but makes it easier to reproducibly use this data in R analyses.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are packages for retrieving *current* global climate data that are widely used, for example [WorldClim](https://worldclim.org/) is available via the `raster` package, but I'm not aware of any packages for accessing paleoclimate data, or PaleoClim specifically.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes. No human subjects or personal information is involved. I have endeavoured to 'politely' make requests to [SDMtoolbox](http://www.sdmtoolbox.org/)'s server (see https://github.com/joeroe/rpaleoclim/issues/6), which currently hosts the PaleoClim data, and the caching function reduces server load.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

pkgcheck results: https://github.com/joeroe/rpaleoclim/actions/runs/1813065454

Regarding documentation: functions are documented, but I have removed examples because this causes persistent problems with server timeouts when they are run on CI. This is frustrating because the file downloaded is not very big (16MB) and I have not been able to reproduce these problems with the SDMtoolbox server locally. It is not really feasible to write examples that do not download data or rely on files that are too large to be on CRAN. I realise this is not ideal; any advice on how to get around this problem would be much appreciated!

There is no vignette because the package has a very simple API (two functions) and I think this is adequately explained in the README.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [ ] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ ] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by joeroe** [comment]
Just to clarify, I have explained the two items marked with :heavy_multiplication_x: above.

**Comment by jooolia** [comment]
Dear @joeroe,
Will you pursue fixing the two point mentioned above? Thanks, Julia

**Comment by joeroe** [comment]
Sorry for the delay and thanks for the feedback @jooolia. I've added a vignette and examples for all functions, but I'm still struggling with the server errors that sometimes cause the package to fail R CMD check. I have a couple of things I still want to try to fix it; hopefully early next week.

**Comment by jooolia** [comment]
Ok thanks for the response @joeroe. Let us know when things are ready for another look. Cheers, Julia

**Comment by jooolia** [comment]
Hi @joeroe,
Do you have any updates on this? thanks, Julia

**Comment by joeroe** [comment]
Thank you for your patience @jooolia. I can't get around the server issues, so I have contacted the authors of the data to ask about mirroring it somewhere else. Would it be possible to keep this open just a little longer, while I wait for a response?

**Comment by jooolia** [comment]
Hi @joeroe,
Yes no problem. Thanks for the update.

**Comment by jooolia** [comment]
Hi @joeroe ,
Any new updates here? Thanks, Julia

**Comment by joeroe** [comment]
Still no response unfortunately. I've also recently learned of [pastclim](https://www.biorxiv.org/content/10.1101/2022.05.18.492456v1), which likely makes this package obsolete.

With that in mind I'll withdraw this submission – sorry for taking up your time unnecessarily.

**Comment by jooolia** [comment]
Thanks for the follow-up @joeroe.
