### ISSUE TITLE
Presubmission inquiry: DGVMTools

### ISSUE THREAD

**Issue by MagicForrest** [ropensci/software-review#504]
Submitting Author  Matthew Forrest (@MagicForrest)  
**Reviewers:** 
**Editor:** 
Language Code R
Submitting Author: Matthew Forrest (@MagicForrest)  
Other Package Authors:  Simon Scheiter (@sscheiter), Glenn Moncrieff (@GMoncrieff), Jörg Steinkamp (@joergsteinkamp)
Repository:  https://github.com/MagicForrest/DGVMTools
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: DGVMTools
Type: Package
Version: 1.0.0
Title: DGVM Processing, Analysis and Plotting Tools
Date: 2019-11-01
Authors@R: c(person("Matthew", "Forrest", role=c("aut", "cre"), email="matthew.forrest@senckenberg.de"),
             person("Simon", "Scheiter", role=c("aut"), email="simon.scheiter@senckenberg.de"),
             person("Joerg", "Steinkamp", role=c("aut"), email="joerg.steinkamp@senckenberg.de"),
             person("Glenn", "Moncrieff", role=c("aut"), email="glenn@saeon.ac.za"))
Author: Matthew Forrest [aut, cre], Simon Scheiter [aut], Joerg Steinkamp [aut], Glenn Moncrieff [aut]
Maintainer: Matthew Forrest <matthew.forrest@senckenberg.de>
Description: Package to read, process, benchmark, analyse and plot output produced by dynamic global vegetation
    models (DGVMs) and complimentary data.  Data in standard NetCDF format is supported and package also has bespoke
    functionality for three vegetation models with non-standard output (LPJ-GUESS, aDGVM and aDGVM2). 
Depends:
    R (>= 3.1.0),
    data.table (>= 1.11.8),
    ggplot2
Imports:
    methods,
    sp,
    raster,
    terra,
    compiler,
    maps,
    maptools,
    mapdata,
    RColorBrewer,
    reshape2,
    viridis,
    plyr,
    R.utils,
    units
Suggests:
    knitr,
    rmarkdown,
    ncdf4,
    rgeos,
    testthat,
    Cairo,
    ggpubr
License: GPL | file LICENSE
URL: https://www.bik-f.de
BugReports: https://github.com/MagicForrest/DGVMTools/issues
NeedsCompilation: no
RoxygenNote: 7.1.2
VignetteBuilder: knitr
Encoding: UTF-8
Collate:
    'classes.R'
    'Format-GUESS.R'
    'Format-NetCDF.R'
    'Format-aDGVM.R'
    'Format-aDGVM2.R'
    'Standard-Quantities.R'
    'addArea.R'
    'addStandardSpatialAttributes.R'
    'addTo.R'
    'aggregateSpatial.R'
    'aggregateSubannual.R'
    'aggregateYears.R'
    'availableQuantities.R'
    'averageFields.R'
    'benchmarking.R'
    'byIDfromList.R'
    'calcNewField.R'
    'checkSTAMatches.R'
    'classification-schemes.R'
    'commonSTAInfo.R'
    'compareLayers.R'
    'copyLayers.R'
    'crop-methods.R'
    'defineLayer.R'
    'defineQuantity.R'
    'defineSource.R'
    'determinePFTs.R'
    'export-methods.R'
    'extent-methods.R'
    'getDimInfo.R'
    'getField.R'
    'getScheme.R'
    'is-methods.R'
    'layerOp.R'
    'lookupQuantity.R'
    'makeFieldID.R'
    'makePlotTitle.R'
    'names-methods.R'
    'package-documentation.R'
    'periods.R'
    'plotScatter.R'
    'plotSpatial.R'
    'plotSpatialComparison.R'
    'plotSubannual.R'
    'plotTemporal.R'
    'plotTemporalComparison.R'
    'plotting-framework-functions.R'
    'read-netcdf-utility-functions.R'
    'renameLayers.R'
    'selectDays.R'
    'selectGridcells.R'
    'selectLayers.R'
    'selectMonths.R'
    'selectSeasons.R'
    'selectYears.R'
    'show-methods.R'
    'small-utility-functions.R'
    'summary-methods.R'
    'whichLayers.R'
    'writeField-methods.R'
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Output from dynamic global vegetation models (DGVMs) and similar models is inherently geospatial (since such models simulate the terrestrial land surface) and can be analysed in terms of both spatial patterns and time series.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not a statistical package.

-   Who is the target audience and what are scientific applications of this package?  

Our target audience are scientists using dynamic global vegetation models (DGVMs) to tackle scientific questions concerning ecology and evolution and Earth system science. Within that, we believe the researchers in the fields of ecology and evolution who may not have a lot of modelling or even geospatial data analysis experience will particularly benefit from the package.   Our experience is that many research groups are using such process-based models to complement other methods, and providing high-level tools (especially written in R) removes technical barriers and increases the efficiency of analysis.  Simply put, it doesn't make sense for every group or scientist to write their own scripts to read, crop, aggregate, plot, compare (etc) simulation output and data.  
However, the complete target audience is considerably wider, and includes all users and developers of DGVMs, and also scientist who analyse multi-model ensemble DGVM output such as [TRENDY](https://blogs.exeter.ac.uk/trendy/) or the biome, fire and permafrost sectors of [ISIMIP](https://www.isimip.org/).

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Absolutely none that we are aware of.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by jooolia** [comment]
Dear @MagicForrest,
Thank you for your pre-submission. Can you clarify if this is intended to be a statistical package submission? If that is the case it would be great if you can fill out the stats standards section (currently it is "NA").
Thanks, Julia

**Comment by jooolia** [comment]
Dear @MagicForrest,
Thanks for your response. If it is to be a Data Lifecycle package then it is out of scope as  a ["Packages that wrap or implement statistical or machine learning methods."](https://devguide.ropensci.org/policies.html#other-scope-considerations). However it could potentially in-scope for a statistical package, but would require more [documentation](https://stats-devguide.ropensci.org/pkgdev.html). If that is of interest to you we could ping another editor who is more focused on the statistical package review regarding scope questions regarding the statistical aspects. Another idea is that If the intent is to have a data munging package then another idea would be to split these functions into a package and have the viz+stats+modelling in another. If this of interest I would discuss with some of the editors to get their thoughts on this. 

Thanks, Julia

**Comment by MagicForrest** [comment]
Dear @jooolia,

I see your point, although wrapping statistical methods is really a very small part of what the package does, so I don't think it really fits as a statistical package.  However, when I read that section, I also realised that the package is likely out of scope on the grounds of "Exploratory data analysis packages that visualize or summarize data.".  This is a **big** part of what the package does.  A related question, in that section it also states "General workflow or package development support packages." - does "General workflow" refer to scientific workflow or programming workflow?  If is refers to scientific workflow, then again this strongly suggests out of scope because the package is all about facilitating general scientific workflow.

Because the DGVMTools tries to offer tools for a complete DGVM workflow it is kind of a kitchen sink.  Therefore it appears to qualify in a some ways (it does handle geospatial and it does do data munging) but also rules itself in others (ie. paragraph above).  So I guess the conclusion is that it is out of scope, although I would be happy to hear your final word on it.

I will consider the idea of splitting the package as you suggest.  On the one hand the package is already large so that makes sense.  On the other hand, it is designed to be a one-stop shop, so splitting it is kind of against the core idea.

In any event, thanks for your consideration and this great initiative,

Matt

**Comment by jooolia** [comment]
Dear @MagicForrest,

Yes I think we agree that this package is out of scope for rOpenSci in its current form. I will go ahead and close this issue, but if you have any other thoughts or questions please feel free to re-open or add them to to the issue. 

Thanks, Julia
