### ISSUE TITLE
Presubmission inquiry - stochLAB package for modelling collision risk at offshore wind farms

### ISSUE THREAD

**Issue by grwhumphries** [ropensci/software-review#506]
Submitting Author Grant Humphries
**Reviewers:** 
**Editor:** 
Language Code English
Submitting Author: Grant Humphries (@grwhumphries)  
Other Package Authors: Bruno Caneco (@bcaneco)
Repository:  https://github.com/HiDef-Aerial-Surveying/stochLAB
Submission type: Pre-submission

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: stochLAB
Title: Stochastic Collision Risk Model
Version: 1.0.0
Authors@R: c(
    person("Grant", "Humphries", , "grant.humphries@hidefsurveying.co.uk", role = c("aut", "cre")),
    person("Bruno", "Caneco", , "bruno@dmpstats.com", role = "aut"),
    person("Marine Scotland", role = c("fnd", "cph")),
    person("HiDef", role = "cph"),
    person("DMPstats", role = "cph")
  )
Description: Tool for running Collision Risk Models for seabirds on
    offshore wind farms.
License: GPL (>= 3) + file LICENSE
Depends: 
    R (>= 4.0)
Imports: 
    cli,
    data.table,
    dplyr,
    foreach,
    glue,
    logr,
    magrittr,
    msm,
    pracma,
    purrr,
    rlang,
    stats,
    tibble,
    tidyr
Suggests: 
    rmarkdown,
    knitr,
    spelling,
    testthat (>= 3.0.0),
    covr
Config/testthat/edition: 3
Encoding: UTF-8
Language: en-GB
LazyData: true
LazyDataCompression: bzip2
Roxygen: list(markdown = TRUE)
URL: https://www.github.com/HiDef-Aerial-Surveying/stochLAB,
    https://hidef-aerial-surveying.github.io/stochLAB/
BugReports: https://www.github.com/HiDef-Aerial-Surveying/stochLAB/issues
RoxygenNote: 7.1.2
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [X] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of: This package is for applying a deterministic model to calculate potential collision risk of seabirds at offshore windfarms. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)? No

-   Who is the target audience and what are scientific applications of this package?  This package is for anyone working in the offshore wind industry who is looking to quantify collision risk of seabirds depending on the parameters of the wind farm area or turbines.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? No 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)? N/A

-  Any other questions or issues we should be aware of?:

**Comment by jooolia** [comment]
Dear @grwhumphries,
Thank you for your pre-submission. This is a statistical package submission and you have replied "no" to the documentation of standards in your code, is this something you intend to do before a full submission or do you need support with this point?
Thanks, Julia

**Comment by grwhumphries** [comment]
Thanks @jooolia :) I might need a bit of support with that, if at all possible. Not a process I've followed before. Perhaps if you've got a link to clear documentation - I'm guessing this is done through the `ssr` package?

**Comment by jooolia** [comment]
Yes it would be with the srr package. 

I was having a look at the Readme.Rmd and the vignette to get a feel for the outputs and struggled to use them as most of the code snippets are not R chunks and when I change them to R chunks I get several errors. I will try to have a look using some of the examples provided in other files, but it would be nice to clarify why this is not working. 

Thanks, Julia

**Comment by jooolia** [comment]
Hi @mpadge, you mentioned being in touch about this issue, are there any updates here? Thanks, Julia

**Comment by mpadge** [comment]
Yes, I think we can close this now, as @grwhumphries intends to proceed to a full submission. Right Grant?

**Comment by grwhumphries** [comment]
@mpadge  - yeah that's correct! I'll be doing a full submission soon
