### ISSUE TITLE
datefixR: Fix Really Messy Dates

### ISSUE THREAD

**Issue by nathansam** [ropensci/software-review#533]
**Date accepted:** 2022-07-16
Submitting Author Name: Nathan Constantine-Cooke
Submitting Author Github Handle: @nathansam
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/nathansam/datefixR
Version submitted: 0.1.4.9000
Submission type: Standard
Editor: @adamhsparks
Reviewers: @AlvesKS, @alstat
Due date for @AlvesKS: 2022-05-30
Due date for @alstat: 2022-07-15
Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: datefixR
Title: Fix Really Messy Dates
Version: 0.1.4.9000
Authors@R: person("Nathan",
                  "Constantine-Cooke",
                  email = "nathan.constantine-cooke@ed.ac.uk",
                  role = c("aut", "cre"),
                  comment = c(ORCID = "0000-0002-4437-8713"))
Description: Fixes messy dates in data frames such as those entered via text
  boxes. Standardizes / - and whitespace separation, month abbreviations, and
  year first or day first by converting to R's built-in Date class. Imputes
  missing date or month using user-provided values.  
License: GPL (>= 3)
Depends: R (>= 4.0.0)
Imports: 
    lifecycle,
    stringr
Language: en-US
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
URL: https://www.constantine-cooke.com/datefixR/ https://github.com/nathansam/datefixR
BugReports: https://github.com/nathansam/datefixR/issues
Suggests: 
    rmarkdown,
    knitr,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

datefixR takes date data in which has been stored in many different formats (01/01/2001, 5 April 2020, Dec 2015 etc.) and converts them to R's `Date` type.

-   Who is the target audience and what are scientific applications of this package?

Any researchers using data entered via a questionnaire which (unfortunately) asked for a date as free-text. Given the nature of this data generation, this mainly affects those who work with human subjects.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

[`lubridate::guess_formats()`](https://lubridate.tidyverse.org/reference/guess_formats.html) can be used to guess a date format and [`lubridate::parse_date_time()`](https://lubridate.tidyverse.org/reference/parse_date_time.html) calls this function when it attempts to parse a vector into a POSIXct date-time object. However:

1.  When a date fails to parse in `{lubridate}` then the user is simply told how many dates failed to parse. In `datefixR` the user is told the ID (assumed to be the first column by default but can be user-specified) corresponding to the date which failed to parse and reports the considered date: making it much easier to figure out which dates supplied failed to parse and why.
2.  When imputing a missing day or month, there is no user-control over  this behaviour. For example, when imputing a missing month, the user may wish to impute July, the middle of the year, instead of January.  However, January will always be imputed in `{lubridate}`. In `datefixR`, this behaviour can be controlled by the `month.impute` argument.
3.  These functions require all possible date formats to be specified in the `orders` argument, which may result in a date format not being considered if the user forgets to list one of the possible formats. By contrast, `datefixR` only needs a format to be specified if month-first is to be preferred over day-first when guessing a date.

However, `{lubridate}` of course excels in general date manipulation and is an excellent tool to use alongside `datefixR`.

An alternative function is [`anytime::anydate()`](https://dirk.eddelbuettel.com/code/anytime.html) which also attempts to convert dates to a consistent format (POSIXct). However `{anytime}` assumes year, month, and day have all been provided and does not permit imputation. Moreover, if a date cannot be parsed, then the date is converted to an NA object and no warning is raised- which may lead to issues later in the analysis.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

NA

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/software-review/issues/529

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

pkgcheck claims: "Package has no continuous integration checks." however [Github actions is already used](https://github.com/nathansam/datefixR/actions) so this is a false positive. 

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

(Already available on CRAN)

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

NA

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by jooolia** [comment]
@ropensci-review-bot assign @adamhsparks as editor

**Comment by adamhsparks** [comment]
Hi @nathansam, could you address the issues _lintr_ found, `Avoid 1:nrow(...) expressions, use seq_len.` and the lines of code >80 chars, please?

While you're doing that I'll start looking for reviewers.

**Comment by adamhsparks** [comment]
@ropensci-review-bot seeking reviewers

**Comment by nathansam** [comment]
Hi @adamhsparks, thank you! Those lintr issues should now be fixed.

**Comment by adamhsparks** [comment]
Hi @nathansam, as I've been looking for reviewers and checking over the package some more, I did note some issues with the spelling and tests as well.

When I check the tests, I get this:

```r
Backtrace:
 1. testthat::expect_equal(...)
      at test_fix_dates.R:206:2
 4. datefixR::fix_dates(temp, "date", day.impute = NA)
 9. datefixR::.fix_date(...)
      at datefixR/R/fix_dates.R:81:10

── Warning (test_fix_dates.R:215:3): Imputing month with NA results in NA ──────
NA imputed for subject 1 (date: 1994)

Backtrace:
 1. testthat::expect_equal(...)
      at test_fix_dates.R:215:2
 4. datefixR::fix_dates(temp, "date", month.impute = NA)
 9. datefixR::.fix_date(...)
      at datefixR/R/fix_dates.R:81:10
```

With the spelling, your DESCRIPTION says "en-US" but you've used British English for "behaviour", also the spellcheck is picking up a few other words that are non-standard but probably correct anyway. I suggest setting up spell checking with `usethis::use_spell_check()`.

**Comment by nathansam** [comment]
Thanks @adamhsparks ! I have fixed the typo and have now set up `{spelling}` as you have suggested. Thanks for the suggestion; I will definitely be using it across all R packages I maintain. Thank you for catching the warnings in the tests. The warnings are intended (but were added after the tests were first written), and I have now added explicit `expect_warning()` statements to those tests.

**Comment by adamhsparks** [comment]
@ropensci-review-bot add @AlvesKS to reviewers

**Comment by adamhsparks** [comment]
@ropensci-review-bot add @arhepworth to reviewers

**Comment by nathansam** [comment]
Hi everyone! I hope you are all well! Just dropping a reminder the review due date was yesterday. Thanks for agreeing to review datefixR 🙂.

**Comment by AlvesKS** [comment]
Hi everyone. I just want to let you know that I am still working on the review. I will need some more time to complete it. I am sorry for the delay.
Thanks

**Comment by arhepworth** [comment]
Apologies, have dropped the ball on this one. I can theoretically get it done by the end of the weekend, if that is useful?

From: Nathan Constantine-Cooke ***@***.***>
Date: Wednesday, 1 June 2022 at 20:15
To: ropensci/software-review ***@***.***>
Cc: Anna Hepworth ***@***.***>, Mention ***@***.***>
Subject: [EXT] - Re: [ropensci/software-review] datefixR: Fix Really Messy Dates (Issue #533)

CAUTION: This email originated from outside of DPIRD. Do not click links or open attachments unless you recognise the sender and know the content is safe.



Hi everyone! I hope you are all well! Just dropping a reminder the review due date was yesterday. Thanks for agreeing to review datefixR 🙂.

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fropensci%2Fsoftware-review%2Fissues%2F533%23issuecomment-1143530688&data=05%7C01%7CAnna.Hepworth%40dpird.wa.gov.au%7C0a7b177c0d984932989908da43c86f43%7C7b5e7ee62d234b9aabaaa0beeed2548e%7C0%7C0%7C637896825393348331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A%2BaIkNUq%2BQ2ppQlbQTR%2FIZrxdTnH6epTvQuQh3xtYSc%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPS2KSBQUGYNQ56UJNB4WDLVM5H6LANCNFSM5UWX4TZA&data=05%7C01%7CAnna.Hepworth%40dpird.wa.gov.au%7C0a7b177c0d984932989908da43c86f43%7C7b5e7ee62d234b9aabaaa0beeed2548e%7C0%7C0%7C637896825393348331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EvhUYP98ztradQWwG6pIjse8OBsw0j%2FwkTRDb2NNHWA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[Facebook]<https://www.facebook.com/DPIRDWA>    [Twitter] <https://www.twitter.com/DPIRDWA>     [Linkedin] <https://www.linkedin.com/company/dpirdwa>

[Dept of Primary Industries and Regional Development]   [We're working for Western Australia]

[Artwork: “Kangaroos going to the Waterhole” by Willarra Barker.]

DPIRD acknowledges the Traditional Owners of Country, the Aboriginal people of the many lands that we work on and their language groups throughout Western Australia and recognise their continuing connection to the land and waters.

We respect their continuing culture and the contribution they make to the life of our regions and we pay our respects to their Elders past, present and emerging.

Artwork: “Kangaroos going to the Waterhole” by Willarra Barker.



Western Australia’s COVID-safe principles: Practise physical distancing where possible. Wash hands regularly. Stay home if unwell. Get tested if symptomatic. Download the COVIDSafe app.

DISCLAIMER: The information contained in this email (including attachments) is intended only for the use of the person(s) to whom it is addressed as it may be confidential and contain legally privileged information. If you are not the intended recipient you are hereby notified that any perusal, use, distribution, copying or disclosure is strictly prohibited. If you have received this email in error, please immediately advise us by return email and delete the email document. This email and any attachments to it are also subject to copyright and any unauthorised reproduction, adaptation or transmission is prohibited. This notice should not be removed.

**Comment by adamhsparks** [comment]
That's fine, @arhepworth. Thanks for letting us know.

**Comment by AlvesKS** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
-   [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
-   [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
-   [x] **Function Documentation:** for all exported functions
-   [x] **Examples:** (that run successfully locally) for all exported functions
-   [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

-   [x] **Installation:** Installation succeeds as documented.
-   [x] **Functionality:** Any functional claims of the software been confirmed.
-   [x] **Performance:** Any performance claims of the software been confirmed.
-   [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
-   [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing:

-   [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

The Package `datefixR` developed by Constantine-Cooke provides two functions to convert dates into the R standardized format (`ymd`). Besides the functions cannot distinguish between `dmy` and `mdy` (US format) date types when both are present in the same column, they work pretty well for what they claim to do.

Below, I detail some issues and recommendations for what I think would improve the package.

#### README

I recommend stating clearly what is the purpose of the package in the README file. The way it is stated in the first paragraph of the README file is okay, but I think it could be more detailed.

#### Function naming

I think the names of the function can be easily confused. The authors should consider changing the names to `fixdate_df()` and `fixdate_char()`.

#### Interaction with `dplyr::mutate()`

I notice that it is not possible to use `fix_date()` in the `mutate()` function from `dplyr` package. I recommend adding this functionality.


#### `fix_dates()` documentation 

In the `fix_dates()` description (documentation), it is stated "Cleans up a `dataframe` object which...". Consider replacing "Cleans up" with "correct", "fix up", "tidy", "adjust", etc. When I first read "Cleans up", I  thought that the function would erase the data from the data frame.

#### Vignette

Provide a function to call the first data frame (`bad.dates`) provided in the package Vignette. It would be faster to reproduce the examples. After looking at the function documentation, I saw that the code to build the `bad.dates` data frame (with different data) is provided in the `fix_dates()` documentation (help material), but I think having a ready to use data frame is better. Another option is providing the code to build the data frame in the Vignette.

**Comment by nathansam** [comment]
Thank you for your feedback @AlvesKS ! It is all very much appreciated and is a big help. I will begin implementing your suggestions on an `ropensci` branch of the datefixR repo so changes aren't being pushed to main whilst @arhepworth is still reviewing.

**Comment by adamhsparks** [comment]
@ropensci-review-bot to alstat reviewers

**Comment by adamhsparks** [comment]
@ropensci-review-bot to @alstat reviewers

**Comment by adamhsparks** [comment]
@ropensci-review-bot add @alstat to reviewers

**Comment by alstat** [comment]
Hi @nathansam, I have some suggestions on [datefixR#17](https://github.com/nathansam/datefixR/issues/17), [datefixR#18](https://github.com/nathansam/datefixR/issues/18).

**Comment by adamhsparks** [comment]
Hi @alstat, please don't forget to complete our [review template](https://devguide.ropensci.org/reviewtemplate.html#reviewtemplate) along with the issues that you've opened for datefixR when you're finished with your review. 🙏

**Comment by alstat** [comment]
Noted @adamhsparks, still reviewing, hoping to complete it within the week. Thanks.

**Comment by alstat** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [ ] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [ ] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [ ] **Function Documentation:** for all exported functions
- [ ] **Examples:** (that run successfully locally) for all exported functions
- [ ] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing:

- [ ] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

### Issues opened
- [ ] Docs: add format output in the value returned by fix_date [#17](https://github.com/nathansam/datefixR/issues/17)
- [ ] Docs: add datetime input as limitation [#18](https://github.com/nathansam/datefixR/issues/18)
---

### Review Comments

**Comment by adamhsparks** [comment]
@alstat and @AlvesKS, could I ask you to please complete your reviews with the estimated time taken so I can enter them into our database? thank you

**Comment by adamhsparks** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/533#issuecomment-1144924437 time 9

**Comment by adamhsparks** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/533#issuecomment-1177076018

**Comment by alstat** [comment]
@adamhsparks I've completed the checklist.

**Comment by adamhsparks** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/533#issuecomment-1177076018 time 8

**Comment by adamhsparks** [comment]
Thanks, @alstat for finalising that.

@alstat and @AlvesKS, please let us know when you're satisfied with the changes or if you would prefer more.

**Comment by alstat** [comment]
I'm satisfied with the changes [here](https://github.com/nathansam/datefixR/compare/main...ropensci), both issues I opened were addressed.

**Comment by AlvesKS** [comment]
Hi @adamhsparks,

I am also satisfied with the changes. 
The author has done a great job addressing the suggestions I made.
Congratulations @nathansam!

Kaique

**Comment by adamhsparks** [comment]
@ropensci-review-bot approve datefixR

**Comment by adamhsparks** [comment]
Thank you, @AlvesKS and @alstat for your kind and insightful reviews. I hope you found this experience useful and enjoyable. @nathansam, thank you for submitting datefixR. You can transfer it to rOpenSci now.

**Comment by nathansam** [comment]
Thank you @AlvesKS and @alstat, your reviews were immeasurably helpful! I am of course more than happy to acknowledge you both as reviewers in DESCRIPTION. I have added your details based on the DESCRIPTION files for your own packages. Please let me know if you would like any edits made to your listings in the description. 
https://github.com/nathansam/datefixR/blob/3a2b33b657c19fce085f57ac23a831f043838da8/DESCRIPTION

Thank you @adamhsparks for your editorship throughout and for the issues you have opened. I will begin the process of migrating datefixR to the ropensci organization now.

**Comment by nathansam** [comment]
@ropensci-review-bot finalize transfer of datefixR
