### ISSUE TITLE
Presubmission inquiry - spiro: Manage Data from Cardiopulmonary Exercise Testing

### ISSUE THREAD

**Issue by smnnlt** [ropensci/software-review#537]
Submitting Author Name: Simon Nolte
Submitting Author Github Handle: @smnnlt
Repository:  https://github.com/smnnlt/spiro
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: spiro
Title: Manage Data from Cardiopulmonary Exercise Testing
Version: 0.0.4
Authors@R: 
    person(given = "Simon",
           family = "Nolte",
           role = c("aut", "cre"),
           email = "s.nolte@dshs-koeln.de",
           comment = c(ORCID = "0000-0003-1643-1860"))
Description: Import, process, summarize and visualize raw data from 
    metabolic carts.
License: MIT + file LICENSE
URL: https://github.com/smnnlt/spiro, https://smnnlt.github.io/spiro/
BugReports: https://github.com/smnnlt/spiro/issues
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.0
Imports: 
    ggplot2,
    xml2,
    readxl,
    knitr,
    cowplot,
    digest,
    signal
Suggests: 
    testthat (>= 3.0.0),
    rmarkdown,
    ggborderline
VignetteBuilder: knitr
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [X] data extraction
	- [ ] database access
	- [X] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The spiro package allows to read and process data from raw data files of different metabolic carts.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

N/A

-   Who is the target audience and what are scientific applications of this package?

This package is primarily written for researchers in exercise science, who want to make their analysis of cardiopulmonary exercise testing more standardized, reproducible and faster. It may also be used in a commercial context (e.g., training diagnostics business)

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The [whippr](https://github.com/fmmattioni/whippr) package has a different approach to the same problem. Compared to whippr, spiro has a more automated and simpler data workflow (basically one function for reading and processing data, and one function for summarizing or plotting). spiro has several relevant additional features, that whippr does not have: Automated detection and manual generation of exercise test protocols; data summary by load steps; adding and synchronizing external heart rate data; import of raw data file meta data; advanced data filtering methods (e.g., Butterworth filters; moving breath averages); Wasserman 9-Panel-Plots. Compared to whippr, the spiro package does not offer methods for VO2 kinetics analysis and automated outlier removal.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

This package works with cardiopulmonary exercise data, which is per se sensitive health data. Meta data from the original raw data files is read and anonymized by default (with the exception of data on body mass, which is necessary to perform certain calculations of variables). The anonymization can optionally be deactivated by means of a function argument [spiro(anonymize = FALSE)], so that meta data is saved alongside the processed data. This may be helpful in some settings when there is no intent to share the data. Sharing of the resulting data in such situations could potentially reveal personal information, which is why this option is not activated by default.

-  Any other questions or issues we should be aware of?:

This is my first R package and I'm not exactly sure in which category it fits best. I also haven't seen any package from the field of sports and exercise science in rOpenSci yet, so I'm curious whether it fits your general scope.

**Comment by emilyriederer** [comment]
Hi @smnnlt ! Thank you so much for the inquiry and for your detailed write-up. I really like the slick visualizations you show on the website. 

As we consider whether this package is in-scope, I am hoping to get a bit more information since we don't have very much domain expertise in this field.

- I see your package supports data collected from a number of different devices (e.g. CORTEX, ZAN, etc.) Can you provide any guess for how much of research is covered by the covered formats?
- Not having seen the raw data formats, could you please help us understand better what types of processing/wrangling the package supports? For example, is the data previously unstructured and you're making it structured/tabular? 

It might be helpful to add a bit more of this context to the README.  After reading it someone with little domain knowledge should ideally understand the aim, goals and functionality of the package.

Thanks again!

**Comment by emilyriederer** [comment]
Dear @spiro - 

Thank you for your answers. Taking all of that into account, I believe that this package to be in-scope. I will now close this pre-submission inquiry issue and we look forward to your full submission.

Thanks again!

**Comment by emilyriederer** [comment]
Hi @smnnlt 

I realized in my last message I accidentally tagged a user `spiro` (the package name) instead of your correct handle. Pinging again to make sure you saw that I closed the *pre-submission* issue as a matter of process, but that this is not a rejection! We welcome you to proceed to submit the package for review.

Emily

**Comment by smnnlt** [comment]
Hi @emilyriederer 

Thank you for your message. I am currently working on some final adjustments and look forward to submitting the package in the upcoming 1-2 weeks. 

Simon
