### ISSUE TITLE
Presubmission Inquiry:  fouRplebsAPI - API access to the largest 4chan archive

### ISSUE THREAD

**Issue by buehlk** [ropensci/software-review#540]
Submitting Author Name: Kilian Buehling
Submitting Author Github Handle: @buehlk
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/buehlk/fouRplebsAPI
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: fouRplebsAPI
Type: Package
Title: R implementation for the 4plebs.org API
Version: 1.0.0
Author: person(given = "Kilian", family = "Buehling", role = c("aut", "cre"), email = kilian.buehling@fu-berlin.de)
Maintainer: The package maintainer <kilian.buehling@fu-berlin.de>
Description: This package allows queries to the 4plebs.org API. Researchers can thereby access the largest public 4chan archive, called 4plebs.org. 
    Visual and text data posted in 4chan can be searched whithin and across 4chan channels and can also be accessed with detailed queries and stored in a structured manner.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
URL: https://github.com/buehlk/fouRplebsAPI
BugReports: https://github.com/buehlk/fouRplebsAPI/issues
Imports: httr, jsonlite, purrr, stringr, dplyr
RoxygenNote: 7.2.0
Suggests: 
    covr,
    knitr,
    rmarkdown,
    roxyglobals (>= 0.2.1),
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Remotes: 
    anthonynorth/roxyglobals
Roxygen: list(
    markdown = TRUE,
    roclets = c("collate", "namespace", "rd", "roxyglobals::global_roclet"))
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [x] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package utilizes the 4plebs.org API to access the largest archive of the social media platform 4chan. The retrieved text and image data can then be used for further analyses of public communication on social media.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?  

The target audience are researchers in the field of social science, political science and communication science who want to study public communication on this widely used (but fringe) platform.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
- 
Not that I know of.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-  Any other questions or issues we should be aware of?:

**Comment by emilyriederer** [comment]
Hi @buehlk - thank you for submitting this inquiry. 

Unfortunately, after discussing with the editorial team, we believe that this package is outside our scope. While there are undoubtedly useful research applications to such a tool, we are not confident that the underlying API meets our [ethics and privacy guidance](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research) since their [FAQ](https://archive.4plebs.org/_/articles/faq/) suggests that they are collecting PII data which users had a reasonable expectation to be ephemeral and may not honor requests to delete data. 

Thank you again for considering rOpenSci, and please feel free to submit other packages for consideration in the future.
