### ISSUE TITLE
fwildclusterboot presubmission

### ISSUE THREAD

**Issue by s3alfisc** [ropensci/software-review#542]
Submitting Author Name: Alexander Fischer
Submitting Author Github Handle: @s3alfisc
Other Package Authors Github handles: @droodman, 
Repository:  https://github.com/s3alfisc/fwildclusterboot
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Description: Implementation of the fast algorithm for wild cluster bootstrap 
             inference developed in Roodman et al (2019, STATA Journal) for 
             linear regression models <doi:10.1177/1536867X19830877>, 
             which makes it feasible to quickly calculate bootstrap test 
             statistics based on a large number of bootstrap draws even for 
             large samples. Multiway clustering, regression weights, 
             bootstrap weights, fixed effects and subcluster bootstrapping
             are supported. Further, both restricted (WCR) and unrestricted
             (WCU) bootstrap are supported. Methods are provided for a variety 
             of fitted models, including 'lm()', 'feols()' 
             (from package 'fixest') and 'felm()' (from package 'lfe'). 
             Additionally implements a heteroskedasticity-robust (HC1) wild 
             bootstrap.
             Further, the package provides an R binding to 'WildBootTests.jl',
             which provides additional speed gains and functionality, 
             including the 'WRE' bootstrap for instrumental variable models 
             (based on models of type 'ivreg()' from package 'ivreg')
             and hypotheses with q > 1.
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [x] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

`fwildclusterboot` conducts inference for (linear) regression models via a wild (cluster) bootstrap. It further serves as an R binding of the [WildBootTests.jl](https://github.com/droodman/WildBootTests.jl) library. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Yes, I have worked with the `srr` package and have a [draft ](https://github.com/s3alfisc/fwildclusterboot/blob/ropensci/R/srr-stats-standards.R)available (but it is currently not in the main branch). 

-   Who is the target audience and what are scientific applications of this package?  

The target audience is academic social scientists (economics, political science, sociology). `fwildclusterboot` should be used whenever regression errors are "clustered" into few groups, in which case inference based on asymptotic approximations might fail. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Other R packages that implement the wild cluster bootstrap are `sandwich` via its `vcovBS` function and the `clusterSEs` package. `fwildclusterboot` implements a [significantly faster algorithm](https://www.r-bloggers.com/2021/12/1000x-faster-wild-cluster-bootstrap-inference-in-r-with-fwildclusterboot-%f0%9f%9a%80/). Furter, `fwildclusterboot` offers additional functionality, e.g. the subcluster bootstrap. Through `WildBootTests.jl`, it also allows to run a highly optimized version of the WRE bootstrap for IV regressions (Davidson & MacKinnon, 2010) , which is not available in any other R package. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Yes. 

-  Any other questions or issues we should be aware of?:

`fwildclusterboot` implements the "fast" wild cluster bootstrap in R, but also allows to call `WildBootTests.jl` via the `JuliaConnectoR` package. It's therefore (also) a wrapper package, and you might consider it to be out of scope?

**Comment by emilyriederer** [comment]
Hi @s3alfisc - thanks so much for submitting your package. I especially appreciate all of the details (and impressive benchmarking results!) in the best-in-class answer. 

As a general matter, this seems in-scope for a regression package. Based on your work with the statistical standards, could you please comment on whether you believe that the package is on track to meet at least half of the general + category-specific standards?

Thanks also for the call-out on the optional functionality to call the Julia implementation. We are also planning, but do not yet have standards, for a statistical wrapper package. A member of the statistics peer review team may comment further on whether or not this package could fit that category also.

**Comment by s3alfisc** [comment]
Hi @emilyriederer , thanks for your feedback! I have uploaded my comments based on the statistical software roclets in a separate branch [here ](https://github.com/s3alfisc/fwildclusterboot/blob/ropensci/R/srr-stats-standards.R).

**Comment by mpadge** [comment]
@s3alfisc @emilyriederer I've had a look through the code, and do not think this package should really be considered a statistical "wrapper" package, as it only constucts a single external call to one Julia package. The Julia connection is entirely optional for package functionality, and in terms of code and algorithms represents only a very small portion of the code. I suggest the review process can proceed under the single category nominated above.

@s3alfisc I note that your current version documents compliance with 59 / 115 standards, which is > 50%, so okay to proceed. The `srr_report()` nevertheless notes standard G2.15 appears to be missing. Could you please check and rectify if possible? Note also that our automated check system currently works on GitHub default branch only, but we're happy to use your submission to develop an appropriate workflow for non-default branches. Until then, the checks might have to be generated for default branch, after which I'll manually remove that comment and re-generate them for your "ropensci" branch. Thanks!

**Comment by s3alfisc** [comment]
Hi @mpadge , thanks for your feedback! I will spend some time cleaning up the package over the next days (documenting all srr roclets, add G.2.15, and merge everything into the main branch) and then I will submit `fwildclusterboot`! =)

**Comment by mpadge** [comment]
@s3alfisc No need to merge if you'd rather not. We do want our system to one day work on non-default branches, so as said are happy to use your submission to test that, if that's easier for you. That said, we do generally advise against this, because then you'll be stuck implementing changes to reviews in your non-default branch, which may make your own workflow less robust. Up to you.
