### ISSUE TITLE
presubmission inquiry for eeguana package (EEG data preprocessing)

### ISSUE THREAD

**Issue by bnicenboim** [ropensci/software-review#543]
Submitting Author Name: Bruno Nicenboim
Submitting Author Github Handle: @bnicenboim
Repository:  https://github.com/bnicenboim/eeguana
Submission type: Pre-submission
Language: en

---

-   DESCRIPTION 

```
Package: eeguana
Type: Package
Title: Flexible Manipulation of EEG Data
Description: Flexible manipulation of EEG data in R. It provides a data.table 
    powered framework for manipulating EEG data with dplyr-based functions
    (e.g., `mutate`, `filter`, `summarize`) extended to a new class, eeg_lst,
    other EEG-specialized functions, and `ggplot` wrapper functions.  The new
    class is inspired by tidyverse principles but it's not really "tidy" (due
    to space considerations), it's a list of (i) a wide data table (signal_tbl)
    that contains the signal amplitudes at every sample point of the EEG,  (ii)
    an events data table with information about markers (or triggers), blinks
    and other exported information, and (iii) a long table with experimental
    information, such as participant number (.recording), conditions, etc.
    eeguana can do only basic pre-processing for now.
Version: 0.1.7.9000
Authors@R: c(
    person("Bruno", "Nicenboim", email = "bruno.nicenboim@tilburguniversity.edu", role = c("aut", "cre")),
    person("Kate", "Stone", email = "kate.stone@uni-potsdam.de", role = "ctb"),
    person("Mark", "Fairbanks", email = "mark.t.fairbanks@gmail.com", role = "ctb"))
URL: https://github.com/bnicenboim/eeguana
BugReports: https://github.com/bnicenboim/eeguana/issues
License: MIT + file LICENSE 
Encoding: UTF-8
RoxygenNote: 7.1.2
Depends:
    R (>= 3.1.0),
    stats
Imports:
    ggplot2 (>= 3.1.0),
    dplyr (>= 1.0.0),
    tidyr (>= 0.8.2),
    purrr (>= 0.2.5),
    tidyselect (>= 0.2.5),
    tools,
    magrittr (>= 1.5),
    rlang (>= 0.3.1),
    MBA (>= 0.0.9),
    data.table (>= 1.12.2),
    edfReader (>= 1.2.0),
    gtable (>= 0.2.0),
    scales (>= 1.0.0),
    fICA (>= 1.1),
    JADE (>= 2.0.1),
    methods,
    MASS,
    RcppRoll (>= 0.3.0),
    ellipsis (>= 0.1.0),
    fastICA,
    pracma,
    tidytable (>= 0.6.7),
    gsignal
Suggests:
    akima (>= 0.6.2),
    tibble (>= 2.1.1),
    plotly (>= 4.8.0),
    R.matlab (>= 3.6.2),
    reticulate (>= 1.11.1),
    testthat (>= 2.0.1),
    roxygen2 (>= 6.1.1),
    knitr (>= 1.21),
    rmarkdown (>= 1.11),
    spelling (>= 2.0),
    covr (>= 3.2.1),
    httr,
    cowplot
LazyData: true
LazyDataCompression: xz
VignetteBuilder: knitr
Language: en-US
Roxygen: list(markdown = TRUE)
Config/testthat/edition: 3
Remotes: 
    markfairbanks/tidytable,
     gjmvanboxtel/gsignal
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [X] data extraction
	- [ ] database access
	- [X]  data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text data
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

**data extraction:** `eeguana` is able to load with EEG data from several formats. 
**data munging**: It allows for the manipulation of the data with tidyverse-like functions.
Not sure about: "field and laboratory reproducibility tools".  The package allows for a reproducible workflow by making the user code everything instead of relying in a GUI (as with many matlab tools and the software BrainVision). It also makes the transition between data preprocessing and statistical analysis smoother, since everything can be done in R.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

NA

-   Who is the target audience and what are scientific applications of this package? 

Cognitive scientists (cognitive psychologists, neuro/psycholinguists) that wish to have a complete workflow from data processing to the statistical analysis in R (rather than jump from language/tool to language).  This can be also useful for neuroscientists to some extent, but more specialized and more powerful tools exists in python or matlab.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

To my knowledge there are two:  [erpR](https://cran.r-project.org/package=erpR), which doesn't seem to maintained anymore.It hasn’t been updated since 2014. The more serious competitor is [eegUtils](https://github.com/craddm/eegUtils). The differences are the following ones:
- `eeguana` is more thorougly tested 76% vs 54%, and all the "complicated" functions are tested against [MNE](https://mne.tools/stable/index.html) in python.
- `eeguana` relies on `tidytable` and `data.table` as back-ends for the data manipulation rather than `dplyr`, which makes it faster and less prone to crash with very large datasets. (I'm still cleaning the package from the last vestiges of `tibble` and `dplyr`).
- `eeguana` intends to do "less", it's build in a more modular way, where functions do less and allow for more customization. This is clear in the way `eeguana` plots creating a ggplot that can be customized

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

I don't think this is relevant.

-  Any other questions or issues we should be aware of?:

I'm aware that there is still some work to do in refactoring and cleaning the code. There are some dependencies that I can easily remove now, for example. I want to ask for some research assistant(s) to help me and I wanted to know for sure (to the extent this is possible) that the package could be submitted to Ropensci. (A long time ago, I had the feedback that yes: https://twitter.com/noamross/status/1067208322510655489)

**Comment by emilyriederer** [comment]
Hi @bnicenboim - thank you for reaching out. I believe that this package is firmly in-scope. Please feel free to progress to a full submission whenever you feel comfortable with the dependencies and refactoring.
