### ISSUE TITLE
Presubmission inquiry - melt: Multiple Empirical Likelihood Tests

### ISSUE THREAD

**Issue by markean** [ropensci/software-review#549]
Submitting Author Name: Eunseop Kim
Submitting Author Github Handle: @markean
Repository:  https://github.com/markean/melt
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: melt
Title: Multiple Empirical Likelihood Tests
Version: 1.6.0
Authors@R: c(
    person("Eunseop", "Kim", , "kim.7302@osu.edu", role = c("aut", "cre")),
    person("Steven", "MacEachern", role = c("ctb", "ths")),
    person("Mario", "Peruggia", role = c("ctb", "ths"))
  )
Description: Performs multiple empirical likelihood tests for linear and
    generalized linear models. The core computational routines are
    implemented using the 'Eigen' C++ library and 'RcppEigen' interface,
    with OpenMP for parallel computation. Details of multiple testing
    procedures are given in Kim, MacEachern, and Peruggia (2021)
    <arxiv:2112.09206>.
License: GPL (>= 2)
URL: https://github.com/markean/melt, https://markean.github.io/melt/
BugReports: https://github.com/markean/melt/issues
Depends: 
    R (>= 4.0.0)
Imports: 
    graphics,
    methods,
    Rcpp,
    stats
Suggests: 
    covr,
    ggplot2,
    knitr,
    microbenchmark,
    rmarkdown,
    spelling,
    testthat (>= 3.0.0),
    withr
LinkingTo: 
    BH,
    dqrng,
    Rcpp,
    RcppEigen
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
Language: en-US
LazyData: true
NeedsCompilation: yes
Roxygen: list (markdown = TRUE, roclets = c ("namespace", "rd",
    "srr::srr_stats_roclet"))
RoxygenNote: 7.2.0

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [x] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The package performs hypothesis testing with empirical likelihood for linear models and generalized linear models. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
Yes.

-   Who is the target audience and what are scientific applications of this package?  
Academic statisticians who are interested in empirical likelihood-based inference for (generalized) linear models.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
No, at least in my understanding.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Yes,

-  Any other questions or issues we should be aware of?:
How long does the peer-review process take on average? The plan is to submit the package with a manuscript to the Journal of Statistical Software.

**Comment by emilyriederer** [comment]
Hi @markean ! Thank you for your submission to rOpenSci

I'm tagging in @mpadge to answer your question on the review timeline for statistical packages and interactions with JSS

**Comment by mpadge** [comment]
Thanks @emilyriederer, and note that we'll soon have a new command for stats submissions, `@ropensci-review-bot check srr`, to check compliances with standards. In the meantime, this package gives this result:

---

## 'srr' standards compliance:

- complied with: 86 / 116 = 74.1%
- not complied with: 30 / 116 = 25.9%

This package complies with > 50% of all standads and may be submitted.

---

@markean Some responses to your questions:

> How long does the peer-review process take on average?

For standard (non-stats) submissions, we generally aim to review packages within 2-3 months. The statistical software review process is still very much a work-in-progress, and requires quite a bit more effort on the part of all involved. This means reviews thus far are taking longer than conventional reviews, and the entire process is definitely taking longer than the standard 2-3 months. It is nevertheless early days, and we will endeavour to find out why and how the process is slower than for non-stats reviews, and will do our best to speed things up. I'd suggest ou should at present expect the process to take vaguely between 3 and 6 months.

> The plan is to submit the package with a manuscript to the Journal of Statistical Software.

That's great news! We have two members of the editorial borad of JSS as editors of our statistical peer review program (ping @rkillick & @tdhock :smile:). A slightly longer-term aim is for rOpenSci statistical peer-review to lead to expedited review processes in JSS, for which we have been waiting for appropriate submissions. We'd be very happy for you to help trial that aspect, for which we all at both rOpenSci and JSS would really appreciate if you could first wait for the review here to be completed, and then submit to JSS for (hopefully) expedited review there. Let us know if you have any questions, and @rkillick & @tdhock feel free to comment further regarding JSS alignment.

**Comment by markean** [comment]
@mpadge Thank you for the details on timeline and JSS interaction! Are there some cases (packages) that took the route from rOpenSci to JSS? It would be very helpful for us to see some good examples.

**Comment by markean** [comment]
@tdhock Thank you for the reply.
@emilyriederer @mpadge Would it be okay to proceed to a submission then?

**Comment by emilyriederer** [comment]
Hi @markean ! Yes, indeed. I will close this presubmission inquiry and at your convenience please proceed to the full submission.

**Comment by mpadge** [comment]
@ropensci-review-bot help

**Comment by mpadge** [comment]
@ropensci-review-bot check srr
