### ISSUE TITLE
Review of dfms: Efficient Dynamic Factor Models for R?

### ISSUE THREAD

**Issue by SebKrantz** [ropensci/software-review#555]
Submitting Author Name: Sebastian Krantz
Submitting Author Github Handle: @SebKrantz
Other Package Authors Github handles: @rbagd
Repository:  https://github.com/SebKrantz/dfms
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: dfms
Version: 0.1.1
Title: Dynamic Factor Models
Authors@R: c(person("Sebastian", "Krantz", role = c("aut", "cre"), email = "sebastian.krantz@graduateinstitute.ch"),
             person("Rytis", "Bagdziunas", role = "aut"))
Description: Efficient estimation of Dynamic Factor Models using the Expectation Maximization (EM) algorithm 
  or Two-Step (2S) estimation, on datasets with missing data. The implementation follows advances in the econometric 
  literature: estimation can be done either by running the Kalman Filter and Smoother once with initial values 
  from PCA - following Doz, Giannone and Reichlin (2011) (2S) - or via iterated Kalman Filtering and Smoothing until EM 
  convergence - following Doz, Giannone and Reichlin (2012) - or using the adapted EM algorithm of Banbura and Modugno 
  (2014), allowing estimation with arbitrary patterns of missing data. The implementation makes heavy use of the 
  Armadillo C++ library and the collapse package, providing for particularly speedy estimation. A comprehensive set of 
  methods supports interpretation/visualization of the model and forecasting. Information criteria to choose the number 
  of factors are also provided - following Bai and Ng (2002).
  --- Key References: ---
  Doz, C., Giannone, D., & Reichlin, L. (2011). A two-step estimator for large approximate dynamic 
       factor models based on Kalman filtering. Journal of Econometrics, 164(1), 188-205.
  Doz, C., Giannone, D., & Reichlin, L. (2012). A quasi-maximum likelihood approach for large, approximate 
       dynamic factor models. Review of economics and statistics, 94(4), 1014-1024.
  Banbura, M., & Modugno, M. (2014). Maximum likelihood estimation of factor models on datasets with arbitrary 
       pattern of missing data. Journal of Applied Econometrics, 29(1), 133-160.
URL: https://sebkrantz.github.io/dfms/
BugReports: https://github.com/SebKrantz/dfms/issues
Depends: R (>= 3.0.0)
Imports: Rcpp (>= 1.0.1), collapse (>= 1.8.0)
LinkingTo: Rcpp, RcppArmadillo
Suggests: xts, vars, magrittr, testthat (>= 3.0.0), covr
License: GPL-3
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.1.2
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [x] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [x] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of: 
 
Dynamic factor models are a time series modelling and dimensionality reduction technique. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

I'm working on this. 

-   Who is the target audience and what are scientific applications of this package?  

Anybody working with time series. The package is useful for dimensionality reduction and forecasting with a large amount of time series.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

See README.md. In short: *dfms* is the much faster, provides multiple estimation methods, and has a comprehensive set of methods for exploring the model and forecasting. It is less specialized than economic nowcasting packages.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

No Applicable. 

-  Any other questions or issues we should be aware of?:

First, I would like to ask if you think you'll be able to review this package in a statistical sense. Then, I will likely not be able to comply with all of your standards, as I intend to export some C++ level helper function (mainly efficient Kalman Filtering and Smoothing functions) without any checks on the inputs. My hope here is in part to provide infrastructure that more specialized software (such as nowcasting packages) can take advantage of. The iterative filtering and smoothing performed in the estimation of dynamic factor models via expectation maximization (EM) algorithms does not square well with R-level checks in those functions (which would be executed many times per second).

**Comment by SebKrantz** [comment]
Hi @adamhsparks. Thanks for these initial comments. Let me work a bit further on it still to ensure the package passes your checks as good as possible and we can discuss further about it. What I can definitely offer to do it rigorous checking of inputs at the C++ level in the Kalman Filtering functions. I've not done this so far because Armadillo already has build in checks and throws appropriate error messages, making it practically impossible to pass something wrong. But let me see if I can appease your tests. 

Regarding the installation issue. I'm sorry for that, it turned out that BLAS and LAPACK libraries were linked through a Makevars.win file, instead of a global Makevars file. I have fixed this now.

**Comment by SebKrantz** [comment]
I have now brought *dfms* to a state where I am happy with it. The software is quite robust and inputs are rigorously checked. I still get some *autotest* issues, particularly in the main `DFM()` function, but I don't understand those, as all inputs parameters received the full extent of checking, including for data type, case insensitivity and permissible range. 

I have quickly gone through the *srr* standards, and in my opinion *dfms* broadly meets most of them. I have made some comments in `srr-stats-standards.R` below standards where I have done things a bit differently. 

Regarding unit testing, there is room for much improvement, in particular one could set up R translations of the authors original Matlab codes (which are provided under misc/) to test against. For now I have manually verified equivalence of *dfms* to these codes, and test against tome hard-coded parameter values. 

I general, my time on this package is a bit limited due to much more important development commitments that I have, but it would be nice to get some review, and also to be able to release it to CRAN before Christmas. Let me know how you think about this.

**Comment by adamhsparks** [comment]
Hi @SebKrantz, good to hear that you've managed to improve the package.

There are no requirements for the package review and CRAN. That is, you can put it on CRAN and have it reviewed asynchronously, they don't affect each other.

We can initiate the review process as soon as you can open a new issue requesting the review. We would strive to have the first reviews done within three weeks of the reviewers being assigned. This of course is flexible to work with the reviewers' own commitments as well. So we might have something by Christmas for the reviews for you, but I'd not be surprised if it slipped a little past that.

**Comment by SebKrantz** [comment]
Thanks @adamhsparks for the clarification. I will then open an issue requesting review, and also prepare a first CRAN release.
