### ISSUE TITLE
Pre Submission of concstats

### ISSUE THREAD

**Issue by schneiderpy** [ropensci/software-review#558]
Submitting Author Name: Andreas Schneider
Submitting Author Github Handle: @schneiderpy
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/schneiderpy/concstats
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: concstats
Title: Market Structure, Concentration and Inequality Measures
Version: 0.1.4
Authors@R: 
    person(given = "Andreas",
           family = "Schneider",
           role = c("aut", "cre"),
           email = "schneiderconsultingpy@gmail.com",
           comment = c(ORCID = "https://orcid.org/0000-0001-5630-1097"))
Description: Based on individual market shares of all participants in a
    market or space, the package offers a set of different structural and
    concentration measures frequently - and not so frequently - used in research
    and in practice. Measures can be calculated in groups or individually.
    The calculated measure or the resulting vector in table format should help
    practitioners make more informed decisions. Methods used in this package are
    from:
    1.  Chang, E. J., Guerra, S. M., de Souza Peñaloza, R. A. & Tabak, B. M.
    (2005) "Banking concentration: the Brazilian case".
    2.  Cobham, A. and A. Summer (2013). "Is It All About the Tails? The
    Palma Measure of Income Inequality".
    3.  García Alba Iduñate, P. (1994). "Un Indice de dominancia para el
    analisis de la estructura de los mercados".
    4.  Ginevicius, R. and S. Cirba (2009). "Additive measurement of market
    concentration" <doi:10.3846/1611-1699.2009.10.191-198>.
    5.  Herfindahl, O. C. (1950), "Concentration in the steel industry
    (PhD thesis)".
    6.  Hirschmann, A. O. (1945), "National power and structure of foreign trade".
    7.  Melnik, A., O. Shy, and R. Stenbacka (2008), "Assessing market dominance"
    <doi:10.1016/j.jebo.2008.03.010>.
    8.  Palma, J. G. (2006). "Globalizing Inequality: 'Centrifugal' and
    'Centripetal' Forces at Work".
    9.  Shannon, C. E. (1948). "A Mathematical Theory of Communication".
License: MIT + file LICENSE
URL: https://github.com/schneiderpy/concstats,
    https//schneiderpy.github.io/constats (website)
BugReports: https://github.com/schneiderpy/concstats/issues
Depends:
    R (>= 2.10)
Imports:
    dplyr (>= 1.0.7),
    readr
Suggests: 
    rmarkdown,
    knitr,
    devtools,
    kableExtra,
    ggplot2,
    testthat (>= 3.0.0),
    covr
VignetteBuilder:
    knitr,
    rmarkdown
Encoding: UTF-8
Language: en-US
LazyData: true
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.2.1
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [x] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
Exploring and/or summarizing a given market (or ecosystem) reflected by its given data (e.g. sales) to determine its structure regarding concentration, inequality, market share etc.
- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
Yes, all EDA and general standards are incorporated into the code via srr-tags.
-   Who is the target audience and what are scientific applications of this package?  
The goal of the concstats package is to offer a set of alternative and/or additional measures for researchers in social sciences and practitioners in institutions concerned with competition on a regular basis to better determine a given market structure and therefore reduce uncertainty with respect to a given market situation. 
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Some functions are already implemented in other R packages. The non-exhaustive summary below is by no means a description of each package.
The Herfindahl Hirschman Index can be found in the [hhi](https://joss.theoj.org/papers/10.21105/joss.00828) and the [divseg](https://github.com/christopherkenny/divseg) packages. While the hhi package has just one function, neither of both packages offer a finite sample correction.
However, almost none of these packages offer finite sample correction, with the exception of the [ineq](https://cran.r-project.org/package=ineq) package. Other functions are new implementations in R, e.g. Dominance Index, Palma ratio, Stenbacka Index, GRS measure, and the dual of the Herfindahl Hirschman Index.
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Not applicable
-  Any other questions or issues we should be aware of?:
Imports (dependencies) dplyr and readr, which are only used in data.R file

**Comment by mpadge** [comment]
@ropensci-review-bot check srr

**Comment by adamhsparks** [comment]
I think we can approve this and proceed with https://github.com/ropensci/software-review/issues/559. @mpadge, I'll reopen that issue and close this one so we can proceed.
