### ISSUE TITLE
openalexR: an R package to interface with the OpenAlex API

### ISSUE THREAD

**Issue by trangdata** [ropensci/software-review#560]
**Date accepted:** 2023-02-23

Submitting Author Name: Trang Le
Submitting Author Github Handle: @trangdata
Other Package Authors Github handles: (comma separated, delete if none) @massimoaria
Repository:  https://github.com/massimoaria/openalexR
Version submitted: 1.0.2
Submission type: Standard
Editor: @ldecicco-USGS
Reviewers: @BriannaLind, @pachadotdev
Due date for @BriannaLind: 2022-12-22
Due date for
Due date for @pachadotdev: 2023-01-24
Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: openalexR
Title: Getting Bibliographic Records from 'OpenAlex' Database Using 'DSL'
    API
Version: 1.0.2
Authors@R: c(
    person(given = "Massimo",
           family = "Aria",
           role = c("aut", "cre", "cph"),
           email = "aria@unina.it",
           comment = c(ORCID = "0000-0002-8517-9411")),
    person(given = "Corrado",
           family = "Cuccurullo",
           role = c("ctb"),
           email = "cuccurullocorrado@gmail.com",
           comment = c(ORCID = "0000-0002-7401-8575")),       
    person(given = "Trang",
           family = "Le",
           role = "aut",
           email = "grixor@gmail.com",
           comment = c(ORCID = "0000-0003-3737-6565"))
    )
Description: A set of tools to extract bibliographic content from
    'OpenAlex' database using API <https://docs.openalex.org/api/>.
License: MIT + file LICENSE
URL: https://github.com/massimoaria/openalexR,
    https://massimoaria.github.io/openalexR/
BugReports: https://github.com/massimoaria/openalexR/issues
Imports: 
    curl,
    httr,
    jsonlite,
    progress,
    tibble
Suggests: 
    testthat (>= 3.0.0),
    dplyr,
    knitr,
    rmarkdown,
    tidyr,
    purrr,
    ggplot2,
    covr
VignetteBuilder: 
    knitr
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.2.1
Config/testthat/edition: 3
Depends: 
    R (>= 2.10)
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences): The package interacts with the [OpenAlex API](https://docs.openalex.org/api). Similar packages in the same category are rcrossref and rotl.

-   Who is the target audience and what are scientific applications of this package?
Anyone who wants to work in R to interact with the OpenAlex API to acquire information on publications, authors, etc., including researchers in the field of bibliometrics, text mining, etc. We include several example analyses in our README.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Please see the detailed answer [here](https://github.com/ropensci/software-review/issues/557#issuecomment-1295068888) with a detailed table of comparison and examples of code differences. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Yes.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
https://github.com/ropensci/software-review/issues/557

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.
N/A. [Passed all checks](https://github.com/massimoaria/openalexR/issues/43).

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by annakrystalli** [comment]
Thanks for submitting @trangdata! 🎉

I'm in the process of assigning a handling editor. 

In the meantime, it appears there's a minor discrepancy in the version stated in the submission and pasted `DESCRIPTION` (1.0.1) and the actual current package version (1.0.2). Would you mind correcting and double-checking the pasted `DESCRIPTION` is up to date?

**Comment by trangdata** [comment]
Thanks so much @annakrystalli! 🌻 

> it appears there's a minor discrepancy in the version stated in the submission and pasted DESCRIPTION (1.0.1) and the actual current package version (1.0.2). 

Ah my bad. I forgot to update the version. Edited now.

**Comment by annakrystalli** [comment]
@ropensci-review-bot assign @ldecicco-USGS as editor

**Comment by ldecicco-USGS** [comment]
### Editor checks:

- [ ] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package. In particular,
    - [ ] Is the case for the package well made?
    - [ ] Is the reference index page clear (grouped by topic if necessary)?
    - [ ] Are vignettes readable, sufficiently detailed and not just perfunctory?
- [x] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap).
- [x] **Installation instructions:** Are installation instructions clear enough for human users?
- [x] **Tests**: If the package has some interactivity / HTTP / plot production etc. are the tests using [state-of-the-art tooling](https://devguide.ropensci.org/building.html#testing)?
- [ ] **Contributing information**: Is the documentation for contribution clear enough e.g. tokens for tests, playgrounds?
- [x] **License:** The package has a CRAN or OSI accepted license.
- [x] **Project management**: Are the issue and PR trackers in a good shape, e.g. are there outstanding bugs, is it clear when feature requests are meant to be tackled?
---

#### Editor comments

---

**Comment by ldecicco-USGS** [comment]
Hi @trangdata ! The package looks great! I'll try to find some editors as soon as possible

**Comment by trangdata** [comment]
Thank you so much @ldecicco-USGS. 🪴  And you mean reviewers right? 😅

**Comment by ldecicco-USGS** [comment]
😆Yup!

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @BriannaLind as reviewer

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @pachamaltese as reviewer

**Comment by BriannaLind** [comment]
Sorry for the delay team - I am diving into the review, will get back asap

**Comment by ldecicco-USGS** [comment]
It turns out I had assigned the review to a fake account that was impersonating the actual reviewer. I'm verifying he's still interested in reviewing. Sorry for the delay @trangdata !

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @pachadotdev as reviewer

**Comment by ldecicco-USGS** [comment]
Hi @pachadotdev and @BriannaLind , checking in to see if you could update us on an approximate timeline for when you'll be able to do the review.

**Comment by pachadotdev** [comment]
> Hi @pachadotdev and @BriannaLind , checking in to see if you could update us on an approximate timeline for when you'll be able to do the review.

hi
i finished the wilsonfreitas review last weekend
i can check this one on monday

**Comment by BriannaLind** [comment]
---
title: "review"
output: 
  rmarkdown::md_document:
    pandoc_args: [
      "--wrap=none"
    ]
---

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [ ] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [ ] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [ ] **Function Documentation:** for all exported functions
- [ ] **Examples:** (that run successfully locally) for all exported functions
- [ ] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing:

- [ ] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

**Comment by trangdata** [comment]
Hi @BriannaLind, first of all, thank you so much for spending your time reviewing the package. ❤️  ✨ I appreciate your comments!

> The first example executed fine, but instead of the nice display shown in the tutorial I had a bunch of (kind of ugly tabsets).

Ah this is interesting. I'm not sure what's going on with knitr, but you're right: we should separate oa_fetch() and the lines to display the output dataframe, so that the user can still see the output any other ways. I will update the readme. 

> The rest of the tutorial worked well, except several times I had to install packages that were not shown in the script but were necessary (this included ggraph, ggtext, and word cloud)

We had a few discussions regarding finding a balance between adding dependencies and making the user separately install things. We decided to keep the package minimal with few dependencies since most use cases won't require additional packages. When the user wants more specific analysis, e.g., snowballing, they would install ggraph separately. The examples were merely to show the variety of use cases for openalexR, so we didn't think attaching, for example, wordcloud, as an `Imports` was necessary. However, if you think these examples should be moved to a different place than readme, we will consider the suggestion!

Thanks again for the constructive feedback!

**Comment by pachadotdev** [comment]
hi @trangdata I; ll try to have my review done by Thu

**Comment by trangdata** [comment]
> I think its totally fine for users to install extra packages separately - I mostly was thinking of a 'new R user' who is going to want to really work through your examples and copy and paste the script ---that it would be nice to have library(XXX) above the code snippet to reduce frustration.

@BriannaLind ah gotcha! That makes sense. I'll keep this in mind when updating the readme.

>  ll try to have my review done by Thu

@pachadotdev Thank you!!! I'm excited to hear your feedback! 🙌🏽

**Comment by maurolepore** [comment]
Dear all,

My EiC rotation just started and I'm checking the status of open issues. I don't mean to intrude but to save you time. So while I'm here I note the second review might be ready soon. 

@pachadotdev, any updates?

**Comment by pachadotdev** [comment]
> Dear all,
> 
> My EiC rotation just started and I'm checking the status of open issues. I don't mean to intrude but to save you time. So while I'm here I note the second review might be ready soon.
> 
> @pachadotdev, any updates?

hi!
I can send it by tonight

**Comment by pachadotdev** [comment]
ready
how do I upload this?

**Comment by ldecicco-USGS** [comment]
Hi @pachadotdev - copy and paste the text in the comments. If there are any formatting issues I can take a look and see how to fix it up.

**Comment by pachadotdev** [comment]
## Package Review (1)

_Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide_

* **Briefly describe any working relationship you have (had) with the package authors.**

* [x]  As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).


#### Documentation

The package includes all the following forms of documentation:

 * [x]  **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README

* [x]  **Installation instructions:** for the development version of package and any non-standard dependencies in README

* [x]  **Vignette(s):** demonstrating major functionality that runs successfully locally

* [x]  **Function Documentation:** for all exported functions

* [x]  **Examples:** (that run successfully locally) for all exported functions

* [x]  **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).


#### Functionality

* [x]  **Installation:** Installation succeeds as documented.

* [x]  **Functionality:** Any functional claims of the software been confirmed.

* [x]  **Performance:** Any performance claims of the software been confirmed.

* [x]  **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.

* [x]  **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.


Estimated hours spent reviewing: 3.5

* [x]  Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.


### Review Comments

Sorry for the delay! The outputs look strange on Windows, but it works perfect on Ubuntu. After checking, it is because I had older pkgs on Windows.

**Comment by pachadotdev** [comment]
## Package Review

_Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide_

* **Briefly describe any working relationship you have (had) with the package authors.**

* [x]  As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).


#### Documentation

The package includes all the following forms of documentation:

 * [x]  **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README

* [x]  **Installation instructions:** for the development version of package and any non-standard dependencies in README

* [x]  **Vignette(s):** demonstrating major functionality that runs successfully locally

* [x]  **Function Documentation:** for all exported functions

* [x]  **Examples:** (that run successfully locally) for all exported functions

* [x]  **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).


#### Functionality

* [x]  **Installation:** Installation succeeds as documented.

* [x]  **Functionality:** Any functional claims of the software been confirmed.

* [x]  **Performance:** Any performance claims of the software been confirmed.

* [x]  **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.

* [x]  **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.


Estimated hours spent reviewing: 3.5

* [x]  Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.


### Review Comments

Sorry for the delay! The outputs look strange on Windows, but it works perfect on Ubuntu. After checking, it is because I had older pkgs on Windows.

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/560#issuecomment-1419932073 time 3.5

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/560#issuecomment-1409244254 time 6

**Comment by ldecicco-USGS** [comment]
Thanks @pachadotdev and @BriannaLind for the reviews! 

It seems like you both gave the package a test drive and things are looking pretty good. I don't see any major suggestions that were put forth yet to fix. Is that right? When I first looked at the package via the editor review, I also thought it was in pretty good shape! 

If that's correct, @pachadotdev and @BriannaLind , could you use the Approval template and verify:
https://devguide.ropensci.org/approval2template.html

**Comment by BriannaLind** [comment]
## Reviewer Response


#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: 6

**Comment by pachadotdev** [comment]
## Reviewer Response
#### Final approval (post-review)

    * [x]  **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**


Estimated hours spent reviewing: 3.5

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot approve openalexR

**Comment by ldecicco-USGS** [comment]
@trangdata Congratulations on the great package. Sorry the timing went a little longer than usual. The "bot" automatically closes this issue when the package gets approved, but we can still use the issue to communicate (or feel free to re-open it if you have any questions). 

Let me know if you have any questions on the instructions above. 

Once again, thanks for submitting to rOpenSci and great work! 🎉

**Comment by trangdata** [comment]
@ldecicco-USGS Thank you so much! ❤️  And huge thank you to the reviewers @pachadotdev and @BriannaLind for your valuable feedback! 🌈 

On the first TODO: @ldecicco-USGS Could you please add (or ask the bot to add) @massimoaria to ropensci so he could transfer "ownership" of the repository, please? The package currently lives at https://github.com/massimoaria/openalexR. Thank you!

**Comment by maelle** [comment]
I sent an invitation to the organization to @massimoaria. Please ping me when the repo is transferred so that I might give @massimoaria admin access back. 

Sorry for the clunkiness, it's only the second time in a short time we encounter this case https://github.com/ropensci-org/buffy/issues/98

**Comment by massimoaria** [comment]
Dear Maelle,
I just transferred the openalexR repository to the rOpenSci organization.

Thanks a lot
Massimo

⁣****************************************************
Dr. Massimo Aria
Full Professor in Statistics for Social Sciences
PhD in Computational Statistics
Bibliometrix R-package creator
K-Synth Academic Spin-Off co-founder
Department of Economics and Statistics
University of Naples Federico II
Monte S. Angelo, via Cinthia I-80126 Napoli, Italy
Room D-25, Sector D, 2nd Floor, Building 3
ph.  +39 081675187
fax  +39 081675009
mob. +39 392 1966384
email ***@***.***
https://www.massimoaria.com
https://www.bibliometrix.org
https://www.k-synth.unina.it
https://scholar.google.it/citations?user=Qu66YZQAAAAJ
https://orcid.org/0000-0002-8517-9411
http://www.researcherid.com/rid/O-7983-2015
https://www.researchgate.net/profile/Massimo_Aria
****************************************************​

**Comment by maelle** [comment]
Awesome, thanks! I've given you admin rights and write access to @trangdata but now that you have admin rights you can increase @trangdata's as needed.

**Comment by trangdata** [comment]
@massimoaria Any chance you could give me admin access so it's easier for me to make changes such as change the repo description url. Thank you! 🌱

**Comment by massimoaria** [comment]
Done!
