### ISSUE TITLE
R package birdsize - scope inquiry

### ISSUE THREAD

**Issue by diazrenata** [ropensci/software-review#561]
Submitting Author Name: Renata Diaz
Submitting Author Github Handle: @diazrenata
Repository:  https://www.github.com/diazrenata/birdsize
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: birdsize
Title: Estimate Avian Body Size Distributions
Version: 0.0.0.9000
Authors@R: 
    person("Renata", "Diaz", , "renata.diaz@weecology.org", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0003-0803-4734"))
Description: Generate estimated body size distributions for populations or communities of birds, given either species ID or species' mean body size. Designed to work naturally with the North American Breeding Bird Survey, or with any dataset of bird species, abundance, and/or mean size data.   
License: MIT + file LICENSE
URL: https://github.com/diazrenata/birdsize
BugReports: https://github.com/diazrenata/birdsize/issues
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.1
Suggests: 
    covr,
    ggplot2,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Depends: 
    R (>= 2.10)
Imports: 
    rlang,
    dplyr,
    magrittr,
    purrr,
    stats
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package automates a workflow (seen in the wild e.g. [here](https://doi.org/10.1111/j.1466-8238.2010.00576.x) and [here](https://doi.org/10.1101/2022.11.08.515659)) of generating estimates of body size and basal metabolic rate, from the individual to ecosystem level, for birds. I am not completely sure whether it's better described as "automating a workflow" or "standardizing a field/lab method", because it is automating - and therefore standardizing - a method used by empirical, computational ecologists to estimate body size and metabolic rate. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

N/A

-   Who is the target audience and what are scientific applications of this package?  

The target audience is ecologists/biodiversity scientists interested in studying the structure, function, and dynamics of bird populations and communities - specifically linking between abundances/population size and other dimensions of community function, like total biomass. Studying *size-based* and *abundance-based* properties of bird communities is key to understanding biodiversity and global change, but it is challenging for most ecologists because most survey methods do not collect size-related data. This package standardizes a computationally-intensive workaround for this challenge and makes it accessible to ecologists with relatively little computational training. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I have not encountered another R package that accomplishes this. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

I'm still working on some of the vignettes for this package, but I wanted to reach out now to check whether this package falls within scope for ROpenSci's review process (or if there are additional functions or documentation that would support that)! Thank you.

**Comment by annakrystalli** [comment]
Hello @diazrenata and many thanks for the pre-submission! The editorial team has concluded the package would be a good fit for rOpenSci review and the most appropriate category would be field and lab reproducibility tools.

One thing to note is that given the package contains external data, it would be appropriate to state the source in the `DESCRIPTION` file under authors using author type "dtc" which stands for "data contributor".

We look forward to your submission once documentation is complete!
