### ISSUE TITLE
remotePARTs code review inquiry

### ISSUE THREAD

**Issue by morrowcj** [ropensci/software-review#563]
Submitting Author Name: Clay Morrow
Submitting Author Github Handle: @morrowcj
Other Package Authors Github handles: @arives
Repository:  https://github.com/morrowcj/remotePARTS
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: remotePARTS
Title: Spatiotemporal Autoregression Analyses for Large Data Sets
Version: 1.0.0
Authors@R: 
    c(person(given = "Clay",
           family = "Morrow",
           role = c("aut", "cre"),
           email = "morrowcj@outlook.com",
           comment = c(ORCID = "0000-0002-3069-3296")),
      person(given = "Anthony",
           family = "Ives",
           role = c("aut"),
           email = "arives@wisc.edu",
           comment = c(ORCID = "0000-0001-9375-9523")))
Description: 
  These tools were created to test map-scale hypotheses about trends in large 
  remotely sensed data sets but any data with spatial and temporal variation
  can be analyzed. Tests are conducted using the PARTS method for analyzing spatially
  autocorrelated time series 
  (Ives et al., 2021: <doi:10.1016/j.rse.2021.112678>). 
  The method's unique approach can handle extremely large data sets that other 
  spatiotemporal models cannot, while still appropriately accounting for 
  spatial and temporal autocorrelation. This is done by partitioning the data 
  into smaller chunks, analyzing chunks separately and then combining the 
  separate analyses into a single, correlated test of the map-scale hypotheses.
URL: https://github.com/morrowcj/remotePARTS
BugReports: https://github.com/morrowcj/remotePARTS/issues
License: GPL (>= 3)
Encoding: UTF-8
LazyData: TRUE
RoxygenNote: 7.2.2
Depends: R (>= 4.0)
Imports: 
  stats,
  geosphere (>= 1.5.10), 
  Rcpp (>= 1.0.5), 
  CompQuadForm,
  foreach,
  parallel,
  iterators, 
  doParallel
Suggests: 
    dplyr (>= 1.0.0),
    data.table,
    knitr,
    rmarkdown,
    markdown,
    sqldf,
    devtools,
    ggplot2,
    reshape2
LinkingTo: Rcpp, RcppEigen
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [x] Spatial Analyses
	- [x] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package is an implementation of our spatial and spetiotemporal statistical method for hypothesis testing ([Ives et al 2021](https://www.sciencedirect.com/science/article/abs/pii/S0034425721003989)).

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

No. I just learned of rOpenSci.

-   Who is the target audience and what are scientific applications of this package?  

Scientists - primarily Ecologists and Earth Scientists.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No. While there are other packages that perform spatiotemporal analyses (e.g., [R-INLA](https://www.r-inla.org/what-is-inla) for a Bayesian approach), traditional methods cannot be feasibly applied to large datasets due to the computational power required to invert the $N \times N$ distance matrices (who's computational complexity scales with $N^3$) for $N$ spatial locations. This method uses a novel approach to reduce the complexity, allowing for hypothesis testing with incredibly large datasets. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes.

-  Any other questions or issues we should be aware of?:

This is my first full-fledged package. The main driver functions are written in `C++` (using the `Rcpp` framework), a language that I had never written code with before. When used (incorrectly) the package will occasionally crash R ("R Session Aborted") and I'm not sure why. I would like help fixing this problem and improving the package more generally.

**Comment by morrowcj** [comment]
I learned of rOpenSci while submitting a manuscript to Methods in Ecology and Evolution.

**Comment by annakrystalli** [comment]
Dear @morrowcj ,

Many thanks for your pre-submission enquiry!

The editorial team has concluded that the package definitely fits in our "stats" scope.

To confirm everything is okay however, before moving to full submission, we do suggest going through the formal process of documenting compliance with the stats standards.  You can call `@ropensci-review-bot check srr` in this issue to confirm documentation has been completed successfully. You can find [more details in our documentation](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr).

**Comment by maurolepore** [comment]
Dear @morrowcj,

Today starts my rotation as EiC meaning the role of @annakrystalli is now mine. Did you have the chance to follow up on the comment above?

**Comment by morrowcj** [comment]
Hello, @maurolepore: 

I have not yet had time to address this yet. It is on my list of tasks but I'm pretty swamped with other projects at the moment. I hope to get back to this by the end of next month. Sorry.

**Comment by maelle** [comment]
@morrowcj Hello, I'm the new current editor-in-chief :smile_cat: Any update?

**Comment by morrowcj** [comment]
@maelle, Yes I did mean JOSS. I did not know that! This is very useful information. Thank you.

**Comment by maelle** [comment]
@morrowcj did you have time to make any decision? :smile_cat:

**Comment by maelle** [comment]
@morrowcj friendly reminder :smile_cat:

**Comment by jhollist** [comment]
@morrowcj I am currently serving as the rOpenSci EIC and just wanted to check in on this.  Have you made a decision on this submission?  Thanks!

**Comment by morrowcj** [comment]
@jhollist, Yes, I think we decided, for now, that we don't want to proceed. Thank you!
