### ISSUE TITLE
waywiser: Ergonomic Methods for Assessing Spatial Models

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/software-review#565]
Submitting Author Name: Michael Mahoney
Submitting Author Github Handle: @mikemahoney218
Repository:  https://github.com/mikemahoney218/waywiser
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: waywiser
Title: Ergonomic Methods for Assessing Spatial Models
Version: 0.2.0.9000
Authors@R: c(
    person("Michael", "Mahoney", , "mike.mahoney.218@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0003-2402-304X")),
    person("Lucas", "Johnson", , "lucas.k.johnson03@gmail.com", role = c("ctb"),
           comment = c(ORCID = "0000-0002-7953-0260")),
    person("RStudio", role = c("cph", "fnd"))
  )
Description: Assessing predictive models of spatial data can be challenging, 
    both because these models are typically built for extrapolating outside the
    original region represented by training data and due to potential spatially
    structured errors, with "hot spots" of higher than expected error
    clustered geographically due to spatial structure in the underlying
    data. Methods are provided for assessing models fit to spatial data, 
    including approaches for measuring the spatial structure of model errors,
    assessing model predictions at multiple spatial scales, and evaluating where 
    predictions can be made safely. Methods are particularly useful for models 
    fit using the 'tidymodels' framework. Methods include Moran's I
    ('Moran' (1950) <doi:10.2307/2332142>), Geary's C 
    ('Geary' (1954) <doi:10.2307/2986645>), Getis-Ord's G
    ('Ord' and 'Getis' (1995) <doi:10.1111/j.1538-4632.1995.tb00912.x>),
    agreement coefficients from Ji and Gallo (2006) 
    (<doi: 10.14358/PERS.72.7.823>), agreement metrics from Willmott (1981)
    (<doi: 10.1080/02723646.1981.10642213>) and Willmott et al. (2012)
    (<doi: 10.1002/joc.2419), an implementation of the area of applicability 
    methodology from 'Meyer' and 'Pebesma' (2021) 
    (<doi:10.1111/2041-210X.13650>), and an implementation of
    multi-scale assessment as described in 'Riemann' et al. (2010)
    (<doi:10.1016/j.rse.2010.05.010>).
License: MIT + file LICENSE
URL: https://github.com/mikemahoney218/waywiser,
    https://mikemahoney218.github.io/waywiser/
BugReports: https://github.com/mikemahoney218/waywiser/issues
Depends: 
    R (>= 3.6)
Imports: 
    dplyr,
    fields,
    FNN,
    glue,
    hardhat,
    Matrix,
    purrr,
    rlang,
    rsample,
    sf (>= 1.0-0),
    spdep (>= 1.1-9),
    stats,
    tibble,
    tidyselect,
    yardstick
Suggests: 
    applicable,
    caret,
    CAST,
    covr,
    ggplot2,
    knitr,
    modeldata,
    recipes,
    rmarkdown,
    spatialsample,
    spelling,
    testthat (>= 3.0.0),
    tidymodels,
    tidyr,
    tigris,
    vip,
    whisker,
    withr
Config/testthat/edition: 3
Config/testthat/parallel: true
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE, roclets = c("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.2.3
Language: en-US
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [x] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

waywiser is a toolkit for assessing spatial models, providing a standardized, ergonomic interface to use multiple pre-existing assessment techniques, with a particular focus on integrating with and feeling similar to the tidymodels ecosystem. While many of these techniques are not exclusively spatial, they all originally emerge from spatial modeling research.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Yes!

-   Who is the target audience and what are scientific applications of this package?  

Anyone fitting models to spatial data, particularly (but not exclusively) people working within the tidymodels ecosystem. This includes a number of domains, and we've already been using it in our modeling practice.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Individual pieces of this package have been implemented elsewhere:

+ Yardstick functions with neighborhood components are simple wrappers around spdep
+ Area of applicability was first implemented in CAST

I am not aware of implementations of:

+ The yardstick functions _without_ neighborhood components
+ Multi-scale model assessment

That said, the primary goal of this package is to provide a standardized interface around all of these tasks, making the user interface as consistent as possible. This also allows for greater integration with tidymodels. Additionally, as discussed in `?ww_area_of_applicability`, there are some differences in the AOA implementation in this package versus in CAST.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

**Comment by annakrystalli** [comment]
@ropensci-review-bot check srr

**Comment by annakrystalli** [comment]
Hello @mikemahoney218 and many thanks for the pre-submission.

Many of the editors are already on a holiday break so we will get back to you with feedback in the New Year.

Enjoy your holidays!

**Comment by mikemahoney218** [comment]
Happy holidays @annakrystalli :smile:

**Comment by mikemahoney218** [comment]
Hi @annakrystalli ! Hope you had a good holiday period. Do you happen to know when I can expect to hear back on this submission? Not trying to rush anyone or interrupt any vacations, I'm just planning out my workload for the next few weeks :smile:

**Comment by annakrystalli** [comment]
Hello @mikemahoney218 ,

No worries. I can confirm we  are happy to accept the package for review so feel free to make a proper submission.
