### ISSUE TITLE
Presubmission of the AICcPermanova R Package

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [ropensci/software-review#585]
Submitting Author Name: Derek Corcoran
Submitting Author Github Handle: @derek-corcoran-barrios

Repository:  https://github.com/Sustainscapes/AICcPerm
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: AICcPermanova
Title: Model Selection of PERMANOVA Models Using AICc
Version: 0.0.3
Authors@R: 
    person(given = "Derek", family ="Corcoran",  
    email = "derek.corcoran.barrios@gmail.com", role = c("aut", "cre"))
Description: Provides tools for model selection and model averaging of PerMANOVA 
    models using Akaike Information Criterion corrected for small sample sizes 
    (AICc) and Information Theoretic criteria principles. The package is built 
    around the PERMANOVA analysis from the 'vegan' package and provides a 
    streamlined workflow for generating and comparing models, obtaining model 
    weights, and summarizing results using model averaging approaches.  The 
    methods implemented in this package are based on the practical information-
    theoretic approach described by Burnham, K. P. and Anderson, D. R. (2002) 
    (<doi:10.1007/b97636>).
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Imports: 
    broom,
    car,
    data.table,
    doParallel,
    dplyr,
    foreach,
    furrr,
    future,
    parallel,
    stats,
    stringr,
    tidyr,
    vegan
URL: https://github.com/Sustainscapes/AICcPerm,
    https://sustainscapes.github.io/AICcPerm/
BugReports: https://github.com/Sustainscapes/AICcPerm/issues
Suggests: 
    covr,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [x] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
The package I build is built to generate a clear workflow for community analysis, specifically for model selection in Permanova, which are a form of regression 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not yet, I am looking into doing it right now, I expect to have it done by the end of this week

-   Who is the target audience and what are scientific applications of this package?  

Community ecologist in general, I see it as very useful for microbiologists working with dna barcoding taxonomy, botanist that do plots for community analysis, etc.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

This package is based on the vegan package, so that package has the analysis made here, however it does not have the model selection capabilities.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable

-  Any other questions or issues we should be aware of?:

There are 2 issues largely for me. I would like to know if the categories I am choosing for the package are the right ones, and the second is that I would like this package to be in either the Methods in ecology and evolution or The Journal of Open Source Software, however when I am asked to check that in the last part of the submission, I am not completely done with the writing of the article, would this be needed to check those boxes?

**Comment by maurolepore** [comment]
Dear @derek-corcoran-barrios, thanks a lot for your pre-submission and for your efforts making the package pass all our checks.

I'll see this carefully and come back to you ASAP.

**Comment by derek-corcoran-barrios** [comment]
Thanks a lot Mauro, I hope you find the package useful 😊

Cheers

**Comment by maurolepore** [comment]
Dear @derek-corcoran-barrios 

Sorry for the delay. 
 
Answering your questions:

1. Does the package do statistics itself of rather wrap other packages that do the stats? If it doesn't do stats itself then the standard (non-stats) category "workflow automation" seems like a good fit.

2. In the submission template I see "Although not required, we strongly recommend having a full manuscript prepared when you submit here." Because it's not required, I think it's OK for you to check that box, maybe with a comment on when you think it'll be ready?

**Comment by derek-corcoran-barrios** [comment]
1. This sound great to me, just to answer your question most of the
   stats except for the AICc is calculated by vegan or CAR, so I guess
   workflow automation fits
   2. I will do that

How should I proceed from here? Do I make a new issue?

Cheers

Derek

**Comment by maurolepore** [comment]
Great. 

Yes, please go ahead and open a new issue -- this time as a full submission (not pre-submission) and remember to fill the space where you're asked to point to the pre-submission.

**Comment by derek-corcoran-barrios** [comment]
Thanks I will do that

Cheers
