### ISSUE TITLE
Access to goldilocks package - used to check balance prior to randomizng a cluster randomized trial.

### ISSUE THREAD

**Issue by nzgwynn** [ropensci/software-review#586]
Submitting Author Name: gwynn gebeyehu
Submitting Author Github Handle: @nzgwynn
Repository:  https://github.com/nzgwynn/Goldilocks_package
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: GoldilocksPackage
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: person(given = "gwynn", family = "gebeyehu", email = "nzgwynn@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-1185-8446"))
Author: gwynn sturdevant [aut, cre],
Maintainer: gwynn gebeyehu <nzgwynn@gmail.com>
Description: The Goldilocks package implements the theoretical permutation
    approach developed in this article is an interactive Shiny application. 
    This package allows researchers to randomize cluster randomized trials with 
    confidence by visualizing the distribution of average differences in the 
    treatment and control arms in practice randomizations. The application also 
    allows researchers to randomize a trial and download the resultant 
    randomizations. The Goldilocks application is deployed on the web put some 
    researchers may prefer an R package.
URL: https://www.sciencedirect.com/science/article/pii/S245186542100048X, https://CRAN.R-project.org/package=shiny, https://bit.ly/GoldilocksApp
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.1
Imports: 
    designmatch,
    GGally,
    ggplot2,
    grid,
    lattice,
    random,
    readxl,
    rmarkdown,
    shiny,
    stats
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
This package is a Shiny application that allows researchers to randomizes cluster randomized control trials with confidence.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?  This packages allows anyone randomizing clusters (schools, hospitals, nursing homes, etc...) to randomize with some confidence that balance will be achieved in chosen variables. It is a GUI that allows them to upload data, practice randomizing, then randomize.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? I do not know of any other packages that do this. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)? There is no personal data anywhere in this package.

-  Any other questions or issues we should be aware of?: Thank you for the time you are taking to look at this package.

**Comment by maurolepore** [comment]
@ropensci-review-bot check package

**Comment by maurolepore** [comment]
Dear @nzgwynn,

Thanks for your pre-submission.

I discussed with the editorial boar and unfortunately we consider it out-of-scope for our category "scientific software wrappers":

> Packages that wrap non-R utility programs used for scientific research
> -- https://devguide.ropensci.org/policies.html#package-categories

That category focuses on R wrappers of non-R utilities, but on the repo of this pre-submission we see 100% R code.

We might consider it a "workflow" package under our statistical-software peer-review process. That category has potential but isn't yet developed. However, @noamross would be willing to pilot it if it meets the [guidelines for statistical software](https://stats-devguide.ropensci.org/index.html). That could take a while, so I'll close this issue now but feel free to open a new pre-submission when you are ready and please mention this issue in that issue.

**Comment by maurolepore** [comment]
@ropensci-review-bot out of scope

**Comment by nzgwynn** [comment]
Thank you for your response!
