### ISSUE TITLE
Presubmission Inquiry: Zoomerjoin

### ISSUE THREAD

**Issue by beniaminogreen** [ropensci/software-review#588]
Submitting Author Name: Beniamino Green
Submitting Author Github Handle: @beniaminogreen
Repository:  https://github.com/beniaminogreen/zoomerjoin
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: zoomerjoin
Title: Insanely-Fast Fuzzy Joins
Version: 0.0.0.9000
Authors@R:
    person("Beniamino", "Green", , "beniamino.green@yale.edu", role = c("aut", "cre")
           )
Description: Zoomerjoin empowers users to fuzzily-merge dataframes with
millions or tens of millions of rows in minutes with minimal memory usage.  The
package uses the MinHash algorithm invented by Broder (1997)
<doi:10.1109/SEQUEN.1997.666900> to avoid having to compare every pair of
records in each data set, resulting in fuzzy-merges that finish in linear
time.  As a secondary feature, the package also wraps the rust kdtree crate
to provide euclidian-distance joins that finish in linearithmic time.
License: GPL (>= 3)
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.1
SystemRequirements: Cargo (>= 1.56) (Rust's package manager), rustc
Imports:
    dplyr,
    tibble
Suggests:
    babynames,
    fuzzyjoin,
    stringdist,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0),
    tidyverse,
    microbenchmark,
    arrow,
    covr
Config/testthat/edition: 3
URL: https://beniaminogreen.github.io/zoomerjoin/
BugReports: https://github.com/beniaminogreen/zoomerjoin/issues/
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
        - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

Unsure of this:

Data munging: This package helps users join massive tables on a messy identifying field. This is setting / data type is common or even the modal case when working with administrative data,  text from OCR systems or other social science data. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not a statistical package. 

-   Who is the target audience and what are scientific applications of this package?  

Researchers who work with large administrative, OCR, or genomics data, or data from other domains where transcription or recording errors are common.  Users interested in large-scale probabilistic merges, or more sophisticated fuzzy-merge methods can also use the Locality Sensitive Hash (LSH) algorithms provided in this package as a form of preprocessing to save computation by using the package to identify potential matches and using a classifier to make the final match / non-match classification. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The excellent and renowned [fuzzyjoin](https://github.com/dgrtwo/fuzzyjoin) provides many excellent and tidy fuzzy-merging capabilities, but these do not scale to large datasets as they compare all pairs of potential matches between two datasets. See [here](https://github.com/dgrtwo/fuzzyjoin/issues/51) for a representative thread detailing using fuzzyjoin with a larger dataset, and [here](https://beniaminogreen.github.io/zoomerjoin/articles/benchmarks.html) showing a benchmark comparison of `fuzzyjoin` and `zoomerjoin` for small datasets. 

The superlative [textreuse](https://github.com/ropensci/textreuse)  is similar in that it implements a similar Locality-Sensitive Hash, but it does not offer a joining functionality and the implementation is mostly in R  and might not scale well to datasets with rows in the hundreds of millions. 

I try to synthesize the some of functionality of both packages, providing tidy joins that are backed by a performant, multithreaded Locality-Sensitive Hash algorithm written in Rust. This package combines the functionality of the tidy, dplyr-style fuzzyjoins provided by `fuzzyjoin` with the performance offered by the same Locality-Sensitive Hashing algorithm used in `textreuse.`  The core of the package is written in sleek, performant Rust, which makes the package suitable for datasets with hundreds of millions of observations. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable - does not involve human subjects.

-  Any other questions or issues we should be aware of?

Thanks for taking the time to consider this pre-submission!

**Comment by maurolepore** [comment]
Thanks @beniaminogreen for this pre-submission. The package seems impressive. I'll run a few checks now and explore if it's in the scope of our current rOpenSci categories. I may need a few days to discuss with other editors.

**Comment by maurolepore** [comment]
@ropensci-review-bot check package

**Comment by beniaminogreen** [comment]
> Thanks @beniaminogreen for this pre-submission. The package seems impressive. I'll run a few checks now and explore if it's in the scope of our current rOpenSci categories. I may need a few days to discuss with other editors.

Thanks for having a look at the package!

**Comment by maurolepore** [comment]
Thanks @beniaminogreen for your patience. 

I discussed with the editor's board. Unfortunately we believe this package is out of scope for our current categories. The "data-munging" category in particular fits packages that handle less structured data.

I'm sure this package will be super useful for many users (including myself) and I look forward to seeing it on CRAN. 

Thanks again for sharing it with rOpenSci and please do think of us again next time you have a package that you think might fit in our scope.

All the best!

**Comment by maurolepore** [comment]
@ropensci-review-bot out of scope

**Comment by beniaminogreen** [comment]
> Thanks @beniaminogreen for your patience.
> 
> I discussed with the editor's board. Unfortunately we believe this package is out of scope for our current categories. The "data-munging" category in particular fits packages that handle less structured data.
> 
> I'm sure this package will be super useful for many users (including myself) and I look forward to seeing it on CRAN.
> 
> Thanks again for sharing it with rOpenSci and please do think of us again next time you have a package that you think might fit in our scope.
> 
> All the best!

No worries. Thanks for taking the time to look over the package, and for your kind words about it. 

Best, 
Ben
