### ISSUE TITLE
AICcPermanova: Model Selection of PERMANOVA Models Using AICc

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [ropensci/software-review#589]
Submitting Author Name: Derek Corcoran
Submitting Author Github Handle: @derek-corcoran-barrios
Repository:   https://github.com/Sustainscapes/AICcPerm
Version submitted: 0.0.3
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: AICcPermanova
Title: Model Selection of PERMANOVA Models Using AICc
Version: 0.0.3
Authors@R: 
    person(given = "Derek", family ="Corcoran",  
    email = "derek.corcoran.barrios@gmail.com", role = c("aut", "cre"))
Description: Provides tools for model selection and model averaging of PerMANOVA 
    models using Akaike Information Criterion corrected for small sample sizes 
    (AICc) and Information Theoretic criteria principles. The package is built 
    around the PERMANOVA analysis from the 'vegan' package and provides a 
    streamlined workflow for generating and comparing models, obtaining model 
    weights, and summarizing results using model averaging approaches.  The 
    methods implemented in this package are based on the practical information-
    theoretic approach described by Burnham, K. P. and Anderson, D. R. (2002) 
    (<doi:10.1007/b97636>).
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.2.3
Imports: 
    broom,
    car,
    data.table,
    doParallel,
    dplyr,
    foreach,
    furrr,
    future,
    parallel,
    stats,
    stringr,
    tidyr,
    vegan
URL: https://github.com/Sustainscapes/AICcPerm,
    https://sustainscapes.github.io/AICcPerm/
BugReports: https://github.com/Sustainscapes/AICcPerm/issues
Suggests: 
    covr,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The package I build is built to generate a clear workflow for community analysis, specifically for model selection in Permanova,

-   Who is the target audience and what are scientific applications of this package?
Community ecologist in general, I see it as very useful for microbiologists working with dna barcoding taxonomy, botanist that do plots for community analysis, etc.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
- 
This package is based on the vegan package, so that package has the analysis made here, however it does not have the model selection capabilities. MuMIn does model selection but it cant deal with the PERMANOVA

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/software-review/issues/585

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [x] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)
The manuscript is probably 3 weeks away from finished, but it is almost there

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by derek-corcoran-barrios** [comment]
I dont see any of this issues, they seem fine here and in the presubmission

**Comment by maurolepore** [comment]
I've seen that message in other submissions, then the bot continued to check the pacakge. So I'll try again.

**Comment by maurolepore** [comment]
@ropensci-review-bot check package

**Comment by maurolepore** [comment]
FYI I'll start now the search for a handling editor.

**Comment by maurolepore** [comment]
Dear @derek-corcoran-barrios, 

Sorry for misleading you. 

Two of our stats experts think this should be a stats submission and the category you originally suggested "regression and supervised learning" seems like a good fit.

Unfortunately the template is different so I'll close this issue now and ask you to please open a new issue choosing ["Submit statistical software for review"](https://github.com/ropensci/software-review/issues/new?assignees=&labels=&template=F-submit-statistical-software-for-review.md).
 
Also FYI my EiC rotation is coming to an end soon so likely you'll continue with @maelle.

All the best in the process.

**Comment by derek-corcoran-barrios** [comment]
Thanks Mauro, One more question should I only put one category, so
r"egression and supervised learning" or should I add "workflow automation"
ass well?

Cheers

Derek

**Comment by maurolepore** [comment]
I think it'll be enough with "regression and supervised learning". I'll point @maelle to the editor's thread where that category was suggested.
