### ISSUE TITLE
conrad: Client for the Microsoft Cognitive Services Text to Speech REST API

### ISSUE THREAD

**Issue by howardbaek** [ropensci/software-review#594]
Submitting Author Name: Howard Baek
Submitting Author Github Handle: @howardbaek
Other Package Authors Github handles: (comma separated, delete if none) @muschellij2
Repository:  https://github.com/fhdsl/conrad
Version submitted: 1.0.0
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: conrad
Title: Client for the Microsoft Cognitive Services Text to Speech REST API
Version: 1.0.0
Authors@R: c( 
    person("Howard", "Baek", email = "howardbaek.fh@gmail.com", role = c("aut", "cre", "cph"),
           comment = c(ORCID = "0009-0000-8942-1618")),
    person("John", "Muschelli", email = "muschellij2@gmail.com", role = c("aut"),
           comment = c(ORCID = "0009-0000-8942-1618"))
           )
Description: Convert text into synthesized speech and get a list of supported voices for a region. 
    The Text to Speech REST API supports neural text to speech voices, which support specific languages and dialects 
    that are identified by locale. 
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Depends: 
    R (>= 2.10)
LazyData: true
Imports: 
    httr2,
    jsonlite,
    magrittr
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [x] data extraction
	- [ ] data munging
	- [ ] data deposition
         - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

conrad uses Microsoft's Text to speech REST API to generate audio files as output, data frame of available voices to use in speech synthesis (text-to-speech), and HTTP responses from requests to the API. Also, googleLanguageR label itself as data extraction: https://github.com/ropensci/software-review/issues/127 and this package is very similar in terms of calling text-to-speech APIs.

-   Who is the target audience and what are scientific applications of this package?

The target audience is anyone who wants to convert text into speech using Microsoft's Text-to-Speech API. 

The scientific application would be any researchers or educators looking to generate automated videos (online courses) using text-to-speech with conrad. conrad is one of the backend R packages to [text2speech](https://github.com/jhudsl/text2speech), a R package which consolidates various text-to-speech engines, including Amazon Polly, Coqui TTS, Google Cloud Text-to-Speech API, and Microsoft Cognitive Services Text to Speech REST API. We will submit text2speech for software review later. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are other R packages that are clients to  Amazon Polly, Coqui TTS, and Google Cloud Text-to-Speech API. The difference is that conrad is a client to the Microsoft Cognitive Services Text to Speech REST API. This package is a reboot of [mscstts](https://github.com/jhudsl/mscstts). Differences are explained in [Major differences to mscstts](https://github.com/fhdsl/conrad#major-differences-to-mscstts)

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ ] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by howardbaek** [comment]
I ran `pkgcheck()` and found alot of errors in this package. I'll resubmit after addressing them.

**Comment by maelle** [comment]
@howardbaek why did you close this issue? :slightly_smiling_face: thanks for your interest in software review!
