### ISSUE TITLE
Presubmission Inquiry: audrey (Client for the OpenAI's 'Whisper' Model)

### ISSUE THREAD

**Issue by howardbaek** [ropensci/software-review#597]
Submitting Author Name: Howard Baek
Submitting Author Github Handle: @howardbaek
Repository:  https://github.com/howardbaek/audrey
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: audrey
Title: Client for the OpenAI's 'Whisper' Model
Version: 0.0.0.9000
Authors@R: 
    person("Howard", "Baek", , "howardbaek.fh@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0009-0000-8942-1618"))
Description: Perform speech recognition by converting spoken language from audio file into 
     written text in its original language. Also, translate audio spoken in a non-English language
     into English.
License: MIT + file LICENSE
URL: https://github.com/howardbaek/audrey
BugReports: https://github.com/howardbaek/audrey/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
SystemRequirements: Whisper. To install, follow the instructions provided in this link : <https://github.com/openai/whisper#setup> 
Imports: 
    cli,
    tools,
    withr
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: knitr
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package interacts with the [OpenAI Whisper](https://github.com/openai/whisper) by running `system2()`. Not sure if this qualifies as scientific software wrapper or data retrieval?

-   Who is the target audience and what are scientific applications of this package?  

Anyone who wishes to use OpenAI's Whisper model to perform automatic speech recognition and translation into English. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

This package, https://github.com/bnosac/audio.whisper, does the same thing and is an Rcpp wrapper around the [whisper.cpp C++ library](https://github.com/ggerganov/whisper.cpp). This package is based on a CPU-only inference engine written in C++11, so no external software is needed and you can directly install and use it from R.

My package does require external software to be installed (Whisper + ffmpeg), but doesn't have any Rcpp and simply uses `system2()` to access OpenAI's Whisper model.

-  Any other questions or issues we should be aware of?:

`pkgcheck()` keeps on telling me to "avoid long code lines, it is bad for readability.", but I'm not sure how to make code lines shorter automatically. 

Also, I'm not sure how to fix these `pkgcheck()` messages:

 
![Screenshot 2023-07-16 at 8 44 11 PM](https://github.com/ropensci/software-review/assets/50791792/1711114a-0d2c-4d89-8b7e-db041d628244)

**Comment by maelle** [comment]
:wave: @howardbaek, thanks for your submission!

We're wondering about overlap (https://devguide.ropensci.org/policies.html#overlap) with the audio.whisper package, that seems easier to install since it doesn't require any external software (https://ropensci.org/blog/2021/09/13/system-calls-r-package/#downsides-of-system-commands). Could you please comment on that?

**Comment by howardbaek** [comment]
I didn't know about those policies. I can close this issue.
