### ISSUE TITLE
Presubmission Inquiry: GLMMcosinor

### ISSUE THREAD

**Issue by RWParsons** [ropensci/software-review#601]
Submitting Author Name: Rex Parsons
Submitting Author Github Handle: @RWParsons
Other Package Authors Github handles: (comma separated, delete if none) @oliverjayasinghe, @nicolemwhite
Repository:  https://github.com/RWParsons/GLMMcosinor
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: GLMMcosinor
Title: Fit a cosinor model using a generalised mixed modelling framework
Version: 0.0.9000
Authors@R: c(
    person("Rex", "Parsons", , "rex.parsons94@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-6053-8174")),
    person("Oliver", "Jayasinghe", role = "aut"),
    person("Nicole", "White", role = "aut",
           comment = c(ORCID = "0000-0002-9292-0773"))
  )
Description: Fit the cosinor model using the glmmTMB framework, allowing
    for a wide range of link functions and capacity of heirachical
    structures.
License: GPL (>= 3)
URL: https://github.com/RWParsons/GLMMcosinor,
    https://rwparsons.github.io/GLMMcosinor/
BugReports: https://github.com/RWParsons/GLMMcosinor/issues
Imports:
    assertthat,
    cowplot,
    ggforce,
    ggplot2,
    glmmTMB,
    lme4,
    rlang,
    scales,
    stats
Suggests:
    covr,
    dplyr,
    DT,
    flextable,
    ftExtra,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0),
    vdiffr,
    withr
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd",
    "srr::srr_stats_roclet"))
RoxygenNote: 7.2.3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
     - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [x] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

GLMMcosinor is a package that makes fitting (cosinor) regression models easy and via the glmmTMB framework.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Yes, the standards are included in the relevant Roxygen skeletons.

-   Who is the target audience and what are scientific applications of this package?  

People analysing rhythmic/circular data - for example, circadian biologists.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

While there are a few existing R packages that help the user fit a cosinor or nonlinear model to circular data, none in R (but two in python but are limited to count data-related link functions) use a generalised framework, only one (`{circacompare}`, but fits a nonlinear model, not a cosinor model) allows the specification of a mixed model, very few allow the user to specify other covariates in the model or interaction terms on the cosinor components, and none include all of these features together. `GLMMcosinor` achieves this by using glmmTMB under the hood rather than `lm()` (as, for example, `{cosinor}` does). We have also developed functions to visualise the cosinor components in either polar or time series plots.

The README of the repository shows a table comparing available softare.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

NA

-  Any other questions or issues we should be aware of?:

NA

**Comment by noamross** [comment]
Thank you for your presubmission @RWParsons! Yes, this package makes sense as a submission under the Statistical Regression and Supervised Learning category. We welcome a full submissiom.
