### ISSUE TITLE
Package ‘photosearcher’ is not available for this version of R

### ISSUE THREAD

**Issue by ArthurFilipeDS** [ropensci/software-review#602]
I use the latest version of R (4.3.1), but when installing the package, the following message appeared:

```
install.packages("photosearcher", lib="C:/Program Files/R/R - 4.3.1/library")

Warning in install.packages:
  package ‘photosearcher’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```
Even using older versions of R I was unable to install the package. How can I solve this problem?

**Comment by mpadge** [comment]
photosearcher is not on CRAN. Install instructions are given at https://ropensci.r-universe.dev/photosearcher. If you've got any questions about package usage, please ask on the main package repo at https://github.com/ropensci/photosearcher
