### ISSUE TITLE
Submission: rio

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/software-review#605]
Submitting Author Name: Chung-hong Chan
Submitting Author Github Handle: @chainsawriot
Other Package Authors Github handles: (comma separated, delete if none) @leeper
Repository:  https://github.com/chainsawriot/rio
Version submitted: 0.5.30
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rio
Type: Package
Title: A Swiss-Army Knife for Data I/O
Version: 0.5.30
Authors@R: c(person("Jason", "Becker", role = "ctb", email = "jason@jbecker.co"),
             person("Chung-hong", "Chan", role = c("aut", "cre"), email = "chainsawtiney@gmail.com",
	     	     comment = c(ORCID = "0000-0002-6232-7530")),
             person("Geoffrey CH", "Chan", role = "ctb", email = "gefchchan@gmail.com"),
             person("Thomas J.", "Leeper",
                    role = "aut", 
                    email = "thosjleeper@gmail.com",
                    comment = c(ORCID = "0000-0003-4097-6326")),
             person("Christopher", "Gandrud", role = "ctb"),
             person("Andrew", "MacDonald", role = "ctb"),
             person("Ista", "Zahn", role = "ctb"),
             person("Stanislaus", "Stadlmann", role = "ctb"),
             person("Ruaridh", "Williamson", role = "ctb", email = "ruaridh.williamson@gmail.com"),
             person("Patrick", "Kennedy", role = "ctb"),
             person("Ryan", "Price", email = "ryapric@gmail.com", role = "ctb"),
             person("Trevor L", "Davis", email = "trevor.l.davis@gmail.com", role = "ctb"),
             person("Nathan", "Day", email = "nathancday@gmail.com", role = "ctb"),
             person("Bill", "Denney",
                    email="wdenney@humanpredictions.com",
                    role="ctb",
                    comment=c(ORCID="0000-0002-5759-428X")),
             person("Alex", "Bokov", email = "alex.bokov@gmail.com", role = "ctb",
                    comment=c(ORCID="0000-0002-0511-9815"))
             )
Description: Streamlined data import and export by making assumptions that
    the user is probably willing to make: 'import()' and 'export()' determine
    the data structure from the file extension, reasonable defaults are used for
    data import and export (e.g., 'stringsAsFactors=FALSE'), web-based import is
    natively supported (including from SSL/HTTPS), compressed files can be read
    directly without explicit decompression, and fast import packages are used where
    appropriate. An additional convenience function, 'convert()', provides a simple
    method for converting between file types.
URL: https://github.com/chainsawriot/rio
BugReports: https://github.com/chainsawriot/rio/issues
Depends:
    R (>= 3.6)
Imports:
    tools,
    stats,
    utils,
    foreign,
    haven (>= 1.1.2),
    curl (>= 0.6),
    data.table (>= 1.9.8),
    readxl (>= 0.1.1),
    openxlsx,
    tibble
Suggests:
    datasets,
    bit64,
    testthat,
    knitr,
    magrittr,
    arrow,
    clipr,
    feather,
    fst,
    hexView,
    jsonlite,
    pzfx,
    readODS (>= 1.6.4),
    readr,
    rmarkdown,
    rmatio,
    xml2 (>= 1.2.0),
    yaml
License: GPL-2
VignetteBuilder: knitr
Encoding: UTF-8
RoxygenNote: 7.2.3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [X] data retrieval
	- [X] data extraction
	- [ ] data munging
	- [X] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

This package is for loading and saving data from either files or urls.

-   Who is the target audience and what are scientific applications of this package?

Probably all scientific disciplines that involve dealing with data files.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

As far as I know there are four: reader (not readr), io, ImportExport, and SchemaOnRead. The current package is probably the most used.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

No. I am sorry.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [X] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [X] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [X] does not violate the Terms of Service of any service it interacts with.
- [X] has a CRAN and OSI accepted license.
- [X] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [X] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [X] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [X] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [X] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by chainsawriot** [comment]
@ropensci-review-bot help

**Comment by chainsawriot** [comment]
@ropensci-review-bot check package

**Comment by noamross** [comment]
Thank you for this submission @chainsawriot! I realize the last response from the bot is an error, as a badge should not be generated or checked for until after an editor has approved moving forward with the process.

I believe *rio* is out of scope for us.  Per the package descriptions in our [Aims and Scope](https://devguide.ropensci.org/policies.html#aims-and-scope), retrieval, extraction, or munging categories should be specific to "data sources / topics", "aid in retrieving data from unstructured sources such as text, images and PDFs, as well as parsing scientific data types and outputs from scientific equipment", or "focus on tools for handling data in specific scientific formats generated from scientific workflows or exported from scientific instruments."  The reason for this is that it is hard to have objective reviews for where we draw on relevant field expertise with highly general/swiss army tools. The latter are more likely to have a lot of users that provide feedback so need the review process less. I would recommend [JOSS](https://joss.theoj.org/) as a venue for reviewing and publishing *rio*.

**Comment by maelle** [comment]
@ropensci-review-bot help

**Comment by noamross** [comment]
@ropensci-review-bot out of scope
