### ISSUE TITLE
GoldilocksTwoArm

### ISSUE THREAD

**Issue by nzgwynn** [ropensci/software-review#607]
Submitting Author Name: gwynn gebeyehu
Submitting Author Github Handle: @nzgwynn
Repository:  https://github.com/nzgwynn/goldilocksTwoArm
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: goldilocksTwoArm
Title: Randomize cluster trials with confidence
Version: 0.0.0.9000
Authors@R: person(given = "gwynn", family = "gebeyehu", email = "nzgwynn@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-1185-8446"))
Description: The goldilocksTwoArm package implements the theoretical permutation
    approach developed in this article is an interactive Shiny application. 
    This package allows researchers to randomize cluster randomized trials with 
    confidence by visualizing the distribution of average differences in the 
    treatment and control arms in practice randomizations. The application also 
    allows researchers to randomize a trial and download the resultant 
    randomizations. The Goldilocks application is deployed on the web put some 
    researchers may prefer an R package.
URL: https://github.com/nzgwynn/goldilocksTwoArm, https://www.sciencedirect.com/science/article/pii/S245186542100048X, https://bit.ly/GoldilocksApp
BugReports: https://github.com/nzgwynn/goldilocksTwoArm/issues
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.1
Imports: 
    designmatch,
    GGally,
    ggplot2,
    random,
    readxl,
    rmarkdown,
    shiny,
    stats,
    Rglpk
Suggests: 
    testthat (>= 3.0.0),
    grid,
    lattice,
    knitr
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
This package is a Shiny application that allows researchers to randomizes cluster randomized control trials with confidence. It was also suggested [here](https://github.com/ropensci/software-review/issues/586)

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?   This packages allows anyone randomizing clusters (schools, hospitals, nursing homes, etc...) to randomize with some confidence that balance will be achieved in chosen variables. It is a GUI that allows them to upload data, practice randomizing, then randomize.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? I know of no other packages that do this.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)? There is no personal data anywhere in this package.

-  Any other questions or issues we should be aware of?: Thank you for the time you are taking to look at this package.

**Comment by noamross** [comment]
Thank you for your inquiry @nzgwynn? Can you clarify how this is different than the last submission? As the editor wrote in your last submission (https://github.com/ropensci/software-review/issues/587#issuecomment-1512326297), we consider this to fall under the _statistical_ package.  While we don't have a workflow subcategory there yet, we could pilot it if the package met the statistical standards under the "General" category and relevant standards under the "EDA" category: https://stats-devguide.ropensci.org/standards.html

**Comment by nzgwynn** [comment]
Thank you, I was trying to find that comment, I suppose the best thing to do is resubmit? There are a few things left to be done but I'm sure that I can meet the required standards. Thanks

**Comment by noamross** [comment]
Dear @nzgwynn.  In reviewing a backlog of issues I realized I had not followed up on your question.  My apologies! The next step here would be for you to put in a full submission as a statistical package (https://github.com/ropensci/software-review/issues/new?assignees=&labels=&projects=&template=F-submit-statistical-software-for-review.md).  You will want to first use [srr](https://docs.ropensci.org/srr/) to document your standards and [pkgcheck](https://docs.ropensci.org/pkgcheck/) to check your package (possibly via the [GitHub Action](https://github.com/ropensci-review-tools/pkgcheck-action))
