### ISSUE TITLE
Energy database software query

### ISSUE THREAD

**Issue by MatthewHeun** [ropensci/software-review#611]
Submitting Author Name: Matthew Kuperus Heun
Submitting Author Github Handle: @MatthewHeun
Repository:  https://github.com/EnergyEconomyDecoupling/PFUAggDatabase
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: PFUAggDatabase
Title: Calculate Aggregations and Efficiencies For Energy Conversion Chains in PSUT Format
Version: 0.1.3
Date: 2022-08-19
Authors@R: 
    c(person(given = "Matthew",
             family = "Heun",
             role = c("aut", "cre"),
             email = "matthew.heun@me.com",
             comment = c(ORCID = "0000-0002-7438-214X")))
Description: It is helpful to be able to aggregate and calculate efficiencies for 
             energy conversion chains. 
             This package provides functions to support and create a `targets` workflow
             for such calculations.
             Several targets create outputs in different forms:
             `.csv` files, `.rds` files, and `.pdf` reports.
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Imports:
    dplyr,
    IEATools, 
    magrittr,
    matsbyname,
    matsindf,
    PFUDatabase,
    PFUPipelineTools,
    pins,
    RCLabels,
    readxl,
    Recca, 
    rlang,
    tarchetypes,
    targets,
    tidyr
Suggests: 
    devtools,
    ggplot2,
    knitr,
    MKHthemes,
    PFUSetup,
    rmarkdown,
    spelling,
    testthat (>= 3.0.0),
    tibble
Depends: 
    R (>= 2.10)
LazyData: true
Language: en-US
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This PFUAggDatabase package builds a database (actually, a large data frame) of country-level primary, final, and useful energy and exergy aggregations from several data sources and own analyses for societal exergy analysis practitioners.  The package supplies a {targets} pipeline and assists execution of that pipeline.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

Not applicable.

-   Who is the target audience and what are scientific applications of this package?  

These packages have the potential to be firmly integrated into multi-country and multi-sector energy analysis by practitioners at all levels worldwide.  The data created by these packages are used by researchers in several countries for (a) historical energy and exergy analyses and (b) assessment of energy transition opportunities.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No other packages perform the same task.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable.  Human subjects are not part of this research.

-  Any other questions or issues we should be aware of?:

This package (PFUAggDatabase) is part of a suite of packages by myself and three other authors (@ZekeMarshall, @PaulBrockway, @earamendia).  The packages work together to build the CL-PFU Database (Country-Level PFU Database). We submitted a paper covering the suite of packages to JOSS (https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper), but an editor shortage has pushed the paper to a waitlist (https://github.com/openjournals/joss-reviews/issues/5775). 

With this pre-submission inquiry, we'd like to dialogue with rOpenSci about whether it makes sense to withdraw our paper from JOSS in favor of reviewing the suite of packages at rOpenSci (with a future submission to JOSS).  The following tables provide the suite of packages that work together to create the CL-PFU Database:

On CRAN already:

| Package | Purpose |
|:--------|:--------|
| [RCLabels](https://github.com/MatthewHeun/RCLabels)     | Manipulates matrix row and column names in [matsindf](https://github.com/MatthewHeun/matsindf) data frames |
| [matsbyname](https://github.com/MatthewHeun/matsbyname) | Performs matrix mathematics that respects row and column names |
| [matsindf](https://github.com/MatthewHeun/matsindf)     | Stores matrices in cells of data frames, thereby enabling analyses with [tidyverse](https://www.tidyverse.org) syntax |

Available on GitHub:

| Package | Purpose |
|:--------|:--------|
| [IEATools](https://github.com/MatthewHeun/IEATools) | Converts [IEA WEB](https://www.iea.org) data to RUVY matrices in [matsindf](https://github.com/MatthewHeun/matsindf) data frames |
| [MWTools](https://github.com/EnergyEconomyDecoupling/MWTools) | Converts [ILO](https://www.ilo.org/) and [FAO](https://www.fao.org/) data to RUVY matrices of human and animal muscle work in [matsindf](https://github.com/MatthewHeun/matsindf) data frames |
| [Recca](https://github.com/MatthewHeun/Recca) | Performs `R` energy conversion chain analysis |
| [PFUSetup](https://github.com/EnergyEconomyDecoupling/PFUSetup) | Identifies input and output locations for the [PFUDatabase](https://github.com/EnergyEconomyDecoupling/PFUDatabase) and [PFUAggDatabase](https://github.com/EnergyEconomyDecoupling/PFUAggDatabase) pipelines |
| [PFUPipelineTools](https://github.com/EnergyEconomyDecoupling/PFUPipelineTools) | Provides basic functionality for all PFU pipelines |
| [PFUDatabase](https://github.com/EnergyEconomyDecoupling/PFUDatabase) | Provides a [targets][link-targets] pipeline to create a data frame of RUVY matrices |
| [PFUAggDatabase](https://github.com/EnergyEconomyDecoupling/PFUAggDatabase) | Provides a [targets][link-targets] pipeline to aggregate RUVY matrices |

A few questions:

* Are these packages (especially PFUDatabase and PFUAggDatabase) sufficiently general in scope to be considered by rOpenSci?

* Would rOpenSci review each package on its own or as a complete suite?

* Does the fact that three of these packages are already on CRAN create any problems for an rOpenSci review?

* Would it make sense to submit only the non-CRAN packages to rOpenSci?

Thanks in advance for your feedback!

**Comment by noamross** [comment]
Thank you for you inquiry, @MatthewHeun!  This is certainly an impressive suite of work.
 - Based on an initial review, I don't believe these are general enough in scope for us.  rOpenSci aims to review packages that can be used as tools by a community of researchers.  These appear to be a pipeline designed for producing a specific output.  Much of our feedback would be about how packages could be modified to work as general-purpose tools.  If, for instance, {IEATools} was a general client for IEA data that would be in scope. {Recca} or {MWTools} may be in scope if they performs a standard set of data manipulations or, if it is estimating quantities, could fall under our [statistical package standards](stats-devguide.ropensci.org/standards.html).  We would have to identify reviewers familiar with the methods.
 - Suites of packages are quite challenging to review because of the demands on reviewers and the lack of cross-package diagnostic tools. We only take them as rare exceptions. When we have, we usually we work through them one at a time and they need to stand alone. 
 - In general, we don't care whether a package is on CRAN or not - that's irrelevant to whether a package passes review. We generally advise authors to consider submitting before CRAN because the review process can result in considerable changes, resulting in a CRAN update, and review also reduces the chances of issues coming up at CRAN submittal. But it is up to the author.

**Comment by MatthewHeun** [comment]
Thanks for your reply! At this point, rOpenSci doesn't seem like a good fit for the suite of packages. We will consider other options for the suite. That said, {Recca} and {IEATools} are more general in nature and might be good to submit to rOpenSci at a later date. Thanks again for your quick response.
