### ISSUE TITLE
ClusterApp: A Shiny Application in R

### ISSUE THREAD

**Issue by JohannaMz** [ropensci/software-review#617]
Submitting Author Name: Johanna Märtz
Submitting Author Github Handle: @JohannaMz
Repository:  https://github.com/JohannaMz/ClusterApp
Version submitted: 0.0.0.9000
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ClusterApp
Title: A Shiny R application to guide and streamline cluster studies based
    on GPS data
Version: 0.0.0.9000
Date: 2023-07-15
Authors@R: c(
    person("Johanna", "Märtz", , "johanna@maertz.eu", role = c("cre", "aut"),
           comment = c(ORCID = "0000-0001-9981-0430")),
    person("Aimee", "Tallian", role = c("aut", "ctb")),
    person("Camilla", "Wikenros", role = c("aut", "ctb")),
    person("Rick", "Heeres", role = c("aut", "ctb"))
  )
Description: The Cluster Analysis App is a Shiny App developed for the
    easy and straightforward analysis of GPS collared individuals to
    identify clusters of visits.
License: GPL (>= 3)
URL: https://github.com/JohannaMz/ClusterApp
BugReports: https://github.com/JohannaMz/ClusterApp/issues
Depends: 
    R (>= 2.10)
Imports: 
    bslib,
    config (>= 0.3.1),
    dplyr,
    DT,
    foreign,
    golem (>= 0.4.0),
    hms,
    leaflet,
    lubridate,
    magrittr,
    methods,
    openxlsx,
    readr,
    readxl,
    sf,
    sftrack,
    shiny (>= 1.7.3),
    shinyFiles,
    shinyWidgets,
    stats,
    stringr,
    tidyr,
    tmap,
    utils
Suggests: 
    knitr,
    rmarkdown,
    shinytest2,
    testthat
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.2.3

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
The 'ClusterApp' is developed to facilitate the cluster analysis of GPS data. Automated workflows, as implemented in this Shiny App, 
decreases the chance for error during field data collection, allows projects to maintain methods across personnel and seasons, and makes field methodology transparent and reproducible. 

-   Who is the target audience and what are scientific applications of this package?
Mainly fieldworkers, repeatedly executing cluster analysis of GPS data, to visit clusters of acitvity in the field. Researches will profit from having a transparent and reproducible method description of how GPS clusters were identified. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
As far as we know, only the package "GPSeqClus" by Clapp et al. (2023) applies sequential clustering algorithm to GPS data. This method however differs from the method that we used for clustering GPS data. The strength of our package furthermore lies in the fact that it is packed as a ShinyApp which facilitates user implementation immensly. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Yes

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.
The function run_app does not include a return value or example as it is an inherent function to shiny apps. I still changed the documentation for it to be included, but do not understand why the checks still call an error on these two missing. Furthermore, I was struggling with implementing a testing structure with golem+shinytest2, since one of their latest updates. Therefore the package coverage tests fail and I have not found a way to fix this problem. I am happy for any help! 

## Technical checks

Confirm each of the following by checking the box.

- [x ] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [ x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [ x] does not violate the Terms of Service of any service it interacts with.
- [ ] has a CRAN and OSI accepted license.
- [x ] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [ x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ x] contains a vignette with examples of its essential functions and uses.
- [x ] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [ ] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [x ] The package is novel and will be of interest to the broad readership of the journal.
- [x ] The manuscript describing the package is no longer than 3000 words.
- [ x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [ x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by jhollist** [comment]
@JohannaMz Thank you for the submission of ClusterApp.  It looks to be a nice application that will help GPS intensive field workflows.

Unfortunately, ClusterApp is out of scope for rOpenSci.  In particular, packages that include apps need to provide the means to reproduce interactive workflows (<https://devguide.ropensci.org/policies.html#other-scope-considerations>).  As it stands now, this does not seem to be a option with ClusterApp.  If you are able to make changes to the app that 1.) generates reproducible code from the Shiny app and 2) facilitates running the analysis outside of the Shiny App (e.g. within the R Console via functions), a follow up submission could be reconsidered.

Thank you for considering rOpenSci for your application.
