### ISSUE TITLE
tidyplate: transform microtiter plate data from xlsx and csv files into tidy dataframes

### ISSUE THREAD

**Issue by shubhamdutta26** [ropensci/software-review#621]
Submitting Author Name: Shubham Dutta
Submitting Author Github Handle: @shubhamdutta26
Other Package Authors Github handles: (comma separated, delete if none) @github_handle1, @github_handle2
Repository:  https://github.com/shubhamdutta26/tidyplate
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: tidyplate
Type: Package
Title: Transform microplate data into a tidy dataframe
Version: 0.9.0
Authors@R: 
    person("Shubham", "Dutta", , "shubhamdutta26@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0001-8484-0717"))
Description: The goal of tidyplate package is to help researchers convert different types of
    microplates into tidy dataframes which can be used in data analysis. It accepts xlsx and
    csv files formatted in a specific way as input. This package supports all types of 
    standard microplate formats such as 6-well, 12-well, 24-well, 48-well, 96-well, 384-well,
    and, 1536-well plates.
Imports: 
  janitor, 
  readr, 
  readxl,
  tibble,
  tidyr,
  dplyr,
  purrr,
  rlang
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
URL: https://github.com/shubhamdutta26/tidyplate, http://www.shubhamdutta.com/tidyplate/
BugReports: https://github.com/shubhamdutta26/tidyplate/issues
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
Tidyplate helps researchers transform microplate data from xlsx and csv files to a tidy format. This makes it easy to store and analyze.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
NA
-   Who is the target audience and what are scientific applications of this package?  
Scientists
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
There is a package called “plater” which does the same thing except it cannot take xlsx as input. “plater” only takes csv files as input. The problem is that lots of researchers (including myself) need to store data with metadata in multiple sheets in one Excel document. “tidyplate” will help researchers import specific sheets in a tidy format from these type of files.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
To the best of my knowledge, it does
-  Any other questions or issues we should be aware of?:
This is the first package I wrote. I am writing the vignette. This package has two functions and they are easy to use. I have explained them nicely in the README.

**Comment by jhollist** [comment]
@shubhamdutta26 Thank you for the pre-submission of tidyplate.  Looks like a nice package that will help users like you that prefer to use excel for their microplate data.  

I do have a primary concern in that there is quite a bit of overlap with the existing `plater` package.  While adding excel as an acceptable format is a nice addition, I am not sure it satisfies the rOpenSci criteria for overlap (https://devguide.ropensci.org/policies.html#overlap).  Could you provide some more details on the differences between your package and `plater`?

**Comment by shubhamdutta26** [comment]
> @shubhamdutta26 Thank you for the pre-submission of tidyplate. Looks like a nice package that will help users like you that prefer to use excel for their microplate data.
> 
> I do have a primary concern in that there is quite a bit of overlap with the existing `plater` package. While adding excel as an acceptable format is a nice addition, I am not sure it satisfies the rOpenSci criteria for overlap (https://devguide.ropensci.org/policies.html#overlap). Could you provide some more details on the differences between your package and `plater`?

Hello, Thank you for your reply. There is not much of a difference. I have used `plater` a lot of times and found it to be amazing (not sure why it did not include a function to import from excel sheets). Like I said the only difference is dealing with excel files which can nicely store experimental data and metadata in different sheets (for csv one needs multiple files).
