### ISSUE TITLE
funbiogeo: a data processing and visualization package for functional biogeography

### ISSUE THREAD

**Issue by Rekyt** [ropensci/software-review#622]
Submitting Author Name: Matthias Grenié
Submitting Author Github Handle: @Rekyt
Other Package Authors Github handles: (comma separated, delete if none) @ahasverus
Repository:  https://github.com/FRBCesab/funbiogeo
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Helps users with analyses in functional biogeogeography by loading 
and combining data, computing trait coverage, as well as computing 
functional diversity indices, drawing maps, correlating them with the 
environment, and upscaling assemblages.
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
     - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package aims to provide tools to easily visualize, filter, and analyze data in functional ecology and functional biogeography: species-traits matrices, site-species matrices. It can be used both as a pre- and post-processing tool in functional ecology.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?

There are three main targets for the package:
- Newcomers to the field of functional ecology (= trait ecology), most packages focus on computing functional diversity indices, but there exists no tool to help provide a standard workflow to guide your analyses. These can be students, researchers, etc.
- Experts in functional ecology who are looking for quick and easy visualizations and data exploration tools.
- Applied scientists who would like to use the functional approach but are unsure how to proceed and would like some advanced feature like data upscaling.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

To our knowledge, all other packages focus on computing functional diversity indices and creating functional spaces, but none are focused on the steps prior and after these.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

 N/A

**Comment by jhollist** [comment]
@Rekyt Thank you for the inquiry!  Wanted to at least let you know that I have received this and that it is on my radar.  I probably won't have a chance to dig into it until early next week, but hope to have a response to you early in the week.

**Comment by jhollist** [comment]
@Rekyt the other editors and I are discussing your pre-submission and whether it is within rOpenSci scope.  Hope to have an answer for you soon.

**Comment by Rekyt** [comment]
> @Rekyt the other editors and I are discussing your pre-submission and whether it is within rOpenSci scope. Hope to have an answer for you soon.

Alright! Thanks for the update!
That was precisely the goal of the pre-submission inquiry 😉

**Comment by jhollist** [comment]
@ropensci-review-bot check package

**Comment by jhollist** [comment]
@Rekyt Sorry for the delay in getting back to you!

We have had a chance to take a look and discuss this.  I do think funbiogeo is out of scope for geospatial data and mostly out of scope for data munging.  However, we do think it is a pretty good fit for the [Exploratory Data Analysis (EDA) and Summary Statistics](https://stats-devguide.ropensci.org/overview.html#overview-eda) category for statistical software packages.  

Given this, I would encourage a statistical software submission in the EDA category.  

Most of our checks look good.  Only thing you'll need to add if you do move ahead with a full submission is the codemeta.json file.  Details on this are on https://devguide.ropensci.org/building.html?q=codemeta#creating-metadata-for-your-package.

Thanks!

**Comment by Rekyt** [comment]
@jhollist thanks for your help.

Thanks for the clarification of categories! I didn't realize it could be submitted as a statistical package.
In order to proceed to a full submission, should I edit this issue or close this one and open a new one?

**Comment by jhollist** [comment]
Close and open a new one.  I'll take care of the first step!
