### ISSUE TITLE
Presubmission inquiry: `chopin`

### ISSUE THREAD

**Issue by sigmafelix** [ropensci/software-review#630]
Submitting Author Name: Insang Song
Submitting Author Github Handle: @sigmafelix
Other Package Authors Github handles: (comma separated, delete if none) @Spatiotemporal-Exposures-and-Toxicology
Repository:  https://github.com/Spatiotemporal-Exposures-and-Toxicology/chopin
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: chopin
Title: CHOPIN: Computation for Climate and Health research On Parallelized INfrastructure
Version: 0.4.0.20240222
Authors@R: c(
    person("Insang", "Song", , "geoissong@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0001-8732-3256")),
    person("Kyle", "Messier", role = c("aut", "ctb"),
           comment = c(ORCID = "0000-0001-9508-9623"))
  )
Description: It enables users with basic understanding on geospatial data
    and sf and terra functions to parallelize geospatial operations for
    geospatial exposure assessment modeling and covariate computation.
    Parallelization is done by dividing large datasets into sub-regions
    with regular grids and data's own hierarchy. A computation over the
    large number of raster files can be parallelized with a chopin
    function as well.
License: MIT + file LICENSE
URL: https://github.com/Spatiotemporal-Exposures-and-Toxicology/chopin
BugReports: 
    https://github.com/Spatiotemporal-Exposures-and-Toxicology/chopin/issues
Depends: 
    R (>= 4.1)
Encoding: UTF-8
LazyData: true
LazyDataCompression: xz
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
Imports: 
    doFuture,
    dplyr (>= 1.1.0),
    exactextractr (>= 0.8.2),
    future,
    future.apply,
    methods,
    rlang (>= 0.4.9),
    sf (>= 1.0-10),
    stars (>= 0.6-0),
    terra (>= 1.7-18)
Suggests: 
    covr,
    doParallel,
    future.batchtools,
    igraph,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0),
    units,
    withr
VignetteBuilder: knitr
Config/testthat/edition: 3
LitrVersionUsed: 0.9.0
LitrId: 65b64b88def74fbb9156429f0cf0d122
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

: This package automates parallelization in spatial operations with chopin macros as well as `sf`/`terra` functions. It helps users to leverage maximal computing assets to expedite geospatial exposure assessment.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

: Not applicable

-   Who is the target audience and what are scientific applications of this package?  

: Spatial epidemiologists and health geographers with basic knowledge in geographic information system/science are this package's target audience. This package automates parallelization in spatial operations based on sf and terra functions for geospatial exposure assessment and environmental health research.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

: To the best of our knowledge, no packaged solution exists for parallelization of geospatial operation. A teaching material briefly covers parallelization without packaging ([RPubs source](https://rpubs.com/Vinit_Sehgal/lgar21)). [`sprawl`](https://github.com/lbusett/sprawl) (GitHub-only; not maintained) partially overlaps this package's functionality in that it includes convenience functions where a chain of elementary geospatial functions is wrapped.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

: Not applicable.

-  Any other questions or issues we should be aware of?:

: We used a literate programming package [`litr`](https://github.com/jacobbien/litr-project), which left artifacts in `DESCRIPTION` and R source code files. Would it be okay to include artifacts in these files? All of these except for DESCRIPTION entries are comments.

Thank you very much for consideration!

**Comment by ldecicco-USGS** [comment]
Thank you for your presubmission @sigmafelix ! Yes, this package makes sense as a geospatial submission . We welcome a full submission.

My only initial feedback is that I think you underestimate your list of users. I'm sure there are many other fields that would like to have easy ways to initiate parallel geospatial operations.

**Comment by sigmafelix** [comment]
Thank you for the comments @ldecicco-USGS! I will make a full submission soon.
