### ISSUE TITLE
Presubmission enquiry for cocoon: Extract, Format, and Print Statistical Output

### ISSUE THREAD

**Issue by JeffreyRStevens** [ropensci/software-review#631]
Submitting Author Name: Jeffrey R. Stevens
Submitting Author Github Handle: @JeffreyRStevens
Repository:  https://github.com/JeffreyRStevens/cocoon
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: cocoon
Title: Extract, Format, and Print Statistical Output
Version: 0.0.1
Authors@R: 
    person("Jeffrey R.", "Stevens", , "jeffrey.r.stevens@protonmail.com", 
    role = c("aut", "cre", "cph"),
    comment = c(ORCID = "0000-0003-2375-1360"))
Maintainer: Jeffrey R. Stevens <jeffrey.r.stevens@protonmail.com>
Description: Provides functions that format statistical output in a way that
    can be inserted into R Markdown documents. This is analogous to the 
    `apa_print()` functions in the papaja package but prints Markdown
    or LaTeX syntax.
License: GPL (>= 3)
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Imports: 
    BayesFactor,
    dplyr
URL: https://github.com/JeffreyRStevens/cocoon, https://jeffreyrstevens.github.io/cocoon/
BugReports: https://github.com/JeffreyRStevens/cocoon/issues
VignetteBuilder: knitr

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
This package processes data from statistical objects or raw numeric values to format them for presentation. Thus, it can automate workflows for formatting statistical information, and it is highly customizable to meet scientists needs for presenting statistical information.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
N/A

-   Who is the target audience and what are scientific applications of this package?  
The target audience is scientists needing to format statistical results in American Psychological Association style. But the functions allow customization to meet other scientific article styles for statistical presentation.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
The papaja, apa, and insight packages include some of the same functionality; however, they either output only LaTeX not Markdown syntax (papaja) or do not allow for customization of output (apa, insight).

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
N/A

-  Any other questions or issues we should be aware of?:
N/A

**Comment by ldecicco-USGS** [comment]
@JeffreyRStevens thank you for your submission of 'cocoon'. It looks to be a handy package for people who report stats out with APA formatting. 

Unfortunately it is out of scope for the data munging category of rOpenSci. The packages in that category tend to take data and process it in a way to allow additional analysis. `cocoon` is a very handy tool for formatting statistical data. It looks like a close fit to a topic described in our Statistical Software peer-review documentation: "support tasks around the statistical process", however that is currently considered out-of-scope as well:
https://stats-devguide.ropensci.org/overview.html#overview-workflow

Thank you for considering rOpenSci for your application.

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot out of scope

**Comment by JeffreyRStevens** [comment]
Thank you, @ldecicco-USGS for your review and comments.
