### ISSUE TITLE
cancerprof: API Client for extracting data from State Cancer Profiles

### ISSUE THREAD

**Issue by realbp** [ropensci/software-review#635]
Submitting Author Name: Brian Park
Submitting Author Github Handle: @realbp
Repository:  https://github.com/getwilds/cancerprof
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: cancerprof
Title: API Client for State Cancer Profiles
Version: 0.0.0.9000
Authors@R: 
    person("Brian", "Park", , "joon.brianpark@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: An API Client for accessing data from State Cancer Profiles for programmable analysis.
License: MIT + file LICENSE
URL: https://github.com/getwilds/cancerprof
BugReports: https://github.com/getwilds/cancerprof/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.0
Imports: 
    cdlTools,
    cli,
    dplyr,
    httr2,
    magrittr,
    rlang,
    stringr,
    utils
Suggests: 
    knitr,
    rmarkdown,
    testthat
Config/testthat/edition: 3
VignetteBuilder: knitr
Depends: 
    R (>= 2.10)

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [x] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

cancerprof allows users to extract data from [State Cancer Profiles](https://statecancerprofiles.cancer.gov/index.html) for programmable analysis. cancerprof makes accessing the unstructured api from state cancer profiles intuitive and easy.

-   Who is the target audience and what are scientific applications of this package?  

The target audience for cancerprof is anyone who wants to access data from state cancer profiles to conduct programmable analysis without having to navigate the complex nature of its GUI. Specifically, cancer researchers could use cancerprof to conduct reproducable analysis of cancer crossed references with a variety of topics found within the data from state cancer profiles. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

Currently there are not other softwares or packages that extracts the publicly available data from State Cancer Profiles. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Cancerprof does not breach any data privacy laws and complies with the ethics policies of ropensci. 

-  Any other questions or issues we should be aware of?:
When running `pkgcheck()` and found a lot of "good practice" notes. Am I required to resolve all of these notes for submission or is it okay to ignore these for special cases?

**Comment by ldecicco-USGS** [comment]
Looks like a good fit for an rOpenSci submission. As for the checks, you don't need to necessarily address all the "good practices" notes. You will need to get the main checks (✔️) from the ropensci bot to pass in order to get an editor assigned (which will kick off the full process). Let me know if that doesn't make sense.

I'd recommend adding some details to the Readme. Also, I'm always a big fan of having `pkgdown` produce some rendered documentation. I usually recommend `usethis::use_pkgdown_github_pages()` to get started.

**Comment by realbp** [comment]
Thank you for the feedback! I pkgdown is now up and running at http://getwilds.org/cancerprof/.

I also ran pkgcheck() and got all of the checks to pass.

![Screenshot 2024-04-01 at 12 14 07 PM](https://github.com/ropensci/software-review/assets/72233714/4e6eb3c2-1230-498a-80ab-ed08d28a6632)

Should I open up a issue for submission to start the peer review process?

**Comment by ldecicco-USGS** [comment]
Please do, thanks!
