### ISSUE TITLE
rpigpior

### ISSUE THREAD

**Issue by mnr** [ropensci/software-review#640]
Submitting Author Name: Mark Niemann-Ross
Submitting Author Github Handle: @mnr
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/mnr/rpigpior
Version submitted:0.0.0.1
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
This provides R with access to the Raspberry Pi General Purpose Input Output (GPIO) via 'libgpiod'. This includes detecting a gpio chip as well as turning pins on and off via [gpioset()] and reading the state of pins via [gpioget()]. No additional libraries need to be installed; Raspbian includes 'libgpiod' as part of the standard installation.
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
Raspberry Pi is part of the Internet of Things and is used as laboratory equipment. Other applications include automation, field sampling and analysis, and prototyping.

-   Who is the target audience and what are scientific applications of this package?
Field analysts and prototype creators.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
https://r4pi.org provides a version of R for the Raspberry Pi, but does not provide packaged access to the general purpose input/output (GPIO) pins. At some point, it is possible rpigpior could be included with their distribution.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
yes

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by ldecicco-USGS** [comment]
Hi @mnr ! Please click the 3 dots in the upper right corner of your original comment to edit, then fill in the response to the fields. A quick glance at your package makes me think it could fit in the "field and laboratory reproducibility tools" category. Playing with a Raspberry Pi is high on my list of things to do, so I'm excited to see this submission.

Once the grey "X"'s are fixed and the original submission fields are updated, I'll take a closer look. Thanks for your submission.

**Comment by mnr** [comment]
Thanks for the advice. I missed the questions below the scroll and have filled those out.

I was also able to clean up the R CMD checks.

So...I think we are good to go?

MNR

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package

**Comment by mnr** [comment]
So - I need some guidance on this. It appears that `covr` doesn't like my unit tests.

Here's the problem:

- most of these tests will fail if there isn't a Raspberry Pi GPIO present to test. 
- To avoid those failures, I always check for presence of Raspberry Pi. ` skip_if_not(is.rpi(), message = "Not a Raspberry Pi")`
- many of these tests will fail if there isn't a switch, or LED, or i2c device connected to the RPi GPIO

Because I'm avoiding obvious failures, `covr` states "The following files are not completely covered by tests:"

In some cases, there is a robust set of tests - but requires significant set-up to test. For example, `rpi_i2c_get` includes this test...

` test_that("rpi_i2c_get err chip address", {

    skip_if_not(is.rpi(), message = "Not a Raspberry Pi")

    expect_error(rpi_i2c_get(

        chip_address = 0x07,

        data_address = 0xf0,

        data_size = "b"

      ))

     }) `

...which means a successful test requires an i2c device is connected to the RPi and is configured to appear at chip address 0x77 and produces expected data at 0xf0

Your help is appreciated.
MNR

**Comment by mpadge** [comment]
@mnr The inability to test coverage is in your case not a problem. Special hardware requirements are not something we even thought about in developing this system. I might have a play on my own pi, but other than that we can just wait for Editor-in-Chief @jooolia to make a judgement on scope here and proceed regardless of reported coverage.

**Comment by jooolia** [comment]
@ropensci-review-bot out of scope
