### ISSUE TITLE
phangorn

### ISSUE THREAD

**Issue by KlausVigo** [ropensci/software-review#641]
Submitting Author Name: Klaus Schliep
Submitting Author Github Handle: @KlausVigo
Other Package Authors Github handles: (comma separated, delete if none) @emmanuelparadis, @liamrevell,@darunabas,@leomrtns
Repository:  https://github.com/KlausVigo/phangorn
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: phangorn
Title: Phylogenetic Reconstruction and Analysis
Version: 3.0.0
Authors@R: 
    c(person("Klaus", "Schliep", role = c("aut", "cre"),
             email = "klaus.schliep@gmail.com",
             comment = c(ORCID = "0000-0003-2941-0161")),
      person("Emmanuel", "Paradis", role = "aut",
             comment = c(ORCID = "0000-0003-3092-2199")),
      person("Leonardo", "de Oliveira Martins", role = "aut",
             comment = c(ORCID = "0000-0001-5247-1320")),
      person("Alastair", "Potts", role = "aut"),
      person("Iris", "Bardel-Kahr", role = "aut",
             comment = c(ORCID = "0000-0002-8950-834X")),            
      person("Tim W.", "White", role = "ctb"),
      person("Cyrill", "Stachniss", role = "ctb"),
      person("Michelle", "Kendall", role = "ctb",
             email = "m.kendall@imperial.ac.uk"),
      person("Keren", "Halabi",  role = "ctb"),
      person("Richel", "Bilderbeek",  role = "ctb"),
      person("Kristin", "Winchell", role = "ctb"),
      person("Liam", "Revell", role = "ctb"),
      person("Mike", "Gilchrist", role = "ctb"),
      person("Jeremy", "Beaulieu", role = "ctb"),
      person("Brian", "O'Meara", role = "ctb"),
      person("Long", "Qu", role = "ctb"), 
      person(given= "Joseph", "Brown", role = "ctb", 
             comment = c(ORCID = "0000-0002-3835-8062")),
      person(given="Santiago", "Claramunt", role = "ctb", 
             comment = c(ORCID = "0000-0002-8926-5974")))
Description: Allows for estimation of phylogenetic trees and networks
    using Maximum Likelihood, Maximum Parsimony, distance methods and
    Hadamard conjugation (Schliep 2011). Offers methods for tree comparison, 
    model selection and visualization of phylogenetic networks as described in
    Schliep et al. (2017).
License: GPL (>= 2)
URL: https://github.com/KlausVigo/phangorn,
    https://klausvigo.github.io/phangorn/
BugReports: https://github.com/KlausVigo/phangorn/issues
Depends:
    ape (>= 5.8),
    R (>= 4.1.0)
Imports:
    digest,
    fastmatch,
    generics,
    ggseqlogo,
    ggplot2,
    graphics,
    grDevices,
    igraph (>= 1.0),
    Matrix,
    methods,
    parallel,
    quadprog,
    Rcpp,
    stats,
    utils
Suggests:
    apex,
    Biostrings,
    knitr,
    magick,
    rgl,
    rmarkdown,
    seqinr,
    tinytest,
    vdiffr,
    xtable
LinkingTo:
    Rcpp
Remotes: github::EmmanuelParadis/ape
VignetteBuilder: 
    knitr,
    utils
biocViews: Software, Technology, QualityControl
Encoding: UTF-8
Repository: CRAN
Roxygen: list(old_usage = TRUE)
RoxygenNote: 7.3.1
Language: en-US

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
        - [x] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [x] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:
phangorn offers mainly function for phylogenetic inference (data munging). Additionally there are several tests for data validation and testing assumptions. phylogenetic analysis often require a workflow using different tools, phangorn allows in combination with other R packages (ape, phytools, msa, ...) to simplify such workflows all inside R.   
Some phylogenetic methods like UPGMA or WPGMA have been adopted in statistics, but are in this field better known as hierarchical clustering. 
Additionally I have seen a few packages have also a topic phylogenetics and might even depend on phangorn. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?
No. 

-   Who is the target audience and what are scientific applications of this package?  
Researcher who want to perform phylogenetic analysis, compare their analyses and phylogenetic trees. 
Too teach a whole workflow of phylogenetic reconstruction to interpreting and visualising results in R.  

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Some ultrametric distance methods are available in the stats package (hclust) and unrooted distance methods NJ, BioNJ, fastME in the ape package. phangorn provides maximum likelihood and parsimony methods among others. 
There are some tools packages for phylogenetic comparative methods which can do this analysis but a re usually only for a limited amount of data, not alignments.  
There are several other packages ( [TreeDist](htTBRDist, Quartet, distory) providing tree distances which phangorn complements provide different methods.  
There are several packages (e.g. babette) which have software wrappers to phylogenetic packages. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

We are writing a new software note of the package phangorn as we plan to submit . We especially appreciate feedback which improving the package as well as making the package easier to maintain and thus avoiding to get "Ripleyed" in the future. We tried in the recent time to make several workflows easier to follow (adding the function `pml_bb) and improved the vignettes, any ideas in this respect are very welcome.  

The package differs from most other submissions as it is already for over 15 years on CRAN and is considerably larger than the usual submission to rOpenSci. We are fully aware that the naming of functions is not consistent (the underscore was an assignment operator when the main author started using R) and the package has around 50 reverse dependencies on CRAN and 150 on rOpenSci so changing function names is not a trivial task.  

We are currently working to check the last few ticks with pkgcheck.

Kind regards, 
Klaus Schliep

**Comment by jooolia** [comment]
Dear @KlausVigo, 
Many thanks for your submission of this long-standing package. It seems possible that the statistical category "Dimensionality Reduction, Clustering, and Unsupervised Learning" could be a good fit. Would it be possible to comply with the [Dimensionality Reduction](https://stats-devguide.ropensci.org/standards.html#standards-unsupervised) standards and potentially the [Probability Distributions](https://stats-devguide.ropensci.org/standards.html#standards-distributions) standards? 

Many thanks, Julia

**Comment by jooolia** [comment]
Dear @KlausVigo,
Thanks for your pre-submission. With no response from your end I will close this issue, but feel free to re-open with follow up questions.
Thanks, Julia
