### ISSUE TITLE
eDNAjoint: R package for interpreting paired environmental DNA and traditional surveys

### ISSUE THREAD

**Issue by abigailkeller** [ropensci/software-review#642]
**Date accepted:** 2024-09-26
Submitting Author Name: Abigail Keller
Submitting Author Github Handle: @abigailkeller
Repository:  https://github.com/abigailkeller/eDNAjoint
Version submitted: 0.1
Submission type: Stats
Badge grade: silver
Editor: @emitanaka
Reviewers: @chitrams, @smwindecker

Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: eDNAjoint
Title: Joint Modeling of Traditional and Environmental DNA Survey Data
Version: 0.1
Maintainer: Abigail G. Keller <agkeller@berkeley.edu>
Author: Abigail G. Keller
Authors@R: 
    c(person("Abigail G.", "Keller", role = c("aut", "cre"), email="agkeller@berkeley.edu"),
    person("Ryan P.", "Kelly", role = "ctb", email="rpkelly@uw.edu"))
Description: Models integrate environmental DNA (eDNA) detection data and traditional survey data to jointly estimate species catch rate (see package vignette: https://bookdown.org/abigailkeller/eDNAjoint_vignette/). Models can be used with count data via traditional survey methods (i.e., trapping, electrofishing, visual) and replicated eDNA detection/nondetection data via polymerase chain reaction (i.e., PCR or qPCR) from multiple survey locations. Estimated parameters include probability of a false positive eDNA detection, a site-level covariates that scale the sensitivity of eDNA surveys relative to traditional surveys, and catchability coefficients for traditional gear types. Models are implemented with a Bayesian framework (Markov chain Monte Carlo) using the 'Stan' probabilistic programming language.
License: GPL-3
URL: https://github.com/abigailkeller/eDNAjoint
BugReports: https://github.com/abigailkeller/eDNAjoint/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.3.1
Biarch: true
Depends: 
    R (>= 3.4.0)
Imports: 
    bayestestR,
    dplyr,
    ggplot2,
    loo,
    magrittr,
    methods,
    Rcpp (>= 0.12.0),
    RcppParallel (>= 5.0.1), 
    rlist,
    rstan (>= 2.26.23),
    rstantools (>= 2.3.1.1),
    tidyr
LinkingTo: 
    BH (>= 1.66.0),
    Rcpp (>= 0.12.0),
    RcppEigen (>= 0.3.3.3.0),
    RcppParallel (>= 5.0.1),
    rstan (>= 2.26.23),
    StanHeaders (>= 2.26.22)
SystemRequirements: GNU make
LazyData: true
Suggests: 
    bayesplot,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: knitr
Config/testthat/edition: 3
```

## Scope 

- Please indicate which of our [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one appropriate box below):

     **Statistical Packages**

	- [x] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses
	- [x] Probability Distributions

## Pre-submission Inquiry

- [x] A pre-submission inquiry has been approved in [issue 628](https://github.com/ropensci/software-review/issues/628)

## General Information

-   Who is the target audience and what are scientific applications of this package?

The package eDNAjoint is useful for interpreting observations from paired environmental DNA (eDNA) and traditional surveys. The package runs a Bayesian model that integrates these two data streams to jointly estimate parameters like the false positive probability of eDNA detection and expected catch rate at a site. The package allows users to access pre-compiled models written in Stan. The target audience is environmental science researchers or managers who want to interpret environmental DNA data but do not have experience writing and implementing custom Bayesian models.

-   Paste your responses to our [*General Standard* **G1.1** here](https://stats-devguide.ropensci.org/standards.html#general-standards), describing whether your software is:

This is the first implementation of a model/algorithm developed in [Keller et al. 2022](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/eap.2561).

-   (If applicable) Does your package comply with our [guidance around *Ethics, Data Privacy and Human Subjects Research*](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Not applicable.

## Badging

-    What grade of badge are you aiming for? ([bronze, silver, gold](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-badges))

Silver

-    If aiming for silver or gold, describe which of the [four aspects listed in the *Guide for Authors* chapter](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-silver) the package fulfils (at least one aspect for silver; three for gold)

Compliance with a good number of standards beyond those identified as minimally necessary.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or have another maintainer identified.
- [x] I/we have read the [*Statistical Software Peer Review* Guide for Authors](https://stats-devguide.ropensci.org/pkgdev.html).
- [x] I/we have run [`autotest`](https://github.com/ropensci-review-tools/autotest) checks on the package, and ensured no tests fail.
- [x] The [`srr_stats_pre_submit()` function](https://ropensci-review-tools.github.io/srr/reference/srr_stats_pre_submit.html) confirms this package may be submitted.
- [x] The [`pkgcheck()` function](https://docs.ropensci.org/pkgcheck/reference/pkgcheck.html) confirms this package may be submitted - alternatively, please explain reasons for any checks which your package is unable to pass.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://devguide.ropensci.org/building.html#readme).

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by mpadge** [comment]
Sorry @abigailkeller I'm trying to resolve this. I've worked out that the build fails in building your vignette because of `bayesplot`, but that's clearly not your fault, and nor can I yet work out why. Main problem is that running checks on your package takes hours (on our system at least), so I've thus far only managed to that diagnosis and no further. Once I fix things, you should see a fresh dump of pkgcheck results appear here.

**Comment by abigailkeller** [comment]
@ropensci-review-bot check package

**Comment by abigailkeller** [comment]
@mpadge Thanks! I just ran the check again. It looks like the same issue is happening?

**Comment by jooolia** [comment]
Thank you for your submission @abigailkeller ! And thanks @mpadge for looking into the issues running the checks on our system. 
Based on the pre-submission issue and the checks (minus the failures that Mark is investigating), I think the only package will be ready to pass on to a handing editor. @abigailkeller do you plan on addressing the duplicated function name "jointModel from JM"?
Thanks, Julia

**Comment by abigailkeller** [comment]
Update: since my vignette compilation time was causing build failures ([see issue here](https://github.com/abigailkeller/eDNAjoint/issues/2#issuecomment-2128848886)), I removed the vignette from the package and instead will direct users/reviewers to a copy of my vignette outside the package in [this book](https://bookdown.org/abigailkeller/eDNAjoint_vignette/). This book is linked in the package DESCRIPTION, as well as in the documentation in all functions.

**Comment by jooolia** [comment]
@ropensci-review-bot assign @emitanaka as editor

**Comment by abigailkeller** [comment]
@ropensci-review-bot check package

**Comment by emitanaka** [comment]
@ropensci-review-bot seeking reviewers

**Comment by mpadge** [comment]
@abigailkeller Your checks failed because GitHub returned an "unexpected error". Please try again.
@emitanaka Sorry, that was an oversight on our part; should now be fixed so please try again.
:smile:

**Comment by abigailkeller** [comment]
@ropensci-review-bot check package

**Comment by emitanaka** [comment]
@ropensci-review-bot seeking reviewers

**Comment by emitanaka** [comment]
@ropensci-review-bot add @chitrams to reviewers

**Comment by emitanaka** [comment]
@ropensci-review-bot add @smwindecker to reviewers

**Comment by emitanaka** [comment]
Please note that @smwindecker is mentoring @chitrams for their review and their review will be considered one (not two). I am still seeking one more reviewer for this.

**Comment by abigailkeller** [comment]
@emitanaka Hi! I'm wondering if it is too late in the review process to express interest in publishing in Methods in Ecology and Evolution? I am thinking that publishing in this journal may make the package more visible to my intended audience. However, I know that this was something I should have indicated when creating this issue, so I understand if it is not possible!

Thanks,
Abby

**Comment by abigailkeller** [comment]
@emitanaka @smwindecker @chitrams
Hi! I'm just checking in on this software review. It occurred to me that I may be looking in the wrong place for reviews of the package. Should I keep tracking this thread? Or does the review process happen elsewhere?

Thanks!
Abby

**Comment by smwindecker** [comment]
my apologies Abby it is almost ready.

**Comment by emitanaka** [comment]
@abigailkeller re: submitting to MEE, I think it should not be a problem. You may want to complete the review here first and quote that the package has been reviewed by ropensci. This fastened the case for [JOSS](https://discuss.ropensci.org/t/automated-joss-review-following-ropensci-acceptance/2807).

**Comment by smwindecker** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

------------------------------------------------------------------------

### Compliance with Standards

-   [x] This package complies with a sufficient number of standards for a silver badge
-   [x] This grade of badge is the same as what the authors wanted to achieve

The following standards currently deemed non-applicable (through tags of `@srrstatsNA`) could potentially be applied to future versions of this software: (Please specify)

> G1.2: The reason this was erroring was because the function is looking for "list(markdown = TRUE)" in the description file. The additional content you have ", roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))" is making the uses_markdown_md() return an NA value and thereby erroring the use_lifecycle() function, as described in <https://rdrr.io/cran/usethis/src/R/roxygen.R#sym-uses_roxygen_md>. If you temporarily remove the roclets argument, you can run the `usethis::use_lifecycle()` then paste back the roclets argument into the description file afterwards.

> BS6.0/BS6.1 re default print and plot methods. We agree with the authors that the existing packages that exist to plot stan outputs are sufficient and they do not need to provide their own. I also think the demonstrations and examples in the bookdown are very helpful. We also agree that the rstan.fit object has its own print function, however the jointModel output contains not only the rstan.fit object but also a list of the inits. If they would like, the authors could perhaps try to return the inits in a neater format, for the moment they are returned in an unnamed list of 4, which, to a novice user, may not be immediately obvious correpond to the 4 chains.

Please also comment on any standards which you consider particularly well documented.

> G1.0 This software cites as a primary reference a paper written by the authors making use of this model in an applied context. This is an excellent reference because it demonstrates that the method has already been peer-reviewed.

> G1.3 The bookdown documentation is very thorough, and walks through not only the relevant statistical terminology very clearly, but creates helpful ties to the relevant data use case.

> G5.1 the gobyData is clear, easy to use, and well documented in the bookdown. It is easy to test out the functionality with this data.

> BS1.1 I think the documentation in the bookdown related to how to transform/reshape input data is especially well written. It gives users a great guide for converting their data into the right format.

For packages aiming for silver or gold badges:

-   [x] This package extends beyond minimal compliance with standards in the following ways: (please describe)

> It is our assessment that the package complies with more than half of the potentially applicable standards.

------------------------------------------------------------------------

### General Review

#### Documentation

The package includes all the following forms of documentation:

-   [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
-   [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING
-   [x] The documentation is sufficient to enable general use of the package beyond one specific use case

> Some guidelines for contributing could be listed explicitly if the authors would welcome them.

#### Algorithms

-   How well are algorithms encoded?
-   Is the choice of computer language appropriate for that algorithm, and/or envisioned use of package?
-   Are aspects of algorithmic scaling sufficiently documented and tested?
-   Are there any aspects of algorithmic implementation which could be improved?

> The wrapper to build the stan models is very well designed. It allows users the option to specify a gamma distribution for the overdispersion of survey data and a beta distribution for the eDNA false positive rate. These options are well selected for the subject matter and provide a great resource for researchers in this area.

#### Testing

-   Regardless of actual coverage of tests, are there any fundamental software operations which are not sufficiently expressed in tests?
-   Is there a need for extended tests, or if extended tests exists, have they been implemented in an appropriate way, and are they appropriately documented?

> There is a good set of unit tests provided with the package. Improperly formatted input data gives useful errors to revise input.

#### Visualisation (where appropriate)

-   Do visualisations aid the primary purposes of statistical interpretation of results?
-   Are there any aspects of visualisations which could risk statistical misinterpretation?

> In general the existing visualisations in other packages for stan model outputs are sufficient for visualisation of the outputs from this package. The guidelines in the bookdown are also very clear. However for users that don't work through the bookdown itself, if the authors were interested, they could perhaps point to these options in the help file for the model fit function or in a print message for the fitted object. I spoke to a few colleagues who use similar packages that wrap stan and they agreed they wouldn't expect bespoke plotting functionality.

#### Package Design

-   Is the package well designed for its intended purpose?
-   In relation to **External Design:** Do exported functions and the relationships between them enable general usage of the package?
-   In relation to **External Design:** Do exported functions best serve inter-operability with other packages?
-   In relation to **Internal Design:** Are algorithms implemented appropriately in terms of aspects such as efficiency, flexibility, generality, and accuracy?
-   In relation to **Internal Design:** Could ranges of admissible input structures, or form(s) of output structures, be expanded to enhance inter-operability with other packages?

> The package is well designed. It provides a modelling solution for paired eDNA and traditional sampling data. By building an integrated model with this paired data, it enables users to compare the two survey protocols and get better estimates for the number of the target species.

> As an aside, after speaking with a colleague who works in eDNA, they expressed interest in the intent of the package but noted that non perfectly paired data is more common. It would be great in the future if the authors could consider an extension that would allow users to input non-paired data, to allow more potential users to get the most out of available datasets (though I understand this is a much thornier model, just thought I'd pass along the note).

> In terms of althorithmic implementation the authors have done a good job designing the model in stan. The jointModel function is nicely written to include wrapper arguments for the MCMC options and easy input location for initial values.

> I particularly like the demonstration in the bookdown for simulating from the prior, to help inform model development.

------------------------------------------------------------------------

-   [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing:

Reviewer 1, 9 hours, reviewer 2, 12 hours

-   [x] Should the author(s) deem it appropriate, we agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

### General Comments

> I like that the helpfiles link to the bookdown.

> Regarding BS1.3a, BS2.8, and running the model with the results of previous runs: I was unsure what the standards were suggesting, but if they were suggesting using posteriors as the starting point for continuing the Markov chains, I agree with the authors' assessment that they are not sure how to implement this. I found this discussion that the authors may find interesting on this point: <https://discourse.mc-stan.org/t/start-from-previous-simulation/8282/6>

> We had one issue with installation, which was that for one of us the install took around 30 minutes to complete. This seems unusally long. If this install time cannot be reduced, perhaps just a note in the readme warning users that it may take a long time. The clang messages that come along with the compiled stan models are confronting for a user that has not encountered them before, and may make someone interrupt installation if it is taking so long.

> A few notes from some automatic checks:

> -   The following function have high cyclomatic complexity (\>50): detectionCalculate (117), detectionPlot (117), jointSummarize (105), jointModel (66). You can make them easier to reason about by encapsulating distinct steps of your function into subfunctions.

> -   use '\<-' for assignment instead of '='. '\<-' is the standard, and R users and developers are used it and it is easier to read your code for them if you use '\<-'. See in tests/testthat/test-jointSelect.R:35:10 tests/testthat/test-jointSelect.R:38:10 tests/testthat/test-muCritical.R:57:11 tests/testthat/test-muCritical.R:63:9

> -   style consistency: add spaces around "=" for better readability.

**Comment by abigailkeller** [comment]
@smwindecker Thanks so much for such a thorough review. I really appreciate it! I'll get to work on responding to your comments.

Best,
Abby

**Comment by abigailkeller** [comment]
@smwindecker and @chitrams thank you so much again for your thorough review! I really appreciate it. And thanks @emitanaka for facilitating.

Below are the reviewer comments in bold with my responses beneath. Please let me know if there is anything that can still be improved:

**G1.2: The reason this was erroring was because the function is looking for "list(markdown = TRUE)" in the description file. The additional content you have ", roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))" is making the uses_markdown_md() return an NA value and thereby erroring the use_lifecycle() function, as described in https://rdrr.io/cran/usethis/src/R/roxygen.R#sym-uses_roxygen_md. If you temporarily remove the roclets argument, you can run the usethis::use_lifecycle() then paste back the roclets argument into the description file afterwards.**

Thanks - I don't think I would have figured this out myself! My [README file](https://github.com/abigailkeller/eDNAjoint/blob/master/README.md) now has a lifecycle badge for the package.

**BS6.0/BS6.1 re default print and plot methods. We agree with the authors that the existing packages that exist to plot stan outputs are sufficient and they do not need to provide their own. I also think the demonstrations and examples in the bookdown are very helpful. We also agree that the rstan.fit object has its own print function, however the jointModel output contains not only the rstan.fit object but also a list of the inits. If they would like, the authors could perhaps try to return the inits in a neater format, for the moment they are returned in an unnamed list of 4, which, to a novice user, may not be immediately obvious correpond to the 4 chains.**

Good point! I have updated the code so that the `jointModel` function returns a named list (see [lines 459-460 in jointModel.R](https://github.com/abigailkeller/eDNAjoint/blob/master/R/jointModel.R)).

**Some guidelines for contributing could be listed explicitly if the authors would welcome them.**

I have added both [contributing guidelines](https://github.com/abigailkeller/eDNAjoint/blob/master/CONTRIBUTING.md) and a [code of conduct](https://github.com/abigailkeller/eDNAjoint/blob/master/CODE_OF_CONDUCT.md) to the package repo.

**In general the existing visualisations in other packages for stan model outputs are sufficient for visualisation of the outputs from this package. The guidelines in the bookdown are also very clear. However for users that don't work through the bookdown itself, if the authors were interested, they could perhaps point to these options in the help file for the model fit function or in a print message for the fitted object. I spoke to a few colleagues who use similar packages that wrap stan and they agreed they wouldn't expect bespoke plotting functionality.**

I like it! I've added a print message in [lines 453-457 of jointModel.R](https://github.com/abigailkeller/eDNAjoint/blob/master/R/jointModel.R) to link users to the [Visualization Tips](https://bookdown.org/abigailkeller/eDNAjoint_vignette/tips.html#visualization-tips) section of the user guide.

**As an aside, after speaking with a colleague who works in eDNA, they expressed interest in the intent of the package but noted that non perfectly paired data is more common. It would be great in the future if the authors could consider an extension that would allow users to input non-paired data, to allow more potential users to get the most out of available datasets (though I understand this is a much thornier model, just thought I'd pass along the note).**

I really like this suggestion, thanks! I've updated [the models](https://github.com/abigailkeller/eDNAjoint/tree/master/inst/stan) to accommodate what I am calling "semi-paired data". Instead of requiring the user to have both paired eDNA and traditional survey data at all sites, now the user can have paired data at some sites and eDNA data only at other sites. The models now use the estimated relationship between eDNA and traditional survey data from paired sites to make predictions at the unpaired sites. I have also added [another use case](https://bookdown.org/abigailkeller/eDNAjoint_vignette/usecase4.html) to the user guide to demonstrate this new functionality. 

However, I imagine your colleague may also be referring to "non perfectly paired" data in the sense that the paired data do no align perfectly in space and/or time. I'm definitely interested in addressing this in a future extension. :)

**Should the author(s) deem it appropriate, we agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.**

Yes! I'd be happy to add you both. @smwindecker and @chitrams what are your email addresses?

**We had one issue with installation, which was that for one of us the install took around 30 minutes to complete. This seems unusally long. If this install time cannot be reduced, perhaps just a note in the readme warning users that it may take a long time. The clang messages that come along with the compiled stan models are confronting for a user that has not encountered them before, and may make someone interrupt installation if it is taking so long.**

After the package is through review, I am intending to put the package on Cran and give Cran installation instructions in the repo README. Cran provides pre-compiled binary files, while installing from source requires compiling the models, which I imagine is why it took so long to install and was giving stressful messages! I am hoping installation will be smoother from Cran, but I also have [added more detail to the README](https://github.com/abigailkeller/eDNAjoint/blob/master/README.md) that users may expect long installation times from source.

**A few notes from some automatic checks:**

**The following function have high cyclomatic complexity (>50): detectionCalculate (117), detectionPlot (117), jointSummarize (105), jointModel (66). You can make them easier to reason about by encapsulating distinct steps of your function into subfunctions.**

Thanks! I have made the code more modular and vectorized to reduce cyclomatic complexity. I believe the cyclomatic complexity of detectionCalculate, detectionPlot, jointsSummarize, and jointModel is now 13, 3, 4, and 20, respectively.

**use '<-' for assignment instead of '='. '<-' is the standard, and R users and developers are used it and it is easier to read your code for them if you use '<-'. See in tests/testthat/test-jointSelect.R:35:10 tests/testthat/test-jointSelect.R:38:10 tests/testthat/test-muCritical.R:57:11 tests/testthat/test-muCritical.R:63:9**

I have updated the assignment syntax in [test-muCritical.R](https://github.com/abigailkeller/eDNAjoint/blob/master/tests/testthat/test-muCritical.R) and [test-jointSelect.R](https://github.com/abigailkeller/eDNAjoint/blob/master/tests/testthat/test-jointSelect.R).

**style consistency: add spaces around "=" for better readability.**

I have made sure there are spaces around "=" in all files of the package.

**Comment by abigailkeller** [comment]
@emitanaka @mpadge 
Hi! I'm wondering what are the next steps of the review process? Is there anything else I should be doing on my end?

Thanks!
Abby Keller

**Comment by emitanaka** [comment]
Sorry I am away at a conference will reply back when I am back next week

**Comment by abigailkeller** [comment]
@emitanaka Hi! Just wanted to send a gentle reminder about this review and next steps.

Best,
Abby

**Comment by emitanaka** [comment]
Thank you for your patience @abigailkeller (and apologies, I'm a juggling hell). 

@smwindecker and @chitrams, thank you so much for your thorough review! Could I ask you to complete the review with the template [here](https://devguide.ropensci.org/approval2template.html) to indicate your approval?

@mpadge I have tried to source other reviewers but I hadn't had luck. Given Saras and Chitra have done a thorough review (and I've gone through the responses myself), would that suffice from the rOpenSci perpsective?

**Comment by mpadge** [comment]
@emitanaka The joint review is absolutely fine. In order for our bot to separately log these contributions, we'll nevertheless need two separate review statements.

@chitrams: Could you please make a comment here that your review is included in [the previous joint review](https://github.com/ropensci/software-review/issues/642#issuecomment-2238886129), include a link to that review, and your estimated review duration? Note that you should do this prior to Emi's request for you to complete the approval template. Thanks!

@emitanaka You'll then need to officially log the reviews, as described [in our *Dev Guide*](https://github.com/ropensci/software-review/issues/642#issuecomment-2238886129) by issuing `@ropensci-review-bot submit review <link to review comment> time <time in hours>`. The `<link to review comment>` will need to link to the main review to log @smwindecker, and to the separate comment of @chitrams to log that review.

After that, things should all be good for the final approval steps. Nice work all! :rocket:

**Comment by smwindecker** [comment]
## Reviewer Response


#### Final approval (post-review)

- [x] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: Review 1, 9.5 hours, Reviewer 2, 12.5 hours

**Comment by chitrams** [comment]
Hello! My review is included in the [previous joint review](https://github.com/ropensci/software-review/issues/642#issuecomment-2238886129) and the estimated review duration was 12.5 hours for me.

**Comment by chitrams** [comment]
## Reviewer Response


#### Final approval (post-review)

- [x] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: 12.5 hours

**Comment by emitanaka** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/642#issuecomment-2238886129 time 9.5

**Comment by emitanaka** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/642#issuecomment-2376055557 time 12.5

**Comment by emitanaka** [comment]
@ropensci-review-bot approve eDNAjoint

**Comment by emitanaka** [comment]
Thank you @smwindecker and @chitrams for your reviews and @mpadge for your help!

**Comment by mpadge** [comment]
And congratulations @abigailkeller on finally getting to the exciting end point :fireworks: Great work everybody!

**Comment by abigailkeller** [comment]
@ropensci-review-bot finalize transfer of eDNAjoint

**Comment by abigailkeller** [comment]
Thank you so much @mpadge @chitrams @smwindecker @emitanaka for all the work you've done and advice you've given me! This process has been extremely rewarding for me - I've learned so much!

**Comment by abigailkeller** [comment]
@ropensci/blog-editors I'm interested in writing a blog post about the origin of the package and my experiences developing it. How should I get started?

**Comment by abigailkeller** [comment]
Hi @steffilazerte!

Thanks for your help with this. Sorry for the delay - I was waiting for a manuscript about the package to be published!

A created a [pull request](https://github.com/ropensci/roweb3/pull/1004) with a blog post. However, it looks like the draft has some errors associated with Netlify rendering. Do you have any tips?

Best,
Abby

**Comment by steffilazerte** [comment]
Hi @abigailkeller! I just redeployed the build to clear the gremlins, thanks!
