### ISSUE TITLE
Presubmission Inquiry of the `cryptoQuotes`-package

### ISSUE THREAD

**Issue by serkor1** [ropensci/software-review#644]
Submitting Author Name: Serkan Korkmaz
Submitting Author Github Handle: @serkor1
Repository:  https://github.com/serkor1/cryptoQuotes
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: cryptoQuotes
Title: A Streamlined Access to Cryptocurrency OHLC-V Market Data and Sentiment Indicators
Version: 1.3.1
Authors@R: c(
    person("Serkan", "Korkmaz", , "serkor1@duck.com", role = c("cre", "aut", "ctb", "cph"),
           comment = c(ORCID = "0000-0002-5052-0982")),
    person("Jonas", "Cuzulan Hirani", , "jjh@vive.dk", role = "ctb",
           comment = c(ORCID = "0000-0002-9512-1993"))
  )
Description: 
  This high-level API client offers a streamlined access to public cryptocurrency market data and sentiment indicators. It features OHLC-V (Open, High, Low, Close, Volume) that comes
  with granularity ranging from seconds to months and essential sentiment indicators to develop and backtest trading strategies, or conduct detailed market analysis. By interacting directly with
  the major cryptocurrency exchanges this package ensures a reliable, and stable, flow of market information, eliminating the need for complex, low-level API interactions or webcrawlers.
License: GPL (>= 2)
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
Suggests: 
    data.table,
    knitr,
    quantmod,
    rmarkdown,
    testthat (>= 3.0.0),
    tidyverse
Config/testthat/edition: 3
Imports:
    cli (>= 3.6.2),
    curl (>= 5.2.1),
    jsonlite (>= 1.8.8),
    lifecycle (>= 1.0.4),
    plotly (>= 4.10.4),
    TTR (>= 0.24.4),
    utils,
    xts (>= 0.13.2),
    zoo (>= 1.8-12)
Depends:
    R (>= 4.0.0)
LazyData: true
VignetteBuilder: knitr
URL: https://serkor1.github.io/cryptoQuotes/, https://github.com/serkor1/cryptoQuotes
BugReports: https://github.com/serkor1/cryptoQuotes/issues

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check an appropriate box below):

    **Data Lifecycle Packages**

	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package retrieves cryptocurrency market data by interacting with public API endpoints provided by the cryptocurrency exchanges.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

-   Who is the target audience and what are scientific applications of this package?  

The primary target audience are researchers and students of Finance, the package compliments the likes of TTR, FinancialInstruments and PerformanceAnalytics.

The secondary target audience are data scientists that are looking to find high quality cryptocurrency data for developing and evaluating prediction models. 

The third target audience are traders that are looking to develop and evaluate trading strategies using cryptocurrency data.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

The packages which comes closest is the [coinmarketcapr](https://github.com/amrrs/coinmarketcapr)- and [crypto2](https://github.com/sstoeckl/crypto2)-packages. 

However, `coinmarketcapr` is gated behind an API subscription and haven't been updated in the last two years. The `crypto2`-package, a fork of [crypto](https://github.com/JesseVent/crypto),  scrapes the data from [coinmarketcap](https://coinmarketcap.com/); the package saw its last update 4 months ago, and prior to that it have not been updated since March 2023. Both packages only supports, to the best of my knowledge, daily data.

The `cryptoQuotes`-package, albeit new as it was released December 2023, retrieves the data  by interacting with the public API endpoints provided by the cryptocurrency exchanges. Furthermore, the available data comes with a higher degree of quality and detail as the data is provided directly from the exchanges, from which  the data can be extracted in 1 second to 1 month intervals, which can be a necessity when studying price dynamics.

Furthermore, `cryptoQuotes` is not gated behind a subscription, and all its functions and features are extensively documented.

> **NOTE:** See issue https://github.com/sstoeckl/crypto2/issues/20 and https://github.com/cran/crypto2/issues/1. It seems that `crypto2` lost its access to the coinmarketcap API; which leaves `coinmarketcapr` as the only similar package left.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable.

-  Any other questions or issues we should be aware of?:

Firstly, `cryptoQuotes` has already been published on `CRAN`. ~~Secondly, I have an update pending (`1.3.1`) which is the `development`-branch of my repository. This update haven't been published as I wanted to submit and, hopefully review, my package with you before that update gets published!~~

**Edit:** I have published `1.3.1` to `CRAN` and moved the latest update to the `main`-branch.

**Comment by serkor1** [comment]
Hi @jooolia,

I see that `phangorn`-package got its presubmission approval the same day it was labelled (Issue https://github.com/ropensci/software-review/issues/641). Have I missed something?

Best,

**Comment by jooolia** [comment]
Hi @serkor1 , 
Thanks for your submission and for your patience, I am currently discussing with the other editors about this submission. 

Cheers, Julia

**Comment by jooolia** [comment]
Dear @serkor1 ,
Thanks for your submission. We have reviewed your information and deemed that the package makes sense as a data retrieval package. We welcome your full submission when you are ready.
Thanks! Julia

**Comment by serkor1** [comment]
Thank you @jooolia, looking forward to it - gonna be a blast! :smile:

**Comment by sstoeckl** [comment]
Dear @serkor1 and @jooolia, I have just pushed fixes for the broken @crypto2 package and, once again, all available historical prices, listing information etc is available for all cryptocurrencies (this is a truly survivorship bias-free dataset for research purposes). It is used to create asset-pricing factors for cryptos etc. If interesting I will consider submitting it to ropensci once I have it back on CRAN.
