### ISSUE TITLE
feowR: Download shapefiles of Freshwater Ecoregions of the World (FEOW)

### ISSUE THREAD

**Issue by brunomioto** [ropensci/software-review#647]
Submitting Author Name: Bruno Henrique Mioto Stabile
Submitting Author Github Handle: @brunomioto
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/brunomioto/feowR
Version submitted:
Submission type: Standard
Editor: @maelle
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: feowR
Title: Download shapefiles of Freshwater Ecoregions of the World (FEOW)
Description: Get access to all shapefiles from Freshwater Ecoregions of the World (FEOW) and a list with IDs and names.
Version: 0.0.0.9000
Authors@R: 
    c(person(given = "Bruno",
             family = "Mioto",
             role = c("aut", "cre"),
             email = "brunomioto97@gmail.com"),
      person(given = "The Nature Conservancy and World Wildlife Fund, Inc",
             role = "cph"))
License: CC BY 4.0 + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
URL: https://github.com/brunomioto/feowR, https://brunomioto.github.io/feowR/
BugReports: https://github.com/brunomioto/feowR/issues
Imports: 
    cli,
    curl,
    piggyback,
    sf
Depends: 
    R (>= 2.10)
LazyData: true
Suggests: 
    dplyr,
    ggplot2,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Config/Needs/website: rmarkdown
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [X] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [X] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

It helps the user to retrieve shapefiles data from Freshwater Ecoregions of the World (FEOW) and save it on the working directory.

-   Who is the target audience and what are scientific applications of this package?

Main use is for biologists (like me) who needs to use this data in other analyses, like selecting points that falls inside each ecoregion.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [X] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [X] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [X] does not violate the Terms of Service of any service it interacts with.
- [X] has a CRAN and OSI accepted license.
- [X] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [X] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [X] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [X] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [X] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by mpadge** [comment]
Sorry that the checks haven't appeared @brunomioto. GitHub has recently been responding to some of the necessary steps with "Unexpected error" messages. Your glitch has provided enough information for us to fix on our side so it shouldn't happen again. In the meantime, I'll manually push the checks in a moment.

**Comment by brunomioto** [comment]
Just updated the package adding a test for "No internet connection". 
The code is now 100% covered.

**Comment by jooolia** [comment]
Dear @brunomioto,
Thank you for your submission. We are in the process of looking for a handling editor. Thanks, Julia

**Comment by jooolia** [comment]
@ropensci-review-bot assign @maelle  as editor

**Comment by jooolia** [comment]
@ropensci-review-bot assign @maelle as editor

**Comment by maelle** [comment]
@ropensci-review-bot out-of-scope

**Comment by maelle** [comment]
@ropensci-review-bot help

**Comment by maelle** [comment]
@ropensci-review-bot out of scope

**Comment by maelle** [comment]
@ropensci-review-bot out of scope
