### ISSUE TITLE
Presubmission inquiry: rJavaEnv

### ISSUE THREAD

**Issue by e-kotov** [ropensci/software-review#648]
Submitting Author Name: Egor Kotov
Submitting Author Github Handle: @e-kotov
Repository:  https://github.com/e-kotov/rJavaEnv
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rJavaEnv
Title: Java Environments for R Projects
Version: 0.0.1
Authors@R: c(
    person("Egor", "Kotov", , "kotov.egor@gmail.com", role = c("aut", "cre", "cph"),
           comment = c(ORCID = "0000-0001-6690-5345")),
    person("Mauricio", "Vargas", , "mavargas11@uc.cl", role = "ctb",
           comment = c(ORCID = "0000-0003-1017-7574"))
  )
Description: Install specific version of Java runtime environment at the R
    project level. The goal of rJavaEnv is to manage multiple Java JDKs in
    R projects by automating the process of downloading, installing, and
    configuring Java environments on a per-project basis.  This package is
    inspired by the renv <https://rstudio.github.io/renv/> package for
    managing R environments in R projects. You can request a specific Java
    Development Kit (JDK) in your project, and rJavaEnv will download and
    install the requested Java environment in a project-specific directory
    and set the PATH and JAVA_HOME for when you are using this project.
    Therefore, you can have different Java versions for different projects
    without contaminating your system with different Java versions.
License: MIT + file LICENSE
URL: https://github.com/e-kotov/rJavaEnv, http://www.ekotov.pro/rJavaEnv/
BugReports: https://github.com/e-kotov/rJavaEnv/issues
Imports: 
    checkmate,
    cli,
    curl,
    jsonlite,
    utils
Suggests: 
    knitr,
    rJava,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.2.9000
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses
	- [ ] Probability Distributions

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

  - **The package provides tools to automate the download, installation, and configuration of Java Development Kits (JDKs), enabling seamless integration with R projects. It falls under workflow automation because it simplifies the process of setting up and managing Java environments for projects relying on `Java`/`rJava`-dependent R packages, which is essential for maintaining reproducibility and efficiency in scientific workflows. It may also be used in tandem with other workflow automation packages such as [`{targets}`](https://github.com/ropensci/targets). E.g. one can use R packages that require different Java versions in the same project, because `{targets}` runs all steps in a separate R processes. Hence adding `rJavaEnv::java_env_set("java_path", "session")` (see [docs](https://www.ekotov.pro/rJavaEnv/reference/java_env_set.html)) in the beginning of a particular script invoked by `{targets}` will use a different Java version without conflicting with any other step of the workflow.**

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

  - **Not applicable.**

- Who is the target audience and what are scientific applications of this package?  

    - **One target audience is R users who use Java-dependent R packages. The package is useful in scientific applications where specific Java versions are required, ensuring reproducibility and consistency in analysis by managing Java environments on a per-project basis. There are more than 100 `Java`/`rJava`-dependent R packages on CRAN and Bioconductor (you can find my [brief overview here](https://www.ekotov.pro/rJavaEnv/articles/why-rJavaEnv.html)) and very often users face issues with getting the right Java version installed. Popular packages include [{`r5r`}](https://github.com/ipeaGIT/r5r), [`{opentripplanner}`](https://github.com/ropensci/opentripplanner/), [`tabulapdf}`](https://github.com/ropensci/tabulapdf/), multiple text analysis packages such as [{openNLP}](https://cran.r-project.org/package=openNLP), [{mallet}](https://cran.r-project.org/package=mallet), and others.**
    - **Another target audience is the developers of `Java`/`rJava`-dependent R packages, who can use `{rJavaEnv}` for Java set-up instructions to use their packages. Some have already tested the pre-release version of `{rJavaEnv}` in [a workshop with 35-40 people](https://github.com/e-kotov/rJavaEnv/issues/6#issuecomment-2184249625) and were happy with the results, others have [even contributed](https://github.com/e-kotov/rJavaEnv/pull/19) to `{rJavaEnv}`.**

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
    - **There are no R packages that accomplish the same thing. There are more non-R general tools such as [`sdkman`](https://sdkman.io/), however these tools do not work in the same way on all platforms, e.g. `sdkman` can only work on Windows with WSL or MSYS+MinGW, that is, it will not work out of the box for most users without additional complicated setup which often requires admin privileges. What is more, these general purpose tools set Java version globally. The approach of `{rJavaEnv}` to providing a safe per-project installation of Java is currently detailed in [this comment](https://github.com/e-kotov/rJavaEnv/issues/3#issuecomment-2182915496) in the package Issues (to be converted into a separate vignette). `{rJavaEnv}` works on all three major platforms and does not require admin privileges. Also, it does not pollute the user's system with system-wide Java installs and always only impacts the current project/working directory and only for R projects.**

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

    - **Not applicable.**

-  Any other questions or issues we should be aware of?:

   - **The package does have a few caveats (currently discussed in [package issues](https://github.com/e-kotov/rJavaEnv/issues/3)), such as not being able to handle Java installs properly on Linux systems that did not have any system Java installed previously and that install `{rJava}` package from source and therefore require some Java to be present for that. I am in the process of addressing these issues before the full submission to rOpenSci.**

**Comment by jooolia** [comment]
Hi @e-kotov, thanks for the pre-submission. We are discussing with the editors. Thanks, Julia

**Comment by jooolia** [comment]
Dear @e-kotov,
Thank you very much for your submission. Your package {rJavaEnv} looks very useful and helpful for many use cases, however we believe for us it is out-of-scope for the workflow category. The category is  for “tools that automate and link together workflows, such as build systems and tools to manage continuous integration” and your package is even more general than the packages that we aim to support here. Many thanks again for your pre-submission and I am looking forward to testing out your package in the future. 

Many thanks, Julia

**Comment by e-kotov** [comment]
Dear @jooolia , thank you and the editors for taking the time to review `{rJavaEnv}`.
