### ISSUE TITLE
Presubmission inquiry: mbquartR

### ISSUE THREAD

**Issue by alex-koiter** [ropensci/software-review#649]
Submitting Author Name: Alex koiter
Submitting Author Github Handle: @alex-koiter
Repository:  https://github.com/alex-koiter/mbquartR
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: mbquartR
Title: Finding Manitoba Quarter Sections
Version: 0.0.0.9000
Authors@R: 
    person("Alex", "Koiter", , "koitera@brandonu.ca", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-9355-9561"))
Description: This package has three main functions: 1) find the coordinates of a quarter sections given the legal land description (e.g., "NE-11-33-29W"); 2) find the legal land description using coordinates (lat and long); and 3) plot these points on a map. 
License: MIT + file LICENSE
URL: http://alexkoiter.ca/mbquartR/, https://github.com/alex-koiter/mbquartR
BugReports: https://github.com/alex-koiter/mbquartR/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
Suggests: 
    testthat (>= 3.0.0),
    curl (>= 5.2.1)
Config/testthat/edition: 3
Imports: 
    dplyr (>= 1.1.4),
    purrr (>= 1.0.2),
    sf (>= 1.0.16),
    tibble (>= 3.2.1),
    tidyr (>= 1.3.1),
    stringr (>= 1.5.1),
    units (>= 0.8.5),
    mapview (>= 2.11.2),
    readr (>= 2.1.4),
    crayon (>= 1.5.2),
    rlang
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):

**Data Lifecycle Packages**

  - [x] data retrieval
  - [x] data extraction
  - [ ] data munging
  - [ ] data deposition
    - [ ] data validation and testing
  - [ ] workflow automation
  - [ ] version control
  - [ ] citation management and bibliometrics
  - [ ] scientific software wrappers
  - [ ] field and lab reproducibility tools
  - [ ] database software bindings
  - [ ] geospatial data
  - [ ] text analysis
    
 **Statistical Packages**

  - [ ] Bayesian and Monte Carlo Routines
  - [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
  - [ ] Machine Learning
  - [ ] Regression and Supervised Learning
  - [ ] Exploratory Data Analysis (EDA) and Summary Statistics
  - [ ] Spatial Analyses
  - [ ] Time Series Analyses
  - [ ] Probability Distributions    

**Questions**

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package enables users to download the Manitoba Original Survey Legal Descriptions data from the Manitoba government geoportal. It includes functions that allow users to easily search for parcels of land (i.e., quarter sections) by either the legal land description or by coordinates and plot them on an interactive map.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

NA

-  Who is the target audience and what are scientific applications of this package?  

The target audience are those who work with geospatial data in Manitoba, particularly those who are working with rural or farm parcels of land where the legal land description is commonly used as the method of identifying the location. Also anyone who needs to quickly go back and forth between geographic coordinates and the legal land description. Currently, there are a few web-based tools (https://geoportal.gov.mb.ca/datasets/11fa11f9015b45438d6493dcb3d8071c/, https://www.masc.mb.ca/masc.nsf/land_parcel_info.html, https://legallandconverter.com/p4.html) that allow users to locate land parcels but do not allow for batch processing, do not return coordinates, and/or are fee based. Being able to convert back and forth is also helpful for scientist preparing outreach materials. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

NA. This package provides access to publicly available data.

-  Any other questions or issues we should be aware of?:

 No

**Comment by jooolia** [comment]
@ropensci-review-bot check package

**Comment by jooolia** [comment]
Dear @alex-koiter ,
Thank you for your pre-submission to rOpenSci. This package looks like a good fit for the data retrieval and data extraction categories and we look forward to receiving your full submission. 
Cheers, Julia
