### ISSUE TITLE
pre-submission inquiry: fireexposuR

### ISSUE THREAD

**Issue by heyairf** [ropensci/software-review#652]
Submitting Author Name: Air Forbes
Submitting Author Github Handle: @heyairf

Repository:  https://github.com/heyairf/fireexposuR
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: fireexposuR
Title: Compute and Visualize Wildfire Exposure
Version: 0.2.0
Authors@R: c(person("Air", "Forbes", email = "amforbes@ualberta.ca", 
    role = c("aut", "cre"), comment = c(ORCID = "0000-0002-9842-7648")),
    person("Jennifer", "Beverly", role = "aut"))
Description: This package computes wildfire exposure using methods from
    Beverly et al. (2010), Beverly et al. (2021), and Beverly and Forbes
    (2023).  It provides functions to standardize the mapping and
    visualization of wildfire exposure. This package requires
    pre-processing of data which is documented in Forbes and Beverly
    (Manuscript in preparation).
License: GPL (>= 3)
Imports: 
    dplyr,
    geosphere,
    ggplot2,
    ggspatial,
    magrittr,
    maptiles,
    MultiscaleDTM,
    rlang,
    terra,
    tidyr,
    tidyselect,
    tidyterra
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.3.1
Roxygen: list(markdown = TRUE)
URL: https://github.com/heyairf/fireexposuR
BugReports: https://github.com/heyairf/fireexposuR/issues
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Depends: 
    R (>= 2.10)
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [x] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses
	- [ ] Probability Distributions

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package was developed to share methodologies from existing research by modifying/expanding existing functions. The functions automate and standardize assessments to increase access and quality assurance in the calculation for interested users. 

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

n/a

-   Who is the target audience and what are scientific applications of this package?  

Users interested in wildfire risk assessments including but not limited to researchers, consultants, planners, land use decision makers. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are no other R packages that fill this role. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

n/a

-  Any other questions or issues we should be aware of?:

My pre-submission inquiry is surrounding the test suite. I am _very_ new to R package development and am unsure how to use testthat appropriately in my project. Examples online are very simple, and because of the spatial analysis most functions are using S4 objects which seems to complicate things further. I have attempted to find answers through my university and haven't been able to find any support. Would anyone be able to advise me on this or steer me to someone who could? I believe it is the only element that needs addressing before I can submit my package.

**Comment by adamhsparks** [comment]
Hi @heyairf, this isn't really the proper place to offer support for this request. We're happy to help but I'd suggest you try the rOpenSci forums, https://discuss.ropensci.org or if you prefer a Slack interface you could try https://dslc.io.

Since this is a pre-submission inquiry, from the looks of it, the package would be in-scope.

**Comment by adamhsparks** [comment]
If you haven't, you should refer to the Testing packages chapter in the "R-pkgs" book, https://r-pkgs.org/testing-basics.html. 

A further suggestion from the editors was to check other spatial packages for their test-suites and see how they implemented them. https://github.com/r-spatialecology/landscapemetrics/tree/main/tests/testthat is one that was suggested.

I'll close this issue now. Please feel free to open a new issue for software review when you've addressed this issue with the package.

**Comment by heyairf** [comment]
My apologies, thanks for directing me to the right place to ask!

**Comment by adamhsparks** [comment]
No worries. It looks like a nice package. 😊

**Comment by adamhsparks** [comment]
Hi @heyairf, @maurolepore had some further suggestions that I was remiss in reporting back here. So here they are.

[21.1 Testing functions (except 21.1.4)](https://mastering-shiny.org/scaling-testing.html#testing-functions)
[21.2 Workflow](https://mastering-shiny.org/scaling-testing.html#workflow-1)
[21.6 Philosophy](https://mastering-shiny.org/scaling-testing.html#philosophy)

and Mauro also has a YouTube playlist on testing in R, https://www.youtube.com/playlist?list=PLvgdJdJDL-APxwVpLE7vjeg-Pgdd4e64W&themeRefresh=1

**Comment by heyairf** [comment]
Thank you for the additional resources! I really appreciate it. I have just posted my most pressing/specific question in the discussion forum [here](https://discuss.ropensci.org/t/s4-data-for-testthat-and-examples/4007).
