### ISSUE TITLE
forcis: An R client to access the FORCIS database

### ISSUE THREAD

**Issue by ahasverus** [ropensci/software-review#655]
Submitting Author Name: Nicolas Casajus
Submitting Author Github Handle: @ahasverus
Other Package Authors Github handles: (comma separated, delete if none) @MatGreco90, @ChaabaneS, @xgiraud
Repository:  https://github.com/frbcesab/forcis
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: forcis
Type: Package
Title: An R Client to Access the FORCIS Database
Version: 0.0.0.9000
Authors@R: c(
    person(given   = "Nicolas",
           family  = "Casajus",
           role    = c("aut", "cre", "cph"),
           email   = "nicolas.casajus@fondationbiodiversite.fr",
           comment = c(ORCID = "0000-0002-5537-5294")),
    person(given   = "Mattia",
           family  = "Greco",
           role    = "aut",
           email   = "mgreco@iopan.pl",
           comment = c(ORCID = "0000-0003-2416-6235")),
    person(given   = "Xavier",
           family  = "Giraud",
           role    = "aut",
           email   = "giraud@cerege.fr",
           comment = c(ORCID = "0000-0001-5067-8176")),
    person(given   = "Sonia",
           family  = "Chaabane",
           role    = "aut",
           email   = "sonia.chaabane@fondationbiodiversite.fr",
           comment = c(ORCID = "0000-0002-4653-8610")))
Description: Provides an interface to the FORCIS database 
    (<https://zenodo.org/doi/10.5281/zenodo.7390791>) on global foraminifera
    distribution. This package allows to download and to handle FORCIS data.
    It is part of the FRB-CESAB working group FORCIS.
    <https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/forcis/>.
URL: https://frbcesab.github.io/forcis
BugReports: https://github.com/FRBCesab/forcis/issues
License: GPL (>= 2)
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.2
VignetteBuilder: knitr
Depends: 
    R (>= 2.10)
Imports: 
    dplyr,
    ggplot2,
    jsonlite,
    rlang,
    sf,
    tidyr,
    utils,
    vroom
Suggests: 
    fs,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0),
    withr
Config/testthat/edition: 3
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):

    **Data Lifecycle Packages**

	- [x] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
        - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses
	- [ ] Probability Distributions

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

> This package is designed to download the FORCIS data files hosted on [Zenodo](https://zenodo.org/doi/10.5281/zenodo.7390791). But many functions have been developed to handle, select, filter, and reshape data. This is why we hesitate between **Data retrieval** and maybe **Data munging**.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

> Not applicable.

-   Who is the target audience and what are scientific applications of this package?  

> This package should be of interest to scientists working on Foraminifera species distribution and interested in the FORCIS database (spatial analyses, time series analyses, etc.). The package have been developed to facilitate the data wrangling to avoid some pitfalls and to easily get data ready to be analyzed/visualized.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

> No other package exists to handle the FORCIS database. Note that we also are authors of the database.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

> Not applicable.

-  Any other questions or issues we should be aware of?:

> The package is nearly complete (documentation needs to be polished) and we plan to write and submit a software paper to Methods in Ecology and Evolution.

**Comment by adamhsparks** [comment]
Hi @ahasverus, what sort of feedback are you looking for with your pre-submission here? Is your question around the categories?

**Comment by ahasverus** [comment]
Hi @adamhsparks.
Yes my question is about the categories (can we choose more than one category?) and also "Is this package can interest ROpenSci?".

**Comment by adamhsparks** [comment]
Sorry, @ahasverus, I'm checking with the editorial board on this now and will get back to you.

**Comment by adamhsparks** [comment]
@ahasverus, yes, this is in-scope. Please feel welcome to submit this for code review and you may select more than one category.

From the form above,
>Please indicate which **_category or categories_** from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):
