### ISSUE TITLE
Pre-Submission Enquiry: butterfly

### ISSUE THREAD

**Issue by thomaszwagerman** [ropensci/software-review#665]
Submitting Author Name: Thomas Zwagerman
Submitting Author Github Handle: @thomaszwagerman
Repository:  https://github.com/thomaszwagerman/butterfly
Submission type: Pre-submission
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: butterfly
Title: Verification For Continually Updating Timeseries Data
Version: 1.0.0
Authors@R: 
    person("Thomas", "Zwagerman", , "thozwa@bas.ac.uk", role = c("aut", "cre"),
           comment = c(ORCID = "0009-0003-3742-3234"))
Description: Verification of continually updating timeseries data where we expect new values, but want to ensure previous data remains unchanged.
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.2
Imports: 
    cli,
    dplyr,
    lifecycle,
    waldo
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Depends: 
    R (>= 2.10)
LazyData: true
VignetteBuilder: knitr
URL: https://github.com/thomaszwagerman/butterfly
BugReports: https://github.com/thomaszwagerman/butterfly/issues
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) or [statistical package categories](https://stats-devguide.ropensci.org/overview.html#overview-categories) this package falls under. (Please check one or more appropriate boxes below):

    **Data Lifecycle Packages**

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [x] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
    
     **Statistical Packages**

	- [ ] Bayesian and Monte Carlo Routines
	- [ ] Dimensionality Reduction, Clustering, and Unsupervised Learning
	- [ ] Machine Learning
	- [ ] Regression and Supervised Learning
	- [ ] Exploratory Data Analysis (EDA) and Summary Statistics
	- [ ] Spatial Analyses
	- [ ] Time Series Analyses
	- [ ] Probability Distributions

- Explain how and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

This package was written to handle the verification of continually updating time-series data, where we expect new values over time, but want to ensure previous data remains unchanged. This package provides functionality that can be used as part of a data pipeline, to check and flag changes to previous data and prevent changes going unnoticed.

- If submitting a statistical package, have you already [incorporated documentation of standards into your code via the **srr** package](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-srr)?

N/A

-   Who is the target audience and what are scientific applications of this package?  

Researchers, data engineers, data stewards etc. We have implemented this package in an operational data pipeline, which extracts ERA5 data and performs some calculations to generate a new publishable dataset. [ERA5 can be subject to retrospective changes](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=documentation), and so to prevent these changes going unnoticed and affecting our dataset, we use butterfly to verify our data has not unexpectedly changed compared to previously published versions.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

To my knowledge, there is no other package that handles the comparing of **iterations** of the same data, i.e. we want to verify there are no changes in previous data, but at the same time we do not want **new** data to throw an error and stop our pipeline. 

However, my concerns are 1) this is not enough 'extra' functionality to justify a separate new rOpenSci package, and 2) the overlap with the following packages:

[waldo](https://github.com/r-lib/waldo) - `butterfly` uses `waldo::compare()` in every function to provide a report on difference. There is therefore significant overlap, however `butterfly` builds on `waldo` by providing the functionality of comparing objects where we expect changes in some places (entirely new rows of data), but not in others (previously published data). `butterfly` also provides extra user feedback to provide clarity on what it is and isn’t comparing, due to the nature of comparing only “matched” rows.

[diffdf](https://github.com/gowerc/diffdf) - similar to `waldo`, but specifically for data frames, `diffdf` provides the ability to compare data frames directly. `diffdf::diffdf()`  could have been used in our case, but I prefer `waldo`’s more explicit and clear user feedback. That said, there is significant overlap in functionality: `butterfly::loupe()` and `diffdf::diffdf_has_issues()` both provide a TRUE/FALSE difference check, while `diffdf::diffdf_issue_rows()` and `butterfly::catch()` both return the rows where changes have occurred. However, it lacks the flexibility of `butterfly` to compare object where we expect some changes, but not others.

[assertr](https://github.com/tonyfischetti/assertr) - `assertr` provides assertion functionality that can be used as part of a pipeline, and test assertions on a particular dataset, but it does not offer tools for comparison. I would use them hand-in-hand but `butterfly` has a comparison purpose.

[daquiri](https://github.com/ropensci/daiquiri/) - `daquiri` provides tools to check data quality and visually inspect timeseries data. It is a quality assurance package for timeseries, but does not have a comparison/verification purpose like `butterfly`.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-  Any other questions or issues we should be aware of?:

The implementation of this package is very simple, almost so simple that I question whether an existing solution/package already exists. A review would be much appreciated, but getting pointed in the direction of already existing solutions to this kind of data verification problem would also be very welcome!

Many thanks :sunglasses:,

Thomas

**Comment by adamhsparks** [comment]
Hi @thomaszwagerman, thank you for your inquiry.

The editorial board has a few questions for you to consider but broadly feel that this would be in-scope.

1. Is there potential to generalise the package, _e.g._, Implement a change tolerance or examine changes in _relationships_ between variables?
2. Do you think that this work would be better as a PR contribution to the other packages that you've mentioned here that offer similar functionality?

**Comment by thomaszwagerman** [comment]
Hi @adamhsparks, 

 I'm glad that this would be in-scope.

Thank you for your response and these questions, both good points. To answer your questions:

**Q1:**
The aim of this package was to generalise out from our particular ERA5 use case, and I am keen to accommodate other use cases, so for me that potential is definitely there as long as it remains within the constraints of data versioning/verification. 

With regards to your particular examples: 

- Change tolerance: I agree this would be a useful feature to add, with accompanying warnings that can be silenced. 
- Examine changes in relationships between variables: I can also the see merit of this in model parameterisation (_e.g._ how does the relationship between _x_ and _y_ change if I change parameter _z_), so yes I think this would be a valuable addition.

**Q2:**
I think it **is** possible to incorporate the (matched comparison part) of `butterfly::loupe()` in `waldo::compare()` or `diffdf::diffdf()`, through adding an argument which specifies the unique identifier that should be used to match data frames, but operate as normal when it is NULL. This would be a non-breaking change, and might be welcomed by their respective authors?

Trickier to incorporate into other package's functionality would be the additional `cli::cat_*()` feedback (which is useful in automatic logging and stopping of pipelines), as well as the different returns implemented in butterfly (TRUE/FALSE for `loupe()`, and dataframes with/without changed rows for `catch()`/`release()`). These are quite valuable for our use, and the separation of concern (data verification/versioning vs simply quality control) is also a benefit of a separate package.

**Comment by adamhsparks** [comment]
@thomaszwagerman, thanks for your consideration of our suggestions and comments.

We're still happy to accept this as a submission. If you'd like to incorporate the examples from Q1 that would be welcome and would make the package more novel, but it is not totally necessary.

**Comment by adamhsparks** [comment]
@thomaszwagerman, are you OK for me to close this issue? Have we addressed all your questions sufficiently?

**Comment by thomaszwagerman** [comment]
@adamhsparks yes - many thanks for the guidance and input.

I've implemented the tolerance feature, but I need to think about how to implement checking relationships between variables. I will start a submission when I have given that some thought, and it is more appropriate to do so.
